### ISSUE TITLE
Lidar raw-data calibration

### ISSUE THREAD

**Issue by lhcezx** [nutonomy/nuscenes-devkit#1000]
Hi, I would like to ask a question about the raw Lidar data from nuscenes, in which coordinate system is the Lidar data? Does the raw lidar data already have pre-calibrated to the vehicle coordinate system? Or is it's based on the LiDAR coordinate system OR the world coordinate system?

**Comment by whyekit-motional** [comment]
@lhcezx the lidar data is in the lidar coordinate system

**Comment by lhcezx** [comment]
> @lhcezx the lidar data is in the lidar coordinate system

thx a lot
