### ISSUE TITLE
error when submitting zipped file in nuScenes lidarseg challenge

### ISSUE THREAD

**Issue by CSPaulia** [nutonomy/nuscenes-devkit#1002]
Hi,
Thank for all the hard work.
I am curious why the feedback of the challenge is like the pic below?
![屏幕截图 2023-11-02 180629](https://github.com/nutonomy/nuscenes-devkit/assets/68882168/f81a26a4-95cc-46ed-b96f-a3f80981ee44)
The Pic is from the stderr file.

**Comment by whyekit-motional** [comment]
@CSPaulia pls try re-submitting now

**Comment by CSPaulia** [comment]
Thank you very much!
