### ISSUE TITLE
What is the focal length of the camera, etc.?

### ISSUE THREAD

**Issue by yu8ri1** [nutonomy/nuscenes-devkit#1003]
What are the f-number, focal length and sensor size (Cmos) values for the front facing camera?
I think the focal length and sensor size are expressed in inches, but I would like to know the values when they are converted to (mm).

**Comment by whyekit-motional** [comment]
@yu8ri1 I believe https://www.nuscenes.org/nuscenes#data-collection should have the information you require

**Comment by yu8ri1** [comment]
@whyekit-motional Thank you for your reply, I saw the URL. I have one question: I think the top 300 pixels of the 6s camera are cropped as ROI from the resolution 1600*1200. I think the camera's internal parameters you provide are the internal parameters corresponding to the cropped image, but are they different from the internal parameters for the resolution of 1600*1200?

**Comment by whyekit-motional** [comment]
@yu8ri1 I think the camera intrinsics should be based on the full resolution (since we do the cropping after capturing the image)

**Comment by yu8ri1** [comment]
thanks reply.
 is full resolution 1920*1080 or 16001200 ?

**Comment by whyekit-motional** [comment]
The full resolution would be 1600x1200
