### ISSUE TITLE
How did the lidar in the keyframe sample align with the 6-way camera 

### ISSUE THREAD

**Issue by hjfenghj** [nutonomy/nuscenes-devkit#1004]
First of all, thank you very much for your work

I used a keyframe lidar to find the 6 cameras closest to the timestamp, and the resulting 6 cameras included non keyframes defined in sample.json. May I ask how your team aligned lidar with cam during the sample process.

I use the following code to complete a 6-way camera search for a certain keyframe lidar

![image](https://github.com/nutonomy/nuscenes-devkit/assets/72334253/02ce388c-6ae4-4d92-8ef4-f678abe06c28)

**Comment by whyekit-motional** [comment]
@hjfenghj pls refer to https://www.nuscenes.org/nuscenes#data-collection, in particular:

> In order to achieve good cross-modality data alignment between the LIDAR and the cameras, the exposure of a camera is triggered when the top LIDAR sweeps across the center of the camera’s FOV. The timestamp of the image is the exposure trigger time; and the timestamp of the LIDAR scan is the time when the full rotation of the current LIDAR frame is achieved. Given that the camera’s exposure time is nearly instantaneous, this method generally yields good data alignment. Note that the cameras run at 12Hz while the LIDAR runs at 20Hz. The 12 camera exposures are spread as evenly as possible across the 20 LIDAR scans, so not all LIDAR scans have a corresponding camera frame. Reducing the frame rate of the cameras to 12Hz helps to reduce the compute, bandwidth and storage requirement of the perception system.
