### ISSUE TITLE
about dataset of segmentation and detection 

### ISSUE THREAD

**Issue by yu8ri1** [nutonomy/nuscenes-devkit#1009]
Is it possible to map data for segmentation and object detection?

**Comment by whyekit-motional** [comment]
@yu8ri1 pls check out the map expansion (tutorial can be found here: https://colab.research.google.com/github/nutonomy/nuscenes-devkit/blob/master/python-sdk/tutorials/map_expansion_tutorial.ipynb)

**Comment by yu8ri1** [comment]
I may have misled you with my poor English ... .
My question is: Is the point cloud for semantic segmentation and the point cloud for 3D object detection the same point cloud used?
If so, I would like to know how to know the correspondence.

**Comment by whyekit-motional** [comment]
@yu8ri1 yes, the point cloud for semantic segmentation and the point cloud for 3D object detection is exactly the same

In other words, you simply need to load [nuScenes](https://arxiv.org/abs/1903.11027) to get the lidar point cloud (xyz, intensity, etc.) and then load [Panoptic nuScenes](https://arxiv.org/abs/2109.03805) to get the semantic label for each lidar point (there is a one-to-one correspondence between the two)

For a concrete example on how to do this, pls see https://github.com/nutonomy/nuscenes-devkit/issues/650#issuecomment-907540001
