### ISSUE TITLE
can not install the data 

### ISSUE THREAD

**Issue by RashoAli** [nutonomy/nuscenes-devkit#1013]
Dear authors,

I have attempted multiple times to install the data from https://www.nuscenes.org/download. 
When selecting Asia or US, the loading animation appears, but nothing is installed. Could you please inform me if there is anything I can do to resolve this issue?

**Comment by whyekit-motional** [comment]
@RashoAli nothing from https://www.nuscenes.org/download does installation (only downloading of the dataset) - for installation of the devkit, pls refer to https://github.com/nutonomy/nuscenes-devkit#devkit-setup

**Comment by whyekit-motional** [comment]
@RashoAli the download links work for me, e.g.:

<img src="https://github.com/nutonomy/nuscenes-devkit/assets/62535720/aede0d25-2013-49df-a01d-f65afa6b9cfd" width="512">

There is probably some issue on your end (firewall, browser, etc.), which you will have to check
