### ISSUE TITLE
speed about get_map_mask

### ISSUE THREAD

**Issue by haofengsiji** [nutonomy/nuscenes-devkit#1018]
Compared to Boston Seaport and Singapore One-North, , the loading speed of Singapore Queenstown and Singapore Holland Village's local map is very slow, as shown in the image below. 

![image](https://github.com/nutonomy/nuscenes-devkit/assets/47882088/9ee58142-8b39-4bf7-8773-2360b2134c7f)

Is there any way to improve the loading speed of the local map?

```python
def load_map(map_name):
    nusc_map = NuScenesMap(dataroot='../../data/nuscenes', 
                        map_name=map_name)
    patch_box = (1000., 1000., 100, 100)
    patch_angle = 0 # Default orientation where North is up
    layer_names = ('drivable_area', 'carpark_area', 'road_block', 'walkway', 'ped_crossing', 'stop_line', 'road_divider', 'lane_divider')
    canvas_size = (256, 256)
    map_mask = nusc_map.get_map_mask(patch_box, patch_angle, layer_names, canvas_size)
```

**Comment by iaoqian** [comment]
Have you solved this problem?
