### ISSUE TITLE
v_comp in RadarPointCloud

### ISSUE THREAD

**Issue by odd2022** [nutonomy/nuscenes-devkit#1022]
Hello, I would like to obtain the radial velocities of radar points in the frame of the radar sensor. 

To do so, I used the function RadarPointCloud.from_file and I would like to know whether the field v_comp was the velocity of radar points in the frame of the radar sensor. 

If so and if I am correct, i just have to convert the velocities in spherical coordinates. 

If not, could you explain to me how v_comp is computed please ? 

Have a nice day

**Comment by whyekit-motional** [comment]
@odd2022 the velocities from the radar have been compensated for ego motion: https://github.com/nutonomy/nuscenes-devkit/blob/9b165b1018a64623b65c17b64f3c9dd746040f36/python-sdk/nuscenes/utils/data_classes.py#L330

**Comment by odd2022** [comment]
Thank you, I saw that but could explain what does it mean exactly please ?

**Comment by whyekit-motional** [comment]
Essentially, the velocities are wrt the ego
