### ISSUE TITLE
About frame rate in sweeps.

### ISSUE THREAD

**Issue by Little-Podi** [nutonomy/nuscenes-devkit#1025]
Hi, I noticed that the dense camera data provided in sweeps does not strictly follow a 12Hz frame rate. Sometimes, it only contains 4 sweeps between two adjacent key frames, which should be the case of 10Hz. Is this normal? Does it mean the actual frame rate is lower than 12Hz?

**Comment by whyekit-motional** [comment]
@Little-Podi pls show an example in the dataset where you see 4 sweeps between adjacent key frames

**Comment by Little-Podi** [comment]
For example, starting from `samples/CAM_FRONT/n008-2018-08-01-15-52-19-0400__CAM_FRONT__1533153304162404.jpg`, if I use `camera_data["next"]` to access the next frame iteratively, I will only go through 4 sweeps before I reach `samples/CAM_FRONT/n008-2018-08-01-15-52-19-0400__CAM_FRONT__1533153304612404.jpg`.
```
sweeps/CAM_FRONT/n008-2018-08-01-15-52-19-0400__CAM_FRONT__1533153304262404.jpg
sweeps/CAM_FRONT/n008-2018-08-01-15-52-19-0400__CAM_FRONT__1533153304362404.jpg
sweeps/CAM_FRONT/n008-2018-08-01-15-52-19-0400__CAM_FRONT__1533153304412404.jpg
sweeps/CAM_FRONT/n008-2018-08-01-15-52-19-0400__CAM_FRONT__1533153304512404.jpg
```
In fact, I have encountered plenty of cases like this.

**Comment by whyekit-motional** [comment]
@Little-Podi it is possible that, in a given scene, some non-keyframes were dropped due to high system load (https://forum.nuscenes.org/t/clarification-on-timestamps-and-capture-frequency-of-sweeps/481/2)

**Comment by Little-Podi** [comment]
Thanks. Does it mean that in cases where some non-keyframes are dropped, the actual interval is doubled, and we cannot assume the intervals between these sweeps are absolutely equal?

**Comment by whyekit-motional** [comment]
Yes, depending on your use case, it might be better to calculate the actual time difference between sweeps instead of assuming it based on the fps

**Comment by Little-Podi** [comment]
I see. Thanks a lot.
