### ISSUE TITLE
Abount nuScenes CAN bus  expansion data

### ISSUE THREAD

**Issue by DanielZ98** [nutonomy/nuscenes-devkit#1028]
Hi, I have recently been working with the nuscenes CAN bus expansion and have encountered some issues. Specifically, I noticed that data from scene-0161 to scene-168, and scene-170 to scene-176 are missing in the nuscenes CAN bus expansion. I have verified the integrity of my downloaded files using md5 checksum and found no issues.

Could you please let me know if there are plans to supplement this missing CAN bus data in the future?

**Comment by whyekit-motional** [comment]
@DanielZ98 pls refer to https://github.com/nutonomy/nuscenes-devkit/issues/465
