### ISSUE TITLE
How do you define global coordinate system?

### ISSUE THREAD

**Issue by admyxs** [nutonomy/nuscenes-devkit#1029]
What are the origins of x, y, and z respectively?
![image](https://github.com/nutonomy/nuscenes-devkit/assets/50825926/e0a2bcbf-703b-4bd8-8326-088c85902f29)

**Comment by whyekit-motional** [comment]
@admyxs pls refer to https://github.com/nutonomy/nuscenes-devkit/blob/9b165b1018a64623b65c17b64f3c9dd746040f36/python-sdk/nuscenes/map_expansion/map_api.py#L45-L49

**Comment by admyxs** [comment]
thank for your quick reply 
but I want to know where the origin of z axes is

**Comment by whyekit-motional** [comment]
The reference (0, 0, 0) is the point at the top left corner of the respective map.

**Comment by admyxs** [comment]
> The reference (0, 0, 0) is the point at the top left corner of the respective map.


thank for you quick reply!
But what you said conflicts with the code.

https://github.com/nutonomy/nuscenes-devkit/blob/9b165b1018a64623b65c17b64f3c9dd746040f36/python-sdk/nuscenes/map_expansion/map_api.py#L45-L49

The code says it's south western corner, so it should be bottom left corner.

**Comment by admyxs** [comment]
thank for you quick reply again!!!
And I want to know where the origin of z axes is?

**Comment by whyekit-motional** [comment]
@admyxs you can image the z-plane of the global frame to be the flat map
