### ISSUE TITLE
Trouble with getting started tutorial

### ISSUE THREAD

**Issue by benijohn** [nutonomy/nuscenes-devkit#1030]
Hi, I am trying to go through this tutorial https://www.nuscenes.org/tutorials/nuimages_tutorial.html

It took some time to get the file structure to work as it needed the absolute path and it seems there is a folder in v1.0-mini that is also named v1.0-mini. I ended up having to remove the first level v1.0-mini folder and put its contents directly into ~/data/sets/nuimages such that /nuimages now contains: v1.0-mini, samples, sweeps, and maps. Is this correct? This allowed the first part of the tutorial to work. However, when I get to the line, 

`sample_idx = 0
sample = nuim.sample[sample_idx]
sample`

my output does not match the tutorial. The tutorial states it should be:

> Loaded 50 sample(s) in 0.000s,
Out[5]:
{'token': '09acd654cb514bdeab8e3afedad74fca',
 'timestamp': 1535352274870176,
 'log_token': '4ed5d1230fcb48d39db895f754e724f9',
 'key_camera_token': '0128b121887b4d0d86b8b1a43ac001e9'}

But mine was

> Loaded 404 sample(s) in 0.001s,
Out[14]:
{'token': 'ca9a282c9e77460f8360f564131a8af5',
 'timestamp': 1532402927647951,
 'prev': '',
 'next': '39586f9d59004284a7114a68825e8eec',
 'scene_token': 'cc8c0bf57f984915a77078b10eb33198'}

Which as you can see does not contain the same keys. Is this expected behavior? It seems that neither of the keys {'token', 'scene_token'} will work to continue the tutorial. Did I do something wrong in the setup? How can I move forward with this tutorial?

Thank you!

Benjamin

**Comment by whyekit-motional** [comment]
@benijohn it looks like you might have downloaded the `v.1.0-mini` of nuScenes, instead of nuImages

**Comment by benijohn** [comment]
@whyekit-motional you are correct. I did not realize they were different datasets. Thank you for your reply!
