### ISSUE TITLE
Issue downloading data

### ISSUE THREAD

**Issue by Divadi** [nutonomy/nuscenes-devkit#1031]
Hello - I've been trying to download the sensor data for the NuPlan expansion from the website, but I'm met with this error:
![image](https://github.com/nutonomy/nuscenes-devkit/assets/17109672/65c82c3a-781a-4ded-8c9f-0d2d528cb3f4)
I am able to download log databases, but none of the sensor data. However, this was working for me until the day before yesterday. Is there something potentially problematic on my end?

Thank you!

**Comment by GordonGustafson** [comment]
While we sort this out the issue with downloading large files on the website, please download the files from here:
nuScenes: https://d36yt3mvayqw5m.cloudfront.net
nuPlan: https://d1qinkmu0ju04f.cloudfront.net

**Comment by GordonGustafson** [comment]
Downloading large files on the website should work again, let us know if you see any issues!
