### ISSUE TITLE
Unpacking v1.0-trainval dataset

### ISSUE THREAD

**Issue by ArseniuML** [nutonomy/nuscenes-devkit#1032]
I've downloaded v1.0-trainval dataset and want to unpack it properly. Dataset consists of 10 blobs, and if I click "Extract to..." on each blob and specify nuScenes root, each blob tar would be unpacked in nuScenes_root/v1.0-trainval0X_blobs folder, which would contain samples and sweeps subfolders.
However, documentation says that samples and sweeps must be subfolders of nuScenes_root. So how do I can unpack these tars properly? The problem is that tars are huge, each tar is unpacking ~1hour, and if I will move and merge samples and sweeps by hands after unpacking, it will consume more and more hours of time...

**Comment by whyekit-motional** [comment]
@ArseniuML I think if you simply unpack everything via `tar`, the `samples` and `sweeps` folders from each blob will get merged automatically
