### ISSUE TITLE
can not pip install in python3.11

### ISSUE THREAD

**Issue by mcmingchang** [nutonomy/nuscenes-devkit#1034]
when build matplotlib-3.5.3
There is nothing we can do to fix this, as all we can do is make new releases and the OP is explicitly asking for 3.5.0.
https://github.com/matplotlib/matplotlib/issues/26715

**Comment by whyekit-motional** [comment]
@mcmingchang pls note the following from https://github.com/nutonomy/nuscenes-devkit?tab=readme-ov-file#devkit-setup:

>  The devkit is tested for Python 3.6 and Python 3.7.
