### ISSUE TITLE
How can I get single scene data?

### ISSUE THREAD

**Issue by BoynextDoor114514** [nutonomy/nuscenes-devkit#1035]
Hello! I want to get every scene data from trainval dataset, what should I do?

**Comment by whyekit-motional** [comment]
You can use the `prev` and `next` keys in each sample record to traverse an entire scene (pls see https://colab.research.google.com/github/nutonomy/nuscenes-devkit/blob/master/python-sdk/tutorials/nuscenes_tutorial.ipynb for the details)
