### ISSUE TITLE
camera mount height

### ISSUE THREAD

**Issue by cxl-ustb** [nutonomy/nuscenes-devkit#1036]
What does ego pose look like specifically? Where is the origin? What do X, Y, and Z point to respectively? I would like to know the height of 6 cameras relative to the ground. Thank you very much.

**Comment by whyekit-motional** [comment]
@cxl-ustb you can see how the coordinate system of each camera looks like relative to the ego here: https://www.nuscenes.org/static/media/data.9ef46c59.png
