### ISSUE TITLE
There is no md5 on the download page

### ISSUE THREAD

**Issue by lihao1998h** [nutonomy/nuscenes-devkit#1039]
How should I check whether the file I downloaded is complete, I have tried multiple times to decompress, tar -xzvf, but there will be errors.
`tar: Skipping to next header `
`tar: Archive contains where numeric off_t value expected`
`tar: \366\201@: Unknown file type 'Q', extracted as normal file`

<img width="904" alt="微信图片_20240305091134" src="https://github.com/nutonomy/nuscenes-devkit/assets/41355487/4246f66b-253f-4fd6-ba0d-1b33089de3a8">

**Comment by tjyuyao** [comment]
Same error here, any solutions?
