### ISSUE TITLE
Identities of train and val scenes

### ISSUE THREAD

**Issue by nrhine1** [nutonomy/nuscenes-devkit#104]
The [Download](https://www.nuscenes.org/download) page says the trainval split consists of: "850 scenes, 700 train, 150 val." I am assuming this distinction is intended to standardize the training and validation sets. How is each scene identified as belonging to either train or val? I can't find these annotations or descriptions. Thanks!

**Comment by Alex-nutonomy** [comment]
Hi @nrhine1, please check out https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/splits.py for the split definitions.
