### ISSUE TITLE
Eval AI Submission Stuck at the status “Submitted”

### ISSUE THREAD

**Issue by goahence** [nutonomy/nuscenes-devkit#1043]
Hi, we have recently uploaded a compressed file to the Eval AI server as part of our participation in the nuScenes 3D Object Tracking Challenge. However, the status of our submission continues to be marked as "Submitted", despite a time-lapse of approximately 3 days since the initial submission. Any guidance or recommendations you could provide in resolving this issue would be greatly appreciated.
![微信图片_20240312204207](https://github.com/nutonomy/nuscenes-devkit/assets/102583216/3ebce12b-8906-44d6-9122-5a74b7b29397)

**Comment by whyekit-motional** [comment]
@goahence pls confirm if this is still an issue

**Comment by goahence** [comment]
Sorry, it seems the status has not changed.
![Uploading 微信图片_20240315193057.png…]()

**Comment by whyekit-motional** [comment]
@goahence try resubmitting to trigger a re-run of the evaluation

**Comment by goahence** [comment]
Thanks! The problem has been solved.
