### ISSUE TITLE
Leader Board Not Updated with our verified submission

### ISSUE THREAD

**Issue by DLAI007** [nutonomy/nuscenes-devkit#1047]
We made our model score public and even sent mail to NuScenes with the needed details. Its been 1 week and still it's not updated yet. Please help!

![submission](https://github.com/nutonomy/nuscenes-devkit/assets/163508822/4622f52d-417b-4fb7-851d-83ffc23875ae)

**Comment by whyekit-motional** [comment]
@DLAI007 pls ensure that you have sent the required information to nuscenes@motional.com - pls see https://github.com/nutonomy/nuscenes-devkit/tree/master/python-sdk/nuscenes/eval/detection#participation for details

**Comment by DLAI007** [comment]
@whyekit-motional 
The details were already emailed to nuscenes@motional.com on March 11th 2024.

**Comment by bhaskarjyotidutta** [comment]
@whyekit-motional need help on it, been already quite long since we shared all the needed details. Thanks.

**Comment by DLAI007** [comment]
@whyekit-motional please help us on it. Its been quite long since our submissions of all the needed details to nuscenes@motional.com, and  still no updation of our model in the leaderboard.

**Comment by whyekit-motional** [comment]
@DLAI007 if you have sent in all the required details as per https://github.com/nutonomy/nuscenes-devkit/tree/master/python-sdk/nuscenes/eval/detection#participation, then your submission will be processed in due course

However, if there are missing details, then we will have to circle back to you (so for the fastest turnaround time, pls ensure you have all the required details the first time)

We appreciate your patience, as we have a lot of submissions to process (on top of other matters)
