### ISSUE TITLE
What is the function obtain_sensor2top want to do?

### ISSUE THREAD

**Issue by fdy61** [nutonomy/nuscenes-devkit#1049]
I am studying the code in Nuscenes_converter.py,
![image](https://github.com/nutonomy/nuscenes-devkit/assets/134828384/bf74a1ac-ae1f-458d-9ec2-4cdd7012fc6d)
So what is the function obtain_sensor2top want to do?

**Comment by whyekit-motional** [comment]
@fdy61 pls include a link to that piece of code

**Comment by fdy61** [comment]
Thanks for your reply.
Here is the link: https://github.com/HuangJunJie2017/BEVDet/blob/6fd935a084d403d097d5e2f18a45568e11bf3dc0/tools/data_converter/nuscenes_converter.py#L208   
And obtain_sensor2top is defined in https://github.com/HuangJunJie2017/BEVDet/blob/6fd935a084d403d097d5e2f18a45568e11bf3dc0/tools/data_converter/nuscenes_converter.py#L276

**Comment by fdy61** [comment]
what's the meaning of the comment "# sweep->ego->global->ego'->lidar" on line 323, I cannot understand.

**Comment by whyekit-motional** [comment]
@fdy61 since the code comes from https://github.com/HuangJunJie2017/BEVDet/, you should be posting your question at https://github.com/HuangJunJie2017/BEVDet/issues, not here :smile:

**Comment by fdy61** [comment]
Is that the nuscenes datasets' specific preprocessing function like create_data.py, nuscenes_converter.py and so on comes from the specifc detection tasks and their authors right? I wrongly think that you develop this data preprocessing codes.

**Comment by whyekit-motional** [comment]
@fdy61 yes, I believe those scripts are from the authors of BEVDet

**Comment by fdy61** [comment]
I see.Thank you very much.
