### ISSUE TITLE
Numpy version

### ISSUE THREAD

**Issue by eskjorg** [nutonomy/nuscenes-devkit#105]
Is numpy==1.14.5 necessary? Some other dependencies of mine requires numpy>=1.16.1. Would be convenient to be able to install both in the same environment without conflict. How about for example using numpy==1.16 in NuScenes?

One hack that seems to work right now is:
1. pip install nuscenes-devkit
2. pip install --upgrade numpy
3. pip install other-package

**Comment by Alex-nutonomy** [comment]
We have seen some non nuscenes-devkit code that is slower with `numpy > 1.14.5`, so we don't have any plan to upgrade the numpy version anytime soon. However, your proposed steps will allow you to use any numpy version you like.
