### ISSUE TITLE
Question about how to calculate the velocity of box.

### ISSUE THREAD

**Issue by fdy61** [nutonomy/nuscenes-devkit#1050]
In line 377 we can see the function box_velocity.
https://github.com/nutonomy/nuscenes-devkit/blob/9df79f48bac3cc713f4dbd2b48049be845605c51/python-sdk/nuscenes/nuscenes.py#L377
This function calculate the velocity through **pos_diff / time_diff**. I want to know, in the sample_annotation.json, for a particular annotation, what's the meaning of its' prev and next annotation? Are they annotations of the same object in the same scene but in different key frames?

**Comment by whyekit-motional** [comment]
@fdy61 pls refer to the schema for `sample_annotation` here: https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/schema_nuscenes.md#sample_annotation

In particular:
```
"next": <str> -- Foreign key. Sample annotation from the same object instance that follows this in time. Empty if this is the last annotation for this object.
"prev": <str> -- Foreign key. Sample annotation from the same object instance that precedes this in time. Empty if this is the first annotation for this object.
```
