### ISSUE TITLE
what's the type of the Lidar Sensor?

### ISSUE THREAD

**Issue by fdy61** [nutonomy/nuscenes-devkit#1054]
Is it MEMS or some type else?
One more question, does each point cloud in sample_data.json fully represent a 360-degree environment, or do I need to combine the previous frames of point cloud data according to the key named 'prev' in each sample_data to observe the complete object?

**Comment by whyekit-motional** [comment]
@fdy61 pls refer to https://www.nuscenes.org/nuscenes#data-collection for the details of the lidar used

Each point cloud in `sample_data.json` represents a single 360-degree sweep of the environment (but you can aggregate multiple sweeps to get a denser observation of a given object)
