### ISSUE TITLE
KeyError: 'is_key_frame' ,can't find the key in record

### ISSUE THREAD

**Issue by Liuliuliuyikou** [nutonomy/nuscenes-devkit#1061]
I have been using the nuscenes dataset before and it performed well. However, the following error occurred recently when loading data.
line 126, in __init__
    version="v1.0-trainval", dataroot=self.dataroot, verbose=False
  File "/home/ljh/miniconda3/envs/clip_env/lib/python3.7/site-packages/nuscenes/nuscenes.py", line 124, in __init__
    self.__make_reverse_index__(verbose)
  File "/home/ljh/miniconda3/envs/clip_env/lib/python3.7/site-packages/nuscenes/nuscenes.py", line 186, in __make_reverse_index__
    if record['is_key_frame']:
KeyError: 'is_key_frame'
The only thing I did during this period was to try to load the data and train the model with pytorch_lighting . How can I solve this problem?

**Comment by whyekit-motional** [comment]
@Liuliuliuyikou without a working code snippet from you (i.e. something a reader can simply copy, paste and run), it is hard to say, but I can suggest a few things to help you:
- Ensure that the nuScenes data is in the correct location
- Print `record` to see what is being stored in that variable

**Comment by Liuliuliuyikou** [comment]
Thank you, the problem has been solved
