### ISSUE TITLE
Radar point cloud projection of the same scene

### ISSUE THREAD

**Issue by jasonhengtw** [nutonomy/nuscenes-devkit#1062]
I want to ask about different frames of the same scene (scene-1094). I use the render_pointcloud_in_image function to project the radar point cloud onto the image. However, in this scene, the car in front sometimes has a little cloud and sometimes not?
And sometimes there are many points corresponding to the car. How do I confirm which point cloud corresponds to the car?

**Comment by whyekit-motional** [comment]
@jasonhengtw if you used the same parameters for `render_pointcloud_in_image` each time you run it, the rendered image should be the same each time (i.e. it is deterministic)

**Comment by jasonhengtw** [comment]
Sorry for not making it clear, I am in scene-1094 scene, and then through the program 
`scene_rec = self.nusc.get('scene', scene_token)`        
`sample_rec = self.nusc.get('sample', scene_rec['first_sample_token'])`
` sd_rec = self.nusc.get('sample_data', sample_rec['data']['CAM_FRONT'])`
`pointsensor = self.nusc.get('sample_data', sample_rec['data']['RADAR_FRONT']) `
obtains camera and radar information, and projects it onto the image through `map_pointcloud_to_image`.

If I want to project the next image, should I directly perform the following two programs on the radar and image?
`sd_rec = self.nusc.get('sample_data', sd_rec['next'])`
`pointsensor = self.nusc.get('sample_data', pointsensor['next'])`

**Comment by whyekit-motional** [comment]
@jasonhengtw doing `nusc.get('sample_data', sd_rec['next'])` and `self.nusc.get('sample_data', pointsensor['next'])` would get you the next sweep for the camera and the radar respectively, but these are not guaranteed to be close to each other (in terms of timestamp), since the cameras and radars operate at different frequencies

For a better alignment, you could try this instead:
```python
next_sample_rec = self.nusc.get('sample', sample_rec['next'])
sd_rec = self.nusc.get('sample_data', next_sample_rec['data']['CAM_FRONT'])
pointsensor = self.nusc.get('sample_data', next_sample_rec['data']['RADAR_FRONT']) 
```

**Comment by jasonhengtw** [comment]
But in the process of doing this, won't the image skip frames?

**Comment by whyekit-motional** [comment]
Yes, it will skip to the next image with "good enough" closeness (in terms of timestamp) to the other sensors
