### ISSUE TITLE
Extract ego velocity at a given time

### ISSUE THREAD

**Issue by samueleruffino99** [nutonomy/nuscenes-devkit#1063]
Hello,
I was wondering if you have ego velocity in the can_bus, or the best way is to extarct velocities from ego positions and time?
Thnak you!

**Comment by whyekit-motional** [comment]
@samueleruffino99 yes, the CAN bus expansion contains the speed of the ego - pls see the tutorial for more details: https://colab.research.google.com/github/nutonomy/nuscenes-devkit/blob/master/python-sdk/tutorials/can_bus_tutorial.ipynb
