### ISSUE TITLE
Memory Requirement - Reg

### ISSUE THREAD

**Issue by jyothsna-phd22** [nutonomy/nuscenes-devkit#1064]
Hi,
I am working on nuscenes lidar-only dataset for object detection. Can you please address my question regarding the memory Requirement to work on nuscenes full dataset?

Right now, we have a nvidia GeForce RTX 4080 system each with 32GB RAM, 16GB dedicated GPU and 9728 CUDA cores. Is it sufficient to work on Nuscenes lidar-only full dataset with this specification?

**Comment by whyekit-motional** [comment]
@jyothsna-phd22 whether your GPU specifications are sufficient depends on the model and training parameters you use, not the dataset :smile:

**Comment by jyothsna-phd22** [comment]
I agree with you... But I'm bothering about minimal requirement of RAM.

**Comment by whyekit-motional** [comment]
@jyothsna-phd22 loading the data should be quite lightweight, so I don't think CPU RAM will be an issue
