### ISSUE TITLE
Coordinate system of radar point cloud and velocity information?

### ISSUE THREAD

**Issue by seamie6** [nutonomy/nuscenes-devkit#1065]
To my understanding, the radar point cloud data is stored in the current radar sensor's coordinate system, yes?

Also, for the velocity information (component velocity), in this issue: https://github.com/nutonomy/nuscenes-devkit/issues/805 it is said `vx and vy are the component velocities in the current radar frame`. And then compensated velocity is adjusted for the velocity of the ego vehicle.
Does this mean velocity information is stored in the current radar sensor's coordinate system or the ego frame of when the current radar sensor captured. I am pretty sure it is the current radar sensor's coordinate system, but I just want to be make sure.

Thank you.

**Comment by whyekit-motional** [comment]
@seamie6 yes, the radar point cloud data is stored in the sensor frame
