### ISSUE TITLE
About coordinate and box_velocity 

### ISSUE THREAD

**Issue by Nan-yxchen** [nutonomy/nuscenes-devkit#1066]
Greeting! I have several small questions about coordinate and velocity:

1. Is the box_velocity information of the target in the global coordinate frame?

2. Is there two calculate methods of ego_velocity? One is the ego_pose_diff/time_diff, and anther one is the information from CAN_BUS. Or is ego_velocity available directly in Nusecenes? And the ego_pose(ego_velocity) is in the global coordinate frame too?

3. I have one last question I'd like to confirm:  Is the origin of the global coordinate frame the top left corner of the map?  Is the ego coordinate system the same XYZ direction as the IMU coordinate system?

Greatly thanks in advance!!!

**Comment by Nan-yxchen** [comment]
@whyekit-motional I got it, Thanks! But I still confused about some questions:

1. If I use the CAN_BUS information to calculate the velocity of ego,  Is the CAN_BUS information in the global frame? And is the ego_pose.json information in the global frame too?

2. The x,y,z-axis in your response means the IMU coordinate and ego coordinate? I read other issues said that the x axis of global coordinate is going from the top left corner to the top right corner along the top edge of that rectangle, and the y axis of global coordinate is going from the top left corner to the bottom left corner along the left edge of that rectangle.

Greatly thanks in advance!!!

**Comment by whyekit-motional** [comment]
@Nan-yxchen 

1. If you read the velocity of the ego directly from the CAN bus, it will be in the ego frame - pls see https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/can_bus/README.md#pose
2. I was referring to both the IMU frame and ego frame in my response (you can also visualize the various frames at https://www.nuscenes.org/static/media/data.9ef46c59.png)

**Comment by Nan-yxchen** [comment]
@whyekit-motional Oh, I totally got it! Thanks a lot
