### ISSUE TITLE
About sample['anns']

### ISSUE THREAD

**Issue by Nan-yxchen** [nutonomy/nuscenes-devkit#1067]
Sorry to bother again! When I read the nuScenes tutorial, I found a code that is 'sample['anns']', which can list all the sample_annotation_token related to the sample_token. But I didn't find any key named 'anns' in all json file. So is there some hidden method to list these annotation token in nuscenes.py?

Greatly thanks in advance!!!

**Comment by Nan-yxchen** [comment]
I also have one problem:

1. As the overview of nuScenes say: a scene lasts about 20 seconds. So are neighboring scenes (e.g., scene01 and scene02) geographically contiguous?

**Comment by whyekit-motional** [comment]
@Nan-yxchen pls see my replies below:

- > So is there some hidden method to list these annotation token in nuscenes.py?

The `anns` entry for each sample is being populated here: https://github.com/nutonomy/nuscenes-devkit/blob/4df2701feb3436ae49edaf70128488865a3f6ff9/python-sdk/nuscenes/nuscenes.py#L192

- > As the overview of nuScenes say: a scene lasts about 20 seconds. So are neighboring scenes (e.g., scene01 and scene02) geographically contiguous?

There is no guarantee that neighboring scenes are geographically contiguous

- > What is the temporal and spatial relationship between neighboring scenes?

There is no temporal or spatial relationship between neighboring scenes - you should take each scene to be independent

**Comment by Nan-yxchen** [comment]
@whyekit-motional Oh, I got it. Thanks, that's very helpful.
