### ISSUE TITLE
translation matrix for camera sensors is with respect to the center of the rear axle?

### ISSUE THREAD

**Issue by Fengtao22** [nutonomy/nuscenes-devkit#1069]
Take the front camera rotation matrix and translation matrix as an example, its values are roughly: rots =  [[0, 0, 1], [-1, 0, 0], [0, -1, 0]]  and trans = [1.7, 0, 1.5]. If I need to get the origin of the ego vehicle (which I assume to be org_c = [0, 1.5, -1.7] with respect to the front camera coordinate), then the following equation makes sense:

rots*org_c + trans = [0, 0, 0]   

Hence, I assume the rotation matrix and translation matrix are with respect to the center of the rear axle. Given LiDAR coordinate aligns with the ego vehicle, we can still consider the rotation matrix as cam2lidar. But the translation matrix are not used for mapping camera's point to Lidar sensor.

**Comment by whyekit-motional** [comment]
@Fengtao22 yes, the translation provided in each `calibrated_sensor` record is wrt the ego frame - pls see https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/schema_nuscenes.md#calibrated_sensor for details

**Comment by Fengtao22** [comment]
Thanks for your confirmation!
