### ISSUE TITLE
Distance to other vehicles

### ISSUE THREAD

**Issue by giladdiv** [nutonomy/nuscenes-devkit#107]
What is the easiest way to get the distance between the ego-vehicle and other vehicles in the scenes.
Is it just the xyz field of the object box that we get from nusc.get_sample_data?

**Comment by holger-nutonomy** [comment]
Have a look at [this function](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/detection/loaders.py#L121) from the eval code. You can't use it immediately, but it shows that the easiest setup is to just work in global coordinates so you don't need to do any transformations. 
As for `get_sample_data()` it transforms the boxes into the sensor coordinate frame. If that's what you want it will work, but keep in mind that sensor coordinates and ego vehicle coordinates are not the same.

**Comment by giladdiv** [comment]
Thanks,
And does the wlh from `get_sample_data()` is the object size in meters from the LIDAR? or from other source?

**Comment by holger-nutonomy** [comment]
Yes, before and after transforming coordinates to a sensor frame, everything is in meters.

**Comment by Saumya-Shah** [comment]
Can you please repost the link to the function in the eval code you mentioned before? The given hyperlink doesn't work.

**Comment by holger-nutonomy** [comment]
@Saumya-Shah The file was moved to the "common" folder: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/common/loaders.py#L179
