### ISSUE TITLE
How the point cloud semantically segmented file is encoded？

### ISSUE THREAD

**Issue by magical1998** [nutonomy/nuscenes-devkit#1070]
What is the specific encoding method of the point cloud segmentation file, and is it suitable for the first 16 bits of SenmanticKITTI for semantic segmentation, and the last 16 bits for panoramic segmentation?

**Comment by whyekit-motional** [comment]
The labels for each point in a given lidar point cloud is simply a numpy array which is saved into a `.bin` file via numpy's `tofile(...)`: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.tofile.html
