### ISSUE TITLE
Problem with NuScenes format to KITTI format

### ISSUE THREAD

**Issue by FrancoArtale** [nutonomy/nuscenes-devkit#1071]
Hi!!

I'm using the export_kitti.py file, and when i used it with the v1.0-mini dataset of nuscenes i have a problem. In KITTI format we have the next:

<object_type, truncation, occlusion, alpha, left, top, right, bottom, height, width, length, x, y, z, rotation_y>  --> 15 elements

and examples of the output of the export_kitti.py are:
['barrier',  '0.00',  '4',  '-10.00',  '0.00',  '519.72',  '58.90',  '575.55',  '1.1',  '1.64',  '0.36',  '-17.09',  '2.14',  '26.36',  '0.45',  '0.0000'],
['traffic_cone',  '0.00',  '4',  '-10.00',  '49.28',  '521.53',  '65.74',  '566.71',  '0.96',  '0.20',  '0.21',  '-16.70',  '2.09',  '27.20',  '2.07','0.0000'],
['car',  '0.00',  '4',  '-10.00',  '889.41',  '439.58',  '944.63',  '493.10',  '3.1',  '3.24',  '7.10',  '5.73','1.32', '79.10','-1.49','0.0000'],
 
16 elements in each.
![4f545737bf3347fbbc9af60b0be9a963](https://github.com/nutonomy/nuscenes-devkit/assets/145915144/67f7fc3a-e879-4090-86d6-c96cb00706cc)
[4f545737bf3347fbbc9af60b0be9a963.txt](https://github.com/nutonomy/nuscenes-devkit/files/14971982/4f545737bf3347fbbc9af60b0be9a963.txt)

 
What's the problem here?
What does not correspond?

export_kitti.py is in \nuscenes-devkit\python-sdk\nuscenes\scripts\export_kitti.py.

Greetings,
FA.

**Comment by whyekit-motional** [comment]
@FrancoArtale the last element is the classification score for a given box: https://github.com/nutonomy/nuscenes-devkit/blob/4df2701feb3436ae49edaf70128488865a3f6ff9/python-sdk/nuscenes/utils/kitti.py#L410
