### ISSUE TITLE
Conert radar to lidar problems

### ISSUE THREAD

**Issue by xiaobh1519** [nutonomy/nuscenes-devkit#1072]
Excuse me! 
I am currently trying to convert the NuScenes dataset to Kitti format, but I noticed that Kitti does not have radar data. Therefore, I want to convert radar data from NuScenes to Liadr format (and align them). How can I convert radar data to Liadr points in NuScenes?
Translate the above into English:
I am currently looking to convert the NuScenes dataset into Kitti format, but I have found that Kitti does not include radar data. Consequently, I wish to convert the radar data from NuScenes into Liadr format (and align them). How can I transform the radar data into Liadr points within NuScenes?

**Comment by whyekit-motional** [comment]
@xiaobh1519 in the first place, I'm not sure if it's even logical to convert the radar data to the format used by the lidar data, since radar data and lidar data are inherently different (e.g. radar data would have fields like doppler velocity, which are not present in the lidar data)

**Comment by xiaobh1519** [comment]
> @xiaobh1519 in the first place, I'm not sure if it's even logical to convert the radar data to the format used by the lidar data, since radar data and lidar data are inherently different (e.g. radar data would have fields like doppler velocity, which are not present in the lidar data)

I just want to extract the coordinates (x, y, z) of the radar points and convert them to the lidar coordinate system. Do you think this is possible?

**Comment by whyekit-motional** [comment]
If you are talking about transforming radar points to the lidar frame, then yes it is definitely possible - you will just need to construct the relevant transformation matrices
