### ISSUE TITLE
Rotation problem of point cloud object detection

### ISSUE THREAD

**Issue by yinheyanxian** [nutonomy/nuscenes-devkit#1078]
Hello, my question is about rotation.
I see in nuScenes schema that rotation is represented by a quaternion, which means that the 3D bounding box can be rotated in the x, y, and z axes.
![1](https://github.com/nutonomy/nuscenes-devkit/assets/105580694/36ee7575-de38-4b58-b8ed-0aad5a37617f)
However, some point cloud detection libraries, such as MMDetection3d or OpenPCDet, only consider rotation on the z-axis, i.e. only the yaw Angle, when creating training files for the nuscenes dataset.
Is this accurate?  Due to the possibility of some cars going uphill or downhill, they may also rotate on the y-axis. When creating ground truth for these cars, if we don't consider the rotation of the y-axis and only consider the rotation of the z-axis, it may not include all the object points. 
Are my considerations superfluous?
Thank you in advance.

**Comment by whyekit-motional** [comment]
@yinheyanxian you are right to say that if the boxes are sitting on a significant incline, then roll and pitch would become important

For nuScenes, the data was collected on roads which were generally flat, so it is reasonable for users to consider only yaw, similar to what is done here: https://github.com/nutonomy/nuscenes-devkit/blob/4df2701feb3436ae49edaf70128488865a3f6ff9/python-sdk/nuscenes/nuscenes.py#L290

**Comment by yinheyanxian** [comment]
> @yinheyanxian you are right to say that if the boxes are sitting on a significant incline, then roll and pitch would become important
> 
> For nuScenes, the data was collected on roads which were generally flat, so it is reasonable for users to consider only yaw, similar to what is done here:
> 
> https://github.com/nutonomy/nuscenes-devkit/blob/4df2701feb3436ae49edaf70128488865a3f6ff9/python-sdk/nuscenes/nuscenes.py#L290

Thank you for your answer. My question is resolved.
