### ISSUE TITLE
Alignment of multi-frame radar dynamic object data

### ISSUE THREAD

**Issue by lotterf** [nutonomy/nuscenes-devkit#1079]
Hi, the data set published by your team is very helpful to me, thank you and your team for your free effort. However, I still have some questions about the multi-frame radar accumulation in the data set. I found that the self-driving motion had been calibrated and aligned by the self-driving sensors. However, how should I calibrate the speed of various dynamic objects in the scene? It might be possible to use the acquired radial velocity to correct, but I think this would lead to a certain bias.

**Comment by whyekit-motional** [comment]
@lotterf pls take a look at the following:
https://github.com/nutonomy/nuscenes-devkit/blob/4df2701feb3436ae49edaf70128488865a3f6ff9/python-sdk/nuscenes/utils/data_classes.py#L329-L330

if you do not want to use `vx_comp` and `vy_comp`, you can try working with `vx` and `vy`

**Comment by lotterf** [comment]
![微信图片_20240515114646](https://github.com/nutonomy/nuscenes-devkit/assets/109028420/1202463f-76fe-4582-91d4-78a9cfff245c)
Yes, I know that the given vx and vy can be used to correct the data and reduce the error, but I find from the paper that vx and vy can not get the actual speed, I want to know whether there will be any error after correction. If so, I wonder if it will be big?

**Comment by whyekit-motional** [comment]
I don't recall the exact number, but the error shouldn't be too significant, I think

**Comment by lotterf** [comment]
Ok, I get it. Thank you for your patience.

**Comment by HYY-ying** [comment]
> @lotterf pls take a look at the following:
> 
> https://github.com/nutonomy/nuscenes-devkit/blob/4df2701feb3436ae49edaf70128488865a3f6ff9/python-sdk/nuscenes/utils/data_classes.py#L329-L330
> 
> if you do not want to use `vx_comp` and `vy_comp`, you can try working with `vx` and `vy`

Hello, I would like to ask how vx and vy are obtained. What radar can measure is radial velocity and azimuth. Are vx and vy obtained by decomposing radial velocity in radar coordinate system? Is the source code available and where can I find instructions?

**Comment by whyekit-motional** [comment]
@HYY-ying I believe this is internal to the radar
