### ISSUE TITLE
When v1.1.13 will be released in PyPI ?

### ISSUE THREAD

**Issue by toshi-k** [nutonomy/nuscenes-devkit#1080]
Although the latest version of nuscenes-devkit is v1.1.13, it hasn't been available in PyPI yet.
https://pypi.org/project/nuscenes-devkit/

Does anyone know when it will be released ?

**Comment by whyekit-motional** [comment]
@toshi-k there is currently no firm release data for the next version of `nuscenes-devkit`

**Comment by toshi-k** [comment]
@whyekit-motional Thank you for the answer! I'm looking forward to the release of next version, but I close this issue at once.
