### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by Anivie** [nutonomy/nuscenes-devkit#1081]
install failed when install with pip, is there any dependencies too old?
```
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
```

**Comment by whyekit-motional** [comment]
@Anivie I am unable to reproduce your error - `pip install nuscenes-devkit` works on my end:

![image](https://github.com/nutonomy/nuscenes-devkit/assets/62535720/6505364c-3ef8-466a-8b3c-def4aaa2007b)

**Comment by Anivie** [comment]
> @Anivie I am unable to reproduce your error - `pip install nuscenes-devkit` works on my end:
> 
> ![image](https://private-user-images.githubusercontent.com/62535720/331912622-6505364c-3ef8-466a-8b3c-def4aaa2007b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNzk1MTcsIm5iZiI6MTcxNjE3OTIxNywicGF0aCI6Ii82MjUzNTcyMC8zMzE5MTI2MjItNjUwNTM2NGMtM2VmOC00NjZhLThiM2MtZGVmNGFhYTIwMDdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA0MjY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NjZlNzk2ZTUxZDc5YWJjMmU1NTFmOTNiZTE0ZWU3ZmE1Yjc5ZDBlNjgxZmM2MzEzNGZhM2IyZDM4NWZiMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PUwx7Wo5b5oGc7XdKZ2xGleqL4peh9oXfIfmzvrVL8A)

How can I provide specific information to find this problem? Here is the complete error message:
```
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "D:\APPData\Anaconda_Environment\torch\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\APPData\Anaconda_Environment\torch\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\APPData\Anaconda_Environment\torch\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "D:\APPData\Anaconda_Environment\torch\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\APPData\Anaconda_Environment\torch\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Users\anivi\AppData\Local\Temp\pip-build-env-8ojz2fm_\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\anivi\AppData\Local\Temp\pip-build-env-8ojz2fm_\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\anivi\AppData\Local\Temp\pip-build-env-8ojz2fm_\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2191, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by whyekit-motional** [comment]
@Anivie perhaps check the version of python of the environment you are working with

**Comment by Anivie** [comment]
> @Anivie perhaps check the version of python of the environment you are working with

Python version: 3.12.3 on anaconda.
And this is the package installed:
<details>
  <summary>Info</summary>
  <pre><code> 
Package                   Version
------------------------- --------------------
anyio                     4.2.0
argon2-cffi               21.3.0
argon2-cffi-bindings      21.2.0
asttokens                 2.0.5
async-lru                 2.0.4
attrs                     23.1.0
Babel                     2.11.0
beautifulsoup4            4.12.2
bleach                    4.1.0
Brotli                    1.0.9
certifi                   2024.2.2
cffi                      1.16.0
chardet                   5.2.0
charset-normalizer        2.0.4
colorama                  0.4.6
comm                      0.2.1
contourpy                 1.2.1
cycler                    0.12.1
debugpy                   1.6.7
decorator                 5.1.1
defusedxml                0.7.1
executing                 0.8.3
fastjsonschema            2.16.2
filelock                  3.13.1
fonttools                 4.51.0
fsspec                    2024.2.0
idna                      3.7
intel-openmp              2021.4.0
ipykernel                 6.28.0
ipython                   8.20.0
ipywidgets                8.1.2
jedi                      0.18.1
Jinja2                    3.1.3
json5                     0.9.6
jsonschema                4.19.2
jsonschema-specifications 2023.7.1
jupyter                   1.0.0
jupyter_client            8.6.0
jupyter-console           6.6.3
jupyter_core              5.5.0
jupyter-events            0.8.0
jupyter-lsp               2.2.0
jupyter_server            2.10.0
jupyter_server_terminals  0.4.4
jupyterlab                4.0.11
jupyterlab-pygments       0.1.2
jupyterlab_server         2.25.1
jupyterlab-widgets        3.0.10
kiwisolver                1.4.5
MarkupSafe                2.1.3
matplotlib                3.9.0
matplotlib-inline         0.1.6
mistune                   2.0.4
mkl                       2021.4.0
mpmath                    1.3.0
nbclient                  0.8.0
nbconvert                 7.10.0
nbformat                  5.9.2
nest-asyncio              1.6.0
networkx                  3.2.1
notebook                  7.0.8
notebook_shim             0.2.3
numpy                     1.26.4
opencv-python             4.9.0.80
overrides                 7.4.0
packaging                 23.2
pandas                    2.2.2
pandocfilters             1.5.0
parso                     0.8.3
pillow                    10.2.0
pip                       24.0
platformdirs              3.10.0
ply                       3.11
prometheus-client         0.14.1
prompt-toolkit            3.0.43
psutil                    5.9.0
pure-eval                 0.2.2
py-cpuinfo                9.0.0
pycparser                 2.21
Pygments                  2.15.1
pyparsing                 3.1.2
PyQt5                     5.15.10
PyQt5-sip                 12.13.0
PySocks                   1.7.1
python-dateutil           2.8.2
python-json-logger        2.0.7
pytz                      2024.1
pywin32                   305.1
pywinpty                  2.0.10
PyYAML                    6.0.1
pyzmq                     25.1.2
qtconsole                 5.5.1
QtPy                      2.4.1
referencing               0.30.2
requests                  2.31.0
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rpds-py                   0.10.6
scipy                     1.13.0
seaborn                   0.13.2
Send2Trash                1.8.2
setuptools                69.5.1
sip                       6.7.12
six                       1.16.0
sniffio                   1.3.0
soupsieve                 2.5
stack-data                0.2.0
sympy                     1.12
tbb                       2021.11.0
terminado                 0.17.1
thop                      0.1.1.post2209072238
tinycss2                  1.2.1
torch                     2.3.0+cu121
torchaudio                2.3.0+cu121
torchvision               0.18.0+cu121
tornado                   6.3.3
tqdm                      4.66.4
traitlets                 5.7.1
typing_extensions         4.11.0
tzdata                    2024.1
ultralytics               8.2.18
urllib3                   2.2.1
wcwidth                   0.2.5
webencodings              0.5.1
websocket-client          1.8.0
wheel                     0.43.0
widgetsnbextension        4.0.10
win-inet-pton             1.1.0
  </code></pre>
</details>
Is this an known issue? I tried other ways like updating my pip, but it still didn't work

**Comment by whyekit-motional** [comment]
Pls try with python 3.6 or 3.7: https://github.com/nutonomy/nuscenes-devkit?tab=readme-ov-file#devkit-setup
```
The devkit is tested for Python 3.6 and Python 3.7.
```
