### ISSUE TITLE
Navigation. How can I get waypoints from (x1,y1) to (x2 y2) in nuscenes map

### ISSUE THREAD

**Issue by 16Huzeyu** [nutonomy/nuscenes-devkit#1083]
I know I can get the road id which the point(x1,x2) is in . How can I get waypoints from (x1,y1) to (x2 y2) in nuscenes map?

**Comment by whyekit-motional** [comment]
@16Huzeyu do explore `arcline_path_utils` from `nuscenes.map_expansion` - it can be used like so: 
```python
poses = arcline_path_utils.discretize_lane(lane_record, resolution_meters=1)
```

**Comment by 16Huzeyu** [comment]
@whyekit-motional Thank you for your reply!! This api can give me waypoints in one road but what I also need is how to get the road ids between (x1,y1) and (x2,y2).Then I can use arcline_path_utils.discretize_lane to get all waypoints in these road.So firstly,how can I get  road ids between (x1,y1) and (x2,y2).

**Comment by 16Huzeyu** [comment]
@whyekit-motional  It is like a Shortest path problem .How can i pass from (x1, y1) to (x2, y2) ,I want to find a shortest path,and the road ids are the nodes in path.

**Comment by whyekit-motional** [comment]
@16Huzeyu for this, you would need to write up your own algorithm to determine the shortest path
