### ISSUE TITLE
Cannot download anything

### ISSUE THREAD

**Issue by jamesheatonrdm** [nutonomy/nuscenes-devkit#1084]
None of the links on the download page appear to be working. I have tried with Firefox, Chrome and Edge on two different devices. The actual links to the downloads appears to just be the downloads page itself.

**Comment by whyekit-motional** [comment]
@jamesheatonrdm the download links seem to be working for me:
![Screenshot from 2024-05-31 09-13-15](https://github.com/nutonomy/nuscenes-devkit/assets/62535720/69d1ddd0-b078-4f12-a101-f502a5cfa0f5)

**Comment by jamesheatonrdm** [comment]
@whyekit-motional 

I've just tried again this time on another device and still the same issue.

Possibly a problem with my account?
I certainly verified it though so I'm not sure.

**Comment by whyekit-motional** [comment]
@jamesheatonrdm pls provide more details (what steps did you go through / what did you click to get that error message, the username you are using on nuscenes.org, etc.)

**Comment by jamesheatonrdm** [comment]
@whyekit-motional 

Sorry that image is when I go to verify my account again. As you can see it says it's confirmed.

The email address I am using is jheaton@aurrigo.com 

The only steps I take are
1. Login
2. go to the nuscenes download page at https://www.nuscenes.org/download and attempt to click the download links. Any of them (USA or Asia) do not start any downloads, they just reload the page

**Comment by whyekit-motional** [comment]
Thanks for the details @jamesheatonrdm, we are looking into your issue so pls hang tight!

**Comment by whyekit-motional** [comment]
@jamesheatonrdm pls try downloading again
