### ISSUE TITLE
how does the start angle and end angle of the lidar to project to the image with the moving object

### ISSUE THREAD

**Issue by ZOUYIyi** [nutonomy/nuscenes-devkit#1085]
I konw that the camera triggered when the lidar swap the center of the camera , but supose the lidar frame start and end in the back of the car ,then the back camera just half frame with the lidar ,anther half frame is 100ms behand the lidar , if some moving object in there , it cant be properly project to the image, how to solve this case in the nuscenes?

**Comment by whyekit-motional** [comment]
@ZOUYIyi I believe there is some mechanism (that is internal to the lidar) to handle this
