### ISSUE TITLE
can_bus assignment to key frames?

### ISSUE THREAD

**Issue by seamie6** [nutonomy/nuscenes-devkit#1086]
Hello, I am wondering if for the can_bus expansion, there is a look-up table for mapping measurements to keyframes or frames by say supplying a token. For a given scene you can expect 40 key frames, but for the can_bus expansion for the pose field, there are 938 measurements.

A manual way I can think of is just taking the keyframes timestamp and looking for the closest match inside of 'pose' but is there a built-in way to perform this? Thank you

**Comment by whyekit-motional** [comment]
@seamie6 there isn't a built-in way to do what you described, but I think the manual way which you suggested would work fine
