### ISSUE TITLE
why is the steering angle so big?

### ISSUE THREAD

**Issue by nunuisacat** [nutonomy/nuscenes-devkit#1087]
Hi, thanks for the nice dataset.
I have a question regarding the value interval of steering angle feedback data.
Normally the steering angle should be within minus plus 30 Degree, which corresponds to radians [-0,5, +0.5], but why the interval in canbus recording is [-7.7, 6.3]? 
Did I misunderstand anything?
Thanks for the help.

**Comment by whyekit-motional** [comment]
@nunuisacat pls provide a working code snippet to reproduce your observation

**Comment by nunuisacat** [comment]
> @nunuisacat pls provide a working code snippet to reproduce your observation

Hello, thanks for the kind and in-time reply.
Here are the code:
`
    from nuscenes.can_bus.can_bus_api import NuScenesCanBus
    from nuscenes.nuscenes import NuScenes

    nusc = NuScenes("v1.0-mini", "/data/nuscenes")
    nusc_can = NuScenesCanBus(dataroot="/data/nuscenes")

    scene_name =nusc.scene[1]["name"]
    # get the steer angle feedback from the can bus
    saf = nusc_can.get_messages(scene_name, "steeranglefeedback")

    # use the bicycle model:  steering_angle/wheelbase = curvature  to calculate the curvature
    Kappa = saf[-1]['value'] / 2.588 

I aim to use the steering angle to calculate the needed trajectory curvature.   
since saf[-1]['value']=3.06 thus Kappa = 3.06/2.588 = 1.18,  the turning radius 1/Kappa will be smaller
than 1m, which is obvious not possible.
Thanks for the help.:)

**Comment by whyekit-motional** [comment]
@nunuisacat if the driver turns the steering wheel with multiple revolutions (e.g. during a strong left / right turn), then the steering angle would be large
