### ISSUE TITLE
Untar files

### ISSUE THREAD

**Issue by bertoni9** [nutonomy/nuscenes-devkit#109]
Hello,

When I untar the files **v1.0-trainval\*_blobs.tgz** on a Ubuntu 18.04.1 LTS, it gives me the following error:
```
sweeps/RADAR_FRONT/n015-2018-07-27-11-36-48+0800__RADAR_FRONT__1532663153790733.pcd

gzip: stdin: invalid compressed data--crc error
sweeps/RADAR_FRONT/n008-2018-07-26-12-13-50-0400__RADAR_FRONT__1532622141160534.pcd
sweeps/RADAR_FRONT/n015-2018-07-27-11-36-48+0800__RADAR_FRONT__1532663021491223.pcd
.v1.0-trainval02_blobs.txt
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

The command I run is `tar xvzf <filename>`

Thank you very much

**Comment by holger-nutonomy** [comment]
Could you check that your md5 hash matches that from the Download page for that archive file?

**Comment by bertoni9** [comment]
Indeed, it is different. I will try to download them again, thank you for your quick answer.
