### ISSUE TITLE
How is the nuScenes raster map created?

### ISSUE THREAD

**Issue by zehranrgi** [nutonomy/nuscenes-devkit#1092]
I couldn’t find any sources to learn about it, either from papers or through searching. Could you provide some insights, please? (I mean if there is any software etc. I want to create my raster map for my dataset.)
 
example image: 
![image](https://github.com/nutonomy/nuscenes-devkit/assets/70450368/0e45ad3d-da0b-45ca-bfec-5200fdb5f9bd)

**Comment by whyekit-motional** [comment]
@zehranrgi in-house software was used for creating the raster maps in nuScenes
