### ISSUE TITLE
Problem between nuscenes and kitti

### ISSUE THREAD

**Issue by FrancoArtale** [nutonomy/nuscenes-devkit#1093]
Hello, I hope you are doing well.

I have a question regarding the script nuscenes-devkit/python-sdk/nuscenes/scripts/export_kitti.py.

My question is: does this script take into account the height difference between the two datasets? I am referring to the fact that in KITTI the camera height is 1.65 meters and in nuScenes it is 1.8403 meters if I am not mistaken. Is this considered? If not, for example, could I add 0.1903 meters to the z-coordinate of each object in the KITTI dataset, or conversely subtract 0.1903 meters from the z-coordinate of each object in the nuScenes dataset?

Best regards,
FA

**Comment by FrancoArtale** [comment]
Hello, is there someone there?

**Comment by whyekit-motional** [comment]
@FrancoArtale the annotations in nuScenes are in the global frame, so they are independent of the mounting height of the sensors
