### ISSUE TITLE
Where can I find the md5 of a downloaded file?

### ISSUE THREAD

**Issue by zhcm** [nutonomy/nuscenes-devkit#1094]

**Comment by whyekit-motional** [comment]
@zhcm we will update [nuscenes.org/donw](https://www.nuscenes.org/nuscenes#download) with the md5 hashes once we have them

**Comment by chloexiangyy** [comment]
> @zhcm we will update [nuscenes.org/donw](https://www.nuscenes.org/nuscenes#download) with the md5 hashes once we have them

Hi! So that means we need to wait for maybe several days?

**Comment by dinggh0817** [comment]
Perhaps the sha256sum of my copy could be your reference.

`$ sha256sum ./v1.0-trainval_meta.tgz ./v1.0-trainval01_blobs.tgz ./v1.0-trainval02_blobs.tgz ./v1.0-trainval03_blobs.tgz ./v1.0-trainval04_blobs.tgz ./v1.0-trainval05_blobs.tgz ./v1.0-trainval06_blobs.tgz ./v1.0-trainval07_blobs.tgz ./v1.0-trainval08_blobs.tgz ./v1.0-trainval09_blobs.tgz ./v1.0-trainval10_blobs.tgz `

`668f991320b28832cb0d89fa4c6ea170682e523337eada585dab3be40d4c322d  ./v1.0-trainval_meta.tgz
b098fe4690b58bbae893918e8b99f7a016376f3cbe3b0d3ebf7521808bf851e8  ./v1.0-trainval01_blobs.tgz
cf9e91dd48fd7cbbeb2f70640ec31ccf10de17077c4b710d38bd63eed052c01d  ./v1.0-trainval02_blobs.tgz
bb54a48ab0ea009557c95525ec81034164f6a84f6d3ce19d7b4d8b70465cc4ae  ./v1.0-trainval03_blobs.tgz
79d20e6cba75fdd1fbe0aab53aa3850b5eb3fe931c6ab3470616639b2c4828d0  ./v1.0-trainval04_blobs.tgz
5e6681042c4f0740c00ecaaf46efb74082150849b56f139001addae08d29dc97  ./v1.0-trainval05_blobs.tgz
b1360d2a7810759b71bbdc0bc4c58a9f70cd4e0b12a9e37b61176ba78f14cecd  ./v1.0-trainval06_blobs.tgz
8c017f5d615dca99d5f8ee91b91b23b9128ed16b0ab271329d25f25861301dcb  ./v1.0-trainval07_blobs.tgz
3855efc7776fb1235e9e53dd35bc7a3cbf78f06e3e23cdb4d5881ddff6985f9c  ./v1.0-trainval08_blobs.tgz
a96c591b4467ba3bef067fe76e5c58192c31386983ef685a63132c49f5484cfc  ./v1.0-trainval09_blobs.tgz
4eef3fc729712ce0bfb1d74bdcc554d9c954fd58b15024bd4be34f5006eede90  ./v1.0-trainval10_blobs.tgz`


`$ sha256sum ./v1.0-test_meta.tgz ./v1.0-test_blobs.tgz`

`c5f5169875eead4874fc345235e3fc9a4b60dcad42a18386a824a1d1d58f3ed6  ./v1.0-test_meta.tgz
98534ec5cc89e6b710fd5944035abdf9655a030b51931ead651a06a23a2537df  ./v1.0-test_blobs.tgz`
