### ISSUE TITLE
Where is the global coordinate frame of the lines?

### ISSUE THREAD

**Issue by mmahdavian** [nutonomy/nuscenes-devkit#1096]
Hello. I am using Nuscenes to get line vectors using the map extractor. I use a function like this:
`map_geoms = self.map_extractor.get_map_geom(location, lidar2global_translation, lidar2global_rotation)
`
The location is map name and the next two inputs are global lidar translation and rotation. The map_geoms contains LineStrings in shapely format and I need to know the global coordinate frames of the lines. Are they defined with respect to ego vehicle or the global map coordinate frame?

Thank You

**Comment by whyekit-motional** [comment]
@mmahdavian the map objects in nuScenes are in the global coordinate frame
