### ISSUE TITLE
Unable to import NuScenesMap in Google Colab

### ISSUE THREAD

**Issue by Hoang-it** [nutonomy/nuscenes-devkit#1097]
Hello, I'm trying to run the prediction_tutorial.ipynb. While I'm running, I face the issue with NuScenesMap when running these code 
`from nuscenes.map_expansion.map_api import NuScenesMap
nusc_map = NuScenesMap(map_name='singapore-onenorth', dataroot=DATAROOT)`

These are the stacktrace of this:
`
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/matplotlib/docstring.py](https://localhost:8080/#) in __missing__(self, key)
     60         try:
---> 61             cls, = [cls for cls in _recursive_subclasses(Artist)
     62                     if cls.__name__ == name]

ValueError: too many values to unpack (expected 1)

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
5 frames
[<ipython-input-19-1ea97ee625c2>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from nuscenes.map_expansion.map_api import NuScenesMap
      2 nusc_map = NuScenesMap(map_name='singapore-onenorth', dataroot=DATAROOT)

[/usr/local/lib/python3.10/dist-packages/nuscenes/map_expansion/map_api.py](https://localhost:8080/#) in <module>
     18 from matplotlib.figure import Figure
     19 from matplotlib.patches import Rectangle, Arrow
---> 20 from mpl_toolkits.axes_grid1.inset_locator import mark_inset
     21 from pyquaternion import Quaternion
     22 from shapely import affinity

[/usr/local/lib/python3.10/dist-packages/mpl_toolkits/axes_grid1/inset_locator.py](https://localhost:8080/#) in <module>
    354 
    355 @docstring.dedent_interpd
--> 356 def inset_axes(parent_axes, width, height, loc='upper right',
    357                bbox_to_anchor=None, bbox_transform=None,
    358                axes_class=None, axes_kwargs=None,

[/usr/local/lib/python3.10/dist-packages/matplotlib/docstring.py](https://localhost:8080/#) in __call__(self, obj)
     82 
     83     def __call__(self, obj):
---> 84         super().__call__(obj)
     85         if isinstance(obj, type) and obj.__init__ != object.__init__:
     86             self(obj.__init__)

[/usr/local/lib/python3.10/dist-packages/matplotlib/docstring.py](https://localhost:8080/#) in __call__(self, func)
     36     def __call__(self, func):
     37         if func.__doc__:
---> 38             func.__doc__ = inspect.cleandoc(func.__doc__) % self.params
     39         return func
     40 

[/usr/local/lib/python3.10/dist-packages/matplotlib/docstring.py](https://localhost:8080/#) in __missing__(self, key)
     62                     if cls.__name__ == name]
     63         except ValueError as e:
---> 64             raise KeyError(key) from e
     65         return self.setdefault(key, kwdoc(cls))
     66 

KeyError: 'Axes:kwdoc'
`

Can u help me resolve this?
Regard,
HN

**Comment by whyekit-motional** [comment]
@Hoang-it try checking the version of `matplotlib` used in Colab

**Comment by AII6** [comment]
> @Hoang-it try checking the version of `matplotlib` used in Colab

Hello, I checked the version of `matplotlib` used in Colab and it satisfy the requirement. I also tried other versions but they all occured the abover errors.

**Comment by whyekit-motional** [comment]
@AII6 I can't seem to reproduce your error - perhaps sharing your Colab notebook would help
