### ISSUE TITLE
Missing LIDAR_TOP files

### ISSUE THREAD

**Issue by safetylab24** [nutonomy/nuscenes-devkit#1099]
We are trying to load in the nuScenes dataset, but there's always LIDAR_TOP files missing. 

For context, we are trying to use CenterPoint for 3D Object detection: [Paper](https://arxiv.org/pdf/2006.11275).

Here is the exact error message: 
FileNotFoundError: [Errno 2] No such file or directory: '/home/vrb230004/media/datasets/nuscenes/sweeps/LIDAR_TOP/n015-2018-07-18-11-07-57+0800__LIDAR_TOP__1531883530649557.pcd.bin'

It seems the model is trying to pull data that is listed in the sample_data.json, but it can't find it in the folders. We also tried reinstalling the NuScenes dataset multiple times but we still were not able to fix this issue. Even though this is specific to CenterPoint, has anyone faced this issue before? How did you go about solving it?

**Comment by whyekit-motional** [comment]
@safetylab24 pls check if the path to your `data_root` is correct

**Comment by safetylab24** [comment]
The issue was actually just that we weren't downloading the LIDAR blobs on nuscenes. We just downloaded the keyframes. Thanks for the help!
