### ISSUE TITLE
Camera Data Synchronization

### ISSUE THREAD

**Issue by StepTurtle** [nutonomy/nuscenes-devkit#1100]
Hi,

I want to ask a question about the synchronization about sensors. Let first share some graphs I obtained.

This one shows the timestamps which obtained from rosbag which is created with [this tool](https://github.com/clynamen/nuscenes2bag)

![nuScenes](https://github.com/user-attachments/assets/89b917dd-3f5f-4ed9-adb6-936da384c3f7)

This one shows the timestamps which obtained with nuscenes-devkit tool and visualized with matplotlib.

![Figure_1](https://github.com/user-attachments/assets/585747d8-eb52-43ae-a9eb-6d079224b072)

It was stated in the paper that the cameras are synchronized. I thought all the cameras would have close timestamps, but as shown in this graph, they come in sequence following a certain pattern. In this case, the time difference between `CAM_BACK` and `LIDAR_FRONT` becomes quite large, and `CAM_BACK` even coincides with a new lidar frame.

Therefore, my question is, what should I do if I want the sensors to be closer in time to each other? Since the gaps between the camera data are relatively consistent, do you think it would be a problem if I work by ignoring these differences?

Or do you have any suggestions on what to do if I want to use the sensors in sync?

```
Gaps between sensor times:

Two Lidar Message: ~0:00:00.050318 (50 ms)

Lidar and Front Left Camera: ~0:00:00.007532 (7 ms)
Lidar and Front Camera: ~0:00:00.015148 (15 ms)
Lidar and Front Right Camera: ~0:00:00.022975 (22 ms)
Lidar and Back Right Camera: ~0:00:00.031937 (31 ms)
Lidar and Back Camera: ~0:00:00.040728 (40 ms)
Lidar and Back Left Camera: ~0:00:00.049703 (49 ms)
```

**Comment by whyekit-motional** [comment]
@StepTurtle if your use the keyframes, the sensor data for each keyframe would have already been synced for you (pls see `Sensor synchronization` at https://www.nuscenes.org/nuscenes#data-collection for details)
