### ISSUE TITLE
After converting to kitti format, the alpha angles in the fourth bit are all -10, is this normal? Shouldn't this value be -pi to pi in kitti format?

### ISSUE THREAD

**Issue by liaopan-lp** [nutonomy/nuscenes-devkit#1101]
As the title suggests, happy coding!

**Comment by whyekit-motional** [comment]
@liaopan-lp pls provide more details of the issue you are facing (code snippet for reproducibility, example output, etc.)

**Comment by haidongqing2022** [comment]
I had the same problem with me, how did you solve it.like this:pedestrian 0.00 0 -10.00 1575.11 486.96 1600.00 551.27 1.6 0.62 0.67 20.38 1.53 33.10 -3.08 0.0000
bicycle 0.00 0 -10.00 1542.08 474.87 1600.00 539.88 1.7 0.69 1.77 20.81 1.28 34.42 3.04 0.0000
pedestrian 0.00 0 -10.00 704.67 453.99 730.60 505.98 1.8 0.63 0.69 -3.40 0.48 43.58 -2.06 0.0000
truck 0.00 0 -10.00 128.04 404.18 293.79 479.40 3.2 2.51 6.45 -27.72 -0.64 58.10 0.10 0.0000
pedestrian 0.00 0 -10.00 822.48 456.92 849.18 508.08 1.8 0.70 0.91 0.69 0.56 44.44 -1.32 0.0000
motorcycle 0.00 0 -10.00 135.75 446.30 206.78 496.47 1.3 0.84 2.23 -17.91 0.10 35.15 0.64 0.0000
barrier 0.00 0 -10.00 667.14 472.08 721.71 502.74 1.2 2.07 0.62 -4.88 0.42 50.75 -1.46 0.0000
barrier 0.00 0 -10.00 1229.37 490.93 1278.98 515.78 1.1 2.14 0.70 20.86 1.11 60.36 -1.34 0.0000
pedestrian 0.00 0 -10.00 779.25 468.71 806.62 527.82 1.6 0.65 0.71 -0.64 0.99 35.14 0.00 0.0000
car 0.00 0 -10.00 1275.77 466.21 1519.05 611.08 1.6 1.71 4.01 7.45 1.33 16.69 -1.46 0.0000
pedestrian 0.00 0 -10.00 1574.16 483.66 1600.00 548.17 1.7 0.79 0.74 21.43 1.52 34.74 3.13 0.0000
barrier 0.00 0 -10.00 1540.16 495.00 1600.00 523.57 1.2 2.26 0.71 34.47 1.41 57.89 -0.68 0.0000
car 0.00 0 -10.00 619.54 446.13 748.99 502.54 2.2 2.13 4.96 -5.43 0.37 52.48 0.10 0.0000
pedestrian 0.00 0 -10.00 813.95 458.05 843.42 515.43 1.8 0.77 0.95 0.41 0.76 41.40 -1.39 0.0000
barrier 0.00 0 -10.00 1578.36 513.89 1600.00 600.30 0.96 1.97 0.70 10.71 1.29 16.28 -3.08 0.0000
barrier 0.00 0 -10.00 1433.18 493.33 1488.55 520.00 1.1 2.00 0.63 27.68 1.19 54.40 -1.48 0.0000
