### ISSUE TITLE
Camera/LiDAR/Radar Coordinate System exact origin

### ISSUE THREAD

**Issue by seamie6** [nutonomy/nuscenes-devkit#1102]
I have a quick question about the origin of the camera coordinate system. I am looking for the exact positioning of this origin relative to the camera. Is the origin located at the centre point of the camera's outer lens,is it located at the centre of the camera fixture, or perhaps somewhere else? Also say for LiDAR and radar, where is the origin located?

Thank you.

**Comment by whyekit-motional** [comment]
@seamie6 pls check out the [`calibrated_sensor`](https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/schema_nuscenes.md#calibrated_sensor) records

**Comment by JillianaaaCHEN** [comment]
> @seamie6 pls check out the [`calibrated_sensor`](https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/schema_nuscenes.md#calibrated_sensor) records

Thanks for the answer.
I have another question: the "calibrated_sensor records" you pointed out say that all extrinsics are relative to the ego vehicle body frame. But in the Data Collection section of nuscenes on the official website, it says "the transformation matrix from camera to LIDAR by aligning the planes of the calibration target", which means that the camera extrinsic parameters are calibrated relative to the lidar. 
Which description should be correct?

**Comment by seamie6** [comment]
> @seamie6 pls check out the [`calibrated_sensor`](https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/schema_nuscenes.md#calibrated_sensor) records

Thanks for the reply, I understand from this I can get coordinates of the origin of the cameras relative to the ego-vehicle. However, I am not necessarily looking for the point values relative to the ego-vehicle, more so I am looking for the positioning of this origin relative to the physical camera sensor. Is there any way I can figure out this? Referring back to my original question, I am wondering if this origin is centred on the lens, the actual camera fixture etc.

**Comment by whyekit-motional** [comment]
@seamie6 information about where the origin of the camera (i.e. its optical center) lies on the camera itself is not available

As a side note: generally, the only information needed is the optical center, which is what's used for projecting light using the projection model (this optical center is provided in the [`calibrated_sensor`](https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/schema_nuscenes.md#calibrated_sensor) records as I've mentioned above)
