### ISSUE TITLE
[Help Wanted] Get map elements pose

### ISSUE THREAD

**Issue by bjzhb666** [nutonomy/nuscenes-devkit#1103]
Thanks for your great work. I want to get the pose (global coordinate system) of map elements (e.g., 'road_divider' 'lane_divider' 'ped_crossing'  'contours', etc.). What should I do?

**Comment by bjzhb666** [comment]
Oh, I found it in the tutorial. Thanks

**Comment by bjzhb666** [comment]
there is One more thing I want to check. **Does this pose (in the red box) represent the center line of a lane or the lane line (boundary) of a lane?** Thanks
![image](https://github.com/user-attachments/assets/83e176c3-2c63-478d-b488-25dc6f31bee6)

**Comment by whyekit-motional** [comment]
@bjzhb666 it should be the center-line of a lane

**Comment by bjzhb666** [comment]
Thanks for your response. However, I found some GT center lines are not located at the center of the lane, but at the boundary. Is this caused by the offset mentioned in https://github.com/nutonomy/nuscenes-devkit/issues/144#issuecomment-500073604? Thanks!
![image](https://github.com/user-attachments/assets/f724bb3b-ca87-488e-ae24-192d5c30984e)

**Comment by whyekit-motional** [comment]
@bjzhb666 that is possible

**Comment by bjzhb666** [comment]
Thanks for your response. We found most center lines are correctly located in the middle of the lane. The image provided above is a special case.
![image](https://github.com/user-attachments/assets/52bfe031-b4c1-4304-abb4-50f342ec38f3)
