### ISSUE TITLE
About how to get the data of maps

### ISSUE THREAD

**Issue by bhsh0112** [nutonomy/nuscenes-devkit#1104]
Hi,

Can you please explain how can I get the data of a new map,with the same structure in "maps" folder.
I just got some map data store in .xodr(OpenDrive) format.I want to convert it to what the data of maps like in nuscenes,but I can't realise it.Do you have some tools to solve that problem?

Thanks!

**Comment by whyekit-motional** [comment]
@bhsh0112 you need to write your own scripts to convert the maps from `.xodr` format to the format used in nuScenes

**Comment by bhsh0112** [comment]
> @bhsh0112 you need to write your own scripts to convert the maps from `.xodr` format to the format used in nuScenes

Thans for your response!

Can you please tell me that the data of maps in nuscenes comes from what format of data and if you have scripts to convert it to the .json format used in nuScenes?

Thanks!

**Comment by whyekit-motional** [comment]
@bhsh0112 the maps were converted from an internal tool and file format, which cannot be made public

**Comment by bhsh0112** [comment]
> @bhsh0112 the maps were converted from an internal tool and file format, which cannot be made public
Thanks for your response!

**Comment by whyekit-motional** [comment]
Closing this issue since it has been addressed
