### ISSUE TITLE
coordinate

### ISSUE THREAD

**Issue by xiaobh1519** [nutonomy/nuscenes-devkit#1105]
I selected two clips of data from the can_bus_pose, both representing left turns, and found that their orientation values are completely different, and their variation trends are also different. I'd like to know what orientation represents and in which coordinate system it is defined. And if it is in a world coordinate system, where is the origin located?
![image](https://github.com/user-attachments/assets/e31391cf-bfdb-431c-8ca5-e4a4fe72f69e)
The orientation data is like this format：xxxx，0，0，xxxx，so i just compare the first number and the last number

![image](https://github.com/user-attachments/assets/922828d5-fe59-49ac-9bc0-60c469c96de0)

**Comment by whyekit-motional** [comment]
@xiaobh1519 by "orientation", I assume you mean the `orientation` field from the [`pose` records](https://github.com/nutonomy/nuscenes-devkit/tree/master/python-sdk/nuscenes/can_bus#pose) of the CAN bus expansion - the orientation given is a quaternion, so you might want to convert it to row, pitch and yaw first
