### ISSUE TITLE
extrinsic matrix between RADAR_FRONT and LiDAR

### ISSUE THREAD

**Issue by HAMA-DL-dev** [nutonomy/nuscenes-devkit#1106]
Hello,

Thank you very much for providing this dataset.

I am currently working on transforming the LiDAR point cloud under the assumption that the LiDAR in the nuScenes dataset is positioned where the RADAR_FRONT is located. This is because we need to use a front-facing LiDAR instead of a front-facing RADAR in our lab's vehicle. In other words, our ultimate goal is to obtain a point cloud with the LiDAR positioned at a lower height than before and train the model to correctly identify objects.

However, I was unable to find the extrinsic matrix between the RADAR_FRONT and LiDAR in the nuScenes dataset, and I would like to seek your advice regarding this matter.

Best regards,

**Comment by whyekit-motional** [comment]
@HAMA-DL-dev the extrinsics of each sensor wrt the ego is given in the [`calibrated_sensor`](https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/schema_nuscenes.md#calibrated_sensor) records

From there, you can derive the transformation matrix between any pair of sensor you desire

**Comment by HAMA-DL-dev** [comment]
> you can derive the transformation matrix between any pair of sensor you desire

I apologize for not checking thoroughly due to my impatience. I will be more careful before opening an issue next time. Thank you for your prompt reply.

**Comment by whyekit-motional** [comment]
No worries :smile: closing this issue now, since it has been addressed
