### ISSUE TITLE
How to obtain the point cloud based HD prior map?

### ISSUE THREAD

**Issue by maSiki29** [nutonomy/nuscenes-devkit#1108]
I would like to use the nuScenes dataset for localization. In my work, I need a point cloud-based prior map. However, I only see the 2D layer-based map in the NuScenesMap class, like in the following figure. Is there any way to create a HD point cloud map, similar to the sample data from LIDAR_TOP?

<img width="529" alt="截圖 2024-08-21 下午6 26 08" src="https://github.com/user-attachments/assets/512cc027-8c68-44a2-9145-0bf427457fd1">

**Comment by whyekit-motional** [comment]
@maSiki29 only the 2D layer-based maps are available
