### ISSUE TITLE
Devkit with the mini dataset?

### ISSUE THREAD

**Issue by AnneCCollin** [nutonomy/nuscenes-devkit#111]
Hello,

I'd like to play around with some of the scenes of the newly released dataset, but I see on the devkit readme: "For the devkit to work you will need to download all archives"; does that mean we have to download the whole 250GB of data for the provided notebook to work?

I've seen the rendered notebook online, which is great, but I'd like to run some things on my laptop. Is there a way to just work with the mini version?

**Comment by Alex-nutonomy** [comment]
The notebook itself will work with the mini, but to use the full devkit code you will need all the data.
