### ISSUE TITLE
Meanings of 5 dimensions of input LiDAR points

### ISSUE THREAD

**Issue by Terencedu** [nutonomy/nuscenes-devkit#1110]
Hi teams,

I see LiDAR pcd.bin file is a array of shape (34752, 5).

What are the meanings of these 5 dimensions? Because I want to replace it with my custom LiDAR data.

Dimension[:3] is x, y, z position of the LiDAR point in LiDAR coordinate？X-axis points to the right, the y-axis points forward, and the z-axis points upwards.

What about dimension[-2] and dimension[-1]? They are all integers.

Thank you for your help!

![image](https://github.com/user-attachments/assets/e7a9c717-deb7-4c67-b1b2-523f4cacf2f9)

**Comment by whyekit-motional** [comment]
@Terencedu pls see https://github.com/nutonomy/nuscenes-devkit/blob/4df2701feb3436ae49edaf70128488865a3f6ff9/python-sdk/nuscenes/utils/data_classes.py#L249

**Comment by Terencedu** [comment]
I got it. Thank you very much!
