### ISSUE TITLE
Which one is the IMU data? ego_pose.json/V1.0-trainval, scene-xxxx_ms_imu.json/can_bus, or scene-xxxx_pose.json/can_bus?

### ISSUE THREAD

**Issue by Rango-T10000** [nutonomy/nuscenes-devkit#1111]
Dear authors:

Thanks for your valuable dataset. I have a question about IMU data.
In this dataset, I find the quaternion(w, x, y, z ) is used to express the 3D rotation of ego car in this dataset.
However, I find that the quaternion(w, x, y, z ) shows in the following different files:

1.  ego_pose.json/V1.0-trainval:
<img width="625" alt="image" src="https://github.com/user-attachments/assets/20b19d32-1ad1-4b88-9007-6f8f9178d2f9">

2. scene-xxxx_ms_imu.json/can_bus:
<img width="1341" alt="image" src="https://github.com/user-attachments/assets/9eecbbe7-b11d-4ed8-8148-260d447b3370">

3. scene-xxxx_pose.json/can_bus:
<img width="1347" alt="image" src="https://github.com/user-attachments/assets/bd48bb37-2095-4174-9d44-b1a75b179e30">

I am confused about all these quaternion(w, x, y, z ), so which one is the real IMU data for the ego car?
Could you please help me with that?

**Comment by whyekit-motional** [comment]
The quaternions in `*_imu.json` are from the raw IMU data, while those in `ego_pose.json` and `scene_*_pose.json` are the outputs of a lidar map-based localization algorithm
