### ISSUE TITLE
Wrong Stop Sign in Map Expansion

### ISSUE THREAD

**Issue by SaraMo14** [nutonomy/nuscenes-devkit#1112]
Hi, 

In scene 0159 (singapore one-north) there is a yield sign which is classified as STOP_SIGN in the map expansion.

These are the sign details in the map:
{'token': '496167e7-7ea7-40fb-bf97-ad0def0f58c4', 'polygon_token': '2f77c181-47ba-419f-81d5-382381e33975', 'stop_line_type': 'STOP_SIGN', 'ped_crossing_tokens': [], 'traffic_light_tokens': [], 'road_block_token': '45997e53-13ec-40d7-af82-3ca7b9fb6561', 'exterior_node_tokens': ['903f28d9-fd2f-4ce6-b054-3da3e11624fa', '91787110-89ac-42ee-9387-a22d7fe03ca9', '08a114f9-7d12-47aa-8a5a-ac31bd2fc083', '0219907a-ff2e-4184-b93f-e853854f6e4d', '0d46a11f-d06b-4b6f-8171-35ef0b7328e7', '481e09cb-572e-4754-827f-2dcebd5d66c2', 'f4f8c4fb-01ab-4913-aeb6-746170d7273f'], 'holes': [], 'cue': []}

Is this possible or am i mistaken?

**Comment by whyekit-motional** [comment]
@SaraMo14 try rendering the stop-line record in the camera frame to see if there's a stop-sign around, e.g.:
```python
sample_token = # Select a sample token from scene-0159.

nusc_map.render_map_in_image(
    nusc, sample_token, layer_names=["stop_line"], camera_channel="CAM_FRONT"
)
```
