### ISSUE TITLE
Question about ego_pose

### ISSUE THREAD

**Issue by sgtziggy** [nutonomy/nuscenes-devkit#1113]
Hi, I am a student who is learning to use the nuscenes dataset, sorry to ask a very simple question. I want to ask if the first two terms of translation in ego_pose and instance in the data set are the x and y coordinates? Why do they appear to have absolute values in the same coordinate, but ego_pose is negative?
![Uploading 1725954755279.jpg…]()

**Comment by sgtziggy** [comment]
![1725954755279](https://github.com/user-attachments/assets/40ffdf36-d3be-4f4b-acfe-017b86d28983)

**Comment by whyekit-motional** [comment]
@sgtziggy pls refer to the schema, in particular for [`ego_pose`](https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/schema_nuscenes.md#ego_pose) and [`sample_annotation`](https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/schema_nuscenes.md#ego_pose)
