### ISSUE TITLE
Radar based detection task and evaluation

### ISSUE THREAD

**Issue by SM1991CODES** [nutonomy/nuscenes-devkit#1114]
Hello,
I am trying to adapt a lidar object detector for radar data and would like to benchmark it.
However, I see an issue that due to the lower mounting position of radars, it's FOV to the sides is fairly limited.

Therefore, a lot of annotations would actually end up on totally empty space in radar point cloud.
![image](https://github.com/user-attachments/assets/1bb43e30-6c26-4617-80f0-19d2a711a7fa)

The red boxes mark object centers.

One solution I can think of is - limit the y-axis to street width (25 meters on either side approx)

But for this, the evaluation also needs to ignore GT beyond this range on y-axis.
How may I do this? Or is there a a better solution?

Best Regards
Sambit

**Comment by whyekit-motional** [comment]
During evaluation, boxes which do not have any points in them will get filtered out: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/common/loaders.py#L231

However, note that `num_pts` is the sum of both the number of lidar points and the number of radar points: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/common/loaders.py#L137

So you could modify that to consider only radar points, which should help to remove boxes which do not contain any radar points when you run your evaluation
