### ISSUE TITLE
How to detect objects within different speed ranges and different distance ranges

### ISSUE THREAD

**Issue by Distrber** [nutonomy/nuscenes-devkit#1116]
Test as shown in the table below
![image](https://github.com/user-attachments/assets/1c4a5cad-86ac-4b4c-86cd-4e68083ef9bd)
![image](https://github.com/user-attachments/assets/35b08c82-b5fc-4765-ac49-02c91e27a8cc)

**Comment by whyekit-motional** [comment]
@Distrber pls reach out to the authors of the paper regarding your question
