### ISSUE TITLE
Sidewalk vs. Driveable Area

### ISSUE THREAD

**Issue by johnwlambert** [nutonomy/nuscenes-devkit#112]
I can't see how sidewalk is annotated differently from driveable area. Are they lumped together into the "semantic prior", i.e. they are not differentiated?

I just see a single foreground and single background intensity value here: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/map_mask.py#L28

**Comment by Alex-nutonomy** [comment]
The semantic prior includes both driveable area and pedestrian walkways.
