### ISSUE TITLE
  The problem of first rotating and then translating

### ISSUE THREAD

**Issue by persuelx** [nutonomy/nuscenes-devkit#1120]
box.translate(-np.array(pose_rec['translation']))
    box.rotate(Quaternion(pose_rec['rotation']).inverse)
How should I understand the nuscenes question of translating first and then rotating later，Usually, it is rotated first and then translated.thank you!!

**Comment by whyekit-motional** [comment]
@persuelx it depends on the situation - for example, rotation is performed first followed by translation: https://github.com/nutonomy/nuscenes-devkit/blob/835ddecae31c763bcb303a16cc715df77d77c1a3/python-sdk/nuscenes/nuscenes.py#L884-L885
