### ISSUE TITLE
Some questions about nuscenes/eval/prediction/splits.py #558

### ISSUE THREAD

**Issue by iyuner** [nutonomy/nuscenes-devkit#1121]
Hi, I share the same doubts as in the issue https://github.com/nutonomy/nuscenes-devkit/issues/558. I saw it was closed but the two questions regarding splitting the train and trainval, also for the meaning of `NUM_IN_TRAIN_VAL `, were not answered. I open a new one for it.

Thank you!

**Comment by whyekit-motional** [comment]
Pls refer to https://github.com/nutonomy/nuscenes-devkit/issues/558
