### ISSUE TITLE
2d vehicle orientation w.r.t. other vehicles orientation

### ISSUE THREAD

**Issue by marcelmmm** [nutonomy/nuscenes-devkit#1122]
I transformed lane centerlines and vehicle positions in the coordinate frame of one specified vehicle. How can I get the orientations of the other vehicles w.r.t. to the local coordinate frame of the one specified vehicle?
We are in 2d here. I would like to get an orientation vector in the relative coordinate frame. The documentation is kind of confusing.

**Comment by whyekit-motional** [comment]
@marcelmmm pls specify which part of the documentation is confusing for you
