### ISSUE TITLE
connection refused when using wget to download nuScenes

### ISSUE THREAD

**Issue by Ishida-Mitsunari** [nutonomy/nuscenes-devkit#1123]
I tried to download nuScenes with operation
`wget https://motional-nuscenes.s3.amazonaws.com/public/v1.0/v1.0-trainval01_blobs.tgz`
but failed. The error information is:
Resolving motional-nuscenes.s3.amazonaws.com (motional-nuscenes.s3.amazonaws.com)... 52.219.151.109, 52.219.152.9, 52.219.17.5, ...
Connecting to motional-nuscenes.s3.amazonaws.com (motional-nuscenes.s3.amazonaws.com)|52.219.151.109|:443... failed: Connection refused.

**Comment by whyekit-motional** [comment]
@Ishida-Mitsunari the download seems to be working on my side - perhaps you can check the following:
- Ensure you have a stable internet connection 
- Check that you don't have any firewall interfering with your download
- Try downloading via the aws cli
