### ISSUE TITLE
Official Leaderboard Not Updated with Our Verified Submission

### ISSUE THREAD

**Issue by atxmeyc** [nutonomy/nuscenes-devkit#1126]
We submitted our results on Eval.ai and emailed nuscenes@motional.com on October, 2024. However, we have not received a response yet. Could you kindly confirm if you have received our email? If there are any issues with our submission or if additional materials are required, please kindly let us know. We are prepared to provide any necessary information to assist with the review process.

![figure](https://github.com/user-attachments/assets/ab4e168b-b8bb-482f-b951-9f938b0c65ec)

**Comment by whyekit-motional** [comment]
@atxmeyc pls provide some way to trace your email (e.g. email address that it was sent from)

**Comment by atxmeyc** [comment]
> @atxmeyc pls provide some way to trace your email (e.g. email address that it was sent from)

Thank you for your reply. We have sent the materials via the email address cheng.mei@tyjt-ai.com.

**Comment by whyekit-motional** [comment]
@atxmeyc we can't seem to find your submission - do try re-sending and I'll keep a lookout for it

In addition, do ensure that you have all the [required details](https://github.com/nutonomy/nuscenes-devkit/tree/master/python-sdk/nuscenes/eval/detection#participation) in your email, to ensure that the process is as smooth / fast as possible

**Comment by atxmeyc** [comment]
> @atxmeyc we can't seem to find your submission - do try re-sending and I'll keep a lookout for it
> 
> In addition, do ensure that you have all the [required details](https://github.com/nutonomy/nuscenes-devkit/tree/master/python-sdk/nuscenes/eval/detection#participation) in your email, to ensure that the process is as smooth / fast as possible

Thank you very much. We have just resubmitted via the email koumudai17@gmail.com.

**Comment by whyekit-motional** [comment]
@atxmeyc your submission has been processed - pls check it on https://www.nuscenes.org/object-detection

**Comment by atxmeyc** [comment]
> @atxmeyc your submission has been processed - pls check it on https://www.nuscenes.org/object-detection

Thank you very much.
