### ISSUE TITLE
Trouble for downloading dataset

### ISSUE THREAD

**Issue by WJ-Lai** [nutonomy/nuscenes-devkit#113]
Hi, I want to download the full nuScenes dataset, but the download speed is too slow.
After building download missions by chrome (on Windows), it show 0 KB/s (never larger than 50 KB/s).

It's strange so I want to ask if there are some solutions for it?
Is Chinese Wall blocking it ?

Thanks.

**Comment by agongdai** [comment]
@WJ-Lai, I am in China, too. I am pretty sure that it's the Wall. I use some VPN service, it's super fast. Without VPN, it's like what you said. (Why does the Wall block AWS?...)

Solution: VPN.

**Comment by Qiang-Xu** [comment]
hey @WJ-Lai, we're working on it, will have something this week, thanks a lot for reporting it.

**Comment by zhixinwang** [comment]
Hi, could you provide the key frames for single download? Now the Lidar blobs and camera blobs have included the key frames and intermediate frames. And the intermediate frames have 10 larger than key ones. Thus the dataset is too large to download.  I think most people only need the keyframes. 
Thanks.

**Comment by Qiang-Xu** [comment]
@WJ-Lai @zhixinwang done.
