### ISSUE TITLE
2d annotations only in samples/CAM_FRONT dataset. 

### ISSUE THREAD

**Issue by ghimiredhikura** [nutonomy/nuscenes-devkit#114]
How can I get object annotations only in samples/CAM_FRONT image subset. 
Thanks.

**Comment by holger-nutonomy** [comment]
Take a look at [this method](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L201). If your `sample_data_token` corresponds to a `CAM_FRONT` image, it will give you exactly what you need (and filter out annotations that don't fall into this camera). To find out whether an image is from `CAM_FRONT`, just check that the sensor channel is `CAM_FRONT`. Alternatively you can check that a `sample_data`'s `filename` includes the string `CAM_FRONT`. See the [schema](https://github.com/nutonomy/nuscenes-devkit/blob/master/schema.md) for more details.

**Comment by HenryJunW** [comment]
Hello, is there any method I can use to find out the corresponding token from the cam_front image filename? Thanks.

**Comment by holger-nutonomy** [comment]
Just go through `nusc.sample_data` and find the entry with the correct `filename`.
See the schema at: https://github.com/nutonomy/nuscenes-devkit/blob/master/schema.md#sample_data
