### ISSUE TITLE
Terrain models

### ISSUE THREAD

**Issue by jiangye-st** [nutonomy/nuscenes-devkit#116]
Does the dataset use any terrain models? It seems for each sample, ground always has zero elevation, because after transform LiDAR points to global frame, the ones on the ground have a height of 0. If I place an object on the ground in the global frame, how can I get the right elevation so that it can be correctly projected onto images?

**Comment by oscar-nutonomy** [comment]
hey Jiangye,

the sample_annotations have a translation field giving x, y, z values in
global coordinate system. The z values indicates height.

**Comment by jiangye-st** [comment]
Thank you for the quick response. Is this z value relative to the ego pose of the corresponding sample?

**Comment by oscar-nutonomy** [comment]
Take a look at https://www.nuscenes.org/data-format under
*sample_annotation*. There is your answer: *"A bounding box defining the
position of an object seen in a sample. All location data is given with
respect to the global coordinate system."*

HTH

**Comment by jiangye-st** [comment]
Thank you
