### ISSUE TITLE
Handling of invalid Lidar points

### ISSUE THREAD

**Issue by Lapayo** [nutonomy/nuscenes-devkit#117]
Hi,
I am trying to apply a spherical projection on the data, but I am not quite sure how invalid Lidar points are handled in your dataset? By invalid I mean rays that never returned to the sensor due to absorption, diffusion, ..
Have they just been left out of the point clouds or is it still possible to detect those points?

Thanks in advance!

**Comment by holger-nutonomy** [comment]
Hi,

Lidar: Invalid points have been left out for performance reasons.
Radar: You can define a number of flags to filter the points by: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/data_classes.py#L275

Let me know if you have any more questions.

**Comment by Lapayo** [comment]
Thanks for your answer, however I am not quite sure, if I understood it correctly. I am talking about the Lidar Pointclouds:

I am loading the pointcloud directly using numpy (as in LidarPointCloud) and the number of floats is always a multiple of `channels * #rings` (5 * 32)
But if invalid points would have been dropped this should not always be the case.

Additionally, if I reshape the pointclouds `scan.reshape(-1, 32, 5)` the following statement holds `scan[:,i,4] == i `, which means we seem to have the same amount of points in every row. This seems a bit contrary to dropping single points from the cloud.
 Or are entire columns dropped if one of the detections failed?

**Comment by oscar-nutonomy** [comment]
@Lapayo : I'm not sure if I understand you, but can you check this code:
```
from nuscenes.utils.data_classes import LidarPointCloud
from nuscenes import NuScenes

nusc = NuScenes('v1.0-mini')

for sample_data in nusc.sample_data[::100]:
    if sample_data['channel'] == 'LIDAR_TOP':
        pc = LidarPointCloud.from_file(nusc.get_sample_data_path(sample_data['token']))
        cnt = pc.nbr_points()
        assert cnt%(32*5) == 0
```
When running this the assert fails on the fourth PC. Wouldn't that suggest that we do indeed drop invalid points?

**Comment by Lapayo** [comment]
@oscar-nutonomy Thanks for your answer! However, the pointcloud nbr_points() methods does only return the number of points and does not include the channel dimension.

In my equation above I was refering to a point cloud directly loaded using numpy. Using the LidarPointCloud class the correct assertion should be just `assert cnt%32 == 0` which does not fail (on the mini dataset).

This also implies that there are no (single) points dropped.

I really appreciate your help and I hope to get this resolved. :-)

**Comment by oscar-nutonomy** [comment]
@Lapayo . You are right! Thanks. We will have to look into this closer.

**Comment by Lapayo** [comment]
Hey,
from the photos I concluded that you are using the HDL-32E Lidar, is this correct?
The manual for the 32E says:

> Note: The minimum return distance for the HDL-32E is approximately 1 meter. Ignore returns closer than this

 (https://velodynelidar.com/lidar/products/manual/63-9113%20HDL-32E%20manual_Rev%20G.pdf)

In the given point clouds I found multiple points with distances below 1.0 meters. Some of those seem to be correct like points from the car roof. But other points < 1.0 are outliers e.g. on car surfaces, that are farer than 1.0 meters.

Probably, if this is the correct manual for the Lidar, dropping all the points < 1.0m could fix the problem (at least for my use case)

**Comment by holger-nutonomy** [comment]
For more information on the lidar, please contact holger@nutonomy.com.
I agree on the suggestion to filter points by minimum distance. [Here](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/data_classes.py#L61) is an example in our devkit.
