### ISSUE TITLE
Camera distortion parameters

### ISSUE THREAD

**Issue by AnneCCollin** [nutonomy/nuscenes-devkit#120]
Hello,

Is there a place where we can get the distortion parameters for the cameras? (k1, k2, p1, p2)? I found the calibration parameters in the calibrated_sensor table, but the others don't seem to be there. Thanks!

**Comment by holger-nutonomy** [comment]
Hi, the images are all undistorted and rectified, so you don't need to worry about that. The calibration parameters are a historical artifact and we'll add a note to clarify that. Let me know if you have any more questions.
