### ISSUE TITLE
Could you provide the devkit version that support the Teaser dataset (v0.1) ?

### ISSUE THREAD

**Issue by PhyllisH** [nutonomy/nuscenes-devkit#121]
Since I want to load a mini version of the full dataset, however, the 'version='v1.0-mini'' setting in the tutorial does not work.

**Comment by oscar-nutonomy** [comment]
Hi Phyllis. 

`v1.0-mini` is different from the `teaser-release`. 

`v1.0-mini` comprises 10 scenes and you can download it from the download page. This data is compatible with the current master on this repo.

If you want to use the teaser release (`v0.1`), you can use this code: https://github.com/nutonomy/nuscenes-devkit/releases/tag/v0.1.1

HTH
