### ISSUE TITLE
 Is there an overview of different scenarios?

### ISSUE THREAD

**Issue by f5556666** [nutonomy/nuscenes-devkit#124]
Do you have an overview of 1000 scenes, such as which scenes are night scenes and which scenes are rain scenes?
Also,Are there any papers introducing this data set?

**Comment by Qiang-Xu** [comment]
https://www.nuscenes.org/publications

https://www.nuscenes.org/data-format, in `scene` table, there is `description` column. You can download metadata from download page and check scene.json:
![image](https://user-images.githubusercontent.com/29718352/56438778-ea7b2200-6298-11e9-8294-7b88e1d085c4.png)

**Comment by oscar-nutonomy** [comment]
Dear @f5556666 : We didn't schematize the weather conditions so you have to query the description string. Like this for example:
```
night_cnt = 0
rain_cnt = 0
for scene in nusc.scene:
    if 'night' in scene['description'].lower():
        night_cnt += 1
    if 'rain' in scene['description'].lower():
        rain_cnt += 1
print('Nbr rain scenes: {}, nbr night scenes: {}'.format(rain_cnt, night_cnt))
```
