### ISSUE TITLE
Should list avaiable DB versions

### ISSUE THREAD

**Issue by jinfagang** [nutonomy/nuscenes-devkit#125]
I am using previous teaser data which somewhat labels as v0.1, but can not parse now:

```
File "/usr/local/lib/python3.6/dist-packages/nuscenes/nuscenes.py", line 49, in __init__
    raise ValueError('Invalid DB version: {}'.format(version))
ValueError: Invalid DB version: v0.1

```

It better enum avaiable datasets now

**Comment by oscar-nutonomy** [comment]
@jinfagang : please download the new data instead. We don't support the schema of the teaser release anymore.
