### ISSUE TITLE
Reading RADAR data to a text file 

### ISSUE THREAD

**Issue by jaishreealavandar** [nutonomy/nuscenes-devkit#127]
Hi,
I have 3 questions.
1. How to import .pcd RADAR data and read values from a text file?
2. What is the difference between samples and sweeps in RADAR data?
3. Which RADAR is used for data collection just to refer to their documentation. Is it ARS 408?   
Thanks.

**Comment by oscar-nutonomy** [comment]
hey @jaishreealavandar .
1) https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/data_classes.py#L259
2) The RADAR `samples` are roughly aligned with the synchronized LIDAR and cameras. The `sweeps` have no guarantee on being synced with the other sensors. But they have time-stamps so for many applications you can still use them.
3) We can not disclose the radar model unfortunately.

**Comment by anupamsobti** [comment]
Hi @oscar-nutonomy 

What are `x_rms`, `y_rms`, `vx_rms` and `vy_rms`? Are these compensated too?

**Comment by holger-nutonomy** [comment]
Please contact holger@nutomomy.com for more information.
