### ISSUE TITLE
Axes.set_ylim has no left and right

### ISSUE THREAD

**Issue by ThierryDeruyttere** [nutonomy/nuscenes-devkit#13]
https://github.com/nutonomy/nuscenes-devkit/blob/56487d3ea2914380d9655d142b1fd28977eb9bc5/python-sdk/nuscenes_utils/data_classes.py#L218

Proposed change:

        ax.set_ylim(top=y_lim[0], bottom=y_lim[1])

**Comment by jderbisz** [comment]
After fresh clone I confirm spotting the same, should be top, bottom instead left right.

**Comment by holger-nutonomy** [comment]
Hi. Thanks for spotting this bug. It will be addressed in this week's PR.
