### ISSUE TITLE
Help wanted, about x, y, z directions

### ISSUE THREAD

**Issue by jinfagang** [nutonomy/nuscenes-devkit#131]
I try to project the transformation and hwl on image, here is what I got:

![image](https://user-images.githubusercontent.com/21303438/56717889-40a40580-6770-11e9-812b-2c7779e0b1c1.png)

The projection is right ( the centers are not offset), but the rotation was wrong when rotate 3d box.

What comfusing is: **which direction is xyz in interms of car whl?**, in kitti, the top axis which is the height of vehicle is -y.

I assume nuScenes is also too. But the result was totally wrong in rotate

**Comment by holger-nutonomy** [comment]
Hi, I suggest you take a look at the the [`render_sample_data` method](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L761), particular the `box.render()` part. There is also a [script that projects 3d boxes to 2d](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_2d_annotations_as_json.py#L121). For the coordinate frame orientation please refer to https://www.nuscenes.org/data-collection. 

> which direction is xyz in interms of car whl?

The object translation xyz is given in meters in global coordinates. wlh are in meters and independent of the orientation. The rotation is given as a quaternion.

Let me know if you have any more questions.

**Comment by jinfagang** [comment]
@holger-nutonomy  Thanks for your reply. So the y axis is the height of object?

**Comment by holger-nutonomy** [comment]
Only for the camera frame. For lidar/radar/imu/ego pose z is the "height of the object".

**Comment by jinfagang** [comment]
@holger-nutonomy  Thanks. Then it should rotate around z (which is yaw, since object on ground can not pitch and roll). But the rotation_matrix calculated from quarternion does not seems rotate around z. it rotate around all axis. 

I can reproduce the box with the Box classes inside kit. But when I calculate myself, I got some puzzels.

**Comment by holger-nutonomy** [comment]
Please note that the box rotation models only yaw, but since the sensors are not perfectly aligned with the vertical axis, it still makes sense to model all 3 rotations.

**Comment by Joseph-pt** [comment]
Hi, sir. I also want to project 3D box in lidar to image plane to visualize it, Can you visualize it successfully? @jinfagang
