### ISSUE TITLE
regress the velocity in global coordinate system?

### ISSUE THREAD

**Issue by WERush** [nutonomy/nuscenes-devkit#132]
Hi, all,

I noticed that in your paper, you modified the pointpillar to also learn velocities as an additional regression target for each 3D box. You regress the velocity of each box in global coordinate system or in lidar coordinate system? And I suppose only one sweep could not perform the velocity regression, how did you make it?

Thanks

**Comment by Alex-nutonomy** [comment]
We learned the velocity of each box in the lidar coordinate system.

And yes, in the paper we did experiments with combining multiple sweeps into one aggregated point cloud. The single sweep experiment struggles to learn velocity, while the 5 and 10 sweep experiments can learn it.

**Comment by WERush** [comment]
Thanks for your reply.

By the way, which loss did you use to regress the velocity? I tried the smoothL1 but always got the velocity score=0. Is there any special technique? I have transformed the global coordinate to lidar coordinate. Thanks so much.
