### ISSUE TITLE
More details about LIDAR data

### ISSUE THREAD

**Issue by WJ-Lai** [nutonomy/nuscenes-devkit#133]
Hi!

I'm going to flatten the "front view" of a LIDAR sensor to a 2D image ([method liks this](https://github.com/Karthikeya108/AdvancedObjectDetection)), but the horizontal resolution,  vertical resolution and y fudge factor of the LIDAR sensor are not provided. 

1. Could you please provide the LIDAR specs so that we can get more details about the senor.
2. For each LIDAR data(*.pcd.bin), there are about 35000 points. In order to plot LIDAR data on the camera image, it decrease to about 3000 points after using the mask (in function `map_pointcloud_to_image`). Is that the all points of a frame?  Is there any way can I get more points for a front view?

Thanks!

**Comment by holger-nutonomy** [comment]
1. There are 32 beams. Please contact me at holger@nuTonomy.com .
2. According to https://www.nuscenes.org/public/images/camera-fov.jpg , all cameras except the rear camera have a 70 degree fov. So we are capturing 17/360=20% of the lidar points in the horizontal direction. Additionally some points at the top and bottom may not fall into the image. So I guess this is correct.
