### ISSUE TITLE
pointpillar config

### ISSUE THREAD

**Issue by WERush** [nutonomy/nuscenes-devkit#134]
Hi,

Can you provide your config file that you used in your paper? I can not reproduce the baseline results that you reported with pointpillar, especially the average velocity error (0.29 (yours) vs 1.5 (ours)). 

Thanks

**Comment by holger-nutonomy** [comment]
@Alex-nutonomy

**Comment by Alex-nutonomy** [comment]
@WERush, we haven't published our full configs from the nuScenes paper, but this open source project should be able to reproduce the results: https://github.com/traveller59/second.pytorch. Please give it a try and let me know if you still have issues.

**Comment by poodarchu** [comment]
> Hi,
> 
> Can you provide your config file that you used in your paper? I can not reproduce the baseline results that you reported with pointpillar, especially the average velocity error (0.29 (yours) vs 1.5 (ours)).
> 
> Thanks

Have you get a better velocity result now?
