### ISSUE TITLE
Mistakes about point cloud axis.

### ISSUE THREAD

**Issue by WJ-Lai** [nutonomy/nuscenes-devkit#137]
Hi, I found there are some mistakes about point cloud axis.

1. In `data_classes.py` line 249, the return of  function `from_file` should be (x, z, y, intensity). The order of y and z is wrong. 
I found this problem by ploting a 3D scatter plot. Also, if you watch the range of `pc.points`, you will find the range of `pc.points[0, :]` and `pc.points[2, :]` is similar and the range of `pc.points[1, :]` is very different from them. For these reasons, I think `pc.points[1, :]` is z axis, which means height.

2. In `nuscenes.py` line 550, it should be `y axis` instead of `z axis` in th comment. 
(line 551 is right, because `pc.points[2, :]` is y axis which is also means depth.)

3. In `nuscenes.py` line 554, it should be `coloring = pc.points[1, :]`, because the depth is `pc.points[1, :]`, not `pc.points[2, :]`.
(It is apparent that there is a contradiction between line 551 and line 554, because depth is y axis and height is z axis. It not should be both use `pc.points[2, :]`)

4. It you modify codes as I said and run `render_pointcloud_in_image` again, you will find the output image with point clouds is more reasonable.

5. If my finds are right, I'm afraid that they will have an influence of other functions like `view_points` or the radar data may have the same mistakes.

Thanks!

**Comment by holger-nutonomy** [comment]
Hi, thank you for reporting this. It is critical for us to get this right. We'll take the xyz definitions from [this diagram](https://www.nuscenes.org/public/images/data.jpg) (note that these vary for each sensor).

1. I just loaded a raw lidar pointcloud and cannot confirm your observation:
```
import os
import numpy as np

from nuscenes.nuscenes import NuScenes
from nuscenes.utils.data_classes import LidarPointCloud

nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=False)
sd = [sd for sd in nusc.sample_data if sd['sensor_modality'] == 'lidar'][0]
pcl = LidarPointCloud.from_file(os.path.join(nusc.dataroot, sd['filename']))
np.std(pcl.points, axis=1)
```
This returns:
```
array([12.0470085, 13.339389 ,  1.998435 , 22.355246 ], dtype=float32)
```
So the z axis has the least variation and is therefore the height. This agrees with the diagram and is therefore correct. I assume you were looking at the pointcloud after transformation. If you can find a pointcloud for which my code shows something else, please let me know.

2. According to the diagram, the camera z axis points "away from the camera". That's also written in this comment. So it is correct.

3. Note that we have transformed the pointcloud now in several ways, so the meaning of xyz is not the same as above. We're in the camera frame now, so z is again pointing forward. Regarding line 555, I agree that the comment was outdated. I am changing "height" to "depth". 

4. Please try `nusc.render_pointcloud_in_image(nusc.sample[0]['token'])`. In my opinion the rendering looks good. Here is our code (you can see that it's rendering the depth as intended:
![depth](https://user-images.githubusercontent.com/39502217/57061161-81f76080-6cee-11e9-9b95-521c803d160e.png)
Here is your code (which is rendering the height):
![height](https://user-images.githubusercontent.com/39502217/57061188-950a3080-6cee-11e9-92ff-c4dc405d8a17.png)

5. If you can provide code that does not what it should I am happy to make any required changes :-).

**Comment by sainisanjay** [comment]
Hi @holger-nutonomy , 
Please guide me to project the Pointcloud on image. I am using below script: 
```
import os
import numpy as np
from nuscenes.nuscenes import NuScenes 
from nuscenes.utils.data_classes import LidarPointCloud, RadarPointCloud

nusc = NuScenes(version='v1.0-mini', dataroot='/home/sanjay/deeplearning/data/sets/nuscenes', verbose=False)
sd = [sd for sd in nusc.sample_data if sd['sensor_modality'] == 'lidar'][0]
pcl = LidarPointCloud.from_file(os.path.join(nusc.dataroot, sd['filename']))
print(np.std(pcl.points, axis=1))
my_sample = nusc.sample[10]
nusc.render_pointcloud_in_image(my_sample['token'], pointsensor_channel='LIDAR_TOP')
#nusc.render_pointcloud_in_image(nusc.sample[0]['token'])
```
above script run successfully but never display anything. 
any idea whats wrong?? Thanks
