### ISSUE TITLE
AssertionError:  Database version not found: /data/sets/nuscenes/v1.0-mini

### ISSUE THREAD

**Issue by jaishreealavandar** [nutonomy/nuscenes-devkit#139]
Hi, 
I m getting the following error: 
______________________________________________________________________
Traceback (most recent call last):
  File "/home/jai/nuscenes-devkit/python-sdk/nuscenes/tests/test_nuscenes.py", line 20, in test_load
    nusc = NuScenes(version='v1.0-mini', dataroot=os.environ['NUSCENES'], verbose=False)
  File "/home/jai/nuscenes-devkit/python-sdk/nuscenes/nuscenes.py", line 56, in __init__
    assert osp.exists(self.table_root), 'Database version not found: {}'.format(self.table_root)
AssertionError: Database version not found: /data/sets/nuscenes/v1.0-mini
_________________________________________________________________________
Data is at "/home/jai/data/sets/nuscenes"
Is data located right? How can this be sorted? 
Thank you.

 
Thank

**Comment by holger-nutonomy** [comment]
Initialize NuScenes as:
`nusc = NuScenes(dataroot='/home/jai/data/sets/nuscenes')`
And check that the folder exists.

**Comment by sindhu-pr** [comment]
@holger-motional @jaishreealavandar Where should this initialisation code be inserted?

**Comment by whyekit-motional** [comment]
@sindhu-pr the line of code to initialize nuScenes described by @holger-motional above can be placed anywhere, as long it is before the bulk of your code that uses the nuscenes-devkit. As an example, pls check out the nuScenes tutorial here: https://www.nuscenes.org/nuscenes?tutorial=nuscenes

**Comment by sindhu-pr** [comment]
@whyekit-motional I have downloaded one blob of trainval dataset. I have unpacked it to /data/sets/nuscenes. Does this folder tree work and should I set the NUSCENES_ROOT variable?

**Comment by whyekit-motional** [comment]
@sindhu-pr you will need all the blobs, if you wish to use the `trainval`. If you just want to get a feel of things, I suggest to use the `mini` dataset instead.

**Comment by sindhu-pr** [comment]
@whyekit-motional Thanks! I have downloaded mini dataset as well. I am using the LSS paper (ECCV 2020) on the dataset. This code has a main.py file and as you suggested perhaps it is better to insert the above initialisation code in this main.py file.

**Comment by Dlatego** [comment]
I switched to an absolute path to solve it

**Comment by 1941038421Gyh** [comment]
> I switched to an absolute path to solve it

Thank you! It works.
