### ISSUE TITLE
Unwanted BBOX in 2d Annotation

### ISSUE THREAD

**Issue by ManivannanMurugavel** [nutonomy/nuscenes-devkit#142]
Hi 
  I have annotated 2d bounding box using your script "export_2d_annotations_as_json.py". The result gives a lot of extra boxes for a single object.
Example:
![n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151188012404](https://user-images.githubusercontent.com/20641562/57276648-d704ef00-70bf-11e9-9328-5220ad67da23.jpg)
![n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151250612404](https://user-images.githubusercontent.com/20641562/57276650-d79d8580-70bf-11e9-9649-762fc115f764.jpg)
![n008-2018-08-01-15-52-19-0400__CAM_FRONT__1533153285362404](https://user-images.githubusercontent.com/20641562/57276651-d79d8580-70bf-11e9-8103-f1370a9ad1bd.jpg)
If you see the images, there are multiple bounding boxes
Could you tell me if this is some sort of bug ? If it is what is the fix ?.

**Comment by holger-nutonomy** [comment]
Dear @ManivannanMurugavel, please check whether there are actually objects behind the visible object to which these boxes may belong. In general the projection from 3d to 2d is a heuristic and there is no way to figure out if one object is occluded by another. Even if we compute in 3d whether one cuboid occludes another, the vehicles may have irregular shapes or be partially transparent, s.t. the result will not be perfect.
We do have a visibility field as an indicator how much of the area of the object is visible. You can [filter less visible objects](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_2d_annotations_as_json.py#L189) to avoid some of these issues. 
Another trick may be to compute the number of lidar points that fall within the cuboid and discard cuboids with < x points.
