### ISSUE TITLE
How to convert nuscenes 3d data format to kitti 3d format

### ISSUE THREAD

**Issue by kl456123** [nutonomy/nuscenes-devkit#143]
Is it possible to make it ?

**Comment by kl456123** [comment]
![image](https://user-images.githubusercontent.com/10957718/57459445-da59cf80-72a5-11e9-8ca3-06d785d24ba3.png)

**Comment by kl456123** [comment]
It is very strange that some annotations of 3d bboxes may be wrong from this view. The box that is above the ground plane is empty !!

**Comment by kl456123** [comment]
So that my detection model get a very bad performance. Is there anything I miss ? Thanks.

**Comment by holger-nutonomy** [comment]
Hi. Please start a new issue for a new topic. I believe you may have projected boxes in front and behind the camera to your image. Please use [this code](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L696) instead.

**Comment by kl456123** [comment]
I use the following code to visualize, But the results is the same.
```python
def visualize(index):
      sample = nusc.sample[index]
      my_sample = nusc.get('sample', sample['token'])
      nusc.render_sample_data(
          my_sample['data'][SENSOR], out_path='images/{:06d}'.format(index))
visualize(4871)
```
![image](https://user-images.githubusercontent.com/10957718/57499623-f182d680-7312-11e9-8b36-a02e9c530f30.png)

**Comment by holger-nutonomy** [comment]
You are right. Unfortunately due to an imperfect localization the (otherwise stationary) cuboid drifted upwards. Our annotators are instructed to correct drifting cuboids, but they have missed this one.

**Comment by kl456123** [comment]
So the boxes in the back of the camera will not be projected in the image, is it right ?

**Comment by holger-nutonomy** [comment]
Yes, that is right. The scripts are all correct. It's just that box which is too high.
