### ISSUE TITLE
ego_pose per scene

### ISSUE THREAD

**Issue by cathrinasowa** [nutonomy/nuscenes-devkit#144]
Hi
I am trying around with the devkit you provided. The code is really easy to understand. Nevertheless I do have a question or two. 
As I understood it, it is possible to retrieve the pose of the ego vehicle  from the dataset and even render it in the map for a certain location and scene. My question is if it is possible to retrieve the ego pose per sample for a given scene. 
I am working with the data taken in Boston. Is it possible for you to tell me the GPS coordinates of the xyz origin? From this I can calculate alle other GPS positions. 
Thank you in advance.
Cheers Cathrina

**Comment by oscar-nutonomy** [comment]
Also: as a heads up; due to the way we created the maps there is no guarantee that the will be perfect alignment between GPU and the map coordinate system.

**Comment by cathrinasowa** [comment]
Hi,
Thank you for your fast and detailed answer. The first point you answered I found out the moment you answered. I am testing code to detect, track and globaly position traffic objects. In order to test this I thought it would be nice to transform the found coordinates into GPS and have a look if I am right. 
The GPS origins are really good to know. Thank you for this. Even if it is not perfectly aligned I get a good guess.

Cheers
Cathrina

**Comment by cathrinasowa** [comment]
Hi Holger,

I do see an offset from the static instances to the street visible in google maps. It is just a few meters in south east direction. A much bigger offset can be seen in the Singapore data. 
Maybe it is because of my transformation from ENU to geodetic coordinates. 
What I do is the following:
I did get the origin of the map in lat long from you for Boston and Singapore.
I supposed that all the instances translation coordinates are cartesian coordinates in a cartesian coordinate system whith it origin at the given lat long. Is this a correct assumption?
Then I selected the right UTM sector which is 19T for Boston.
In the next step I took proj to project from lat long to UTM and vice versa.
Proj(proj='utm', zone=__bostonZone, ellps='WGS84', preserve_units=False)
If I past in the lat long of the origin I do get a UTM coordinate.
To calculate the lat long of an instance I add the x value of the translation of the object to given UTM x coordinate of the origin and inverse the transformation. The same goes for the y coordinate.
But I do have an offset to the South West of more then 500m in Boston and even more for Singapore.
What I do get ist the following:
UTM for lat long origin 330471.7802963524, 4689228.145595022
trasnlation of an instance 373.256, 1130.419
scene 0103 
oneInstanceToken = parser.nusc.get('instance', parser.nusc.sample_annotation[5]['instance_token'])['first_annotation_token']
translation = parser.nusc.get('sample_annotation', oneInstanceToken)['translation']
 lat long of instance  42.347104525174444 -71.05365689200067

My questions are:
If I get the translation of an instance the first value is the x coordinate and the second the y coordinate, right?
Does every scene has its own coordinate system or are all instances of all scenes in own big coordinate system?
Is the origin of this big system at the given lat long?

Any help or suggestion is appreciated.

Have a nice weekend
Best wishes
Cathrina

**Comment by holger-nutonomy** [comment]
Hi Cathrina,

unfortunately you are right - the origin I gave you for singapore-onenorth is wrong.
I've played a bit with this now by overlaying the map on Google Earth (https://earth.google.com).
![alignment](https://user-images.githubusercontent.com/39502217/59138819-374bb280-8944-11e9-884d-6cf2f77dc822.png)
Aligning it by hand to about <10m offset, I get the following .klm file:
```
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Folder>
    <name>nuScenes singapore-onenorth</name>
    <description>Singapore One North overlay</description>
    <GroundOverlay>
      <name>Singapore</name>
      <description>Singapore One North map.</description>
      <Icon>
        <href>https://i.ibb.co/tqbwHzJ/map-singapore-small.png</href>
      </Icon>
      <LatLonBox>
        <north>1.30647</north>
        <south>1.29107</south>
        <east>103.7990</east>
        <west>103.7847</west>
      </LatLonBox>
    </GroundOverlay>
  </Folder>
</kml>
```
To answer your questions:

> If I get the translation of an instance the first value is the x coordinate and the second the y coordinate, right?

Yes
> Does every scene has its own coordinate system or are all instances of all scenes in own big coordinate system?

Every scene in the same map location (e.g. singapore-onenorth) has the same coordinate system. You can see this in the paper where we simply compute spatial statistics across all scenes and put them in a visualization of the map:
![density](https://user-images.githubusercontent.com/39502217/59139023-526af200-8945-11e9-8b7f-57666d92dfd4.png)

> Is the origin of this big system at the given lat long?

Yes. Unfortunately the numbers I had were wrong. I will try to find the right ones.
Btw., the maps have the following size:
```
# Obtained from the dimensions of the map png files (divided by 10 for metric scale).
CANVAS_EDGES = {'singapore-onenorth': [1585.6, 2025.0],
                'singapore-hollandvillage': [2808.3, 2922.9],
                'singapore-queenstown': [3228.6, 3687.1],
                'boston-seaport': [2979.5, 2118.1]}
```

**Comment by cathrinasowa** [comment]
Hi Holger,

you said that only the scenes in the same map location have the same coordinate system. Consequently all of the map locations have another origin and therefore their own geodetic coordinates for the origins. 
Following this line I would assume that every scene in Boston has the same origin as there is only one map location. 
Nevertheless I found one error in my code, where I received weired translation values.
 Now I do have the precision mentioned by you, I do have an offset between different coordinate transformation methods, but this problem is on my side.
Sorry for the late reply but there has been a national holiday in Germany yesterday.
I really appreciate your help and suggestions.
Thank you for your work.

Best wishes
Cathrina

**Comment by holger-nutonomy** [comment]
> Following this line I would assume that every scene in Boston has the same origin as there is only one map location.

That is correct.
If you find any other issues, please let us know in which scene etc. so we can investigate more closely.
Btw. soon we will release 11 more semantic map layers, which will hopefully be useful to you (see image below).
![map](https://user-images.githubusercontent.com/39502217/59313326-607e8280-8c65-11e9-9dba-344d9120cf14.png)

**Comment by cathrinasowa** [comment]
Are those semantic layers included in the mini dataset? Will it be possible to access eg. the road segments individually?
This looks really interesting. Thank you for showing me this.

**Comment by holger-nutonomy** [comment]
Yes, it's just one .json file per map location, regardless of which split is used.
You will be able to access every single node, edge, segment etc.

**Comment by fabvio** [comment]
Hi, I am working as well with your dataset and it would be really helpful for me to know the starting coordinates in the 4 configurations to retrieve an estimation of the GPS position. Could you please provide them? Thanks in advance

**Comment by holger-nutonomy** [comment]
Hi, it turns out that my numbers above are correct. The problem was that Google Earth automatically crops the image to the non-transparent parts which lead to the issues. Sorry for the confusion. Please do not answer on this post anymore, but rather open individual posts at https://forum.nuscenes.org/ if you have any more questions:

boston-seaport: origin_latlon: [42.336849169438615, -71.05785369873047] [(map)](https://www.google.com/maps/place/42%C2%B020'12.7%22N+71%C2%B003'28.3%22W/@42.3411594,-71.0547353,15.46z/data=!4m5!3m4!1s0x0:0x0!8m2!3d42.3368492!4d-71.0578537)
singapore-onenorth: origin_latlon: [1.2882100868743724, 103.78475189208984] [(map)](https://www.google.com/maps/place/1%C2%B017'17.6%22N+103%C2%B047'05.1%22E/@1.2942276,103.7840466,15.92z/data=!4m5!3m4!1s0x0:0x0!8m2!3d1.2882101!4d103.7847519)
singapore-hollandvillage: origin_latlon: [1.2993652317780957, 103.78217697143555] [(map)](https://www.google.com/maps/place/1%C2%B017'57.7%22N+103%C2%B046'55.8%22E/@1.3071563,103.784314,14.75z/data=!4m5!3m4!1s0x0:0x0!8m2!3d1.2993611!4d103.7821667)
singapore-queenstown: origin_latlon: [1.2782562240223188, 103.76741409301758] [(map)](https://www.google.com/maps/place/1%C2%B016'41.7%22N+103%C2%B046'02.7%22E/@1.2931037,103.7807879,15.25z/data=!4m5!3m4!1s0x0:0x0!8m2!3d1.2782562!4d103.7674141)

**Comment by meissnerda71974** [comment]
Hello,  started working with the nuscenes data and i want to transform the translation of the ego_pose into lat/long, just the same as @cathrinasowa discribed. I am using pyproj to first transform the given origin_latlon to utm-coordinates.
trans = Proj(proj='utm', zone=utm_sector, datum='WGS84', preserve_units=False)
origin_lat = 42.336849169438615
origin_long = -71.05785369873047
x_origin, y_origin =  trans(longitude=origin_long, latitude=origin_lat)
Then I am adding the x/y-translation and I transform the new utm-coordinattes into lat/lon:
x = x_origin + x_translation 
y = y_origin + y_translation
longitude, latitude = trans(x, y, inverse=True)
The results are lat/lon's that are very close to the positions identified by the frames of the cam_cannels (CAM_BACK, CAM_BACK_LEFT etc.), but there is at least a drift of 30-40 meters. 
Am I missing here something?
Is the x-/y-axis of the translation scaled? It seems to me that an scale-factor of around x_factor = 1.059 and y_factor_0.98 brings me close to positions estimated by the frames of the cam_channels. 

I am currently working with the boston-seaport map.

Thanks in advance.
Best regards, 
Daniel.
