### ISSUE TITLE
RADAR data Acquisition

### ISSUE THREAD

**Issue by jaishreealavandar** [nutonomy/nuscenes-devkit#149]
Hi @nutonomy,
Could you please answer the following questions.

1. Where can I find LiDAR data format? No metadata unlike RADAR.
2. Normally RADAR data comes from different CAN message IDs , Is the Nuscenes RADAR data extracted by bitwise operations from the CAN frames ?
3. Are all the 5 RADARs connected to single CAN bus, while acquiring data?
4. How to print out the radar data in numbers in jupyter notebook? After printing metadata, actual data is printed in encoded format. 

Many Thanks.

**Comment by holger-nutonomy** [comment]
@jaishreealavandar Please post all requests that are not directly related to the devkit at https://forum.nuscenes.org

**Comment by jaishreealavandar** [comment]
Hi @holger-nutonomy, 

I have posted in the link mentioned and the devkit question below. 

To implement Kalman filter, I want to print the RADAR datasets as numbers, but actual data is getting printed in encoded format. How to decode the data?

Thank you.

**Comment by holger-nutonomy** [comment]
Please read radar data using [this function](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/data_classes.py#L275), as done [here](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L527).

We'll try to answer your other questions in the forum.

**Comment by jaishreealavandar** [comment]
Thank you!
