### ISSUE TITLE
linewidth datatype changed in def render_cv2

### ISSUE THREAD

**Issue by jderbisz** [nutonomy/nuscenes-devkit#15]
The definition that works:

def render_cv2(self, im: np.ndarray, view: np.ndarray=np.eye(3), normalize: bool=False,
                   colors: Tuple=((0, 0, 255), (255, 0, 0), (155, 155, 155)), linewidth: int=2) -> None:

**Comment by holger-nutonomy** [comment]
Hi. Thanks for spotting this bug. It will be addressed in this week's PR.
