### ISSUE TITLE
Hash values are unnecessarily big

### ISSUE THREAD

**Issue by nlgranger** [nutonomy/nuscenes-devkit#152]
I quickly checked and the first 64 bits/8bytes of the token are sufficient to discriminate individual elements.
This is fortunate since your devkit already uses python dict [where the key hashing function returns 64 bits values](https://docs.python.org/3/reference/datamodel.html#object.__hash__) (actually 61 due to the randomization added for security) ;-)

**Comment by holger-nutonomy** [comment]
The tokens are taken from a larger database and we want to avoid collisions there. I agree that the tokens could be more compact, but then we could have also just enumerated them one by one. Further optimization may be possible on the lidar and radar raw data format (e.g. reduce precision).

Btw., please start any future conversations at: https://forum.nuscenes.org
