### ISSUE TITLE
is the KITTI tranformation available now?

### ISSUE THREAD

**Issue by poodarchu** [nutonomy/nuscenes-devkit#154]
I noticed that there're still frequently commits, so is the nuscenes_kitti branch ready to be used now?

**Comment by holger-nutonomy** [comment]
Yes, I just merged the PR into master: 
https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_kitti.py
Let me know if you have any questions.
