### ISSUE TITLE
conda distribution

### ISSUE THREAD

**Issue by analog-cbarber** [nutonomy/nuscenes-devkit#155]
It would be nice to have a conda distribution of this package.

While it is possible to pip install into a conda environment, this package depends on two packages that have different names in public conda channels (namely pyquaternion/quaternion and opencv-python/opencv) which could lead to dependency problems.

Ideally a feedstock should be added to conda-forge.

**Comment by analog-cbarber** [comment]
Actually pyquaternion and quaternion (aka numpy-quaternion on pip) are not related. There does not appear to be a distribution of pyquaternion on conda-forge.

**Comment by analog-cbarber** [comment]
I have gotten a version of this working on my fork:

https://github.com/analog-garage/nuscenes-devkit/commit/b9da3caf13363590e25ae46f0ab98bfa8a6e1df7

This uses a post-link hack to install pyquaternion using pip.

I had to cleanup setup.py a bit to get this to work.

I haven't tested this yet other than to make sure that the devkit can be imported.

**Comment by holger-nutonomy** [comment]
Hi @analog-cbarber. Thanks for figuring out how to install the Conda distribution.
So far we have not heard from any users that are facing dependency problems and I am worried that adding more complexity to the installation may deter some users.
May I ask you to create a short post about your observations at https://forum.nuscenes.org , so we can close this issue, but observe if this is a widespread problem and should become part of this repository?

**Comment by analog-cbarber** [comment]
Users might not notice a dependency problem if they don't have conda packages that depend on opencv or if they happen to have installed the same version in both pip and conda, but there could eventually be a problem. If I create a conda environment and install opencv and then pip install opencv-python then I end up with both packages installed at the same time. Not sure what that means for the actual python packages, but I believe that the last installed version will overwrite the previous version, so you could have a situation where a pip install with no version constraint overwrites a constrained package from a conda install and violates its declared version dependency.

I encountered exactly this type of problem with a project in which a pip install was overwriting a package with a broken version I had excluded from my conda dependencies. This kind of thing doesn't happen very often, but when it does it can be really confusing and may stymie many users. Sadly incompatible APIs and buggy updates are not at all uncommon in major python packages (in the last six months I have seen broken versions of pandas, pytables, numpy, matplotlib and numba that I had to exclude in package dependencies).

In general, it is a bad idea to use pip in a conda environment unless there is no other choice.

So it is fine to offer a pip install, but for people who are using conda environments it is always better to give them a conda option. This would not add any complexity for end-users. If they are using a conda environment you tell them to use `conda install` otherwise `pip install`.  And it simplifies things for those of us building conda packages that depend on your package because we can then just add it as a dependency instead of asking our own users to manually install it in an extra step.

There would be a small amount of extra work on your part, of course.

You might want to consider leaving this issue open so that other users can find it easily, but add one or more labels to indicate that it is a feature request, and not necessarily a bug.

I'll add something to the forum when I have some time.

**Comment by Dawars** [comment]
I have this problem, I installed the devkit in a conda environment and it has overridden the conda opencv installation which now displays the following error:
```
Traceback (most recent call last):
  File "/projects/.../dataloader/nuscenes_dataset.py", line 9, in <module>
    from nuscenes import NuScenes
  File "/opt/conda/lib/python3.7/site-packages/nuscenes/__init__.py", line 1, in <module>
    from .nuscenes import NuScenes, NuScenesExplorer
  File "/opt/conda/lib/python3.7/site-packages/nuscenes/nuscenes.py", line 12, in <module>
    import cv2
  File "/opt/conda/lib/python3.7/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libSM.so.6: cannot open shared object file: No such file or directory
```

**Comment by analog-cbarber** [comment]
You can try checking the `conda` branch of my fork: https://github.com/analog-garage/nuscenes-devkit/tree/conda and building a conda package:

~~~sh
$ cd setup
$ conda build conda.recipe
...
$ conda activate -n your-target-env
(your-target-env) $ conda install --use-local nuscenes-devkit
~~~

I haven't had the time to actually test the running code to see if there is some subtle difference in dependencies between pip and python, but it should otherwise work.

**Comment by holger-nutonomy** [comment]
I have decided not to adopt the solution presented here, but to reference to it from the installation document for interested parties.
