### ISSUE TITLE
2 d bounding box in KITTI format

### ISSUE THREAD

**Issue by jjldr** [nutonomy/nuscenes-devkit#156]
The current  "nuscenes format to KITTI format" tools have no 2d bounding box output, all of them are -1.0.  For producing 2d annotation, I use the "project_kitti_box_to_image" function that you provide in kitti.py , the following error happens:

 File "/home/jjldr/nuscenes-devkit/python-sdk/nuscenes/utils/geometry_utils.py", line 40, in view_points
    assert points.shape[0] == 3
AssertionError

Please help me !!!

**Comment by holger-nutonomy** [comment]
Hi. Code fixed in the PR referenced above. Please test it. The issue was that the input to view_points can be empty if all corners are behind the camera.
