### ISSUE TITLE
What is the height of LIDAR to the ground? 

### ISSUE THREAD

**Issue by lh0616** [nutonomy/nuscenes-devkit#161]
Can you provide the height of the lidar installation location? I need this value.

**Comment by holger-nutonomy** [comment]
You can actually read it from the calibrated sensor table:
```
cat calibrated_sensor.json | grep -A 5 dc8b396651c05aedbb9cdaae573bb567 | grep 1.8 | sort -u
```
On the trainval set this returns 3 different values:
```
1.84019
1.84023
1.84292
```
So the lidar is 1.84m above the ground.

**Comment by gbirman** [comment]
In issue #108, you confirm that the [0,0,0] coordinate of the ego coordinate frame is on the midpoint of the rear axle of the car. Given that this point hangs above the ground (approx. 12 cm according to https://www.renault.co.uk/vehicles/new-vehicles/zoe/dimensions.html),  how is it that the calibrated_sensor translation z-value represents the height of the LIDAR from the ground? Thanks for the clarification.

**Comment by holger-nutonomy** [comment]
Actually that information was incorrect. It should be `The "ego vehicle body frame" refers to the center of the rear axle projected onto the ground`.
