### ISSUE TITLE
export_kitti.py

### ISSUE THREAD

**Issue by kl456123** [nutonomy/nuscenes-devkit#162]
May be you should generate some list files of samle names like "trainval.txt" in kitti.
It's more convenient, I think.

**Comment by kl456123** [comment]
And Maybe more like kitti, more better. so that I dont need to modify any dataloader code in pytorch framework

**Comment by kl456123** [comment]
And the script generates many invalid images at the same time.

**Comment by kl456123** [comment]
After using your script, I got the even worse performance than using my script. Many invisible box are not filtered out...

**Comment by kl456123** [comment]
Personally speaking, The visibility is the most important thing in your dataset, otherwise the dataset may be very hard to use.

**Comment by holger-nutonomy** [comment]
@kl456123 Yes, we will look into it, but currently are busy with other things.

> And the script generates many invalid images at the same time.

Can you elaborate how the images are invalid?

> After using your script, I got the even worse performance than using my script.

What does your script do? Simply filter by visibility? Note that this depends a lot on your method - whether it can deal with partial occlusion and whether false positives or false negatives have a higher impact.

However, I want to stress that we are simply providing these scripts for legacy reasons. If you really want to use the full power of nuScenes (multimodal, 360 degree, 3d boxes ...) you should use our format.

**Comment by kl456123** [comment]
> Can you elaborate how the images are invalid?

some images that cannot be opened using PIL


> What does your script do? Simply filter by visibility?

 filter bboxes according to visibility_token, just like in export_2d_annotations_as_json.py
But there still are some invisibility bboxes after that...
Finally I got a better monocular 3d detection results due to your dataset in real scenes than kitti.

**Comment by kl456123** [comment]
![demo](https://user-images.githubusercontent.com/10957718/58418606-cd691880-80ba-11e9-960d-e85c586c9761.jpg)
![1546843222330047000](https://user-images.githubusercontent.com/10957718/58418745-3486cd00-80bb-11e9-8ad8-f5336005cc5d.jpg)

**Comment by holger-nutonomy** [comment]
> > Can you elaborate how the images are invalid?
> 
> some images that cannot be opened using PIL

I haven't experienced that. Can you tell us their names?

> Finally I got a better monocular 3d detection results due to your dataset in real scenes than kitti.

Great!

**Comment by holger-nutonomy** [comment]
Closing this for now. Will reopen if you can find which images are broken.
