### ISSUE TITLE
Spurious cuboid

### ISSUE THREAD

**Issue by johnwlambert** [nutonomy/nuscenes-devkit#163]
Hello nuScenes, question for you -- from 16-18 seconds of this video, it looks like there is a  spurious cuboid https://youtu.be/Sipud0IonvQ?t=18. Was this intentional?

<img width="539" alt="Screen Shot 2019-05-28 at 8 39 28 PM" src="https://user-images.githubusercontent.com/16724970/58527775-e213e200-8188-11e9-9f41-b0cd4a619e89.png">

**Comment by holger-nutonomy** [comment]
Hi @johnwlambert,
the cuboid you are seeing is actually not *as bad* as it seems. Here is the view from our [3d explorer](https://www.nuscenes.org/explore/scene-0011/0):
![cuboid](https://user-images.githubusercontent.com/39502217/58834624-205f4480-8654-11e9-905d-386e76857dd9.png)
What is wrong here is the z value (vertical position) of the cuboid, which is about 30cm too low. Unfortunately that was missed in our quality control.
