### ISSUE TITLE
lane road border annotations

### ISSUE THREAD

**Issue by rfsch** [nutonomy/nuscenes-devkit#164]
Hi 

I wonder if there are any annotations available for road marking, lanes, borders ? Or is there a way to incorporate them easily into nuscenes ? If not is there any other LIDAR dataset I could use that has lane/road markings annotated ? 

Thanks

**Comment by holger-nutonomy** [comment]
Please see the answer in our forum: https://forum.nuscenes.org/t/lane-and-road-border-annotated-ground-thruth-lidar-dataset-needed/60/2
