### ISSUE TITLE
Ego vehicle's speed and steering angle

### ISSUE THREAD

**Issue by jagdishbhanushali** [nutonomy/nuscenes-devkit#165]
Hi,
I am looking to get vehicle data. I found closed issue here https://github.com/nutonomy/nuscenes-devkit/issues/23, but don't have any update on that.
Greatly appreciate if we get speed, acceleration and steering angle.

**Comment by holger-nutonomy** [comment]
Hi. So far there are unfortunately no updates compared to https://github.com/nutonomy/nuscenes-devkit/issues/23 . We are currently working on rolling out the map extension and the vehicle data will be tackled after that.
