### ISSUE TITLE
assert_download.py error

### ISSUE THREAD

**Issue by sankim90** [nutonomy/nuscenes-devkit#166]
Hi.
I used python 3.7, and install dev-kit in local

To validation  I run assert_download, the following issues arise.

![Screenshot from 2019-06-17 18-37-55](https://user-images.githubusercontent.com/36911945/59594608-1d258780-912f-11e9-9371-6e58d1623f31.png)

Can I ignore it?

**Comment by holger-nutonomy** [comment]
It means that you didn't download the radar data.
Please try downloading it again, otherwise the tutorial won't work either.
