### ISSUE TITLE
NuScenes Error

### ISSUE THREAD

**Issue by HazemEssamAli** [nutonomy/nuscenes-devkit#168]
**Hello,**

**I always receive an error when I run the following code:**

get_ipython().run_line_magic('matplotlib', 'inline')
from nuscenes.nuscenes import NuScenes
nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=True)

**I guess the problem is in saving the datasets (v1.0-mini file), I know that I should save it under the specified dataroot but unfortunately I can not find it. can anyone help me please?**

**Here is the error I receive:**

Traceback (most recent call last):

  File "<ipython-input-18-22a1f015afd3>", line 3, in <module>
    from nuscenes.nuscenes import NuScenes

  File "C:\Users\haal1\tensorflow\nuscenes-devkit\python-sdk\nuscenes\nuscenes.py", line 21, in <module>
    from nuscenes.utils.data_classes import LidarPointCloud, RadarPointCloud, Box

ModuleNotFoundError: No module named 'nuscenes.utils'; 'nuscenes' is not a package

**Comment by chocojoX** [comment]
Have you installed the devkit ? `pip install nuscenes-devkit`

**Comment by HazemEssamAli** [comment]
yes, I have installed it and everything is installed.

at that step (python -m unittest) I receive 3 Failures and they are all the same:

AssertionError: Set NUSCENES env. variable to enable tests.

**Comment by holger-nutonomy** [comment]
The latter error occurs if you run the tests, as the tests need to know where your data is stored. Please [follow the instructions](https://github.com/nutonomy/nuscenes-devkit/blob/master/setup/installation.md) and run this command (adjusted for your path):
```
export NUSCENES="/data/sets/nuscenes"
```
Note that as a normal user you don't need to do that.

The error above looks more like you did not add the code to your Pythonpath:
```
export PYTHONPATH="${PYTHONPATH}:$HOME/nuscenes-devkit/python-sdk"
```

**Comment by HazemEssamAli** [comment]
Hello Holger, thank you for your reply, I can not do export command on my windows so I added the path manually, is there another way to add the path than the export command?

**Comment by holger-nutonomy** [comment]
Please note that we don't support Windows.
Apparently SET is the equivalent:
https://stackoverflow.com/questions/18701783/windows-equivalent-of-export
Good luck.

**Comment by HazemEssamAli** [comment]
Thank you for your answer, I’ll give it another try

**Comment by kir9-git** [comment]
Hi,

I receive this error while running any of the tutorial as well for any new jupyter book for procesing after installing and initializing the necessary setup requirements as mentioned in the requirements.txt file. 
Added the path in the environment variables in Windows 10 also done, still I get the following error:
![ENvironemnt_Variable](https://user-images.githubusercontent.com/38406867/84901782-93a1f000-b0c9-11ea-9ee2-3d5cff436d99.PNG)


ModuleNotFoundError: No module named 'nuscenes.utils'; 'nuscenes' is not a package
