### ISSUE TITLE
How do I read pcd.bin with pcl?

### ISSUE THREAD

**Issue by RogerAylagas** [nutonomy/nuscenes-devkit#17]
Hi,
I know this might be a noob question, but I am trying to read the point cloud of a pcd.bin file of the Lidar using PCL library in C++ but as the extension is pcd.bin loadPCDFile() does not work. I have alredy tried PCDReader but same error occurs

> [pcl::PCDReader::readHeader] No points to read

**How can I read the binary pointclouds using pcl in c++?**

**Comment by holger-nutonomy** [comment]
Hi,
that is actually a good question! The `.pcd.bin` extension is a bit confusing. Essentially we took a `.pcd` file, removed the headers and saved the data in binary format. You can see how we load it [here](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes_utils/data_classes.py#L34). So the LIDAR data is simply a bunch of float32 = 4 Bytes and each point is described by 5 floats. The following code in Python would print out the numbers:
```
import numpy as np

file_path = '/data/nuscenes/samples/LIDAR_TOP/n015-2018-07-18-11-50-34+0800__LIDAR_TOP__1531886224949600.pcd.bin'

with open(file_path, "rb") as f:
    number = f.read(4)
    while number != b"":
        print(np.frombuffer(number, dtype=np.float32))
        number = f.read(4)
```
Now you just need to implement that in C++.

**Comment by RogerAylagas** [comment]
Thank you for the quick response, just one more question: what are the fields of the points? x ,y ,z and intensity I supose, but what is the 5th field?
Thank you again!

**Comment by holger-nutonomy** [comment]
As described at https://github.com/nutonomy/nuscenes-devkit/blob/radar-visualization/python-sdk/nuscenes_utils/data_classes.py#L228 , that's the ring index (an integer between 0 and 31). We do not currently use it.

**Comment by RogerAylagas** [comment]
Oh okey thank you so much!!

**Comment by dada9375** [comment]
Hi Holger,
unfortunately I cannot find the page  https://github.com/nutonomy/nuscenes-devkit/blob/radar-visualization/python-sdk/nuscenes_utils/data_classes.py#L228 
Wasit removed?

**Comment by holger-nutonomy** [comment]
Hi @dada9375,
yes, we changed the folder structure a bit. It is now under: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/data_classes.py#L249

**Comment by dada9375** [comment]
Thanks Holger

**Comment by zexhuang** [comment]
Hi @holger-nutonomy, 
I tried to use the RadarPointCloud.from_file() to read a given pcd.bin file, but the from_file() only the file that  end with .pcd extension. In this case, how can I load the raw point cloud into a numpy array format?
