### ISSUE TITLE
Applying intrinces got not accurate bboxes

### ISSUE THREAD

**Issue by jinfagang** [nutonomy/nuscenes-devkit#170]
![image](https://user-images.githubusercontent.com/21303438/59910109-d04df380-9443-11e9-8589-5d24c0631e17.png)

I token dim, location from annotations, as  well a intrinsic, the box drawing above not accurate. I am trying to project 3D on image by using intrinsic but not using SDK, It seems something were miss.

Except for this intrinsic, should we got a rector matrix like KITTI?

I got calib data in KITTI is 3x4 like:

```
[[7.215377e+02 0.000000e+00 6.095593e+02 4.485728e+01]
 [0.000000e+00 7.215377e+02 1.728540e+02 2.163791e-01]
 [0.000000e+00 0.000000e+00 1.000000e+00 2.745884e-03]]
```

but intrinsic from nuScenes is 3x3 like:

```
[[1.26641720e+03 0.00000000e+00 8.16267020e+02]
 [0.00000000e+00 1.26641720e+03 4.91507066e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
```

How can I got the same 3x4 matrix from nuScenes? 

thanks in advance

**Comment by holger-nutonomy** [comment]
Take a look at our KITTI conversion code for inspiration:
https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_kitti.py
Note that you don't need a separate rectification matrix as the rectification is "baked into" the images.
