### ISSUE TITLE
Missing 2D Annotations for Images.

### ISSUE THREAD

**Issue by Rupesh14** [nutonomy/nuscenes-devkit#171]

**Comment by Rupesh14** [comment]
When I convert the 3d Annotation into 2D using the python file given in [github](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_2d_annotations_as_json.py). It results the annotation for only few images not for all images. And Also I like to know what is **dataroot** and **version** params in that file. Do these params have any impact on number of images that get annotated.

**Comment by holger-nutonomy** [comment]
Dataroot is the folder on your disk where nuScenes is.
version is `v1.0-trainval` for the v1.0 release and the trainval split.
You can basically ignore these.
I suppose the missing images are those without annotations?

**Comment by Rupesh14** [comment]
Certain Images seem to have no annotation upon 3D to 2D conversion.

**Comment by Rupesh14** [comment]
[Issue Noticed in this line](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_2d_annotations_as_json.py#L143) that it does not return values for all the scenarios as they are filtered by "> 0". Most of the images fail in this condition and are not considered.

**Comment by holger-nutonomy** [comment]
Hi. In the line you are referring to the majority of the *annotations* is filtered. That makes sense as most cameras have a 70 degree FOV. However, on the image-level it looks very different.
In fact I've just taken a look at a number of randomly sampled images with 0 annotations and they were all correct. Some examples:
![temp1](https://user-images.githubusercontent.com/39502217/60172111-95cac900-983e-11e9-9871-33b718016a89.jpg)
![temp2](https://user-images.githubusercontent.com/39502217/60172112-96635f80-983e-11e9-8d34-1538173d3938.jpg)
![temp3](https://user-images.githubusercontent.com/39502217/60172113-96635f80-983e-11e9-8d08-ce63232f69b3.jpg)
![temp4](https://user-images.githubusercontent.com/39502217/60172114-96635f80-983e-11e9-9315-834a1ed4de1c.jpg)
Of course there are some scenes were most of the frames have 0 objects in them.
If you find an image that has no annotations but should, please tell us the token and reopen this issue.

**Comment by Rupesh14** [comment]
sample_token: f15297033ecb46b49866929ac71889f8, filename: CAM_FRONT/n008-2018-09-18-14-43-59-0400__CAM_FRONT__1537296428112404.jpg
For the above sample token, there are 3D annotations. However, I am not getting any corresponding 2D annotations for the same. This is one of the tokens out of 2.4 million tokens
