### ISSUE TITLE
Inconsistent depth values between RADAR and LiDAR scans

### ISSUE THREAD

**Issue by brade31919** [nutonomy/nuscenes-devkit#173]
Hi nuscenes-devkit team,

When using nuscenes dataset, I found some serious inconsistencies between the rendered RADAR and LiDAR points. Here are some examples:

In sample d0ecf474e0e64950aa265cd44b9c9d75, if we plot the 'LIDAR_TOP' on 'CAM_BACK_RIGHT' using the given method render_pointcloud_in_image(), we will get the following depth map:
![gg](https://user-images.githubusercontent.com/13144700/60102992-0c909500-975f-11e9-90fe-c74c38b99b5f.png)
which looks reasonable.

But if we render the radar 'RADAR_BACK_RIGHT' on 'CAM_BACK_RIGHT', we will get the following depth map:
![gg](https://user-images.githubusercontent.com/13144700/60103173-6e50ff00-975f-11e9-8222-1655bcd2f2e1.png)
We can see that the yellow points are not consistent with the LiDAR scans.

Similar for the case between 'LIDAR_TOP' and 'RADAR_FRONT_LEFT' (both map to 'CAM_BACK_LEFT') in the same sample.

Is it resulted from errors of radar measurements?

**Comment by holger-nutonomy** [comment]
Hi, are you sure that the both plots use the same color scheme for the depth?
If they are scaled separately, then the second plot could be correct.

**Comment by holger-nutonomy** [comment]
Hi, looking at this closer I don't think the color scale is the problem.
If you look at the sensor setup figure you will see that `RADAR_BACK_RIGHT` on `CAM_BACK_RIGHT` actually point in quite different directions.
![sensors](https://user-images.githubusercontent.com/39502217/60154924-68205880-981b-11e9-94f8-d7f6c36a8375.png)
Rather you should look at `CAM_BACK`:
![fig1](https://user-images.githubusercontent.com/39502217/60155018-a0279b80-981b-11e9-8dc9-e61cb04cfba4.png)
The few points on that still project into `CAM_BACK_RIGHT` may be reflections or other noise.
It may also help to use different [filter settings](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/data_classes.py#L279) for the radar returns, although I couldn't find a good setting, other than only keeping returns on moving objects:
`RadarPointCloud.dynprop_states = [0, 2, 6]`

**Comment by brade31919** [comment]
Hi Holger,

Thank you for replying me.
Actually, for the posted example:
```
sample d0ecf474e0e64950aa265cd44b9c9d75 
lidar: 'LIDAR_TOP' 
radar: 'RADAR_BACK_RIGHT'
camera: 'CAM_BACK_RIGHT'
```

The inconsistency is resulted from color scaling.

However, for another orientation in the same example
```
sample d0ecf474e0e64950aa265cd44b9c9d75 
lidar: 'LIDAR_TOP' 
radar: 'RADAR_FRONT_LEFT' 
camera: 'CAM_BACK_LEFT'
```

After we used consistent color scaling, we obtained:
![image](https://user-images.githubusercontent.com/13144700/60257443-c3158680-98d3-11e9-8656-662080df674f.png)
and
![image](https://user-images.githubusercontent.com/13144700/60257517-e6d8cc80-98d3-11e9-92f7-4e42cdf9e782.png)
We can see inconsistencies on the window. So...maybe that are resulted from reflections?

The reason for projecting radars facing slightly different from camera is that the radar points on orientations except "front" and "back" are way too sparse. Considering radar sensors have larger field of view, I think projecting multiple sensors onto one camera might be good (at least I think so...). Or do you have any other suggestions.

I will try the filter settings you mentioned. Is there any documentation or suggested articles about filtering on radar signal?

**Comment by holger-nutonomy** [comment]
Yes, I think that may be due to reflections.
Note that the radar has a larger FOV, but the coverage is not uniform at all.
In fact, each of our radars combines short range and long range as shown here:
![radar](https://user-images.githubusercontent.com/39502217/60258653-26b9a700-9908-11e9-972a-7456d948492e.png)

If you write me at holger@nutonomy.com I can send you the manufacturer's handbook, but I'm not sure if that will help.

**Comment by brade31919** [comment]
Hi Holger,

Haha it seems that the setting of the radar is pretty complicated.
I think the handbook will be helpful!
I will send the email to you later.

Thank you for the answer
