### ISSUE TITLE
Projection error of lidar points to cam_front 

### ISSUE THREAD

**Issue by fabvio** [nutonomy/nuscenes-devkit#175]
Hi,
first of all, thanks for releasing the dataset. I have problems in the projection of LiDAR points on the CAM_FRONT image. I want to render the lidar points on CAM_FRONT also for sweeps, so I'm using the following code:

```                
# In images, lidars there is an ordered list of associated CAM_FRONT samples + sweeps and pointclouds

for image, lidar in zip(images, lidars):
    # nexp is a nuscenes explorer
    lidar_points, lidar_coloring, lidar_image = nexp.map_pointcloud_to_image(pointsensor_token=lidar['token'], camera_token=image['token'])

    savename_viz = os.path.join(DIR_VIZ, os.path.basename(image['filename'].replace('.jpg', '_lidar.png')))

    plt.figure(figsize=(9, 16))
    plt.imshow(lidar_image)
    plt.scatter(lidar_points[0, :], lidar_points[1, :], c=lidar_coloring, s=5)
    plt.axis('off')
    plt.savefig(savename_viz)

```

What I get is some good projections, and some really noisy ones. Do you have any idea of where is the problem?

Wrong projection
![wrong](https://user-images.githubusercontent.com/10325202/60165235-4618dd00-97ff-11e9-805c-39ad31597e46.png)

Right projection
![right](https://user-images.githubusercontent.com/10325202/60165236-46b17380-97ff-11e9-9636-f56fa6559d5e.png)

**Comment by holger-nutonomy** [comment]
Hi. Take a look at the picture of our car:
![](https://www.nuscenes.org/public/images/gallery-2.jpg)
You can see that the camera mounts on the roof (mostly) have the same shape as the wrong points in your lidar pointcloud. In fact, these points always show up in the lidar data, but *behind* the camera. To be absolutely sure we remove close points to the ego vehicle by [filtering by distance](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/geometry_utils.py#L76). I have checked this on a lot of *samples* and I have never seen any issues. However, when you start using the non-keyframes, camera and lidar are slightly out of sync, as they have different capture frequencies. Particularly if you move along the 20s scene using the `next` pointers on both camera and lidar, the time difference will accumulate and you are rendering pointclouds collected in the future. Hence the points are in front of the camera.

My suggestions are:
- Make sure that your images are close in time to the pointclouds. E.g. by following [this simple logic](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L940).
- Checkout [this PR](https://github.com/nutonomy/nuscenes-devkit/pull/177) that also introduces the distance filtering to the `map_pointcloud_to_image` function.
Please let me know if the issue persists.

**Comment by fabvio** [comment]
Thank you!
