### ISSUE TITLE
Reopened: Missing 2D Annotations

### ISSUE THREAD

**Issue by Rupesh14** [nutonomy/nuscenes-devkit#176]
Reopening the following [issue](https://github.com/nutonomy/nuscenes-devkit/issues/171)

sample_token: f15297033ecb46b49866929ac71889f8, filename: CAM_FRONT/n008-2018-09-18-14-43-59-0400__CAM_FRONT__1537296428112404.jpg
For the above sample token, there are 3D annotations. However, I am not getting any corresponding 2D annotations for the same. This is one of the tokens out of 2.4 million tokens

**Comment by holger-nutonomy** [comment]
Hi, running
```
[sd for sd in nusc.sample_data if sd['filename'].endswith('CAM_FRONT/n008-2018-09-18-14-43-59-0400__CAM_FRONT__1537296428112404.jpg')]
```
returns
```
[{'token': '92d035d2ded443508d35da9ea40130d2',
  'sample_token': 'f15297033ecb46b49866929ac71889f8',
  'ego_pose_token': '92d035d2ded443508d35da9ea40130d2',
  'calibrated_sensor_token': '42090f44e84a42d6868f1c5ecff086d5',
  'timestamp': 1537296428112404,
  'fileformat': 'jpg',
  'is_key_frame': False,
  'height': 900,
  'width': 1600,
  'filename': 'sweeps/CAM_FRONT/n008-2018-09-18-14-43-59-0400__CAM_FRONT__1537296428112404.jpg',
  'prev': '249ff825f4524eed86029a895e453ed1',
  'next': 'c54bcbe5b8b0403bb62dcc35f7183ed4',
  'sensor_modality': 'camera',
  'channel': 'CAM_FRONT'}]
```
So the image you are looking at is not a keyframe (`'is_key_frame': False`).
We annotate for keyframes at 2Hz which means that all non-keyframes do not have annotations.
