### ISSUE TITLE
timestamps and syncing

### ISSUE THREAD

**Issue by melonii** [nutonomy/nuscenes-devkit#180]
At first: Thanks a lot for the data and the corresponding devkit!
Please correct me if the following is wrong:

Annotations are given on a sample-level, so their position in the global coordinate system belongs to the sample-timestamp X (which seems to be equal to the Lidar-sample_data-timestamp?!).
Say you use render_sample_data() for CAM_FRONT, then boxes made from annotations with timestamp X are transformed to the sensor coordinate system by using the ego_pose of the specific sample_data and therefore timestamp Y (because CAM_FRONT data has a different timestamp as the sample).

So here we make a little mistake by assuming the ego_pose didn't change too much between timestamp X and timestamp Y?

**Comment by holger-nutonomy** [comment]
> which seems to be equal to the Lidar-sample_data-timestamp?!

Exactly

> So here we make a little mistake by assuming the ego_pose didn't change too much between timestamp X and timestamp Y?

It's more difficult than that. Capturing a single point cloud is not instantaneous. As described [here](https://www.nuscenes.org/data-collection?externalData=all&mapData=all&modalities=Any), as the lidar sweeps around the vehicle we trigger each camera when the lidar is in the center of its FOV. So the single lidar timestamp is confusing. It is really the period of 1/20s duration before that timestamp. Hence for a lidar point in the center of the FOV the time difference should be almost 0, whereas for the point 180 degrees away it should be 1/40s. 
Also note that the annotators are instructed to respect camera, radar and lidar (as good as possible).

**Comment by melonii** [comment]
That makes sense. 
The process is like:
Lidar sweeps, boom, hits the center of FOV of CAM_BACK --> photo, timestamp and ego_pose are saved. Lidar sweep continuous, completes one sweep, boom, accumulated pointcloud, timestamp and ego_pose are saved. 
-->The lidar points in the FOV of a camera nearly have the same timestamp.

That's it for cameras and lidar, but how come the annotations into play?
A moving scene of duration 1/20s is represented by one sample. During this 1/20s different cameras at different timestamps and at different ego_poses are triggered. While annotating the annotator has to define translation and rotation of an object in global coordinates, while keeping in mind, that the whole scene was moving during the 1/20s.

My issue:
I would like to transform the annotations from global coordinates to ego coordinates on a sample-level, not individually for e.g. CAM_BACK and its individual ego_pose. Would it be best practice to just use the lidar-sample_data-ego_pose as the "default"-one?

**Comment by holger-nutonomy** [comment]
I don't think that makes much sense, since the annotations will not be valid.
