### ISSUE TITLE
nuscenes to rosbag

### ISSUE THREAD

**Issue by poodarchu** [nutonomy/nuscenes-devkit#182]
can you support convert nuScenes scenes to rosbag files?

**Comment by holger-nutonomy** [comment]
Hi. Unfortunately that is beyond our scope, but if you want to write such code I'd be happy to link to it from our documentation.

**Comment by poodarchu** [comment]
ok

**Comment by shmpwk** [comment]
@poodarchu If you implement that code, could you share it with us?
