### ISSUE TITLE
Shapely version problem

### ISSUE THREAD

**Issue by hahakid** [nutonomy/nuscenes-devkit#183]
When installing on win10, and using pip install -r requirements.txt,  a issue will be triggered.
This is caused by version of  Shapely.
---------------------
lgeos = CDLL("geos_c.dll")
..................
OSError: [WinError 126] The specified module could not be found
--------------------
According to  [https://github.com/Toblerity/Shapely/issues/738](url), I manully degraded the version to **1.4.1** , because the pip will use the newest version of Shapely (**1.6.1**).
This helps me install the toolkit successfully, but I am not sure if the version will cause any other problem. 

Does the repo has a strict requirements on **Shapely** version?

**Comment by oscar-nutonomy** [comment]
hey @hahakid : please post to forum instead. Tnx.
https://forum.nuscenes.org/
