### ISSUE TITLE
Database access for sweep images

### ISSUE THREAD

**Issue by chandamarnath** [nutonomy/nuscenes-devkit#184]
I was wondering if there was a method to access the sweep data, both lidar and camera and their associated timestamps through the database tokens? As far as I can see the DB tokens map only to sample images, timestamps and data.
Thanks!

**Comment by holger-nutonomy** [comment]
All sensor readings (lidar, camera, radar) are stored in the [`sample_data` table](https://github.com/nutonomy/nuscenes-devkit/blob/master/schema.md#sample_data). Some of these are keyframes as indicated by `is_key_frame`, others are not.
If you start from the `sample` table then you get only keyframes, but you can use the `next` and `prev` pointers to move forward/backward in time, which also includes non-keyframes.
