### ISSUE TITLE
What is the Focal length of the camera in mm

### ISSUE THREAD

**Issue by sainisanjay** [nutonomy/nuscenes-devkit#185]
@holger-nutonomy @aloukkal 
I would like to calculate the distance of the object from the camera thus Focal length is required in mm. Kindly let me know whats is the camera Focal Length in mm. 
As you have used "1/1.8'' CMOS sensor of 1600x1200 resolution" the following website shows: 
[https://www.vision-doctor.com/en/camera-technology-basics/sensor-and-pixel-sizes.html](url)
7.2x5.4mm. 
is it right???

**Comment by holger-nutonomy** [comment]
Yes, that matches the numbers for the sensor size that I have found. Let me know if you have more questions.
