### ISSUE TITLE
What does 'false alarm probability of cluster' of radar point cloud mean?

### ISSUE THREAD

**Issue by djkzzh** [nutonomy/nuscenes-devkit#187]
Hi, i have two question about radar point cloud. The first one is that what's cluster of radar point cloud and how to obtain point cloud cluster. The second one is that What does 'false alarm probability of cluster' of radar point cloud mean and how to calculate the false alarm probability.

Thank you!

**Comment by holger-nutonomy** [comment]
Hi. The radar sensor performs clustering of the radar returns for the purpose of object detection etc.. The different flags can be used to filter clusters by their dynamic properties, ambiguity and an estimate of their confidence / false alarm probability.
I do not know what clustering algorithm the vendor uses and the manual does not go into detail there. If you want to take a closer look, please contact me at holger@nutonomy.com and I'll send you the technical manual of the radar sensor.

**Comment by djkzzh** [comment]
Thanks for the quick reply.
