### ISSUE TITLE
Feature request: projecting the map into image space

### ISSUE THREAD

**Issue by johnwlambert** [nutonomy/nuscenes-devkit#188]
Thanks very much for the map expansion pack and [Jupyter notebook](https://www.google.com/url?q=https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/map_expansion/map_demo.ipynb&sa=D&source=hangouts&ust=1563470906254000&usg=AFQjCNH4mCIcDBuzGLvaZCvQsN6oBKtfSA). I think this will provide great value to our community.

I'm having a bit of trouble understanding the many overlapping layers, and figure they would be easier to understand when projected into image space.

We provided image space projections in our Jupyter notebooks when we created Argoverse. Would you consider adding such functionality to your Jupyter notebooks?  Would it also be possible to provided rendered versions of the notebooks to prevent the need for a full download of all of the data?

For an example of projecting the map into image space, please see this Argoverse notebook (scroll to the last two figures): https://github.com/argoai/argoverse-api/blob/master/demo_usage/argoverse_map_tutorial.ipynb

**Comment by holger-nutonomy** [comment]
Thank you for your interest and for providing Argoverse.

We have a rendered version of the devkit tutorial (https://www.nuscenes.org/tutorial) and will add another one for the map tutorial in the same menu.

Projecting the map into the image space sounds like an interesting idea. Unfortunately we're pretty busy at the moment, but I'll create a feature request for it.

**Comment by SaikiranKannaiah436** [comment]
> Thanks very much for the map expansion pack and [Jupyter notebook](https://www.google.com/url?q=https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/map_expansion/map_demo.ipynb&sa=D&source=hangouts&ust=1563470906254000&usg=AFQjCNH4mCIcDBuzGLvaZCvQsN6oBKtfSA). I think this will provide great value to our community.
> 
> I'm having a bit of trouble understanding the many overlapping layers, and figure they would be easier to understand when projected into image space.
> 
> We provided image space projections in our Jupyter notebooks when we created Argoverse. Would you consider adding such functionality to your Jupyter notebooks? Would it also be possible to provided rendered versions of the notebooks to prevent the need for a full download of all of the data?
> 
> For an example of projecting the map into image space, please see this Argoverse notebook (scroll to the last two figures): https://github.com/argoai/argoverse-api/blob/master/demo_usage/argoverse_map_tutorial.ipynb

Wow! This is exactly what I was looking for :). Thanks a lot.

**Comment by holger-nutonomy** [comment]
As a first step the map tutorial can be found at: https://www.nuscenes.org/map-tutorial

**Comment by holger-nutonomy** [comment]
This request has been addressed in: https://github.com/nutonomy/nuscenes-devkit/pull/195
Let me know if you have any questions.
