### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by aacmi** [nutonomy/nuscenes-devkit#189]
Hi ,

I'm using this package [(https://github.com/traveller59/second.pytorch)]. nuscenes-devkit is installed as per the instructions.

When i execute this: 
 python3 create_data.py nuscenes_data_prep --root-path=/home/ubuntu/nuscene_trainval --version="v1.0-trainval" --dataset_name="nuscene"--max_sweeps=10

I'm getting the following error,

assert name in REGISTERED_DATASET_CLASSES, f"available class: {REGISTERED_DATASET_CLASSES}"
AssertionError: available class: {'KittiDataset': <class 'second.data.kitti_dataset.KittiDataset'>, 'NuScenesDataset': <class 'second.data.nuscenes_dataset.NuScenesDataset'>, 'NuScenesDatasetD8': <class 'second.data.nuscenes_dataset.NuScenesDatasetD8'>, 'NuScenesDatasetD8Velo': <class 'second.data.nuscenes_dataset.NuScenesDatasetD8Velo'>, 'NuScenesDatasetVelo': <class 'second.data.nuscenes_dataset.NuScenesDatasetVelo'>, 'NuScenesDatasetD7': <class 'second.data.nuscenes_dataset.NuScenesDatasetD7'>, 'NuScenesDatasetD6': <class 'second.data.nuscenes_dataset.NuScenesDatasetD6'>, 'NuScenesDatasetD5': <class 'second.data.nuscenes_dataset.NuScenesDatasetD5'>, 'NuScenesDatasetD4': <class 'second.data.nuscenes_dataset.NuScenesDatasetD4'>, 'NuScenesDatasetD3': <class 'second.data.nuscenes_dataset.NuScenesDatasetD3'>, 'NuScenesDatasetD2': <class 'second.data.nuscenes_dataset.NuScenesDatasetD2'>, 'NuScenesDatasetD2Velo': <class 'second.data.nuscenes_dataset.NuScenesDatasetD2Velo'>}

Any idea/help will be appreciated.
thanks.

**Comment by holger-nutonomy** [comment]
Hi. Please note that that repository does not belong to us. Generally it is best to ask the authors in their own repo. Looking at their readme, it looks like you specified the wrong dataset_name. It should be `--dataset_name="NuscenesDataset"`.

**Comment by TangeniThePyGuru** [comment]
The dataset name should be written as `--dataset_name="NuScenesDataset"`, the error also points that out, that the name can only be one of the class names listed. Refer to the third line
