### ISSUE TITLE
Poor python skills

### ISSUE THREAD

**Issue by jinfagang** [nutonomy/nuscenes-devkit#19]
Can not run it under python3, this syntax is really not pythonic:

```
    def __init__(self, version: str='v0.1', dataroot: str='/data/nuscenes', verbose: bool=True):

```

**Comment by holger-nutonomy** [comment]
Hi. Which part are you unhappy about? I suppose you mean the type hints, e.g. ": str". This is a new and very useful feature introduced in Python 3.5: https://docs.python.org/3/library/typing.html
Please make sure that you install Python 3.7 as described at https://github.com/nutonomy/nuscenes-devkit
