### ISSUE TITLE
Project lidar pointcloud into camera front image_plane 

### ISSUE THREAD

**Issue by GotCstl** [nutonomy/nuscenes-devkit#192]
Hi,

I would like to project the Lidar_Top pointcloud into the camera_front image plane, ie like in the Kitti Dataset using projection matrix to get each lidar point pixel coordinates. Is there a way to do it with NuScenes?

**Comment by holger-nutonomy** [comment]
Please take a look at https://www.nuscenes.org/tutorial , specifically `render_pointcloud_in_image` does what you want. Also please ask all further questions in https://forum.nuscenes.org
