### ISSUE TITLE
How to include the map information on the birdview

### ISSUE THREAD

**Issue by M-Hammod** [nutonomy/nuscenes-devkit#193]
Hi, 
I wonder if you could provide some code example of how to include map information in the bird view 

![image](https://user-images.githubusercontent.com/24555279/61804820-984f1d00-ae02-11e9-8a25-15bf35596060.png)

**Comment by holger-nutonomy** [comment]
Hi. Please familiarize yourself with the newly added map expansion pack: https://www.nuscenes.org/map-tutorial
In particular `render_map_mask` and `get_map_mask` are what you need.

Please ask any further questions on: https://forum.nuscenes.org

**Comment by holger-nutonomy** [comment]
Please note that the nuScenes map has been updated to fix the slight offset in some 43 scenes. Take a look at https://github.com/nutonomy/nuscenes-devkit/pull/279 for more information and download the new maps from https://www.nuscenes.org/download.
