### ISSUE TITLE
ego_pose_on_map

### ISSUE THREAD

**Issue by M-Hammod** [nutonomy/nuscenes-devkit#197]
I'm trying to render ego_pose on the map and I got the following result using the nuscenes_mini, as you can see the ego vehicle track (orange) ends up outside the map, is there a reason that area is not mapped as derivable layer in the map?: 
![Figure_1](https://user-images.githubusercontent.com/24555279/62185903-2f9bff00-b332-11e9-84cd-5e62e7cbf7d1.png)

Thanks

**Comment by holger-nutonomy** [comment]
Hi, please read the note in the PR https://github.com/nutonomy/nuscenes-devkit/pull/196:
```
Note that the maps are constantly evolving, whereas we only released a single snapshot of the data. Therefore for some scenes there is a bad fit between ego poses and maps. When rendering these scenes with the verbose flag, a warning will be issued.
```
So the issue is not in the map, which is correct, but rather in the ego pose and map not aligning very well for some scenes. The error can be up to 1 lane width.

**Comment by holger-nutonomy** [comment]
Please note that the nuScenes map has been updated to fix the slight offset in some 43 scenes. Take a look at https://github.com/nutonomy/nuscenes-devkit/pull/279 for more information and download the new maps from https://www.nuscenes.org/download.
