### ISSUE TITLE
Pedestrians on map

### ISSUE THREAD

**Issue by atanas1054** [nutonomy/nuscenes-devkit#198]
Hello,

How can I get the position of the pedestrians on the semantic map? Also, I want to get the semantic labels in an area around each pedestrian.

**Comment by holger-nutonomy** [comment]
Take a look at https://www.nuscenes.org/map-tutorial
In particular the line `nusc_map.layers_on_point(point[0], point[1])`.
The point would be the x/y of the [sample_annotation's translation](https://github.com/nutonomy/nuscenes-devkit/blob/master/schema.md#sample_annotation).

**Comment by holger-nutonomy** [comment]
Please note that the nuScenes map has been updated to fix the slight offset in some 43 scenes. Take a look at https://github.com/nutonomy/nuscenes-devkit/pull/279 for more information and download the new maps from https://www.nuscenes.org/download.
