### ISSUE TITLE
Installing with pip from local clone

### ISSUE THREAD

**Issue by DavidS3141** [nutonomy/nuscenes-devkit#199]
Thanks for the great dataset. I wanted to play around a little bit with the evaluation code so I cloned the github repo into my project and wanted to install it in editable mode using `pip install -e packages/nuscenes-devkit` as I sometimes do with other packages as well. However, in this case it did not work directly, as the `setup.py` lies in the subdir `setup`. So I change the pip-command to `pip install -e packages/nuscenes-devkit/setup`. However, on the first run, this creates a directory `python-sdk/nuscenes-devkit.egg-info` and fails, and with subsequent calls it provides a slightly different error because now this is regarded by the `setup.py` also as python package (see [here](https://github.com/nutonomy/nuscenes-devkit/blob/master/setup/setup.py#L17)). This I fixed and the original error returns. I am not super familiar with `setuptools` and organizing Pypi packages, so I just wanted to ask, how is the intended way to get this working? I assume there is an intended way, because it works nicely from installing it directly from the Pypi repo.

Any help is appreciated.

**Comment by holger-nutonomy** [comment]
Hi. I've tried a few options from https://stackoverflow.com/questions/30306099/pip-install-editable-vs-python-setup-py-develop , but couldn't get any to work. Apparently `pip install -e . installs dependencies with pip, while python setup.py [...] installs with easy_install`. That may explain the differences. 

One option for debugging is simply to create an account on test.pypi.org and submit the pip package there:
```
cd ~/nuscenes-devkit/setup
python setup.py bdist_wheel
python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/nuscenes_devkit-*
pip install --index-url https://test.pypi.org/simple --extra-index-url https://pypi.org/simple nuscenes-devkit==1.0.2
```
But I still think the best option for developing is simply to have the code and add it to your Pythonpath.

**Comment by holger-nutonomy** [comment]
Did you find the solution? Closing this for now. Let me know if you have any more questions.

**Comment by likui01** [comment]
> Hi. I've tried a few options from https://stackoverflow.com/questions/30306099/pip-install-editable-vs-python-setup-py-develop , but couldn't get any to work. Apparently `pip install -e . installs dependencies with pip, while python setup.py [...] installs with easy_install`. That may explain the differences.
> 
> One option for debugging is simply to create an account on test.pypi.org and submit the pip package there:
> 
> ```
> cd ~/nuscenes-devkit/setup
> python setup.py bdist_wheel
> python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/nuscenes_devkit-*
> pip install --index-url https://test.pypi.org/simple --extra-index-url https://pypi.org/simple nuscenes-devkit==1.0.2
> ```
> 
> But I still think the best option for developing is simply to have the code and add it to your Pythonpath.

error in nuscenes-devkit setup command: "values of 'package_data' dict" must be a list of strings (got '*.json')

I get this error, when running this.
any idea how to fix it?

**Comment by holger-nutonomy** [comment]
Unfortunately I haven't seen that issue. I suggest you just use pip install or don't use pip at all.

**Comment by likui01** [comment]
thank you for your reply, 
I use pip install, but when i run  following, i get error.
 import NuScenesMap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'NuScenesMap'

**Comment by holger-nutonomy** [comment]
- I don't think you can just `import NuScenesMap`. You should do `from nuscenes.map_expansion.map_api import NuScenesMap`.
- I suggest you update your pip package. I just created a new version, as the previous one was quite old : https://pypi.org/project/nuscenes-devkit/

**Comment by likui01** [comment]
Thank you for update, now it works :)

**Comment by Varatharajan-Raja** [comment]
I had a similar issue while running with docker. I resolved it with this [setup.py](https://stackoverflow.com/questions/72715462/how-to-install-this-python-package-from-sources)
