### ISSUE TITLE
Height prediction irrelevant for evaluation metric

### ISSUE THREAD

**Issue by DavidS3141** [nutonomy/nuscenes-devkit#200]
I realised that none of the implemented metrics in the evaluation code is sensitive to the provided height prediction in the submitted results. I actually tested this and moved all predictions 100m under the ground, and the metrics return the same values, as only the xy-position is relevant for AP and ATE and all other errors do not include position at all.

Is this intended behaviour, and when yes, with what reasoning?

If not, might I suggest including this into the ASE by aligning the prediction with the ground truth in xy-position and orientation, but not aligning in z-position, and then computing the IOU. This was actually the behaviour I expected to see, when I read the metric description, as xy-position and orientation were the only things talked about, so I assumed those were the features used for alignment.

**Comment by holger-nutonomy** [comment]
Hi. We deliberately dropped z from AP and ATE as our localization does not have a z component (but the annotations do). Regardless of that I don't think z should go into ASE as the goal was to entirely disentangle scale and translation. The formula for ASE is similar to IOU, but not the same.
