### ISSUE TITLE
Possible erroneous values in RADAR pointcloud data

### ISSUE THREAD

**Issue by kotianaj** [nutonomy/nuscenes-devkit#201]
Hi Nuscenes Team,

I am currently working on a camera-radar fusion technique using 'CAM_FRONT' and 'RADAR_FRONT' from sample folder of mini dataset. While mapping the radar pointclouds on image using "map_pointcloud_to_image" method and then filtering it with my algorithm, I came across few possible discrepancies and therefore wanted to bring it to your notice. 
I have formulated few related questions as well,

![image](https://user-images.githubusercontent.com/53562117/62293338-b05d1700-b468-11e9-9ac3-12f1eb89db50.png)

![image](https://user-images.githubusercontent.com/53562117/62294924-552d2380-b46c-11e9-82df-7c5267fc38c3.png)

**-** The figure is from **scene1 frame 0** of sample folder. The gray coloured car has four radar pointclouds on it (represented by yellow dots) and since it is a parked car, the velocity components should be close to 0. However, if you refer **table 1**, the radar point (represented by a blue dot) at pixel **x = 832.3** and **y = 500.1** with a **radar_id = 85** (obtained from .pcd file) shows a high velocity values v.i.z. **vx_comp = 21.267 m/s** and **vy_comp = 4.5218 m/s**, which could possibly be from the black car that is approaching the ego vehicle.

**Question 1:** Is it a known problem, could it be possible that the image and mapped radar points are not perfectly overlapping and therefore the pixels don't exactly represent radar pcs on image?

![image](https://user-images.githubusercontent.com/53562117/62295035-84439500-b46c-11e9-8ba5-1d8b4a75c2d6.png)

![image](https://user-images.githubusercontent.com/53562117/62295013-7726a600-b46c-11e9-9c80-f0f5ae8218d0.png)

**-** According to the radar calibration, **x is front** (x coordinates in forward direction are positive) and **y is left** (y coordinates on the left side are positive) in radar coordinate system. So, taking this into consideration the y coordinates of radar point clouds lying on the left side of the ego vehicle (assuming the position of radar sensor as 0,0) should be positive and those on the right should have negative values. Likewise, after transforming the radar pointclouds to image coordinate system, **z becomes front** (positive in front) and **x becomes right** (positive on the right side). But, if you refer **table 2**, in which I have considered two points in the left half of the image plane (represented with yellow and white coloured stars). The point cloud with **radar_id = 23** is with an opposite sign convention in both the coordinate system.
Similarly, if you refer table 3, there is a similar discrepancy in radar point cloud with **radar_id = 51** in the right half of image plane (represented with cyan coloured star).

**Question 2:** Is my assumption related to the sign convention correct? If so, what could be the reason for this change in sign convention?

![image](https://user-images.githubusercontent.com/53562117/62296866-506a6e80-b470-11e9-9ac4-3a678a195713.png)

**-** This is related to velocity components, before (vx, vy) and after compensation (vx_comp, vy_comp). 

**Question 3:** Is there a positive/negative direction defined for vx, vy and likewise for vx_comp and vy_comp mentioned in table 4)? Could you please explain a bit how the compensated velocities were calculated?

Best Regards,
Ajay K

**Comment by holger-nutonomy** [comment]
Question 1: In general the location of the radar returns is far less accurate than for e.g. lidar. There may also be a time offset between the camera and radar which may explain while you are already getting radar returns from the fast moving black car although in the camera it isn't at that location yet. Ultimately there can also be minor calibration issues or issues resulting from reflections on the cars. You should also consider filtering the radar returns by the various flags. However in general we haven't seen any systematic errors, e.g. indicating a bad calibration.

Question 2: Your summary of the coordinate frames is correct.
A good visualization can be found [here](https://www.nuscenes.org/data-collection).
However, I don't understand the problem. You said:
Radar: `right should have **negative** values` (y)
Camera: `**positive** on the right side` (x)
And your table shows that the camera x and radar y have opposite signs.

Question 3: Note that these are provided by the radar manufacturer. If you send me an email to holger@nutonomy.com I can send you the handbook.

**Comment by kotianaj** [comment]
Hello Holger,
Thank you for the quick reply and also for the suggestion to filter the radar returns.

Regarding Question 2: Let me include more radar pointclouds to the table and elaborate the problem with the help of a figure.

![image](https://user-images.githubusercontent.com/53562117/62314212-d1d2f880-b492-11e9-8093-36b9ff2d26df.png)

![image](https://user-images.githubusercontent.com/53562117/62314240-dc8d8d80-b492-11e9-9864-4540a474abe0.png)

In the below figure, radar_ids: 6, 23, 30 and 54 lie in the positive x and positive y axis (in radar coordinate frame), assuming center of front radar sensor to be the origin. Therefore, the x and y value of all the pointclouds in this quadrant are expected to be positive (something like x = 7.458 and y = 3.034). If you refer table 2, then you will notice that, all other pointclouds except radar_id = 23 (represented by white star), confirm this assumption. The pointcloud in question, has a negative value of y = -9.699, which could be an anomaly.

![image](https://user-images.githubusercontent.com/53562117/62314188-be279200-b492-11e9-81ed-e30841fb0705.png)

Similarly, radar_ids: 51, 72, 79 and 80 lie in the positive x-axis and negative y-axis (again in radar coordinate frame). Which, if we observe in above figure, should have positive x values and negative y values (something like x = 7.458 and y = -3.034). Again if you refer table 3, all the pointclouds except the one with radar_id = 51 (represented by cyan star) comply to the assumption. It has a positive value of y = 6.099. This anomaly is also reflected after the transformation from radar to camera coordinate frame (that is why camera x and radar y have opposite values).

Is there a way to filter them as well, or does it needs to be ignored, as you already mentioned that radar returns are less accurate?

Best Regards,
Ajay K

**Comment by holger-nutonomy** [comment]
It's difficult to follow as you don't provide code. Here are some thoughts:
- Note that the returns with radar_id 6, 23 and 51 are all rejected by the default filtering settings. So you should probably ignore these points.
- Point 23 is in the wrong quadrant in the radar plot. It should have a negative y value. Point 51 is also in the wrong quadrant.
- The columns for radar coordinate and camera coordinate system are correct in your table, but the pixel coordinates are wrong. Point 23 projects to (1611, 547). Below is the code I used:
```
import os

from pyquaternion import Quaternion
import numpy as np

from nuscenes.utils.data_classes import RadarPointCloud
from nuscenes.utils.geometry_utils import view_points
from nuscenes.nuscenes import NuScenes

nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=True)

sample_token = nusc.scene[1]['first_sample_token']
sample_record = nusc.get('sample', sample_token)
radar_token = sample_record['data']['RADAR_FRONT']
camera_token = sample_record['data']['CAM_FRONT']
pointsensor = nusc.get('sample_data', radar_token)
cs_record = nusc.get('calibrated_sensor', pointsensor['calibrated_sensor_token'])
cam = nusc.get('sample_data', camera_token)

pc = RadarPointCloud.from_file(os.path.join(nusc.dataroot, pointsensor['filename']), invalid_states=range(18), dynprop_states=range(8), ambig_states=range(5))
sel_index = int(np.where(pc.points[4, :] == 23)[0])
print(pc.points[:3, sel_index])

# First step: transform the point-cloud to the ego vehicle frame for the timestamp of the sweep.
cs_record = nusc.get('calibrated_sensor', pointsensor['calibrated_sensor_token'])
pc.rotate(Quaternion(cs_record['rotation']).rotation_matrix)
pc.translate(np.array(cs_record['translation']))

# Second step: transform to the global frame.
poserecord = nusc.get('ego_pose', pointsensor['ego_pose_token'])
pc.rotate(Quaternion(poserecord['rotation']).rotation_matrix)
pc.translate(np.array(poserecord['translation']))

# Third step: transform into the ego vehicle frame for the timestamp of the image.
poserecord = nusc.get('ego_pose', cam['ego_pose_token'])
pc.translate(-np.array(poserecord['translation']))
pc.rotate(Quaternion(poserecord['rotation']).rotation_matrix.T)

# Fourth step: transform into the camera.
cs_record = nusc.get('calibrated_sensor', cam['calibrated_sensor_token'])
pc.translate(-np.array(cs_record['translation']))
pc.rotate(Quaternion(cs_record['rotation']).rotation_matrix.T)
print(pc.points[:3, sel_index])

points_im = view_points(pc.points[:3, :], np.array(cs_record['camera_intrinsic']), normalize=True)
print(points_im[:3, sel_index])
```
It returns:
```
[14.         -9.69999981  0.        ]
[ 9.96739111  0.97784966 15.90646939]
[1.61163210e+03 5.47001306e+02 1.00000000e+00]
```

**Comment by kotianaj** [comment]
Thanks Holger for the detailed explanation. 

I am using the same code from nuscenes devkit, that you posted above, for obtaining the corresponding pixel values for each of the radar points.

I checked my code again and yes what you pointed out is correct. 
after the transformation step the point 23 and 51 return
`[1.61163210e+03 5.47001306e+02 1.00000000e+00]` and `[603.44648581 521.95436297   1.        ]`, instead of `[603.4 521.9]` and `[1249.6 503.0]` respectively. Then I checked other radar returns as well and they too were with wrong pixel values.

However, after transformation step, when I passed the `points` array through below filtering code

```
# Remove points that are either outside or behind the camera. Leave a margin of 1 pixel for aesthetic reasons.
mask = np.ones(depths.shape[0], dtype=bool)
mask = np.logical_and(mask, depths > 0)
mask = np.logical_and(mask, points[0, :] > 1)
mask = np.logical_and(mask, points[0, :] < im.size[0] - 1)
mask = np.logical_and(mask, points[1, :] > 1)
mask = np.logical_and(mask, points[1, :] < im.size[1] - 1)
points = points[:, mask]
coloring = coloring[mask]

print(points[:3, sel_index])
```

Then the result I got is same as that in table 2 and 3

```
radar_id = 6
[3.5999999  8.69999981 0.        ]
[-8.59575273  1.14456333  5.80192164]
[-1.02949894e+03  7.17131044e+02  1.00000000e+00]
-->[201.08250344 554.96939417   1.        ]

radar_id = 23
[14.         -9.69999981  0.        ]
[ 9.96739111  0.97784966 15.90646939]
[1.61163210e+03 5.47001306e+02 1.00000000e+00]
-->[603.44648581 521.95436297   1.        ]

radar_id = 51
[29.20000076  6.0999999   0.        ]
[-5.58496372  1.30073842 31.35638901]
[603.44648581 521.95436297   1.        ]
-->[1.24960950e+03 5.03021631e+02 1.00000000e+00]
```

Best Regards,
Ajay K

**Comment by holger-nutonomy** [comment]
The snippet that you posted does not **alter** the points, it only selects a subset of them.
Hence if you are still indexing the 6th, 23rd and 51st point, you are actually indexing different points than you think you are.

**Comment by kotianaj** [comment]
Yes, that is what i concluded as well. I will now try to find a way to locate correct indexes in the resulting subset.
Thanks a lot Holger. Really appreciate your help in understanding the problem.
