### ISSUE TITLE
how to use image_annotations.json

### ISSUE THREAD

**Issue by WJ-Lai** [nutonomy/nuscenes-devkit#203]
Hi, I have got the "image_annotations.json" file by "export_2d_annotations_as_json.py" and put it "v1.0-mini" directory.  When I run `nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=True)`, it could load the load the image annotations table successfully (self.image_annotations had values).

I want to get the 2d annotations for a single image by `nusc.get`:
```
nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=True)
my_scene = nusc.scene[0]
first_sample_token = my_scene['first_sample_token']
my_sample = nusc.get('sample', first_sample_token)
my_annotation_token = my_sample['anns'][18]
my_annotation_metadata = nusc.get('image_annotations', my_annotation_token)
```
it returned errors:
```
  File "/home/vincent/Code/mobilenet-detection/test_code/test_nuscene.py", line 9, in <module>
    my_annotation_metadata = nusc.get('image_annotations', my_annotation_token)
  File "/home/vincent/Code/mobilenet-detection/nuscenes/nuscenes.py", line 171, in get
    assert table_name in self.table_names, "Table {} not found".format(table_name)
AssertionError: Table image_annotations not found
```

Could you please tell me how can I get the 2d annotations for a single image and render it? Thanks!

**Comment by holger-nutonomy** [comment]
Hi. We don't currently provide support for loading or rendering the 2d image annotations. They are only loaded to `nusc.image_annotations` for convenience - a user requested this feature. This is because the projected 2d annotations are generally not tight bounding boxes. I'll consider adding this feature in the future.
