### ISSUE TITLE
Rendering outside Jupyter

### ISSUE THREAD

**Issue by sh0gg0th** [nutonomy/nuscenes-devkit#209]
`render_sample_data` works for me inside the Jupyter notebook, but not in a plain Python script or interpreter. Is this the intended behavior? I'm using Python 3.6, if it matters.

**Comment by sh0gg0th** [comment]
Persists on Python 3.7. Ubuntu 16.04.

**Comment by holger-nutonomy** [comment]
By default matplotlib is not setup to open any windows. Please try the two ideas mentioned in https://forum.nuscenes.org/t/cannot-render-plots-under-windows/110/2 (despite being about MS Windows):
- Run `matplotlib.pyplot.show()`.
- Create a file `~/.matplotlib/matplotlibrc` with the content: `backend: TkAgg`.

**Comment by sh0gg0th** [comment]
`matplotlib.pyplot.show()` did the trick. Thanks a lot!
