### ISSUE TITLE
Orientation angle of the bounding box with respect to the camera

### ISSUE THREAD

**Issue by bertoni9** [nutonomy/nuscenes-devkit#21]
Hello,

For every annotation, the object Box returns the orientation of the bounding box in degrees:

**filename, boxes, kk = nusc.get_sample_data(token_sd, box_vis_level=0)
for box in boxes:
    angle= box.orientation.degrees**

Can you please clarify what the angle refers to? I expected the angle to be the orientation in the XZ plane of the bounding box with respect to the camera. However, people facing the camera sometimes have positive angles, sometimes negative angles. 

In general, how can I obtain the orientation of the bounding box with respect to the camera?

Thank you very much
Lorenzo

**Comment by holger-nutonomy** [comment]
Hi Lorenzo,

- As described in the [sample_annotation table of the schema](https://github.com/nutonomy/nuscenes-devkit/blob/master/schema.md#sample_annotation), every annotation is stored in global coordinates (that includes translation, rotation, velocity). 

- However the method `get_sample_data` transforms the box into the current sensor's coordinate frame (described [here](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes_utils/nuscenes.py#L198)). So you need to make sure that the token_sd corresponds to the right camera.

- Finally note that we store rotations using the third-party [pyquaternion](http://kieranwynn.github.io/pyquaternion/) class. The quaternion can describe arbitrary rotations, so degrees is not necessarily the yaw angle. To convert from quaternion to yaw angle, you can use the following method (which will soon be part of the devkit):
```
def quaternion_yaw(q: Quaternion) -> float:
    """
    Calculate the yaw angle from a quaternion.
    See https://en.wikipedia.org/wiki/Conversion_between_quaternions_and_Euler_angles.
    :param q: Quaternion of interest.
    :return: Yaw angle in radians.
    """

    a = 2.0 * (q[0] * q[3] + q[1] * q[2])
    b = 1.0 - 2.0 * (q[2] ** 2 + q[3] ** 2)

    return np.arctan2(a, b)
```

Let me know if you have any more questions.

**Comment by bertoni9** [comment]
Hello,

Thank you very much for your reply. I implemented the function but I am still not sure about the yaw angle it returns.

As a case study I am considering 2 images:

n015-2018-08-01-16-32-59+0800__CAM_FRONT__1533112709162460
n015-2018-07-18-11-18-34+0800__CAM_FRONT__1531884168362460

(In the first image there is only one person, in the second I only look at the close person on the left side of the image with coordinates of the center as [-5.13221828  0.38146399  9.04940337])

For the first image I get an angle of 1.59 rad --> 91 degrees
For the second image (close person on the left of the image) 3.12 rad --> 179 degrees

Independently from the chosen convenction, The 2 people don't look as having 90 degrees difference between them. (More 45 degrees I'd say). Also looking at the rendered bounding boxes, the angle difference seems less than 90.

Am I missing something? 

Thank you very much
Lorenzo

**Comment by bertoni9** [comment]
Great, thank you very much for your detailed explanation!

**Comment by pxiangwu** [comment]
Hi, @holger-nutonomy , given the (yaw) orientation angle in global coordinate, how can we recover the corresponding quaternion? I found one line of code here: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/kitti.py#L315
This code simply sets the rotation axis to (0, 1, 0) in KITTI coordinate system. So is this the solution to recovering the quaternion? If so, then for the global nuscene coordinate system, should we similarly set the rotation axis to (0, 0, 1)? 
Thank you.

**Comment by holger-nutonomy** [comment]
@pxiangwu I suppose you are asking for nuScenes, not KITTI, right? Try this line: 
`Quaternion(axis=(0, 0, 1), angle=yaw)`
https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/tests/test_geometry_utils.py#L65

**Comment by pxiangwu** [comment]
> @pxiangwu I suppose you are asking for nuScenes, not KITTI, right? Try this line:
> `Quaternion(axis=(0, 0, 1), angle=yaw)`
> https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/tests/test_geometry_utils.py#L65

Thank you so much. I think this is what I am looking for.

**Comment by holger-motional** [comment]
@programmeeer I don't think the `sd['filename'] ` has your local path. It only stores the subpath, e.g. something like `samples/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151605012404.jpg`

**Comment by programmeeer** [comment]
@holger-motional i am trying to test code on colab before i use it on cluster, and code looks like this

from pyquaternion import Quaternion
import numpy as np
import matplotlib.pyplot as plt
from nuscenes.nuscenes import NuScenes



def quaternion_yaw(q: Quaternion, in_image_frame: bool=True) -> float:

    if in_image_frame:
        v = np.dot(q.rotation_matrix, np.array([1, 0, 0]))
        yaw = -np.arctan2(v[2], v[0])
    else:
        v = np.dot(q.rotation_matrix, np.array([1, 0, 0]))
        yaw = np.arctan2(v[1], v[0])

    return yaw



nusc = NuScenes()

sd1_im = [sd for sd in nusc.sample_data if sd['filename'] == '/content/data/set/nuscenes/samples/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151604012404.jpg'][0]
sd2_im = [sd for sd in nusc.sample_data if sd['filename'] == '/content/data/set/nuscenes/samples/CAM_FRONT/n008-2018-08-01-15-16-36-0400__CAM_FRONT__1533151605012404.jpg'][0]



s1 = nusc.get('sample', sd1_im['sample_token'])
s2 = nusc.get('sample', sd2_im['sample_token'])

I am still not sure its because of file path error or ? any suggestions?

**Comment by programmeeer** [comment]
@holger-motional thanks, i was using entire path instead of local path.
