### ISSUE TITLE
Getting error when installing nuscenes on windows using: pip install nuscenes-devkit

### ISSUE THREAD

**Issue by sarimmehdi** [nutonomy/nuscenes-devkit#211]
ERROR: Command errored out with exit status 1:
     command: 'c:\users\sarim\appdata\local\programs\python\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sarim\\AppData\\Local\\Temp\\pip-install-b2hrt6bw\\Shapely\\setup.py'"'"'; __file__='"'"'C:\\Users\\sarim\\AppData\\Local\\Temp\\pip-install-b2hrt6bw\\Shapely\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\sarim\AppData\Local\Temp\pip-install-b2hrt6bw\Shapely\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\sarim\AppData\Local\Temp\pip-install-b2hrt6bw\Shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\sarim\AppData\Local\Temp\pip-install-b2hrt6bw\Shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "c:\users\sarim\appdata\local\programs\python\python37\lib\ctypes\__init__.py", line 364, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] The specified module could not be found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by holger-nutonomy** [comment]
Unfortunately we do not support Windows. 
It seems like there is a problem with the Shapely.
Since that is only used for the map expansion pack I suggest you get the source code from this repository, remove shapely from `installation/requirements.txt` and try if it works.
