### ISSUE TITLE
Questions about radar measurements

### ISSUE THREAD

**Issue by brade31919** [nutonomy/nuscenes-devkit#213]
Hi nuscenes-devkit team,

I am currently working on sensor fusion between RGB images and radar points. When I projected radar points in nuscenes dataset to images, I found some obvious inconsistent measurements on objects. Here are some examples: (All of the tokens are from the mini split)

1. sample token=b2e2ffeabf91451cb31a79649bfd95df
This plot is generated by the following code (function from the devkit), so should be bug-free:
```python
# Here nuscene_dataset is my own dataset object, but this won't affect the resulting plot given the same sample token.
sample_obj = nuscene_dataset.samples[150] 
sample_token = sample_obj["token"]
nuscene_dataset.explorer.render_pointcloud_in_image(sample_token,
                                                   dot_size=30,
                                                   pointsensor_channel="RADAR_FRONT",
                                                   camera_channel="CAM_FRONT")
```
![image](https://user-images.githubusercontent.com/13144700/63552303-9d090d00-c537-11e9-9ecc-c72de90c873f.png)
For better visualization, I further plot with colorbar indicating the depth values:
![image](https://user-images.githubusercontent.com/13144700/63552836-10f7e500-c539-11e9-8107-1eeeb66daa4b.png)

Here are more examples:
2. sample token=d0ecf474e0e64950aa265cd44b9c9d75
![image](https://user-images.githubusercontent.com/13144700/63553160-e3f80200-c539-11e9-93b5-773412d5da00.png)

3. sample token=b8766f4291d5449d95bab459ca724ad8
![image](https://user-images.githubusercontent.com/13144700/63553466-c11a1d80-c53a-11e9-8316-210326f4aa59.png)
There are more similar examples that are not listed here.

In #173, I posted a similar issue on side views However, in these cases (front view), the inconsistent points just too many to be ignored, and they are mainly on foreground objects. I would like to know whether you have more analysis or interpretation on these cases for example:
1. Are they caused by reflections/diffractions from the buildings or other far away objects behind the car or just noisy measurements? (We might be able to obtain useful info from the former but not the latter)
2. Are these points included in the radar point count label for the object?
3. Is there any possible solution to get rid of these points? (I have tried the filter setting, but no promising results were found currently.)

Thank you!

**Comment by holger-nutonomy** [comment]
Please also take a look at https://github.com/nutonomy/nuscenes-devkit/issues/201.
Radar data is generally difficult to work with and we get a lot of questions, but haven't seen any *systematic issues* yet.

Here are some possible explanations sorted by decreasing relevance: 
- Reflections (your third example).
- Need to filter returns outside the radar FOV. I think this should resolve most of the cases you list above. You can use this snippet on the actual point numpy ndarray:
```
def radar_filter_valid_angles(points: np.ndarray,
                              max_abs_angle: float = 60,
                              debug: bool = False) -> np.ndarray:
    """
    # Filter points outside the radar FOV (in the xy plane).
    :param points: <np.float: 4, num_points>.
    :param max_abs_angle: The maximum absolute angle above which radar returns will be removed.
    :param debug: Whether to print debugging messages about the angles and the number of points.
    :return: The filtered pointcloud.
    """
    # We use the x and y values to compute the yaw angle.
    # The convoluted math rotates the "origin" from pointing right to pointing forward and flips it.
    angles = ((90 - (np.arctan2(points[:, 0], points[:, 1]) / np.pi * 180)) + 180) % 360 - 180
    if debug:
        print(angles.astype(np.int32))

    # Filter out the points that have invalid angles.
    valid = np.abs(angles) <= max_abs_angle
    pointcount_before = len(angles)
    pointcount_after = valid.sum()
    points = points[valid, :]
    if debug:
        print('Total points: %d, valid points: %d' % (pointcount_before, pointcount_after))
        min_angle = np.max(np.abs(angles))
        print('Minimum absolute angle was: %f' % min_angle)

    return points
```
- Use a stricter radar return filter setting.
- Multipath effects
- Possible errors in synchronization as the radar is not synchronized with the camera.
- Possible errors in calibration. E.g. in your second example the red points may actually be a few cm higher and reflections in the window.
