### ISSUE TITLE
Getting annotation-specific lidar points

### ISSUE THREAD

**Issue by sh0gg0th** [nutonomy/nuscenes-devkit#214]
What I'm planning to do is run `LidarPointCloud.from_file_multisweep(nusc, sample, 'LIDAR_TOP', 'LIDAR_TOP', 1)` to get the 1-sweep pcd (currently getting an array of all zeroes but must be doing something wrong), then use `get_sample_data` for the annotation-specific box and run `points_in_box` to apply the resulting mask to the pcd. Please let me know if I'm on the right track and not reinventing something that's already there.

Edit: figured out that the points are in the `.points` property, zeros were the timestamps returned as the second object.

**Comment by holger-nutonomy** [comment]
What you want to do sounds reasonable and doesn't currently exist like that.
Please post any further questions at: https://forum.nuscenes.org

**Comment by HenryJunW** [comment]
Do you figure out how to extract the specific object's lidar point cloud? @sh0gg0th

**Comment by HenryJunW** [comment]
Already figure out, thanks.

**Comment by owoshch** [comment]
Hi @HenryJunW!
Could you please share the command to extract the specific object's lidar point cloud?
Thank you!
