### ISSUE TITLE
Visibility Level for 2D Bounding Boxes

### ISSUE THREAD

**Issue by otrivedi** [nutonomy/nuscenes-devkit#218]
Hello,

If I am not wrong, the visibility level of vehicle is set depending upon:
 - Views in all the cameras
 - Views across time

So a vehicle not visible at time T but fully visible at T+1 (in any of the cameras) would be binned as visibility level 4.

If this is correct so far, is there any way to determine which FRAMES the vehicle is fully visible in? for example, given a vehicle instance, I want to get all the camera frames where the vehicle is fully visible (across all time steps). My goal is to get 2D bounding boxes at these frames where I can see the entire vehicle.

Thank you.

**Comment by holger-nutonomy** [comment]
Hi. If you look at the schema (https://github.com/nutonomy/nuscenes-devkit/blob/master/schema.md) you will see that each `sample_annotation` has its own visibility. Hence it is per frame and not across time.
The [instructions](https://github.com/nutonomy/nuscenes-devkit/blob/master/instructions.md) say `The visibility attribute specifies the percentage of object pixels visible in the panoramic view of all cameras`, hence your first statement is correct.
I suggest you get the annotation with highest visibility and closest distance to the ego vehicle.

Please ask any other questions at https://forum.nuscenes.org

**Comment by Gcaption** [comment]
Hello,

How to calculate visibility？
The visibility property specifies the percentage of object pixels that are visible in the panoramic view of all cameras.  
 I have two questions about the visibility property, please help to answer them.   

1. What is the specific method of calculating the visibility percentage, is it estimated manually or is a specific algorithm used to calculate it automatically?   
2.  According to what are the four levels of visibility divided?

Thank you.

**Comment by whyekit-motional** [comment]
The visibility of each object is annotated based on the rules under the `Visibility Attribute` section of https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/instructions_nuscenes.md#special-rules
