### ISSUE TITLE
what's the mean of the num_lidar_pts?

### ISSUE THREAD

**Issue by 1453042287** [nutonomy/nuscenes-devkit#219]
like the title, thanks a lot!

**Comment by holger-nutonomy** [comment]
Do you mean the mean (average) or the meaning?
The meaning is the number of lidar points that fall inside that sample_annotation bounding box in the particular keyframe.

The mean on the mini dataset is 58.8pts/box. (0.85pts/box for radar)
You can compute it with the following code:
```
import numpy as np
from nuscenes.nuscenes import NuScenes

nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=True)
np.mean([s['num_lidar_pts'] for s in nusc.sample_annotation])
```
Please ask such questions at https://forum.nuscenes.org moving forward.
