### ISSUE TITLE
Semantic segmentation for lidar points

### ISSUE THREAD

**Issue by HadarS** [nutonomy/nuscenes-devkit#22]
Hi, 
Is there semantic segmentation for lidar points in the sample data and is there an example of how to use it?
Thank you

**Comment by holger-nutonomy** [comment]
Hi Hadar, what do you mean by semantic segmentation? 
- Pixel-level labels can be retrieved by projecting the 3d boxes to the cameras. However we did not annotate the objects in 2D, as there are a lot of datasets available for that.
- Point labels can be retrieved by assigning to each point the label of its enclosing bounding box (although multiple boxes may include the same point). In the future we plan to add human annotated point labels as well.
Let me know if you have any more questions.
