### ISSUE TITLE
panoramic view of cameras

### ISSUE THREAD

**Issue by brunorigal** [nutonomy/nuscenes-devkit#222]
Thanks for this awesome dataset. 

Is it possible to transform the 6 camera images in a single panoramic view + having the projection of point cloud and 3d boxes in the  panoramic view with the nuscenes-devkit?

**Comment by holger-nutonomy** [comment]
Unfortunately we don't provide such code and there are many design choices to be made here (which projection, how to stitch images together, how to handle regions covered by both or no image, ...). If you would like to work in it we are happy to link to your code. 
Meanwhile you could also look at simply concatenating the images as done in [render_scene()]
![](https://www.nuscenes.org/public/images/tasks.png)
