### ISSUE TITLE
box out of image

### ISSUE THREAD

**Issue by DaHaiHuha** [nutonomy/nuscenes-devkit#225]
Using the latest version to convert to KITTI dataset formate is invaild, the box is simply out of the image and become <0 for example.

I notice this when I transform all the data and try to train PointRCNN net
But the past version hadn't occurred this problem ever.

**Comment by holger-nutonomy** [comment]
Can you provide an example (image + image id + boxes)? A number of people are using this code and it hasn't been changed in 4 months.

**Comment by DaHaiHuha** [comment]
OKay, I realized it might be my mistake so I'll have a double check first

**Comment by holger-nutonomy** [comment]
Okay. Please let us know when you find something.
