### ISSUE TITLE
How to delete overlapped boxes from image ?

### ISSUE THREAD

**Issue by MaxLyubimov** [nutonomy/nuscenes-devkit#228]
Hello!  It's possible to delete boxes from annotation which overlap with other like on this image?   For example  I need to delete red and blue boxes here. 
![test35](https://user-images.githubusercontent.com/50096725/65491249-5bada980-deb7-11e9-88c6-5ee7a98177ca.jpg)
Thanks for help!

**Comment by holger-nutonomy** [comment]
Every `sample_annotation` has a visibility as shown in https://github.com/nutonomy/nuscenes-devkit/blob/master/schema.md#sample_annotation. I suggest you add a line in whatever render method you use to filter if visibility < 40%.
