### ISSUE TITLE
IMU measurements - Velocity, Acceleration

### ISSUE THREAD

**Issue by paulaurel** [nutonomy/nuscenes-devkit#23]
Do we have access to the IMU measurements such as the velocity and acceleration of the ego vehicle? Or do we obtain them by deriving the vehicle's translation with respect to time?

**Comment by holger-nutonomy** [comment]
Hi. We have that data and are currently looking into how we can make it available to the public. Meanwhile you can derive the velocity from the vehicle location using [this code](https://github.com/nutonomy/nuscenes-devkit/blob/eval/python-sdk/nuscenes/nuscenes.py#L311) (note that it isn't merged to master yet).

**Comment by ToniRV** [comment]
Having IMU data would be greatly appreciated! :+1:
