### ISSUE TITLE
Wrong shape error when rendering lidar sample

### ISSUE THREAD

**Issue by leslieliang** [nutonomy/nuscenes-devkit#233]
I get this error when I try to render the data for `lidar_token =  c20de558317f4c00bb6e4c0e01f4386a` via `nusc.render_sample_data(lidar_token)`
```
/usr/local/lib/python3.6/dist-packages/nuscenes/utils/data_classes.py in from_file(cls, file_name)
    253 
    254         scan = np.fromfile(file_name, dtype=np.float32)
--> 255         points = scan.reshape((-1, 5))[:, :cls.nbr_dims()]
    256         return cls(points.T)
    257 

ValueError: cannot reshape array of size 5504 into shape (5)
```

Seems the affected file is `samples/LIDAR_TOP/n015-2018-07-18-11-18-34+0800__LIDAR_TOP__1531884539448719.pcd.bin`.

I ran the `nuscenes/scripts/assert_download.py` script without any errors so I assume there were no problems with the download.

**Comment by holger-nutonomy** [comment]
Note that `assert_download.py` merely checks if the file exists. I assume the file was corrupted during download. For me it works. Please try the file below (unzip it first):
[n015-2018-07-18-11-18-34+0800__LIDAR_TOP__1531884539448719.pcd.zip](https://github.com/nutonomy/nuscenes-devkit/files/3675431/n015-2018-07-18-11-18-34%2B0800__LIDAR_TOP__1531884539448719.pcd.zip)

Let me know if the problem persists.

**Comment by kushal-git312** [comment]
i have the similar issue because my server machine cannot read a pcd binary file of nuscenes mini dataset that i transferred from my local machine to remote server machine using SFTP. 
[ Error reading n008-2018-08-27-11-48-51-0400__LIDAR_TOP__1535385103447886.pcd.bin: operation not allowed ]

I can read that file in my local machine but not in remote server machine. 
I also tried to transfer v1.0-mini.tgz file and extracted inside the server machine but only that file getting corrupted. I also tried to transfer only that file but the error remains the same.

**Comment by whyekit-motional** [comment]
@kushal-git312 perhaps you can instead try downloading the dataset directly to your remote machine (pls see https://github.com/nutonomy/nuscenes-devkit/issues/110 for details)

**Comment by russellyq** [comment]
Hi @whyekit-motional ,

I have also encounter the same issue with FILE n008-2018-08-31-11-19-57-0400__LIDAR_TOP__1535728844546516.pcd.bin that has points shape 131072.

Can you provide me the correct file ?
Thanks.

**Comment by whyekit-motional** [comment]
@russellyq pls re-download the file

**Comment by russellyq** [comment]
> n008-2018-08-31-11-19-57-0400__LIDAR_TOP__1535728844546516.

Hi @whyekit-motional , 

Thanks for your reply. But how do I know which scence the file "n008-2018-08-31-11-19-57-0400__LIDAR_TOP__1535728844546516." belongs to ?

**Comment by whyekit-motional** [comment]
@russellyq you can try something like this:
```python
from nuscenes.nuscenes import NuScenes


nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=False)

target_sample_sensor_data_filename = 'n015-2018-07-24-11-22-45+0800__LIDAR_TOP__1532402932647284'

sensor_name = 'LIDAR_TOP'
for sample in nusc.sample:
    sample_data = sample['data']
    sample_sensor_data = nusc.get('sample_data', sample_data[sensor_name])
    
    if target_sample_sensor_data_filename in sample_sensor_data['filename']:
        scene = nusc.get('scene', sample['scene_token'])
        print(scene['name'])
        break
```

**Comment by russellyq** [comment]
Hi @whyekit-motional,

Thank you so much ! I have re-downloaded the zip file.
