### ISSUE TITLE
split the dataset

### ISSUE THREAD

**Issue by DaHaiHuha** [nutonomy/nuscenes-devkit#235]
Hello, Thank you for the great work! I'm relatively new here and I'm wondering whether we could split the dataset with official SDK into smaller ones, still we'would be okay to load them? Cause the dataset is really big and too heavy for us to debug and test our new thoughts. Thanks in advance!

**Comment by holger-nutonomy** [comment]
Hi. For debugging you should use the mini split, available as a separate file at https://www.nuscenes.org/download. It includes only 10 scenes and therefore loads very quickly.
You just need to initialize NuScenes as `nusc = NuScenes(version='v1.0-mini').

**Comment by DaHaiHuha** [comment]
Thank you but what if I want to split my own v1.0-mini dataset? Thank you for your quick reply

**Comment by holger-nutonomy** [comment]
Yes, as long as the format is valid and you copy all the entries in the .json files you need, you can do that. Just need to define your splits here: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/splits.py
