### ISSUE TITLE
points in 3d_boxes

### ISSUE THREAD

**Issue by DaHaiHuha** [nutonomy/nuscenes-devkit#237]
I'm wondering whether there is a convenient function that could help us to quickly determine whether the points are in the 3d_boxes or to return all the points' indexes within the boxes, Thanks!

**Comment by holger-nutonomy** [comment]
Yes, there is a function to check whether points are in the box:
https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/geometry_utils.py#L112
However, a function to return all the indices you would have to write yourself. Good luck.
