### ISSUE TITLE
get the yaw in global coordinates from the yaw in local coordinate

### ISSUE THREAD

**Issue by brunorigal** [nutonomy/nuscenes-devkit#238]
Hi, 
I find strange that the cameras orientation have large pitches and rolls. How is that possible?
I am trying to get the global yaw from only the yaw in camera coordinate (and not the pitch and roll). Do you have any idea how to do that?

Thanks for your inputs

**Comment by holger-nutonomy** [comment]
How much is the pitch and roll? If you look at the videos I'd say they are imperceptible and therefore pretty small: https://www.youtube.com/watch?time_continue=4&v=Sipud0IonvQ

**Comment by brunorigal** [comment]
This code shows that boxes in camera frame have a large pitch and roll. This is caused by the camera (calibrated sensor) rotation which has a non zero pitch and roll.

Am I missing something?

`
nusc = NuScenes(version='v1.0-trainval', dataroot="./nuScenes/v1.0-trainval", verbose=True)
my_scene = nusc.scene[0]
first_sample_token = my_scene['first_sample_token']
sensor = 'CAM_FRONT'
my_sample = nusc.get('sample', first_sample_token)
cam_front_data = nusc.get('sample_data', my_sample['data'][sensor])
my_annotation_token = my_sample['anns'][0]
box_global =  nusc.get('sample_annotation', my_annotation_token)
nusc.get('sample_annotation', my_annotation_token)
data_path, boxes, camera_intrinsic = nusc.get_sample_data(my_sample['data'][sensor])
print('box orientation in global frame: ', box_global['rotation'])
print('box orientation in camera frame: ', boxes[0].orientation.elements)
sd_record = nusc.get('sample_data', my_sample['data'][sensor])
cs_record = nusc.get('calibrated_sensor', sd_record['calibrated_sensor_token'])
print('camera rotation:',cs_record['rotation'])`

**Comment by holger-nutonomy** [comment]
Hi, I refactored your code a bit, used the mini split and converted from quaternions to euler angles:
```
from pyquaternion import Quaternion
import numpy as np
from nuscenes import NuScenes
nusc = NuScenes(version='v1.0-mini', dataroot="/data/sets/nuscenes-mini", verbose=True)
my_scene = nusc.scene[0]
first_sample_token = my_scene['first_sample_token']
sensor = 'CAM_FRONT'
my_sample = nusc.get('sample', first_sample_token)
cam_front_data = nusc.get('sample_data', my_sample['data'][sensor])

my_annotation_token = my_sample['anns'][0]
box_global = nusc.get('sample_annotation', my_annotation_token)
data_path, boxes, camera_intrinsic = nusc.get_sample_data(my_sample['data'][sensor])
sd_record = nusc.get('sample_data', my_sample['data'][sensor])
cs_record = nusc.get('calibrated_sensor', sd_record['calibrated_sensor_token'])

angles_box_global = np.array(Quaternion(box_global['rotation']).yaw_pitch_roll) / np.pi * 180
angles_box_camera = np.array(Quaternion(boxes[0].orientation.elements).yaw_pitch_roll) / np.pi * 180
angles_camera = np.array(Quaternion(cs_record['rotation']).yaw_pitch_roll) / np.pi * 180

print('box orientation in global frame: ', angles_box_global)
print('box orientation in camera frame: ', angles_box_camera)
print('camera rotation:', angles_camera)
```
Results are:
````
box orientation in global frame:  [-21.091   0.      0.   ]
box orientation in camera frame:  [178.79077403   1.27037324  90.88688192]
camera extrinsics: [  44.75652071   89.54131123 -134.80356665]
````
So the annotation lives in the global frame with no pitch or roll.
When transformed to camera frame we can see that the orientations are less than 2 degrees off.
The camera extrinsics are not easy to read as ego vehicle (IMU) and camera use different coordinate frames: https://www.nuscenes.org/public/images/data.png

**Comment by brunorigal** [comment]
Thanks a lot, I did not thought the axis orientation were different between vehicle and sensor frame.
