### ISSUE TITLE
convert annotations to kitti format

### ISSUE THREAD

**Issue by DaHaiHuha** [nutonomy/nuscenes-devkit#241]
Hi, 
I've been wondering why don't we use the box.orientation.yaw_pitch_roll[0] as the r_y in Kiiti's label?
Cause, as far as I know, the r_y denotes the radians that rotate around the z-axis in Nucense format and y_axis in Kitti, however, that's the same axis if we view them in a global coordinate.
![image](https://user-images.githubusercontent.com/38548370/66637251-3fdf2d00-ec45-11e9-97fa-02d870583f2b.png)
Thanks in advance!

**Comment by DaHaiHuha** [comment]
Additional:
I'll add some supporting materials, but I'll probably make mistakes, so please directly point it out if you have any doubts or suggestions.
![image](https://user-images.githubusercontent.com/38548370/66694494-9a7c9580-ece6-11e9-897e-af313218a066.png)
This is from kitti read me 
![image](https://user-images.githubusercontent.com/38548370/66694501-b7b16400-ece6-11e9-828a-1c0f7cb8b257.png)
This is from NuScenes [paper](https://arxiv.org/pdf/1903.11027.pdf)
```
        # 3D bounding box corners. (Convention: x points forward, y to the left, z up.)
        x_corners = length / 2 * np.array([1, 1, 1, 1, -1, -1, -1, -1])
        y_corners = width / 2 * np.array([1, -1, -1, 1, 1, -1, -1, 1])
        z_corners = height / 2 * np.array([1, 1, -1, -1, 1, 1, -1, -1])
```
This is from Lyft's code. code [here](https://github.com/lyft/nuscenes-devkit/blob/3932b4b186ef304a33641f09ffba2d9a3e8e7e3f/lyft_dataset_sdk/utils/data_classes.py#L601)

**Comment by holger-nutonomy** [comment]
Hi. It's been a while since we wrote the KITTI code.
Can you elaborate whether you want to 1) simplify the current code, 2) point out a potential bug or 3) add a new feature ? 
Are you simply suggesting to replace these two lines?
https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/kitti.py#L398

**Comment by DaHaiHuha** [comment]
Sorry if I didn't say it clearly, yes I think the code could be simplified.
Besides, https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/kitti.py#L398 the code here use the rotation_matrix, but this rotation_matrix is different from what we get from the annotation of NuScenes format, because here:
https://github.com/nutonomy/nuscenes-devkit/blob/f3594b967cbf42396da5c6cb08bd714437b53111/python-sdk/nuscenes/scripts/export_kitti.py#L231
Before your posted code, the matrix is already changed.

Actually, I'm no expert here,  so I'm asking whether we can get the r_y(of KITTI format) directly from 
NuScenes annotation rather than by a rotation matrix that has been converted multiple times? ( the rotation matrix needs to convert to fit different coordinate)

**Comment by holger-nutonomy** [comment]
After taking a look I agree that this could have been simplified. However, that would require rewriting a number of things, as e.g. [get_sample_data](https://github.com/nutonomy/nuscenes-devkit/blob/f3594b967cbf42396da5c6cb08bd714437b53111/python-sdk/nuscenes/scripts/export_kitti.py#L213) already transforms the box. Furthermore the yaw angle in the camera coordinates may be very slightly different as the sensors are not perfectly aligned with the vertical axis. This code has been tested and noone reported any issues, so I think it is better to keep it.

**Comment by Petros626** [comment]
@DaHaiHuha Hey, did you customized the `export_kitti.py` to your simplified solution?
