### ISSUE TITLE
How to convert the nuscenes dataset to kitti tracking fromat?

### ISSUE THREAD

**Issue by SpyderXu** [nutonomy/nuscenes-devkit#242]
How to convert the nuscenes dataset to kitti tracking fromat?

**Comment by holger-nutonomy** [comment]
Check out this script: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_kitti.py
Not every field has a meaningful value, but so far this was sufficient for most people.
