### ISSUE TITLE
Do not understand the conversion between sensor coordinates in export_kitti.py.

### ISSUE THREAD

**Issue by usherbob** [nutonomy/nuscenes-devkit#247]
Hi, there,

I noticed the code of transformation between the camera coordinate and the lidar coordinate is below. 

```
lid_to_ego = transform_matrix(cs_record_lid['translation'], Quaternion(cs_record_lid['rotation']),
                                          inverse=False)
ego_to_cam = transform_matrix(cs_record_cam['translation'], Quaternion(cs_record_cam['rotation']),
                                          inverse=True)
velo_to_cam = np.dot(ego_to_cam, lid_to_ego)
```

Why not `velo_to_cam = np.dot(lid_to_ego, ego_to_cam)`? It makes more sense. I mean, lidar to ego, then ego to the camera.

**Comment by holger-nutonomy** [comment]
What we want to do is:
`cam_vec = ego_to_cam x (lid_to_ego * lidar_vec)`
where x is the matrix-matrix product and * is matrix-vector product.

**Comment by usherbob** [comment]
Thanks for pointing it out.
