### ISSUE TITLE
How to access gps data?

### ISSUE THREAD

**Issue by powermanwxy** [nutonomy/nuscenes-devkit#248]
Hi, I'm doing with some action prediction work on this dataset, but I found you guys haven't publish the raw imu and gps data. Do you have a plan or something?
Thanks!!

**Comment by holger-nutonomy** [comment]
Hi. What we do have is the `ego_pose` which is the output of our lidar/GPU/IMU-based localization. We are working o IMU and GPS data and hope to release it in December/January.

**Comment by holger-nutonomy** [comment]
Please note that the nuScenes map has been updated to fix the slight offset in some 43 scenes. Take a look at https://github.com/nutonomy/nuscenes-devkit/pull/279 for more information and download the new maps from https://www.nuscenes.org/download.

**Comment by Monssica** [comment]
hello, the full nuscenes datasets have ego_pose,does the ego_pose is the results from the nuscenes map?

**Comment by whyekit-motional** [comment]
@Monssica yes, the `ego_pose` is with respect to the corresponding map in nuScenes: https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/schema_nuscenes.md#ego_pose
