### ISSUE TITLE
Detailed directory structure

### ISSUE THREAD

**Issue by debapriyamaji** [nutonomy/nuscenes-devkit#249]
Hi,
While extracting the zip files, I realized that these archives contain files with same name and one is being overwritten by the other.  Can you please publish number of files in each directory after extraction is complete. And what is meant by "Please unpack the archives to the /data/sets/nuscenes folder *without* overwriting folders that occur in multiple archives." ?

**Comment by holger-nutonomy** [comment]
See this issue:
https://github.com/nutonomy/nuscenes-devkit/issues/250
In general, if you find any duplicates, you can be sure that these are identical.
