### ISSUE TITLE
Duplicate data found in Mini that exist in Trainval part 1 dataset

### ISSUE THREAD

**Issue by TangeniThePyGuru** [nutonomy/nuscenes-devkit#250]
I am not sure if I am addressing this issue correctly or whether it's even an issue, but upon trying to merge all my data sets into one I have observed duplicate files between the Mini and the Trainval part 1 dataset. I am not sure if this is supposed to be a problem but I would like to hear from you with regards to this, because I had overwritten the duplicate files. Have i done it correctly? Will this have some sort of implications on my project?

**Comment by holger-nutonomy** [comment]
That's correct. Mini is a subset of trainval. So you don't need the samples/sweeps/maps folders of mini if you have trainval already.
