### ISSUE TITLE
From image to global coordinates

### ISSUE THREAD

**Issue by Marel-88** [nutonomy/nuscenes-devkit#252]
Hi, I need to go back to the global coordinates after projecting the coordinates into the image thanks to the code in the Nuscenes devkit. Any help or suggestion? How did you manage that?

**Comment by holger-nutonomy** [comment]
Look around the codebase for some inspiration, e.g. [here](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L555) (although that's doing the opposite). It should look something like:
```
        # Points live in the camera frame. So they need to be transformed to the global frame.
        # First step: transform the point-cloud to the ego vehicle frame for the timestamp of the sweep.
        cs_record = self.nusc.get('calibrated_sensor', cam_cs_token)
        pc.rotate(Quaternion(cs_record['rotation']).rotation_matrix)
        pc.translate(np.array(cs_record['translation']))

        # Second step: transform to the global frame.
        poserecord = self.nusc.get('ego_pose', pointsensor['ego_pose_token'])
        pc.rotate(Quaternion(poserecord['rotation']).rotation_matrix)
        pc.translate(np.array(poserecord['translation']))
```

**Comment by Marel-88** [comment]
Thank you. But is there any chance to do that just considering the camera
coordinates? I can't use Lidar in my project.

Il mer 6 nov 2019, 03:19 holger-nutonomy <notifications@github.com> ha
scritto:

**Comment by holger-nutonomy** [comment]
Can you repeat what you want to do?
If you want to do an inverse projection from camera pixel coordinates to global coordinates, that is not possible, unless you know the depth at that pixel.

**Comment by Marel-88** [comment]
Alright, thank you. So I should do the pose estimation or calculate the depth image? Do you know how to manage that with your dataset?

**Comment by holger-nutonomy** [comment]
I guess the only option is to use the lidar, project it to the image and interpolate the depth.
Using a depth estimation technique trained on another dataset may not work so well.
