### ISSUE TITLE
Unable to install nuscenes-devkit via pip

### ISSUE THREAD

**Issue by TangeniThePyGuru** [nutonomy/nuscenes-devkit#253]
I had issues installing openCV via pip so i was forced to install it via the alternative (by building my own), when i do a `pip install -r setup/requirements.txt` i get the error below: 

```
ERROR: Could not find a version that satisfies the requirement opencv-python (from versions: none)
ERROR: No matching distribution found for opencv-python
```

I was forced to removed it from my requirements file and everything else installed fine. However when i do `pip install nuscenes-devkit` the same error above shows up.

How can I bypass this?

**Comment by holger-nutonomy** [comment]
Hi. Please check with the `opencv-python` community. My guesses are either:
1) You are using an unsupported OS, perhaps Windows.
2) You are using the wrong Python version (not 3.6+).
3) You pip is outdated. Run `pip install --upgrade pip`.

**Comment by holger-nutonomy** [comment]
Worst case you could comment out every line related to opencv and most things should still work.

**Comment by TangeniThePyGuru** [comment]
Just  a quick question what does `pip install nuscenes-devkit` do? I am assuming it installs the same packages in the requirements.txt file.

I guess that's why  i get this error related to opencv-python package even when i had deleted it from my requirements.

**Comment by TangeniThePyGuru** [comment]
I got the solution.
All I did was remove the opencv-python package from the requirements.txt and run `pip install -r setup/requirements.txt` and everything else worked fine.

**Comment by holger-nutonomy** [comment]
Yes, there are only a few methods that use OpenCV. For all others you can ignore it.

**Comment by Aniket-Mitra** [comment]
@holger-motional  so we cannot do pip install in Windows?

**Comment by whyekit-motional** [comment]
@Aniket-Mitra if you are referring to doing a `pip install` of OpenCV in windows, I suggest checking with the OpenCV community
