### ISSUE TITLE
bounding box projection script incorrect

### ISSUE THREAD

**Issue by mathild7** [nutonomy/nuscenes-devkit#257]
Hi,

export_2d_annotations_as_json.py line: 142

This line attempts to only grab corners in front of camera sensor. However, it pulls in Z-axis coordinates, which should be describing the height. To truly get BBox coordinates 'in front' of the sensor, one would have to get the X-axis coordinates for comparison.

**Comment by holger-nutonomy** [comment]
Hi. If you were to use this function on lidar data, you would be correct. However, we are only using it on camera data. As you can see in https://www.nuscenes.org/public/images/data.png, in the camera frame the Z-axis is pointing "forward".
