### ISSUE TITLE
Question: Scene-Map association

### ISSUE THREAD

**Issue by ADulian** [nutonomy/nuscenes-devkit#259]
Hi,

Question in regards to the use of both nuscene and the map api. I'm looking to incorporate data from the map api into my model, what I have noticed is that rendering ego pose with `render_egoposes_on_fancy_map` requires the scene token, however, if the given scene is not associated with the currently loaded map object e.g. 'boston-seaport' then it will obviously throw an exception. My question is, is there a way to identify to which map a selected scene belongs to? So that I can loop through all the scenes and pass them to the appropriate map object to retrieve the data.

Regards,

**Comment by ADulian** [comment]
Closing down, went a bit through the code and found out that nusc.log contains everything I need.

**Comment by holger-nutonomy** [comment]
Please note that the nuScenes map has been updated to fix the slight offset in some 43 scenes. Take a look at https://github.com/nutonomy/nuscenes-devkit/pull/279 for more information and download the new maps from https://www.nuscenes.org/download.
