### ISSUE TITLE
not support python3.6  ?

### ISSUE THREAD

**Issue by jjldr** [nutonomy/nuscenes-devkit#26]
when I use your tutorial code for test,  raise the following error:

---> 47     def from_file(cls, file_name: str) -> PointCloud:
     48         """
     49         Loads point cloud from disk.

NameError: name 'PointCloud' is not defined

please help me !!!

**Comment by holger-nutonomy** [comment]
Hi. Unfortunately Python 3.6 does not fully support the type annotations that we use. Therefore you will need to install Python 3.7 as described [here](https://github.com/nutonomy/nuscenes-devkit#devkit-setup). And don't forget to setup your PYTHONPATH.

**Comment by ShangxuanWu** [comment]
Is it true that if I manually remove all the "->"s in the code, I can use 3.6 or lower version of python?

**Comment by holger-nutonomy** [comment]
We haven't tried this, but it is possible that it may work.
Note however the devkit is currently undergoing a number of changes for the full release of nuScenes.
If you modify the code it may be difficult to pull the changes.
If you find an automated way to do the changes, please share it here for other people that may be interested.
