### ISSUE TITLE
HD-Map Filter

### ISSUE THREAD

**Issue by eros-ck** [nutonomy/nuscenes-devkit#260]
Does nuscenes-devkit have the API to apply "HD-map" filter? Eg. filter the objects or pointcloud inside the drivable area. 

If not, does the map possibly suppot the functionality in nature? Thanks!

**Comment by holger-nutonomy** [comment]
We don't have an off-the-shelf function, but it shouldn't be difficult to assemble. You can get the center for each object bounding box, then check whether it is [on the map mask](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/map_mask.py#L54). Note that the MapMask class is already loaded in [nuscenes.py](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L80). The map mask includes drivable area and sidewalks, somewhat dilated. 
If you want it more sophisticated and make a distinction between the different map layers, use the [map expansion](https://www.nuscenes.org/map-tutorial). The procedure should be the same, only slower.

**Comment by holger-nutonomy** [comment]
Please note that the nuScenes map has been updated to fix the slight offset in some 43 scenes. Take a look at https://github.com/nutonomy/nuscenes-devkit/pull/279 for more information and download the new maps from https://www.nuscenes.org/download.
