### ISSUE TITLE
Evaluation on Mini dataset gives ""Samples in split doesn't match samples in predictions.""

### ISSUE THREAD

**Issue by chowkamlee81** [nutonomy/nuscenes-devkit#263]
For training and val dataset , evaluation toolkit works but when i start evaluating on v1.0 mini dataset gives

""Samples in split doesn't match samples in predictions.""

Kindly help

**Comment by holger-nutonomy** [comment]
Hi, this error means that either you did not submit results for all the samples (keyframes) or you submitted results for samples not in mini-val. Even if you predict 0 boxes, you need to include an empty list in the results format.
