### ISSUE TITLE
Scrpt to evaluate mAP with respect to distance from ego vehicle

### ISSUE THREAD

**Issue by chowkamlee81** [nutonomy/nuscenes-devkit#264]
Hi,

Is there is any script which we can evaluate mAP with respect to distance  like over has shown their results in pixie, Henry, internet papers. Kindly let us know

**Comment by chowkamlee81** [comment]
Kindly sugfest

**Comment by holger-nutonomy** [comment]
Henry, internet papers? 
We have the official detection evaluation code at https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/detection/evaluate.py. I propose you create a json file with the results as described [here](https://github.com/nutonomy/nuscenes-devkit/tree/master/python-sdk/nuscenes/eval/detection#results-format) and then use the evaluation code to evaluate it. Test set results can be evaluated with our [evaluation server](https://evalai.cloudcv.org/web/challenges/challenge-page/356/).
