### ISSUE TITLE
Lidar downsample

### ISSUE THREAD

**Issue by yzheng97** [nutonomy/nuscenes-devkit#272]
Thanks for your great work. 
I'm working on the detection task from the 16-beam data. I wonder how to downsample your 32-beam lidar points into 16-beam.

**Comment by holger-nutonomy** [comment]
Hi. I suggest you manipulate this method:
https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/data_classes.py#L247
The ring_index will tell you which beam it is, so you can just skip every second beam.

**Comment by yzheng97** [comment]
> Hi. I suggest you manipulate this method:
> https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/data_classes.py#L247
> The ring_index will tell you which beam it is, so you can just skip every second beam.

Many thanks!
