### ISSUE TITLE
Tracking evaluation - threshold accumulation

### ISSUE THREAD

**Issue by Shirly-Perl** [nutonomy/nuscenes-devkit#273]
Hi,
My question is regarding the way thresholds are calculated in the tracking evaluation.
in the function accumulate_threshold(), the recall is calculated per threshold.
the line
matches = events[events.Type == 'MATCH']
implies that only  'MATCH' event counts as true-positive event for recall calculation.
Why don't you count 'SWITCH' event as well? 
I would have expect something like
matches = events[(events.Type == 'MATCH') | (events.Type == 'SWITCH')]
As a switch is also a TP event.
We can see for example, that for precision calculation, motmetrics/metrics.py uses:

def num_detections(df, num_matches, num_switches):
    """Total number of detected objects including matches and switches."""
    return num_matches + num_switches

Thanks a lot!

**Comment by holger-nutonomy** [comment]
Hi, I think you could argue either way about whether a TP should include only match or also switch. I do agree however that it may have been more elegant to use the same definition as in `py-motmetrics` (matches+switches). But it also is not that important as these lines are merely used to define the thresholds at which we evaluate the performance. You could try it out and measure the difference, but I assume it would not differ significantly.
