### ISSUE TITLE
RuntimeWarning: Figures are retained until explicitly closed

### ISSUE THREAD

**Issue by witignite** [nutonomy/nuscenes-devkit#274]
I just wrote a simple script to explore the data and to save several render pictures in each scene so that I can visualize it later. Basically, I call `nusc.render_sample_data` and other `render` functions several times in my script. And I ran into this warning:

```bash
~/nuscenes-devkit/python-sdk/nuscenes/nuscenes.py:671: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig, axes = plt.subplots(int(np.ceil(n/cols)), cols, figsize=(16, 24))
~/nuscenes-devkit/python-sdk/nuscenes/nuscenes.py:878: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  _, ax = plt.subplots(1, 1, figsize=(9, 16))
```

This is not a bug but I was thinking maybe we could probably fix this (?).
- https://github.com/nutonomy/nuscenes-devkit/blob/9fa456a17103dc8f0dd8df4653cb18535b92ce65/python-sdk/nuscenes/nuscenes.py#L671
- https://github.com/nutonomy/nuscenes-devkit/blob/9fa456a17103dc8f0dd8df4653cb18535b92ce65/python-sdk/nuscenes/nuscenes.py#L878

**Comment by holger-nutonomy** [comment]
Hi, normally you can ignore this warning. Without adding another argument ("close_after_render") I cannot think of a way to close the plot. If we close it within that function the user cannot see it. Therefore you should close it in your own code.
