### ISSUE TITLE
top lidar type

### ISSUE THREAD

**Issue by turboxin** [nutonomy/nuscenes-devkit#276]
Hi nuscene team,

Thanks for this great dataset.

According to paper "nuScenes: A multimodal dataset for autonomous driving", top lidar is 32-beam . So I'm guessing that's a velodyne lidar. Is that correct?

As far as I know, there are two types of 32-beam velodyne lidar, HDL-32E and 32C, where 32C have more dense beams in the middle and sparser on the boundary, while 32E have even vertical resolution. Could you please tell me the exact type of lidar that nuscene used? Thanks a lot!

**Comment by holger-nutonomy** [comment]
Hi. Please send an email to holger@nutonomy.com for more information on the sensors.

**Comment by silent-zhou** [comment]
> 

hello,do you know the type of radar now

**Comment by silent-zhou** [comment]
i want to know the Horizontal resolution

**Comment by whyekit-motional** [comment]
@silent-zhou pls see https://www.nuscenes.org/nuscenes#data-collection (under "Car setup") for the types of sensors used in nuScenes

**Comment by issouker97** [comment]
> @silent-zhou pls see https://www.nuscenes.org/nuscenes#data-collection (under "Car setup") for the types of sensors used in nuScenes

Hey, would you please tell me how the lidar's characteristics were adjusted to collect nuscenes dataset, in fact i wanna set up my lidar as the same as the one used for nuscenes but i didn't find the exact parameters used, would you please help me to find this. 

i have aleardy checked on nuscenes website but nothing there about that !
