### ISSUE TITLE
Nuscenes Version check

### ISSUE THREAD

**Issue by hz3014** [nutonomy/nuscenes-devkit#277]
Hi, I have installed multiple nuscenes-devkit versions and im now confused which version is being used. Is there any scripts that tells the version of the devkit? Thanks you!

**Comment by holger-nutonomy** [comment]
If you installed it as a pip package, do `pip show nuscenes-devkit`.

**Comment by hz3014** [comment]
> pip show nuscenes-devkit

Thank you for your prompt reply! 
Do you have suggestion about how to switch between devkit versions?

**Comment by holger-nutonomy** [comment]
It depends how old your devkit was. Lately only the evaluation code changed. If you don't have the map-expansion yet, you can download it from https://www.nuscenes.org/download
