### ISSUE TITLE
render_map_mask does not return all axes

### ISSUE THREAD

**Issue by jhultman** [nutonomy/nuscenes-devkit#281]
Hi, thanks so much for this devkit.

I noticed that [`render_map_mask`](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/map_expansion/map_api.py#L514) returns (somewhat arbitrarily) the most recently created axis in the gridspec. Maybe I misunderstood but the docstring seems to suggest the function is meant to return a list of all the axes (plural). Maybe the final line could be changed from `return fig, ax` to `return fig, fig.axes`.

**Comment by holger-nutonomy** [comment]
@jhultman Thanks for your observation. We'll address this ASAP.
