### ISSUE TITLE
_is_line_record_in_patch bug

### ISSUE THREAD

**Issue by jonahthelion** [nutonomy/nuscenes-devkit#282]
Thank you for building this fantastic library! I found a small but important bug in line 1360 of `_is_line_record_in_patch`

https://github.com/nutonomy/nuscenes-devkit/blob/db2df52aca557a9f81f25235a0618f4f98faa162/python-sdk/nuscenes/map_expansion/map_api.py#L1360

should be

`cond_y = np.logical_and(node_coords[:, 1] < y_max, node_coords[:, 1] > y_min)`

(change the 0 to a 1)

**Comment by holger-nutonomy** [comment]
Thanks @jonahthelion. I believe you are right. I've opened a PR to fix this, which should be merged soon.
