### ISSUE TITLE
Should we remove close points before transforming sweeps? 

### ISSUE THREAD

**Issue by peiyunh** [nutonomy/nuscenes-devkit#287]
Should we call `remove_close` before `transform`? Because `remove_close` seems to assume LiDAR origin sits at (0,0,0). 

https://github.com/nutonomy/nuscenes-devkit/blob/02e9200218977193a1058dd7234f935834378319/python-sdk/nuscenes/utils/data_classes.py#L111-L116

**Comment by holger-nutonomy** [comment]
Thanks. You are right. I've created a PR to fix this.
