### ISSUE TITLE
Suggest using conda instead of virtualenv

### ISSUE THREAD

**Issue by ShangxuanWu** [nutonomy/nuscenes-devkit#29]
I strongly suggest you using anaconda instead of virtualenv, because virtualenv is giving me lots of errors between python3.7 and the rest of the system (Ubuntu14.04).

**Comment by ShangxuanWu** [comment]
All you need to do is to install python-opencv and pyquaterion after having a conda environment.

**Comment by holger-nutonomy** [comment]
Hi @ShangxuanWu. Can you share what errors you get with virtualenv? Whether you use virtualenv, conda or none at all is up to you. Our devkit is not limited to any of those. In a few weeks we will roll out the full dataset incl. a pip package. Then you can just install it via `pip install nuscenes-devkit` and don't need any virtual environment.
