### ISSUE TITLE
Do you provide the global coordinates for the land-divider

### ISSUE THREAD

**Issue by xi-zhang-08** [nutonomy/nuscenes-devkit#290]
Hi, I was wondering if the global coordinates or other coordinates are provided for the land-divider? if so, how can I find it? thank you

**Comment by holger-nutonomy** [comment]
Hi, please take a look at this tutorial: https://www.nuscenes.org/map-tutorial
All map coordinates are global coordinates, but there is only a `lane-divider` class if that's what you mean.
