### ISSUE TITLE
Lidar to camera Right and Left projection of 3D boxes

### ISSUE THREAD

**Issue by anju000** [nutonomy/nuscenes-devkit#298]
Hi

Can you please guide on as to how to project 3d boxes to camera left and right from lidar 3d annotation. I could do it properly for camera front and back.

**Comment by holger-nutonomy** [comment]
Please use this script: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_2d_annotations_as_json.py

**Comment by anju000** [comment]
Hi @holger-nutonomy  Thanks for the quick response but as i go through the method it takes already existing 3d image annotations.. i actually need a conversion from lidar 3d annotations to image 3d annotation

**Comment by holger-nutonomy** [comment]
What do you mean by "I need a conversion from lidar 3d annotations to image 3d annotation" ?

**Comment by anju000** [comment]
If i have a lidar 3d box suppose for the sweep data how do i project the 3d boxes to left and right camera image

**Comment by anju000** [comment]
@holger-nutonomy can you please guide on this

**Comment by holger-nutonomy** [comment]
Please use follow the ideas used in this script. The whole procedure is too tricky to explain here as you still need to check whether a box is "inside" the image and not "behind" it : https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_2d_annotations_as_json.py
