### ISSUE TITLE
unittest failure, MultiIndex

### ISSUE THREAD

**Issue by FiodarKazhamiaka** [nutonomy/nuscenes-devkit#299]
I just cloned the repo and followed the instructions in the Installation.md readme file, the last of which is running the unit tests.

8 tests in the unittest suite fail with the same message.

For example:

> ======================================================================
> ERROR: test_drop_gt (nuscenes.eval.tracking.tests.test_algo.TestAlgo)
> Drop one box from the GT.
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/Users/fiodar/nuscenes-devkit/python-sdk/nuscenes/eval/tracking/tests/test_algo.py", line 217, in test_drop_gt
>     md = ev.accumulate()
>   File "/Users/fiodar/nuscenes-devkit/python-sdk/nuscenes/eval/tracking/algo.py", line 118, in accumulate
>     thresholds, recalls = self.compute_thresholds(gt_box_count)
>   File "/Users/fiodar/nuscenes-devkit/python-sdk/nuscenes/eval/tracking/algo.py", line 298, in compute_thresholds
>     _, scores = self.accumulate_threshold(threshold=None)
>   File "/Users/fiodar/nuscenes-devkit/python-sdk/nuscenes/eval/tracking/algo.py", line 268, in accumulate_threshold
>     events = acc.events.loc[frame_id]
>   File "/Users/fiodar/nuscenes-devkit/python-sdk/nuscenes/eval/tracking/mot.py", line 62, in events
>     self.cached_events_df = MOTAccumulatorCustom.new_event_dataframe_with_data(self._indices, self._events)
>   File "/Users/fiodar/nuscenes-devkit/python-sdk/nuscenes/eval/tracking/mot.py", line 37, in new_event_dataframe_with_data
>     idx = pd.MultiIndex.from_tuples(indices, names=['FrameId', 'Event'])
>   File "/opt/miniconda3/envs/nuscenes/lib/python3.7/site-packages/pandas/core/indexes/multi.py", line 495, in from_tuples
>     return MultiIndex.from_arrays(arrays, sortorder=sortorder, names=names)
>   File "/opt/miniconda3/envs/nuscenes/lib/python3.7/site-packages/pandas/core/indexes/multi.py", line 436, in from_arrays
>     verify_integrity=False,
>   File "/opt/miniconda3/envs/nuscenes/lib/python3.7/site-packages/pandas/core/indexes/multi.py", line 272, in __new__
>     result._set_names(names)
>   File "/opt/miniconda3/envs/nuscenes/lib/python3.7/site-packages/pandas/core/indexes/multi.py", line 1217, in _set_names
>     "Length of names must match number of levels in MultiIndex."
> ValueError: Length of names must match number of levels in MultiIndex.

The other 7 failed tests are:

test_drop_gt_interpolate
test_drop_prediction
test_drop_prediction_multiple
test_empty_submission
test_gt_submission
test_identity_switch
test_scenarios

Any clues as to why this might be happening?

**Comment by holger-nutonomy** [comment]
Thank you for reporting this. It will be fixed in https://github.com/nutonomy/nuscenes-devkit/pull/300.
