### ISSUE TITLE
Issues with the Jupyter Notebook

### ISSUE THREAD

**Issue by shahram95** [nutonomy/nuscenes-devkit#30]
I am trying to run the tutorial.ipynb notebook, I am able to setup the virtualenvwrapper and virtualenv easily, and the notebook is opening but the issue is that there is an error whenever I try to run the first cell. It gives an error: AssertionError: Database version not found: /data/nuscenes/v0.1

Please help me out.

**Comment by holger-nutonomy** [comment]
Hi. It seems like you did not install nuScenes properly. Please see how to download the dataset and install it [here](https://github.com/nutonomy/nuscenes-devkit#dataset-download). Let me know if you have any questions.

**Comment by shahram95** [comment]
I followed the instructions but still can't get it to work. I am sharing step by step procedure I followed, could you go over it and let me know what mistake I am committing.

`Step-by-step method for setting up the virtual environment for running the nuscenes-devkit.

1) Update and Upgrade the packages and install python3.7 (the notebook is tested on python 3.7 and it is recommended to install python 3.7 for seamless and error free execution of the tutorial jupyter notebook)

sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update
sudo apt-get install python3.7
sudo apt install python-pip


2) Install the virtual environment wrapper:
sudo apt-get install
pip install virtualenvwrapper

3) Open .bashrc using nano:

nano ~/.bashrc

and add these two lines in the bottom:

export WORKON_HOME=$HOME/.virtualenvs
source ~/.local/bin/virtualenvwrapper.sh

press ctrl+x-----> press y -----> press <Enter>

exit the terminal to make the changes effective

4) Create the virtual environment:

sudo pip install -U virtualenv
mkvirtualenv <name_of_Virtual_environment> --system-site-packages -p python3.7

5) Activate the virtual environment:

workon <name_of_Virtual_environment>

6) Make the proper file structure:

a) Place the nuscenes-devkit in the home folder
b) The structure should be as follows:

home
|_nuscenes-devkit
   |_instructions.md
   |_license.txt
   |_README.md
   |_requirements.txt
   |_schema.md
   |_setup.py
   |_python-sdk
      |_tutorial.ipynb
      |
      |_nuscenes
      |  |_nuscenes.py
      |  |__init__.py
      |  |_evals
      |  |  |_create_split_logs.py
      |  |  |_eval_utils.py
      |  |  |_ __init__.py
      |  |  |_nuscenes_eval.py
      |  |  |_README.md
      |  |  |_test_eval.py
      |  |_export
      |  |  |_export_egoposes_on_map.py
      |  |  |_export_pointclouds_as_obj.py
      |  |  |_export_scene_videos.py
      |  |  |_ __int__.py
      |  |___pycache__
      |  |  |___init__.cpython-35.pyc
      |  |  |___init.cpython-37.pyc
      |  |  |_nuscenes.cpython-37.pyc
      |  |_utils
      |     |_data_classes.py
      |     |_geometry_utils.py
      |     |___init__.py
      |     |_map_mask.py
      |     |___pycache__
      |        |_data_classes.cpython-37.pyc
      |        |_geometry_utils.cpython-37.pyc
      |        |___init.cpython-37.pyc
      |        |_map_mask.cpython-37.pyc
      |
      |_data
         |_nuscenes
            |_README.pdf
            |_README2.txt
            |_maps
            |_samples
            |  |_CAM_BACK
            |  |_CAM_BACK_LEFT
            |  |_CAM_BACK_RIGHT
            |  |_CAM_FRONT
            |  |_CAM_FRONT_LEFT
            |  |_CAM_FRONT_RIGHT
            |_sweeps
            |  |_CAM_BACK
            |  |_CAM_BACK_LEFT
            |  |_CAM_BACK_RIGHT
            |  |_CAM_FRONT
            |  |_CAM_FRONT_LEFT
            |  |_CAM_FRONT_RIGHT
            |_v0.1
               |_attribute.json
               |_calibrated_sensor.json
               |_category.json
               |_ego_pose.json
               |_instance.json
               |_log.json
               |_map.json
               |_sample.json
               |_sample_annotation.json
               |_sample_data.json
               |_scene.json
               |_sensor.json
               |_visibility.json

*NOTE: It is necessary that the file structure should match otherwise the tutorial.ipynb won't execute.

7) In the home directory execute the following command:

cd && git clone https://github.com/nutonomy/nuscenes-devkit.git

8) Installing the required packages:

a)navigate to home/nuscenes-devkit using cd nuscenes-devkit (from the home directory)

b) Install the requirements by executing the following command:

pip install -r requirements.txt


9) Add the python-sdk directory to PYTHONPATH environment varible by adding the following line to the bottom of BOTH ~/.virtualenvs/nuscenes/bin/postactivate (virtual environment) or ~/.bashrc (global):

a) type nano ~/.bashrc
   add [export PYTHONPATH="${PYTHONPATH}:$HOME/nuscenes-devkit/python-sdk"] (excluding the []) to the bottom-most line press ctrl+x-->press y-->press <Enter>

b) type nano ~/.virtualenvs/nuscenes/bin/postactivate (virtual environment)
   add [export PYTHONPATH="${PYTHONPATH}:$HOME/nuscenes-devkit/python-sdk"] (excluding the []) to the bottom-most line press ctrl+x-->press y-->press <Enter>

10) Deactivate the virtual environment and exit the terminal to make the changes effective.

11) Enter the virtual environment using the follow command:

workon <name_of_Virtual_environment>`

**Comment by holger-nutonomy** [comment]
When unpacking the nuScenes data it seems that you flattened the folder structure:
```
|_data
|_nuscenes
|_maps
|_samples
```
These folders should not be on the same level. It should be `/data/nuscenes/maps`, `/data/nuscenes/samples`, etc.

**Comment by shahram95** [comment]
The nuscenes-devkit is present in the home folder, inside the nuscenes-devkit, there are python-sdk, setup.py, requirements.txt, instructions.md, license.txt, README.md, scehma.md.

Inside python-sdk there is tutorial.ipynb, nuscenes(folder) and data(folder)
inside the data(folder) there is a nuscenes(folder). I am attaching a series of pictures of my file structure, let me know if there is an error in the structure.

![screenshot from 2019-02-13 09-34-43](https://user-images.githubusercontent.com/46133362/52687226-c5092980-2f72-11e9-903f-b83fb0bc4868.png)
![screenshot from 2019-02-13 09-35-04](https://user-images.githubusercontent.com/46133362/52687231-ccc8ce00-2f72-11e9-9e53-e298cf22b587.png)
![screenshot from 2019-02-13 09-35-10](https://user-images.githubusercontent.com/46133362/52687244-d81bf980-2f72-11e9-9631-658f4bd6b9be.png)
![screenshot from 2019-02-13 09-35-14](https://user-images.githubusercontent.com/46133362/52687253-de11da80-2f72-11e9-9234-bee6cdb0697e.png)

**Comment by holger-nutonomy** [comment]
The devkit should reside in `~/nuscenes-devkit` (which is correct).
The data should reside in `/data/nuscenes` (which it doesn't for you).

**Comment by shahram95** [comment]
could you please define the exact location from the home directory where should I place it?
Would really appreciate it.

**Comment by shahram95** [comment]
Could you please tell me is this okay now? 

![screenshot from 2019-02-13 09-51-36](https://user-images.githubusercontent.com/46133362/52687738-0ac6f180-2f75-11e9-837d-27a7cffc31f4.png)
![screenshot from 2019-02-13 09-51-41](https://user-images.githubusercontent.com/46133362/52687749-0ef30f00-2f75-11e9-9421-ce7a50c0be14.png)
![screenshot from 2019-02-13 09-51-47](https://user-images.githubusercontent.com/46133362/52687750-131f2c80-2f75-11e9-8b57-5e9d139cbde3.png)

**Comment by holger-nutonomy** [comment]
> The devkit should reside in `~/nuscenes-devkit` (which is correct).
> The data should reside in `/data/nuscenes` (which it doesn't for you).

The suggested location of the data is not in the home directory. It's at `/data/nuscenes`.
But if you need to put it in the home folder, you can create the NuScenes object as:
```
nusc = NuScenes(dataroot='/home/username/nuscenes-devkit/data/nuscenes')
```
