### ISSUE TITLE
PointPillars

### ISSUE THREAD

**Issue by tjucwb** [nutonomy/nuscenes-devkit#302]
Hallo, I am training PointPillars on Nuscenes, but with my configs, it can not reproduce the results in the leaderboard, is it possible that someone can share a config, which can reproduce a close results?
thanks

**Comment by holger-nutonomy** [comment]
Hi. Unfortunately this is the not the right place for that.
- For the original (but deprecated) PointPillars code, refer to: https://github.com/nutonomy/second.pytorch
- For our preferred third party codebase, refer to: https://github.com/traveller59/second.pytorch
- Another third party codebase is: https://github.com/poodarchu/Det3D
