### ISSUE TITLE
Converting Specific Scenes to Kitti Format

### ISSUE THREAD

**Issue by jmiemirza** [nutonomy/nuscenes-devkit#314]
Hello! 

Is there a way to convert specific scenes in Nuscenes to Kitti Format through the Nuscenes Devkit? 

Forexample, I want to convert only the night scenes. Is it possible? 

Thanks and kind regards.

**Comment by holger-nutonomy** [comment]
Here is the script to convert scenes to KITTI format: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_kitti.py
It doesn't have any options to filter scenes, but that should be relatively easy to add. Just check whether `'night' in scene['description'].lower()`.

**Comment by jmiemirza** [comment]
Many thanks. I was able to filter out the scenes I wanted! :)

**Comment by holger-nutonomy** [comment]
Great!
