### ISSUE TITLE
Split trainval set into train and val sets

### ISSUE THREAD

**Issue by vatsal-shah** [nutonomy/nuscenes-devkit#316]
The trainval set contains 850 scenes, but how can we split it into train and val sets separately? I want to run some experiments on just the val set, anyway I can get just the val set?

**Comment by holger-nutonomy** [comment]
The val split is defined at https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/splits.py#L102 . It is not possible to download it separately.
