### ISSUE TITLE
FAF metric

### ISSUE THREAD

**Issue by camiloleon96** [nutonomy/nuscenes-devkit#319]
Hi!,
I'd like to know why you multiply by 100 to calculate the FAF metric.

Thanks!

https://github.com/nutonomy/nuscenes-devkit/blob/41605aa8858ce4f650ffd332b199ee72bbfec71a/python-sdk/nuscenes/eval/tracking/metrics.py#L178

**Comment by holger-nutonomy** [comment]
Hi. We simply follow other established challenges here and convert the number to a percentage for better readability:
https://motchallenge.net/results/CVPR_2019_Detection_Challenge/
https://motchallenge.net/results/MOT17Det/
