### ISSUE TITLE
Getting the 3D bonding box points value

### ISSUE THREAD

**Issue by shahram95** [nutonomy/nuscenes-devkit#32]
I was just playing around with the notebook and was just wondering how can we get the actual 3D bounding box point printed? Is there any way of getting these points?

**Comment by holger-nutonomy** [comment]
Take a look at the various `render*` methods in NuScenes, e.g. [this](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L736). The logic for what you need is encapsuated in the [Box class](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/data_classes.py#L522), which uses a method `corners` to retrieve the corners of the 3D box and `view_points` to project them to a camera or lidar frame.
