### ISSUE TITLE
Radirginia tech accttllegerowa accvvirginia tech accttllegerowa accvvirginia tech acctt

### ISSUE THREAD

**Issue by alfredrpk** [nutonomy/nuscenes-devkit#321]

**Comment by alfredrpk** [comment]
This shouldn't have been made and I don't know how it was made, please delete if possible, sorry

**Comment by holger-nutonomy** [comment]
What happened?

**Comment by alfredrpk** [comment]
I looked further into why this issue was created and it seems my keyboard had a macro key accidentally set to type some text I was searching (I don't know why it's this jumbled), and press enter, along with some other inputs. I accidentally pressed that macro key on my keyboard when I was on the issue page, and it sent 3 issues through. I'm sorry about any trouble this may have caused.

**Comment by holger-nutonomy** [comment]
Haha okay. Thanks for clarification.
