### ISSUE TITLE
Lidar sampling freq

### ISSUE THREAD

**Issue by ChaturvediShilpa** [nutonomy/nuscenes-devkit#324]
Hi, 

The paper mentions that lidar data is captured at 10Hz with 32 spinning beams generating nearly 1.3 Millions points per second. 

How does sampling rate transforms to points per second ? What is the duration of data like 10 min data or an hour data ?

**Comment by holger-nutonomy** [comment]
Hi. I think you misread. Waymo is 10Hz, our lidar is 20Hz. Let me know if you think that's wrong in the paper. Can you please elaborate on your two questions. I have problems understanding either of them.
The total duration of nuScenes is 1000 * 20s = 5.5h.

**Comment by ChaturvediShilpa** [comment]
Hi, 

Thank you for prompt reply. It was my mistake on sampling rate as it is 20Hz in paper as well.  Does this mean that there will be one point cloud entry every 20 seconds ? 

My question is that lidar dataset present in sweeps folder (LIDAR_TOP nearly 2.3 GB) is of what duration like 5 min or 5 hour ? Also 20 Hz means there is a laser beam sent 20 times in 1 sec.  Then the paper mentions 1.3 Millions points per second being generated. Does this mean there are 1,3 million point cloud record being generated at each sec ?

**Comment by holger-nutonomy** [comment]
> Does this mean that there will be one point cloud entry every 20 seconds ?

No, we publish all 20 pointclouds per second.

> My question is that lidar dataset present in sweeps folder (LIDAR_TOP nearly 2.3 GB) is of what duration like 5 min or 5 hour ?

5.5h or 1000 * 20s * 20Hz pointclouds. Note that the size should be ~100x bigger then your 2.3 GB.

> Also 20 Hz means there is a laser beam sent 20 times in 1 sec. 

Yes.

> Does this mean there are 1,3 million point cloud record being generated at each sec ?

There are 32 lidar beams in LIDAR_TOP creating a total of 20 pointclouds per second. So every beam revolution (aka row) should have around 1300000/20/32 = 2031 points.
