### ISSUE TITLE
Firetruck

### ISSUE THREAD

**Issue by jinglin80** [nutonomy/nuscenes-devkit#328]
If firetruck is included, there are 24 labels total, rather than 23. Otherwise, which label does the firetruck belong to? truck?

![image](https://user-images.githubusercontent.com/39305807/76710448-fb692900-66dd-11ea-9244-b14019104f7b.png)

**Comment by holger-nutonomy** [comment]
Hi. We removed the class from nuScenes as it had only a handful of annotations. Apparently we forgot to remove it from the instructions. This is now fixed in https://github.com/nutonomy/nuscenes-devkit/pull/329.
