### ISSUE TITLE
name 'PointCloud' is not defined

### ISSUE THREAD

**Issue by swirlingsand** [nutonomy/nuscenes-devkit#33]
Using python 3.7.2

```
3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)]
Traceback (most recent call last):
  File "play.py", line 1, in <module>
    from nuscenes.nuscenes import NuScenes
  File "A:\Sync\work\nuscenes-devkit\python-sdk\nuscenes\nuscenes.py", line 30, in <module>
    from nuscenes.utils.data_classes import LidarPointCloud, RadarPointCloud, Box
  File "A:\Sync\work\nuscenes-devkit\python-sdk\nuscenes\utils\data_classes.py", line 20, in <module>
    class PointCloud(ABC):
  File "A:\Sync\work\nuscenes-devkit\python-sdk\nuscenes\utils\data_classes.py", line 47, in PointCloud
    def from_file(cls, file_name: str) -> PointCloud:
NameError: name 'PointCloud' is not defined
```

**Comment by holger-nutonomy** [comment]
Hi, please note that we are not supporting Windows. For some reason using the class PointCloud inside itself as a typing annotation does not work. On Ubuntu this works and is enabled by the line `from __future__ import annotations`. For now I suggest you simply remove `-> PointCloud` from your code, as it is not used at run-time. I'd be interested to hear more about what you need to do to make this work on Windows.

**Comment by Qiang-Xu** [comment]
@holger-nutonomy we can change 
```
-> PointCloud
```
to
```
-> 'PointCloud'
```
which should work.

Details: https://www.python.org/dev/peps/pep-0484/#forward-references

**Comment by holger-nutonomy** [comment]
I've implemented the suggested workaround now.
@swirlingsand Please let us know if it does not work.

**Comment by swirlingsand** [comment]
Working! Thank you :)
