### ISSUE TITLE
Parsing Error on NuScenesMap('arcline_path_3' key not found)

### ISSUE THREAD

**Issue by yucedagonurcan** [nutonomy/nuscenes-devkit#333]
First of all, thank you for this repo and the tutorials. 

- I downloaded the v1.0-mini dataset and place it at: `~/Documents`
- I finished the [tutorial notebook](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/tutorial.ipynb). 
- I downloaded the Map Expansion data: **Map expansion pack (v1.1)  US** and placed it at: `~/Documents/v1.0-mini/maps` _(there are 4 different maps from map expansion and 4 different map masks from the mini dataset I downloaded earlier)_
- Then I switched to the [map_demo notebook](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/map_expansion/map_demo.ipynb) for better understanding the map format and render functionality:
   - When loading the the map I got an error that says there is no 'arcline_path_3' key in boston-seaport.json:

```python
import matplotlib.pyplot as plt
from nuscenes.map_expansion.map_api import NuScenesMap

nusc_map = NuScenesMap(dataroot='/home/adastec-oyucedag/Documents/v1.0-mini/', map_name='boston-seaport')

```
```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-51bca8c15fbf> in <module>
      2 from nuscenes.map_expansion.map_api import NuScenesMap
      3 
----> 4 nusc_map = NuScenesMap(dataroot='/home/adastec-oyucedag/Documents/v1.0-mini/', map_name='boston-seaport')

~/nuscenes-devkit/python-sdk/nuscenes/map_expansion/map_api.py in __init__(self, dataroot, map_name)
     90 
     91         self.canvas_edge = self.json_obj['canvas_edge']
---> 92         self._load_layers()
     93         self._make_token2ind()
     94         self._make_shortcuts()

~/nuscenes-devkit/python-sdk/nuscenes/map_expansion/map_api.py in _load_layers(self)
    141         self.lane_divider = self._load_layer('lane_divider')
    142         self.traffic_light = self._load_layer('traffic_light')
--> 143         self.arcline_path_3 = self._load_arcline_path()
    144         self.lane_connector = self._load_layer('lane_connector')
    145         self.connectivity = self._load_lane_connectivity()

~/nuscenes-devkit/python-sdk/nuscenes/map_expansion/map_api.py in _load_arcline_path(self)
    118         :return: Dictionary Mapping token to arcline_path_3.
    119         """
--> 120         return self.json_obj['arcline_path_3']
    121 
    122     def _load_lane_connectivity(self) -> Dict[str, Dict[str, List[str]]]:

KeyError: 'arcline_path_3'
```
I don’t see any key of `arcline_path_3` or `connectivity` in any of the json map files. Maybe I downloaded the wrong version or files. 

What can I do to fix it? Is there any configuration or files that I missed to read/download?

Have a great day.

**Comment by holger-nutonomy** [comment]
Hi. That's our fault. Over the weekend we are deploying two different PRs for the nuScenes prediction challenge and the new map version 1.2 (the former requires the latter). Please check again on Monday when the new map should be available for download.
