### ISSUE TITLE
Process finished with exit code 137 (interrupted by signal 9: SIGKILL)

### ISSUE THREAD

**Issue by sarimmehdi** [nutonomy/nuscenes-devkit#334]
I run this line and get the above memory error:

```
from nuscenes.nuscenes import NuScenes

nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=True)
```
I have Ubuntu 18.04, GTX 1050Ti, 8 GB RAM, 256 GB SSD and 1 TB HDD. Please tell me how to fix this. Thank you.

**Comment by holger-nutonomy** [comment]
Hi. Unfortunately nuScenes requires a lot of RAM as it is loading the entire database into memory. At least for `v1.0-trainval` it won't work with 8GB of RAM. For mini I would have thought that it works. Check if you are running anything else that is consuming memory.
