### ISSUE TITLE
Split larger dataset to smaller chunks to make it possible to work

### ISSUE THREAD

**Issue by sarimmehdi** [nutonomy/nuscenes-devkit#336]
Hi. I don't think it is practical to load everything into memory at once (not everyone has access to hardware with more than 8 GB RAM). Do you guys know how to split your dataset into smaller chunks to make it possible to load that into memory instead? 

Furthermore, once we split the dataset like that, is it possible to store that split in a separate folder with its own JSON files and folders? This way one could work with that smaller split dataset as one would with the original larger dataset. This would be particularly useful if one has to convert that smaller chunk of the dataset to the kitti format.

**Comment by holger-nutonomy** [comment]
Hi. Unfortunately we are not planning to introduce smaller subsplits. However, I recommend debugging with the mini split. You can also create smaller copies of the tables in `v1.0-trainval` with only a subset of the scenes.

**Comment by holger-nutonomy** [comment]
Also note that the conversion to KITTI isn't ideal and is throwing away most of the information (KITTI is only forward-facing).
