### ISSUE TITLE
Too many packages to be installed

### ISSUE THREAD

**Issue by ZwwWayne** [nutonomy/nuscenes-devkit#348]
Hi the developers,

This devkit is a great work for users to easily access the nuScenes dataset.
One question of mine is that does these packages are all necessary to install the nuscenes-devkit?
As shown in the pictures below, there seem to be many packages to be installed, which may cause difficulty for the python environment control.
![image](https://user-images.githubusercontent.com/40779233/78423368-7b106500-7698-11ea-8392-bdf9358a6996.png)

Therefore, is there anyway to release the burdun to install too many packages? Or if the users do not need all the functionality, is it possible to install a more light-weight version?

**Comment by holger-nutonomy** [comment]
The requirements of nuscenes-devkit can be found at https://github.com/nutonomy/nuscenes-devkit/blob/master/setup/requirements.txt. I don't know where you found the above list, but perhaps these are requirements of our requirements etc. All of our requirements are required and installing them should be very fast. We recommend using a Conda environment to keep it clean and not pollute your system with our requirements.

**Comment by ZwwWayne** [comment]
Hi @holger-nutonomy ,
Thanks for your reply.
I indeed use condo. The screenshot is taken when I type the command `pip install nuscenes-devkit`. So basically they are what installed when I install the devkit.
My concern is there are seems to be a lot of packages needed for nuscenes-devkit, but sometimes users may only need a small part of the devkit. So do you have any plans to enable the users to install and use only part of the devkit, e.g. only the 3D detection evaluation?

**Comment by holger-nutonomy** [comment]
You may remove these requirements if you want:

```
# Tracking
motmetrics<=1.1.3
pandas>=0.24

# Prediction
torch>=1.3.1
torchvision>=0.4.2
```

**Comment by holger-nutonomy** [comment]
FYI, we will remove torch and other requirements in https://github.com/nutonomy/nuscenes-devkit/pull/510.
