### ISSUE TITLE
couldnt find prediction_scenes.json in mini version of dataset

### ISSUE THREAD

**Issue by arunodhayan** [nutonomy/nuscenes-devkit#349]
FileNotFoundError: [Errno 2] No such file or directory: '/data/sets/nuscenes/maps/prediction_scenes.json'

i had unzipped the file using tar and the file prediction_scenes.json is missing in the map folder

**Comment by holger-nutonomy** [comment]
Hi. You need to download the `Map expansion pack (v1.2)` from https://www.nuscenes.org/download.
