### ISSUE TITLE
Feature request: Dataset converter: Waymo => Nuscenes => Waymo

### ISSUE THREAD

**Issue by ternaus** [nutonomy/nuscenes-devkit#350]
It would be nice to be able to convert the Waymo dataset to the nuscenes format.

Nuscences shared a lot of good work on the Lidar + camera. It would be interesting to check how will it work on the Waymo dataset.

**Comment by holger-nutonomy** [comment]
Hi Vladimir,
Great idea! However, we are currently pretty busy with releasing new content. Perhaps someone from your team could contribute this feature? We'd be happy to include it in the devkit.

**Comment by ternaus** [comment]
Not bad :)

I started looking into https://waymo.com/open/challenges/# in my free time. I was thinking about using nuTonomy code as a baseline for these challenges. 

If I will write the code for the conversion, I will create the PR :)

**Comment by asimay** [comment]
did this solved? thanks.
