### ISSUE TITLE
When will the detection leaderboard be open again?

### ISSUE THREAD

**Issue by turboxin** [nutonomy/nuscenes-devkit#351]
It seems that detection leaderboard is closed since new submission won't appear in the leaderboard. I'm wondering when will the leaderboard be open again

**Comment by holger-nutonomy** [comment]
Hi. The detection leaderboard is open all year round. In fact we have received 12 valid submissions in the last month. Please check if there are any errors or if you forgot an option to have your results visible on the leaderboard (the UI looks different for me).

**Comment by turboxin** [comment]
![Uploading 批注 2020-04-08 105238.png…]()

Hi @holger-nutonomy , if I rank all the methods by date on this page:  https://www.nuscenes.org/object-detection?externalData=all&mapData=all&modalities=Any ，the latest submission I can see is still from last year. I'm wondering if I'm looking at the wrong page. 

My user name is turboxin for evalai,  for www.nuscene.org  I can only see my email is tangxin0107@qq.com.  

I submitted to evalai like 5 or 6 days ago and I do choose the "Show on Leaderboard" option. My first three submission failed since I forgot to zip the result file, but I did get eval result for my 4th submission. Would failed submmison count for submmison chances?

Thanks in advance!

**Comment by holger-nutonomy** [comment]
Hi. Apologies for the misunderstanding. I thought you are referring to the leaderboard on the EvalAI page (https://evalai.cloudcv.org/web/challenges/challenge-page/356/leaderboard/1012). You can just go there and check your results. However, I didn't see a submission from your email address on any of the three challenges. Did you use a different address? What's the user name?

Unfortunately the leaderboard on nuScenes.org is not automatically populated and we need to do a fair amount of work to contact people and get the detailed information about their method. We will do that again once the current challenge ends (end of May). 

Failed submissions do not count towards your submission limit.

P.S.: Your picture wasn't uploaded correctly.

**Comment by turboxin** [comment]
Thank you for telling me my results.
Seems that the leaderboard in evalai is closed for now,  it's empty from https://evalai.cloudcv.org/web/challenges/challenge-page/356/leaderboard and I can't select phase,  and from the page you give (https://evalai.cloudcv.org/web/challenges/challenge-page/356/leaderboard/1012) it says "Sorry, the leaderboard is not public".
I will check later. Thank you!

**Comment by holger-nutonomy** [comment]
Okay, we are in contract with the EvalAI admins to make the leaderboard public.

**Comment by holger-nutonomy** [comment]
The detection leaderboard can now be viewed at:
https://evalai.cloudcv.org/web/challenges/challenge-page/356/leaderboard/1012

**Comment by turboxin** [comment]
Great to hear that, thanks! @holger-nutonomy
