### ISSUE TITLE
prediction

### ISSUE THREAD

**Issue by arunodhayan** [nutonomy/nuscenes-devkit#354]
Does the trajectory sets been updated in the tutorial 

cv_model = ConstantVelocityHeading(sec_from_now=6, helper=helper)
physics_oracle = PhysicsOracle(sec_from_now=6, helper=helper)

am trying to save the output as list and then to Json but getting through many error help me

**Comment by freddyaboulton** [comment]
@arunodhayan What is the error?

**Comment by arunodhayan** [comment]
cv_model = ConstantVelocityHeading(sec_from_now=6, helper=helper)
physics_oracle = PhysicsOracle(sec_from_now=6, helper=helper)

when I try to convert this into a list 
object is not subscriptable -- error

**Comment by freddyaboulton** [comment]
@arunodhayan Thanks for clarifying!

`cv_model` and `physics_oracle` are not lists of predictions. They are functions that return predictions.

The next line in the tutorial shows how to use these functions to get predictions:

```
cv_model(f"{instance_token_img}_{sample_token_img}")
```

This will return a [Prediction ](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/prediction/data_classes.py). You can convert this to json by calling the `serialize` method. 

To see an example of how to generate predictions for the entire validation set, see this [script](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/prediction/baseline_model_inference.py).

Hope that answers your question!

**Comment by arunodhayan** [comment]
Ya I got it yesterday itself sorry for not updating here, Thank you so much for the response

like covernet or physics model we can create our own model and do the predictions right...

**Comment by freddyaboulton** [comment]
Hi @arunodhayan 

Of course you can create your own model! This was just a starting point.

Here is the paper for CoverNet: https://arxiv.org/pdf/1911.10298.pdf
