### ISSUE TITLE
CoverNet module release date

### ISSUE THREAD

**Issue by chowkamlee81** [nutonomy/nuscenes-devkit#355]
When code for CoverNet: Multimodal Behavior Prediction using Trajectory Sets likely to get released?

**Comment by freddyaboulton** [comment]
Hi @chowkamlee81 , thanks for the question!

We have already released an implementation of the CoverNet model. This [tutorial](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/tutorials/prediction_tutorial.ipynb) shows how to use it.
