### ISSUE TITLE
export_kitti.py label error

### ISSUE THREAD

**Issue by davidlmljll** [nutonomy/nuscenes-devkit#356]
Hello,firstly,thank you for your work.Some labels are empty when converted to kitti data set format. What is the reason？

**Comment by holger-nutonomy** [comment]
Hi. The primary purpose of the kitti export script is to enable users to use codebases that were made for KITTI for our detection challenge. Therefore we use the class mapping from the detection challenge and discard the other classes: https://github.com/nutonomy/nuscenes-devkit/blob/3758022d577e7c4715eafb26e1a08c1c2ac0f76a/python-sdk/nuscenes/eval/detection/utils.py#L7
Feel free to modify that code on your disk to export other classes.
