### ISSUE TITLE
Question about annotations out of FOV of camera when coverting to KITTI format

### ISSUE THREAD

**Issue by vatsal-shah** [nutonomy/nuscenes-devkit#357]
When converting the dataset to KITTI format, the script converts images of one camera angle (ex. FRONT). Are the objects which do not fall in the selected camera's field of view also included in the ground truth file for the corresponding frame? And the same for the Lidar points, are the points not falling in the FOV of the camera not included in the corresponding point cloud file as well?

**Comment by holger-nutonomy** [comment]
Hi. Please have a look at the code for the details, it is relatively compact.

Regarding the annotations, we discard annotations for which none of the corners of the projected 2d box are in front of the camera:
https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_kitti.py#L234

We only rotate the pointcloud to the KITTI coordinate frame, but do not remove points:
https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_kitti.py#L170

**Comment by vatsal-shah** [comment]
Hi! I had looked at the code, but just wanted to be sure. Thank you for the prompt response!
