### ISSUE TITLE
Why we are using unnecessary depths vector in render_map_in_image?

### ISSUE THREAD

**Issue by yucedagonurcan** [nutonomy/nuscenes-devkit#358]
I was exploring the code in:
https://github.com/nutonomy/nuscenes-devkit/blob/3758022d577e7c4715eafb26e1a08c1c2ac0f76a/python-sdk/nuscenes/map_expansion/map_api.py#L1074-L1081

Grabbing the depths vector just for the shape is unnecessary since we will already have points vector from 1077th line with the same shape:

1077: `inside = np.ones(points.shape[1], dtype=bool)`

It is a small issue but I am asking because I am curious if I am missing something, isn't it unnecessary?

**Comment by holger-nutonomy** [comment]
Yeah, I don't think it will make any difference performance-wise, but it may make the code a bit clearer. I have implemented your suggestion in https://github.com/nutonomy/nuscenes-devkit/pull/360, which will be merged soon.
