### ISSUE TITLE
Too fast 'Car' object???

### ISSUE THREAD

**Issue by droneRL2020** [nutonomy/nuscenes-devkit#359]
I calculated object's velocity by (current pose of object)-(previous timestep pose of object) and found  out 'car' object's x_velocity is 40.5 and y_velocity is -22.4.
I understood one timestep is around 0.5second since  39~41 key frames are taken in 20 Seconds.
Meaning, x_velocity becomes 81m/s and y_velocity becomes -44.8m/s w.r.t global coordinates.

Am I missing something?

![image](https://user-images.githubusercontent.com/34183439/79577389-9e5afb80-80ff-11ea-879f-d0d95fa0efe2.png)

**Comment by holger-nutonomy** [comment]
Hi. Without posting the code it will be very difficult to understand what you did. Is this the largest velocity you found in nuScenes or just a random sample? Most of the velocities should be below 15m/s. You can see the histograms in our paper (https://arxiv.org/pdf/1903.11027.pdf):
![vel](https://user-images.githubusercontent.com/39502217/79626151-85cefd80-8160-11ea-8e7c-0c1b368f6871.png)
Also, if you just took the first and last annotation of a particular instance, it is not clear that that instance was visable for 20s. Perhaps it was visible for 0.5s, which would make 40x difference.
