### ISSUE TITLE
Is there a description for the difference between Map v1.1 and v1.2?

### ISSUE THREAD

**Issue by peiyunh** [nutonomy/nuscenes-devkit#364]
Thanks!

**Comment by holger-nutonomy** [comment]
Hi.
- 1.1 fixed some issues with map and ego pose alignment (we were using the wrong version of a map)
- 1.2 added some missing content in the fringe areas of our hollandvillage and queenstown maps, it added the centerlines and also a file `prediction_scenes.json` for the prediction challenge.
