### ISSUE TITLE
Too fast maximum velocity?(With Code)

### ISSUE THREAD

**Issue by droneRL2020** [nutonomy/nuscenes-devkit#365]
I checked velocity which exceeds 35 and -35 in half second and there were four 'car' data which is larger than 35(70m/s) as below.

![image](https://user-images.githubusercontent.com/34183439/79982183-e18ee300-84e0-11ea-9961-bd9aaa62b714.png)

To check the velocity(residual_vel in the link) I ran this code.
https://github.com/eddyhkchiu/mahalanobis_3d_multi_object_tracking/blob/master/get_nuscenes_stats.py#L82

To get not only velocity but also matching dt, box.tracking_name, box.tracking_id, scene_token I wrote debugging code as below. Changed from this line.(https://github.com/eddyhkchiu/mahalanobis_3d_multi_object_tracking/blob/master/get_nuscenes_stats.py#L72)

        if box.tracking_id not in gt_trajectory_map[box.tracking_name][scene_token]:
            gt_trajectory_map[box.tracking_name][scene_token][box.tracking_id] = {t_idx: box_data}
            if box.tracking_id in time_memory:
                time_memory[box.tracking_id][t_idx] = t
            elif len(time_memory) == 0:
                time_memory = {box.tracking_id:{t_idx:t}}
            else:
                time_memory[box.tracking_id] = {t_idx:t}
        else: 
            gt_trajectory_map[box.tracking_name][scene_token][box.tracking_id][t_idx] = box_data
            time_memory[box.tracking_id][t_idx] = t
        
        # if we can find the same object in the previous frame, get the velocity
        if box.tracking_id in gt_trajectory_map[box.tracking_name][scene_token] and t_idx-1 in gt_trajectory_map[box.tracking_name][scene_token][box.tracking_id]:
          residual_vel = box_data[3:7] - gt_trajectory_map[box.tracking_name][scene_token][box.tracking_id][t_idx-1][3:7]
          if (residual_vel[0] > 35) or (residual_vel[0] < -35):
              dt = time_memory[box.tracking_id][t_idx] - time_memory[box.tracking_id][t_idx-1]
              vel_memory.append((dt, residual_vel, box.tracking_name, box.tracking_id, scene_token))

**Comment by holger-nutonomy** [comment]
Hi. Something is definitely wrong in your code. Unfortunately I didn't have the whole code to reproduce it. The simplest fix would probably be to include the time as well. Please use our official velocity method `NuScenes.box_velocity()`. The following snippet computes velocities for the entire mini split:
```
%matplotlib inline
from nuscenes.nuscenes import NuScenes
import tqdm
import numpy as np

nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=True)

vels = []
for sample_annotation in tqdm.tqdm(nusc.sample_annotation):
    vel = nusc.box_velocity(sample_annotation['token'])
    vels.append(vel)

vels = np.array(vels)
np.nanmin(vels), np.nanmax(vels)
```
The output is
```
(-27.05217827273613, 17.845242033584118)
```
For trainval, it is:
```
(-41.392756994515715, 27.13077815113959)
```
In general the boxes are provided as-is by the annotators without any temporal smoothing. For a car 70m away on a parking lot it may happen that there is some drift between neighboring frames. Note that these are extreme outliers. Only 0.04% of our annotations have any velocity component above 15m/s:
```
np.sum(np.sum(np.abs(vels) > 15, axis=1) > 0) / vels.shape[0]
```
Returns:
```
0.0004030228428202338
```
