### ISSUE TITLE
Pytorch version requirement?

### ISSUE THREAD

**Issue by jonahthelion** [nutonomy/nuscenes-devkit#367]
I'm wondering what's the reasoning behind requiring `torch>=1.3.1`? What in this library conflicts with earlier versions of pytorch?

Thank you!

**Comment by holger-nutonomy** [comment]
Hi. I don't have the entire history in front of me, but we experienced incompatibilities both with Pillow (https://github.com/pytorch/vision/issues/1712) and numpy. This setup is tested and seems to work. You are free to experiment with other versions. If the unit tests pass, chances are it works.

**Comment by holger-nutonomy** [comment]
FYI, we will remove the torch requirement in https://github.com/nutonomy/nuscenes-devkit/pull/510.
