### ISSUE TITLE
ego pose orientation mismatch

### ISSUE THREAD

**Issue by xli4217** [nutonomy/nuscenes-devkit#370]
Hi, below are the first few ego poses from scene-0061 where the first vector is the translation and the last number is the orientation in degrees (calculated from the quaternion provided) all in the global frame. 

[411.3039349319818, 1180.8903791765097, 0.0],  -69.78323712700228
[409.7431520488096, 1176.6769733781416, 0.0],  -70.11635890781453
[408.101879146712, 1172.1515777892457, 0.0], -70.47484456994222
[406.7260055966978, 1168.2112865775816, 0.0],  -71.136324633

However, when I try to calculate the orientation using atan2(y2-y1, x2-x1) from the translations the results do not match that from the data shown. 

Also, if [0,0,0] is at the top left corner of the map, positive x is to the right and positive y is downwards, does that mean a left hand coordinate frame is used? 

Thanks

**Comment by holger-nutonomy** [comment]
Please refer to https://www.nuscenes.org/data-collection for an overview of the coordinate frames.
Please also take a look at the code how we compute the orientations from the quaternions.
