### ISSUE TITLE
Readme and tutorial mismatch for Steer Angle Feedback value

### ISSUE THREAD

**Issue by jinglin80** [nutonomy/nuscenes-devkit#371]
According to the readme, positive value of steer angle feedback indicates right turn, but in the can bus tutorial (https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/tutorials/can_bus_tutorial.ipynb), it has the following description. As shown in the image below, the initial value is positive (around 3), so should the description be " It seems like the scene starts with a strong **right** turn and then continues more or less straight" if the readme description is correct? 

![image](https://user-images.githubusercontent.com/39305807/80335124-5c2d6a80-8821-11ea-9100-234038884306.png)

**Comment by holger-nutonomy** [comment]
Left turn is correct:
![n015-2018-07-18-11-07-57+0800__CAM_FRONT__1531883530412470](https://user-images.githubusercontent.com/39502217/80450073-4c15a800-8953-11ea-86a7-95a4ed323909.jpg)
![n015-2018-07-18-11-07-57+0800__CAM_FRONT__1531883531912467](https://user-images.githubusercontent.com/39502217/80450093-55067980-8953-11ea-953e-7ef5f3e0beed.jpg)
We will adjust the readme accordingly.

Thanks for the feedback.
