### ISSUE TITLE
Angular and Linear acceleration for IMU

### ISSUE THREAD

**Issue by raviy0807** [nutonomy/nuscenes-devkit#378]
The newly released dataset contains the IMU data with following field:

- Linear Acc
-Rotation
-d

It does not mention that the linear Acc is with or without gravitational.
Therefore I have the following questions:

1. How to find linear accel. with/without gravitational?
2. method to get IMU Angle
3. Angular Accel with vehicle frame coordinate
4. Angular Rate in vehicle frame coordinates

**Comment by holger-nutonomy** [comment]
Hi. All the fields are listed at https://github.com/nutonomy/nuscenes-devkit/tree/master/python-sdk/nuscenes/can_bus.  Note that there are different accelerations at different frequencies and filtering stages:

- IMU: linear_accel
- Pose: accel
- Zoe Vehicle Info: longitudinal_accel, transversal_accel

1. I suggest you take a look at the values. I recall that for pose the vertical acceleration corresponds to gravity.
2. In general the IMU sits at the ego vehicle reference frame. You can compute the angle from the quaternion provided by the IMU.
3. You can only compute the angular acceleration by differentiation. There is no sensor on our vehicle that measures it.
4. The angular rate is the rotation_rate provided by the IMU.

If you have more questions, write an email to holger@nutonomy.com and I can send you the specs of the IMU we use.

**Comment by raviy0807** [comment]
@holger-nutonomy , thanks for the reply. 

Just to be sure, Is the provided Linear Acceleration of IMU data is without Gravity?

Could you elaborate on how do I find Linear Acceleration with and without Gravity?
Email : ravi.y0807@gmail.com

**Comment by holger-nutonomy** [comment]
@raviy0807 The values look like `[0.15899741649627686, 0.1085263267159462, 9.796441078186035]`. So that is "with gravity". We don't provide a version without gravity, but you could use the orientation of the ego pose to compensate for it, or as a heuristic you just ignore the z dimension.

**Comment by jingyibo123** [comment]
@holger-motional 
While inspecting the LiDAR / Image sample_data. ego_pose inconsistencies can often be observed, which degrades the sequential usage of sample data.
I wonder if there is plan to public the raw IMU data(at full frequency) and raw GNSS/RTK data, to further odometry/SLAM related researches, similar to KITTI ?

**Comment by whyekit-motional** [comment]
@jingyibo123 nuScenes does provide the raw IMU data - pls take a look at https://www.nuscenes.org/nuscenes?tutorial=can-bus (c.f. https://github.com/nutonomy/nuscenes-devkit/issues/481#issuecomment-716287532)

However, GPS is not used here, which does not work well in urban environments.

**Comment by whyekit-motional** [comment]
I presume you need the coordinate system of the IMU in order to do transformations for visual inertial odometry (VIO) / lidar inertial odometry (LIO) - this is encoded within the `calibrated_sensor` data which indicates the extrinsic parameters (e.g. rotation, translation) of a particular sensor with respect to the ego vehicle body frame

For the bias of the IMU, you can refer to the specs of the IMU used in nuScenes here: https://www.advancednavigation.com/solutions/spatial/

I believe if you need further information related to the IMU, the datasheet provided by Advanced Navigation will have the details

**Comment by jingyibo123** [comment]
> I presume you need the coordinate system of the IMU in order to do transformations for visual inertial odometry (VIO) / lidar inertial odometry (LIO) - this is encoded within the `calibrated_sensor` data which indicates the extrinsic parameters (e.g. rotation, translation) of a particular sensor with respect to the ego vehicle body frame
> 
> For the bias of the IMU, you can refer to the specs of the IMU used in nuScenes here: https://www.advancednavigation.com/solutions/spatial/
> 
> I believe if you need further information related to the IMU, the datasheet provided by Advanced Navigation will have the details

Thanks for the link. 

About the specs, I have another question about the camera, is the images captured with global or rolling shutter?

**Comment by whyekit-motional** [comment]
@jingyibo123 the images in nuScenes were captured with a global shutter
