### ISSUE TITLE
Prediction leader board

### ISSUE THREAD

**Issue by xli4217** [nutonomy/nuscenes-devkit#379]
Hi, will there be a leader board for the prediction tasks on the website soon? Thanks.

**Comment by holger-nutonomy** [comment]
Hi. There will not be a leaderboard on our homepage until after the end of the challenge (end of May). Until then you can only see a small number of methods that already want to share their results on the EvalAI leaderboard (https://evalai.cloudcv.org/web/challenges/challenge-page/591/leaderboard/1659).
