### ISSUE TITLE
Setting visibility threshold for bounding boxes

### ISSUE THREAD

**Issue by shahram95** [nutonomy/nuscenes-devkit#38]
what is the parameter for setting the threshold value for the bounding boxes. By default it is set to BoxVisibility.ANY, how can i change this to make bounding boxes when visibility is greater the 70%?

Thanks in advance.

**Comment by eskjorg** [comment]
Arbitrary threshold not possible atm.

In `nuscenes.utils.geometry_utils.BoxVisibility`, there are 3 alternatives.
`ALL = 0  # Requires all corners are inside the image.
ANY = 1  # Requires at least one corner visible in the image.
NONE = 2  # Requires no corners to be inside, i.e. box can be fully outside the image.`

**Comment by holger-nutonomy** [comment]
@eskjorg is correct that this is the definition of BoxVisibility. Hence it is not related to the visibility percentage (https://github.com/nutonomy/nuscenes-devkit/blob/master/schema.md#visibility). For that purpose you'd need to modify [`get_sample_data()`](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L194) or create your own function.
