### ISSUE TITLE
prediction_tutorial |error | v1.0-mini | missing file "prediction_scenes.json"

### ISSUE THREAD

**Issue by RRK13** [nutonomy/nuscenes-devkit#380]
Request for support, error while trying prediction_tutorial with v1.0-mini, missing file "prediction_scenes.json". The details are shown below. 
Note the data folder has the correct path (DATAROOT = '/data/sets/nuscenes/') and the first step of loading the data is successful.

Code lines. 
`from nuscenes.eval.prediction.splits import get_prediction_challenge_split
mini_train = get_prediction_challenge_split("mini_train")
mini_train[:5]`

Error details 
`---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-2-bfe7e7d26809> in <module>
      1 from nuscenes.eval.prediction.splits import get_prediction_challenge_split
----> 2 mini_train = get_prediction_challenge_split("mini_train")
      3 mini_train[:5]

~/nus_data/lib/python3.7/site-packages/nuscenes/eval/prediction/splits.py in get_prediction_challenge_split(split, dataroot)
     28 
     29     path_to_file = os.path.join(dataroot, "maps", "prediction_scenes.json")
---> 30     prediction_scenes = json.load(open(path_to_file, "r"))
     31     scenes = create_splits_scenes()
     32     scenes_for_split = scenes[split_name]

FileNotFoundError: [Errno 2] No such file or directory: '/data/sets/nuscenes/maps/prediction_scenes.json'`

**Comment by holger-nutonomy** [comment]
I think you need to download the latest version of the map expansion from https://www.nuscenes.org/download

**Comment by bimsarapathiraja** [comment]
I got the latest version but the problem occurs

**Comment by whyekit-motional** [comment]
@bimsarapathiraja pls ensure the following:
- Your `nuscenes-devkit` version is `>= 1.1.2`
- You have downloaded map expansion pack `v1.3`
- Your nuScenes dataset folder structure is:
  ```
  └── nuscenes  
    ├── Usual folders (e.g. samples, sweeps, etc.)
    │
    └── maps
        ├── basemap
        │          ├── boston-seaport.png
        │          └── ...
        ├── expansion
        │          ├── boston-seaport.json
        │          └── ...
        └── prediction
                   └── prediction_scenes.json 
  ```

**Comment by gopalkumr** [comment]
> @bimsarapathiraja pls ensure the following:
> 
> * Your `nuscenes-devkit` version is `>= 1.1.2`
> * You have downloaded map expansion pack `v1.3`
> * Your nuScenes dataset folder structure is:
>   ```
>   └── nuscenes  
>     ├── Usual folders (e.g. samples, sweeps, etc.)
>     │
>     └── maps
>         ├── basemap
>         │          ├── boston-seaport.png
>         │          └── ...
>         ├── expansion
>         │          ├── boston-seaport.json
>         │          └── ...
>         └── prediction
>                    └── prediction_scenes.json 
>   ```

How we can download the version 1.1.2 , I'm getting v1.0 by default. Please help.

<img width="635" alt="image" src="https://user-images.githubusercontent.com/91552766/209797704-8bb453aa-6d15-4e36-b845-7f98bc770673.png">

**Comment by whyekit-motional** [comment]
@gopalkumr the "v1.0" you have shown in your screenshot refers to the version of the **dataset** (which is correct)

For the **devkit**, `pip install nuscenes-devkit` (the last command in your screenshot) should install the latest version of the devkit (which is `>=1.1.2`)
