### ISSUE TITLE
Getting GPS data from nuscenes dataset

### ISSUE THREAD

**Issue by RRK13** [nutonomy/nuscenes-devkit#381]
Full sensor suite (1x LIDAR, 5x RADAR, 6x camera, IMU, GPS), as per the https://www.nuscenes.org/

I was able to get all data except GPS. 

Please share the steps to be taken, to get the GPS data. it would be also helpful if an example is shared.

**Comment by holger-nutonomy** [comment]
Hi. The GPS data is very bad in an urban environment with tall buildings around. Therefore we only release the ego pose, which is the output of our lidar/GPS/IMU-based localization algorithm.

**Comment by Monssica** [comment]
Is the GPS data of the nuscenes dataset published now?

**Comment by Monssica** [comment]
Is the GPS data of the nuscenes dataset published now?

**Comment by whyekit-motional** [comment]
@Monssica do check out the CAN bus expansion: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/can_bus/README.md

**Comment by Monssica** [comment]
Does the provided data processed through the localization algorithm can obtain the ego_pose in the Nuscenes dataset？

**Comment by whyekit-motional** [comment]
It depends on the which data from CAN bus expansion you are referring to, e.g. the IMU data would simply be the measurements from the IMU

**Comment by Monssica** [comment]
okay,From which IMU data is the ego_pose file you published calculated?

**Comment by whyekit-motional** [comment]
In the car setup for nuScenes, there is only one IMU (pls see [here](https://www.nuscenes.org/static/media/data.9ef46c59.png)) - that would be the IMU you are looking for

**Comment by max-monastirsky** [comment]
Hey,
Can we get the GPS location of the (0,0) coordinate of every scene?

**Comment by whyekit-motional** [comment]
@max-monastirsky pls see if this helps you: https://github.com/nutonomy/nuscenes-devkit/issues/144#issuecomment-505377023

**Comment by Gabriel0224** [comment]
I try to use data to do SLAM experiment.  It needs groundtruth data to compared. Do you have the same data to make it ?

**Comment by whyekit-motional** [comment]
@Gabriel0224 whatever data that is already released under nuScenes is whatever is available
