### ISSUE TITLE
Question about the nuscene.render_sample()

### ISSUE THREAD

**Issue by DKandrew** [nutonomy/nuscenes-devkit#383]
It seems like NuScene.render_sample() creates a new matplotlib figure and user needs to use `plt.show()` to display it. Jupyter notebook handles this automatically, but python script does not. If this is a design choice, it is not documented in the `render_sample()`.

**Comment by holger-nutonomy** [comment]
Yes, its a design choice for most of the render functions in the devkit. We also often provide the option to render into a provided axis for maximum flexibility.
