### ISSUE TITLE
How to determine scene number?

### ISSUE THREAD

**Issue by csonthomisi** [nutonomy/nuscenes-devkit#388]
Hi there!
I would like to use the provided calibration data, in the "calibrated_sensor.json" file. I noticed that it contains 850 calibration data for each sensor. If I'm right, each sensor has an own data for each scene. But how can I determine, which one to use? 

I would like to do the following:
- read a lidar file (from sweeps folder)
- read an image file (from sweeps folder)
- find the corresponding rotation and translation matrices for them

Suppose I want to know the calibration data for the data in the "sweeps" folder in part 4 of the trainval package. A scene_token is specified in the "sample.json" file for the sample data, but no such file is specified for the sweeps data.

How can I find out which of the 850 data should be used for a given timestamp?

Thank you very much for help!

**Comment by holger-nutonomy** [comment]
Hi. Please take a look at the tutorial: https://www.nuscenes.org/tutorial
nuScenes is organized as a relational database with foreign keys linking the tables, such as `scene_token`. A sample is an annotated key frame (at 2Hz). All sensor data is organized in the sample_data table. The images and pointclouds of the sample_data table are organized in two folders: `sample` for keyframes and `sweeps` for non-keyframes.
