### ISSUE TITLE
Running nuscenes_eval without any TPs gives uninformative error message

### ISSUE THREAD

**Issue by eskjorg** [nutonomy/nuscenes-devkit#39]
I want to try the `nuscenes_eval.py` script with fake results. I.e. there might be 0 TPs in the results file. 

In this case the `assert np.nanmin(metric_vals) >= 0` fails, since `metric_vals` contains only `np.nan`. Took me a while to understand why.

How about adding an error message to the `assert` statement?
Or should the case of 0 TPs be handled in another way?

**Comment by holger-nutonomy** [comment]
Yes, you are correct. I have already fixed that in the release_v0.2 branch which will soon become the v1.0 code for the full nuScenes dataset. I have also fixed it for the the master branch now.
See https://github.com/nutonomy/nuscenes-devkit/pull/41.
