### ISSUE TITLE
Any API to evaluate detection result locally?

### ISSUE THREAD

**Issue by 300LiterPropofol** [nutonomy/nuscenes-devkit#390]
Hi!

I have a question about how to evaluate our 3D object detector's performance locally according to nuscenes evaluation rule.
In python-sdk/nuscenes/eval/detection/README.md I didn't find direct API to get the evaluation result. It seems like the only way to evaluate the detection results locally is to download and modify the source code in /detection folder.
But I am not sure whether I missed some other tutorials about detection evaluation, is there any API to directly evaluate the detection performance given my detection results?

Thank you!

**Comment by holger-nutonomy** [comment]
Hi,

just call this file: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/detection/evaluate.py#L263
```
python ~/nuscenes-devkit/python-sdk/nuscenes/eval/detection/evaluate.py my_result.json
```
