### ISSUE TITLE
No pedestrian in get_prediction_challenge_split()

### ISSUE THREAD

**Issue by amiryanj** [nutonomy/nuscenes-devkit#393]
I wonder why I get 0 pedestrians in both train and test instances, from get_prediction_challenge_split() (in both mini dataset and main dataset)?
Does it mean the challenge is designed just for the prediction of vehicles?

**Comment by freddyaboulton** [comment]
Hi @amiryanj, thanks for the question!

For this version of the challenge, we are focusing only on vehicles so you are correct that there are no predestrian instances.
