### ISSUE TITLE
Will tracking leaderboard be updated soon?

### ISSUE THREAD

**Issue by tianweiy** [nutonomy/nuscenes-devkit#397]
Hi, I am curious when the tracking leaderboard will be updated on the main website. The reason is that I want to compare with other methods in a paper but the evalAI page truncates the AMOTA value to two significant digits so that the top few are the same.

**Comment by tianweiy** [comment]
+ per class result will also be useful

**Comment by holger-nutonomy** [comment]
We plan to update our leaderboards after the challenges (detection and prediction) are over. I'll send you an email with your results.
