### ISSUE TITLE
tp_metrics crashes for classes without attributes

### ISSUE THREAD

**Issue by eskjorg** [nutonomy/nuscenes-devkit#40]
`eval_utils.attr_acc()` will return `np.nan` for classes without attributes (e.g. _barrier_).

This will eventually lead to `assert np.nanmin(metric_vals) >= 0` failing when `tp_metrics()` is run for the `barrier` class.

Thus, the `nuscenes_eval` script will always crash, I believe. Haven't checked the code thoroughly but I think that is the case..

**Comment by holger-nutonomy** [comment]
This should be fixed now. Please pull from master and try again.
