### ISSUE TITLE
NaN for helper.get_acceleration_for_agent()

### ISSUE THREAD

**Issue by xli4217** [nutonomy/nuscenes-devkit#400]
For some agents in the predication tasks, calling helper.get_acceleration_for_agent() returns nan. An example is 

instance_token: 100047e87c594de396c1e110674a85ad
sample_token: 1c7ffbf13c214f45b62d5ad58d939650

Help would be appreciated.

**Comment by freddyaboulton** [comment]
Hi @xli4217, thanks for posting!

Yes, that is expected because that is the first observation for that agent so there are no previous velocities to use to compute the acceleration.
