### ISSUE TITLE
 Nuscenes minFDE and minADE calcuation

### ISSUE THREAD

**Issue by mzahran001** [nutonomy/nuscenes-devkit#401]
Hi Team 

I have questions about the  function [`rank_metric_over_top_k_modes`](https://github.com/nutonomy/nuscenes-devkit/blob/0fddd0cf7378f76574493d402ad431325d3223d4/python-sdk/nuscenes/eval/prediction/metrics.py#L84). 

From my understanding of the current implementation, it supports calculating the minFDE and minADE for the models that output trajectories with probabilities but if the model doesn’t produce the probabilities the current implementation will fail to calculate the minADE or minFDE.  If we see the [Argoverse implementation](https://github.com/argoai/argoverse-api/blob/2f93a9e18321ec6199c3f6345c533581678382b7/argoverse/evaluation/eval_forecasting.py#L102), it is handling both cases.

What do you think? Am I missing something here? 😅

**Comment by freddyaboulton** [comment]
Hi @mzahran001 , thanks for the question!

Yes, you are right that `rank_metric_over_top_k_modes` expects probabilities to be present. We intended for `rank_metric_over_top_k_modes` to be called by one of the `Metric` classes, like `MinADEK`, and these classes are called on `Predictions` , which need to have probabilities. You actually can't instantiate a `Prediction` if the probabilities are not set. We felt this was better than guessing what to do if we encountered missing probabilities.
