### ISSUE TITLE
When are objects annotated with a velocity of nan?

### ISSUE THREAD

**Issue by Nuri-benbarka** [nutonomy/nuscenes-devkit#405]
Hi,
I am looking at the velocity annotations, and I see that some of them are nan, when are objects annotated this way?
example
scene_token: 'fd8420396768425eabec9bdddf7e64b6'
sample_token: 'b214d0d42c404d4f925aa56ee9cac607'

**Comment by holger-nutonomy** [comment]
Hi. Velocities are not annotated, but just computed from 2 or 3 poses.
It is computed in https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L332 .
I believe the velocity is nan when the time difference between the previous and next annotation are 0 or > 1.5s.
