### ISSUE TITLE
maps/prediction_scenes.json missing

### ISSUE THREAD

**Issue by nfsrules** [nutonomy/nuscenes-devkit#406]
Hi guys,

I'm trying to run the prediction challenge tutorial and I got this error. It seems to be a missing file. 

Is this file available somewhere else in the repository or did I miss something?

Thanks a lot.

![image](https://user-images.githubusercontent.com/23075615/83251892-9a180880-a1aa-11ea-8668-6570034ec252.png)

**Comment by holger-nutonomy** [comment]
Hi. Please download the latest version of the map expansion pack (1.2).
