### ISSUE TITLE
Qusetion about the lane width

### ISSUE THREAD

**Issue by LuanDi1996** [nutonomy/nuscenes-devkit#409]
Hi Team

I am wondering if there some information about the lane width, and if I have a token, how can I know it is lane or lane connector? 

Thanks.

**Comment by holger-nutonomy** [comment]
Hi. Lane width is not directly provided by our maps. If you look at the [map tutorial](https://www.nuscenes.org/map-tutorial), specifically the lane records, you will see the edges on the left/right and from/to side. With these you should be able to compute the lane width.

**Comment by LuanDi1996** [comment]
Thanks for reply, and for the second question, do you know how to judge whether it is a lane or lane connector when given a token?

**Comment by holger-nutonomy** [comment]
What do you mean by lane connector?

**Comment by LuanDi1996** [comment]
For example, in map_api.py, lanes are represented as lane and lane_connector. Now, I want to get a full sequence of lanes by using  _nusc_map.get_outgoing_lane_ids_, but the token it returns is not a lane, but a lane_connector sometimes.

**Comment by holger-nutonomy** [comment]
I'm not too familiar with the prediction-relevant part of the map, but I guess you could just check whether that token is a lane: `nusc_map.get('lane', token)`
