### ISSUE TITLE
Panorama from multiple images

### ISSUE THREAD

**Issue by cazhang** [nutonomy/nuscenes-devkit#411]
I would like to stitch the images captured by 6 cameras to form a panorama. Do you plan to support this function in the future?
Traditional panorama stitching pipeline relies on homograph estimation and warping. 
But control points between image pairs are not easy to find out.  
Since the camera intrinsic and poses (translation+orientation) are all known, is it possible to take advantage this information?
One issue is that cameras are not rotating around the common centre. Any tips?

**Comment by holger-nutonomy** [comment]
Hi, it would be an interesting tool to have and we would happy to link to it if you develop the code. 
Perhaps the lidar data could even be used to seed your control points?
However, we don't currently have any such plans on our roadmap.
