### ISSUE TITLE
Torch Requirement for nuScenes devkit 

### ISSUE THREAD

**Issue by tianweiy** [nutonomy/nuscenes-devkit#413]
Is the torch >=1.3.1 strict? I think multiple 3D object detection frameworks (det3d, spconv) only works well with torch == 1.1.0. 

Moreover, installing from the pip will install PyTorch 1.5 directly which from my experiences doesn't work well with spconv. and will also mess up other existing packages that depend on the exact torch package (apex, spconv, deformable convolution, det3d, etc..) So that you need to reinstall all other packages.

**Comment by tianweiy** [comment]
I am working on a code release recently and I want to find the easiest way for users to install all packages ...

**Comment by holger-nutonomy** [comment]
I am not sure, but in any case torch is used exclusively for the prediction challenge. So if you are not interested in that, you won't need it at all.

**Comment by tianweiy** [comment]
yeah, i decided to create to forked version of the devkit and remove the torch requirement in the setup file.

**Comment by holger-nutonomy** [comment]
I have been notified that one of my colleagues tried Torch 1.1.0, but there were some conflicts with Pillow, so it may not be straightforward, so it's better to remove those requirements.
In the new version of the devkit we will split the requirements into different files to make it more modular: https://github.com/nutonomy/nuscenes-devkit/tree/nuimages_v0.1/setup/requirements

**Comment by holger-nutonomy** [comment]
FYI, we will remove the torch requirement in https://github.com/nutonomy/nuscenes-devkit/pull/510.
