### ISSUE TITLE
Question about lane token

### ISSUE THREAD

**Issue by LuanDi1996** [nutonomy/nuscenes-devkit#415]
Dear all,

Recently I found a lane token by get_outgoing_ids **ee16b887-bbad-49cc-a786-aa276a4b3265** in Singapore-onenorth, but when I use the map_api, it raised an error
 _/nuscenes/map_expansion/map_api.py", line 525, in get_lane
    raise ValueError(f'Lane token ee16b887-bbad-49cc-a786-aa276a4b3265 is not a valid lane.')_
I wonder if it is something wrong about the map, or I get the wrong version maybe since I have met several similar cases in the full dataset.

I searched this token in singapore-onenorth.json, I found it only had a token( showing that it is the outcoming of some lanes), but no record of this lane token.

Thanks

**Comment by holger-nutonomy** [comment]
@LuanDi1996 Hi. Your observation is correct. We are currently investigating this issue. Apparently there are gaps in the currently released center lines, similar to this figure below.
![one_north_baselines](https://user-images.githubusercontent.com/39502217/84632080-fc019d80-af20-11ea-847b-3f7365b5d530.png)

**Comment by holger-nutonomy** [comment]
@LuanDi1996 Apologies. The previous figure I showed you was wrong. There are no gaps in the relevant parts of our map. 
However, you are right that in there are a few outgoing lanes which don't exist. We will clean this up in the next version of the map to avoid errors.
