### ISSUE TITLE
Questions about prediction of zero boxes

### ISSUE THREAD

**Issue by Tai-Wang** [nutonomy/nuscenes-devkit#416]
Hi, 
Is there any standard form for prediction with zero boxes? For example, one of the forms I have tried is shown below. It seems that it does not work well (the detection_name None can not pass the test in the evaluation).
token:{"sample_token": det["metadata"]["token"], "translation": [0, 0, 0], "size": [0, 0, 0], "rotation": [0, 0, 0, 0], "velocity": [0, 0], "detection_name": None, "detection_score": -1, "attribute_name": None}

**Comment by holger-nutonomy** [comment]
Just leave the list of predictions empty. Here is an example: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/detection/tests/test_algo.py#L229
However, at least one sample must have predictions, otherwise the code returns an errror.
