### ISSUE TITLE
NuScene Error

### ISSUE THREAD

**Issue by kir9-git** [nutonomy/nuscenes-devkit#419]
Hi,

I receive this error while running any of the tutorial as well for any new jupyter book for procesing after installing and initializing the necessary setup requirements as mentioned in the requirements.txt file.
Added the path in the environment variables in Windows 10 also done, still I get the following error:
![ENvironemnt_Variable](https://user-images.githubusercontent.com/38406867/84902048-eaa7c500-b0c9-11ea-8efd-5c7e912c6caf.PNG)

---------------------------------------------------------------------------
ModuleNotFoundError: No module named 'nuscenes.utils'; 'nuscenes' is not a package

**Comment by holger-nutonomy** [comment]
Hi, unfortunately we do not support Windows. Note that you need to edit the PYTHONPATH, not the OS PATH. Try to google how to do that on Windows.

**Comment by kir9-git** [comment]
Thanks, I got it resolved.
