### ISSUE TITLE
some annotations are missing

### ISSUE THREAD

**Issue by sxontheway** [nutonomy/nuscenes-devkit#420]
Hi! I find some annotations are missed, for example in "4cf5d6c3f6ab42aab23f67b5a9782d1a". 
The radar detects the black car in the direct front, but there is no annotation for this object. Maybe more similar cases exist, however, I haven't gone through the dataset.  I personally guess there are two possibilities leads this occasion: 
* the object does not appear in the adjacent key-frames so that the interpolation cannot perform
* the annotation is actually missed 

![1592464346(1)](https://user-images.githubusercontent.com/42286907/84989542-6a8b6900-b176-11ea-822e-01afa057a66c.png)
![1592464363(1)](https://user-images.githubusercontent.com/42286907/84989545-6c552c80-b176-11ea-88b0-438c761ed1ee.png)

**Comment by holger-nutonomy** [comment]
I assume the vehicle did not have any lidar points and was therefore not annotated. Note however, that the annotators are instructed to annotate any object with 1 lidar OR radar point (not both).

**Comment by sxontheway** [comment]
Thanks so much for your response.

**Comment by 184338740** [comment]
How to get the 3D annotation with radar & project to CAM_FRONT image?

**Comment by holger-motional** [comment]
@184338740 Let's discuss in https://github.com/nutonomy/nuscenes-devkit/issues/562
