### ISSUE TITLE
NameError: name 'nusc' is not defined

### ISSUE THREAD

**Issue by eskjorg** [nutonomy/nuscenes-devkit#43]
Bug on the following line?
https://github.com/nutonomy/nuscenes-devkit/blob/f529e4f188c8f86c3d542563436b3d03af8440f7/python-sdk/nuscenes/eval/nuscenes_eval.py#L128

**Comment by holger-nutonomy** [comment]
Yes, that's another bug that has been fixed on branch https://github.com/nutonomy/nuscenes-devkit/commits/release_v0.2. Thanks for backporting it to master.

**Comment by eskjorg** [comment]
I see. I take it that I should work with that branch until it is merged into master.

**Comment by holger-nutonomy** [comment]
There are some incompatible map changes in v0.2 and beyond that will not work with the current teaser data release. I suggest you just patch v0.1 up for now as best as you can and in about two weeks we'll roll out v1.0.
