### ISSUE TITLE
Cannot render a lane found from get_incoming_lane_ids

### ISSUE THREAD

**Issue by TsuTikgiau** [nutonomy/nuscenes-devkit#443]
Hello,
recently I try to render a lane I got as following
`nusc_map = NuScenesMap(dataroot='/path/to/v1.02-train', map_name='singapore-onenorth')`
`sample_lane_record = nusc_map.lane[500]`
`incoming_lane = nusc_map.get_incoming_lane_ids(sample_lane_record['token'])`
`fig, ax = nusc_map.render_record('lane', incoming_lane[0], other_layers=[])`
I got a key error from these commands KeyError: 'b7967676-b5c8-422d-a8ec-ab27bac1e511'
I notice that I can find the record of this token by 
`nusc_map.get_lane('b7967676-b5c8-422d-a8ec-ab27bac1e511')`
but it cannot be found by
`nusc_map.get('lane', 'b7967676-b5c8-422d-a8ec-ab27bac1e511')`
I checked the source code of these 2 functions, and noticed that 'b7967676-b5c8-422d-a8ec-ab27bac1e511' can be found in the nusc_map.json_obj['arcline_path_3'] but not nusc_map.json_obj['lane']. 
I'm a little bit confused since this token should also be a lane. Can anybody tell me what is the difference between 'arcline_path_3' and 'lane', and what is the correct way to render 'b7967676-b5c8-422d-a8ec-ab27bac1e511'? Thank you!

**Comment by holger-nutonomy** [comment]
Yeah, the naming currently is not great. The traditional `lane` is a polygon for the lane. The `get_lane` function returns the arcline path in the center of the `lane`. We'll try to improve this in the future.

**Comment by holger-nutonomy** [comment]
@TsuTikgiau I've revisited this now and realized that `b7967676-b5c8-422d-a8ec-ab27bac1e511` is a lane_connector and not a lane:
```
nusc_map.get('lane_connector', 'b7967676-b5c8-422d-a8ec-ab27bac1e511')  # Works
nusc_map.get('lane', 'b7967676-b5c8-422d-a8ec-ab27bac1e511')  # Error
```
