### ISSUE TITLE
Traffic light

### ISSUE THREAD

**Issue by srikanthmalla** [nutonomy/nuscenes-devkit#444]
Hi,
Does the dataset have traffic light (2D/3D) bounding box and state of the traffic light?

Best Regards,
Srikanth

**Comment by holger-nutonomy** [comment]
Hi. We have the traffic light location in 2d (the height is not reliable) in the map (https://www.nuscenes.org/map-tutorial). You could try to estimate where these are in the images using the ego vehicle pose and orientation, but it won't be accurate.
