### ISSUE TITLE
Get the scene of .bin file and converting from KITTI format

### ISSUE THREAD

**Issue by YoushaaMurhij** [nutonomy/nuscenes-devkit#448]
I want to display the image which is related to a lidar data file. Knowing the bin file how to get the image name or the token?
Is there a way to convert Kitti dataset to this format?

**Comment by holger-nutonomy** [comment]
Take a look at https://www.nuscenes.org/public/images/nuscenes-schema.svg. 
The .bin file corresponds to a sample_data['filename']. From there you can get the sample (keyframe). Then you can use sample['data']['CAM_FRONT'] etc. to retrieve the camera sample_data, which also has a filename. Note that this only works for keyframes. If the .bin file is a non-keyframe (from the sweeps folder), it won't work.

**Comment by YoushaaMurhij** [comment]
Thanks for your response. I will try that!

**Comment by yustaub** [comment]
Hi, sir. Can you transform kitti format result tp nuscenes successfully? @YoushaaMurhij

**Comment by holger-nutonomy** [comment]
In https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_kitti.py you can find a script to convert results between nuScenes and KITTI, but it has a number of limitations since the datasets are quite different.

**Comment by yustaub** [comment]
thanks for your reply!! @holger-nutonomy
