### ISSUE TITLE
How to deal with NaN for CoverNet?

### ISSUE THREAD

**Issue by XHwind** [nutonomy/nuscenes-devkit#450]
As mentioned in #400  and #405, the velocity or acceleration can be NaN due to the first observation. I am wondering how would CoverNet deal with this issue. Did CoverNet set all NaN to 0 or ignore all data with NaN?

**Comment by holger-nutonomy** [comment]
Hi. The user can either 
a) use a padding token (e.g. `-1`),
b) ignore the NaN value and interpolate/extrapolate nearby values, or 
c) discard that sample.
Unfortunately the main author is no longer working for us, so I cannot tell you for sure which strategy was used.

**Comment by XHwind** [comment]
Thanks for answering! Also for strategy (c), is it okay to discard those samples during testing on Val/test splits?

**Comment by holger-nutonomy** [comment]
Hm no, if you want to evaluate your performance against other methods, you need to use all of the samples.
