### ISSUE TITLE
Only support converts nuScenes images from CAM_FRONT to KITTI format??

### ISSUE THREAD

**Issue by cch2016** [nutonomy/nuscenes-devkit#453]
I want to converts all camera image to KITTI format, but when I try `CAM_BACK` images,error:
```
======
Reverse indexing ...
Done reverse indexing in 0.1 seconds.
======
> /data/datasets/nuScences/nuscenes-devkit/python-sdk/nuscenes/scripts/export_kitti.py(153)nuscenes_gt_to_kitti()
-> assert (velo_to_cam_rot.round(0) == np.array([[0, -1, 0], [0, 0, -1], [1, 0, 0]])).all()
(Pdb) velo_to_cam_rot
array([[ 0.94808283,  0.31705002,  0.02486433],
       [ 0.03285883, -0.0198925 , -0.99926202],
       [-0.31632143,  0.94820017, -0.02927763]])
(Pdb) velo_to_cam_rot.round(0)
array([[ 1.,  0.,  0.],
       [ 0., -0., -1.],
       [-0.,  1., -0.]])
(Pdb) n
AssertionError
> /data/datasets/nuScences/nuscenes-devkit/python-sdk/nuscenes/scripts/export_kitti.py(153)nuscenes_gt_to_kitti()
-> assert (velo_to_cam_rot.round(0) == np.array([[0, -1, 0], [0, 0, -1], [1, 0, 0]])).all()
```

**Comment by mumianyuxin** [comment]
Same error. Why `assert (velo_to_cam_rot.round(0) == np.array([[0, -1, 0], [0, 0, -1], [1, 0, 0]])).all()` ?

**Comment by holger-nutonomy** [comment]
KITTI only has front cameras, so it is ambiguous how to encode other cameras.

**Comment by mumianyuxin** [comment]
Thanks for your quick reply. I have another question. Because objects are annotated according to lidar data (The object may appear in any direction of 360°). When only image data is used for nuScenes Detection task, should all 6 cameras in different directions be used for detection? Thanks!

**Comment by holger-nutonomy** [comment]
Yes. In nuScenes we always use all 6 cameras and 360 degree coverage.
Therefore I don't recommend converting the data to KITTI, as you lose a lot of information.
