### ISSUE TITLE
about  `alpha = -10.0` default  in export_kitti.py ??

### ISSUE THREAD

**Issue by cch2016** [nutonomy/nuscenes-devkit#454]
why is `alpha=-10` in all car

**Comment by holger-nutonomy** [comment]
Hi @cch2016. We didn't have a good way to compute the alpha. Hence we set it to a dummy value. According to https://github.com/bostondiditeam/kitti/blob/master/resources/devkit_object/readme.txt#L56 the range is `[-pi..pi]`, so we made sure to use a value outside that range.
