### ISSUE TITLE
Angle Threshold for CoverNet

### ISSUE THREAD

**Issue by XHwind** [nutonomy/nuscenes-devkit#455]
In CoverNet's paper, it mentions

> We select a mode uniformly at random when there are no modes with an angle below the threshold.

I am wondering what is the threshold used for CoverNet or this only applies to the implementation of MTP? Also, does that mean for the loss function, we first filter out all the trajectories in the trajectory sets that have angle difference beyond the threshold and afterward calculate the best match with least L2 distance in the remaining trajectories?
Also I am wondering for the regression loss of CoverNet, does it use L1 smooth loss for positions or angles?

**Comment by emwolff** [comment]
Hi @XHwind . Sorry for the delay in answering your question. Yes, this threshold is only applicable to MTP. For CoverNet, we compute the closest match via point-wise L2 (on x and y position -- no angle or heading). For the regression loss for CoverNet, we use L1 on xy positions.
