### ISSUE TITLE
Can we get NuScene Images in PNG format?

### ISSUE THREAD

**Issue by raviy0807** [nutonomy/nuscenes-devkit#456]
I would like to analyze the impact of image format (jpg, png, bmp etc) on NuScene dataset. For this, is there any way to get png format for the image.

Moreover, **I would like to understand, why  we have use jpg format for nuscene?** Is there any technical reason behind it or just to compress size? I am reading paper, where they studiede change in Object Detection Accuracy based on image format.

@holger-nutonomy @kokseang-aptiv @whyekit-aptiv

**Comment by holger-nutonomy** [comment]
Hi. You can convert the jpg images to any format you like, but we don't have the original raw images anymore and the jpgs went through several stages of compression to limit the dataset size that needs to be downloaded.

**Comment by raviy0807** [comment]
Thanks @holger-nutonomy for quick reply. The direct conversion will not help me. Therefore, I would like to understand the compression stages which were performed.
This information will help me to develop the relevant pipeline for my analysis.

**Comment by holger-nutonomy** [comment]
Unfortunately all I can still retrieve is that we used JPEG quality 80 to compress it.
