### ISSUE TITLE
nuImages CAM_FRONT_RIGHT sweeps download seems to be not available

### ISSUE THREAD

**Issue by MartinHahner88** [nutonomy/nuscenes-devkit#460]
I could neither today nor yesterday download the following file from your servers:
![image](https://user-images.githubusercontent.com/14181188/92093355-8d233a80-edd3-11ea-8bf5-3cd7c58afcce.png)
When I click on the respective link, a wheel is shortly spinning, but then nothing is downloading.
I tried both servers, US and Asia, and tried it on two different browsers (Firefox and Chrome). 
The other downloads are worked fine.

**Comment by holger-nutonomy** [comment]
@MartinHahner88 Thanks a lot for flagging this. Apparently there was a typo in the download link. I've fixed it now, but it may take a few hours until the changes are propagated. Let me know if it does not work by tomorrow.

**Comment by MartinHahner88** [comment]
@holger-nutonomy :+1: 
Download works now. 
Thanks for fixing it so swiftly.
