### ISSUE TITLE
Nuscene lidarSeg:AttributeError: 'NuScenes' object has no attribute 'get_sample_lidarseg_stats'

### ISSUE THREAD

**Issue by chowkamlee81** [nutonomy/nuscenes-devkit#464]
I was folllowing tutorial of nuscene lidarseg and got error below:

AttributeError: 'NuScenes' object has no attribute 'get_sample_lidarseg_stats'

Iam using nuscenes-devkit==1.0.9

Kindly hellp

**Comment by holger-nutonomy** [comment]
Hi. You will need nuscenes-devkit==1.1.0 going forward: https://pypi.org/project/nuscenes-devkit/#history
