### ISSUE TITLE
Missing CAN bus data for some scenes

### ISSUE THREAD

**Issue by yixiao1** [nutonomy/nuscenes-devkit#465]
Hello,

I just found that there are missing CAN bus expansion data for some scenes (for instance, scene-0161 to scene-0168). I would like to know if you missed them when you upload the data, or you do not have these data? 

Cheers,
Yi

**Comment by holger-nutonomy** [comment]
Hi, for some logs we weren't able to extract these due to technical problems or because they used older message formats and were therefore skipped on purpose.
