### ISSUE TITLE
Evluation on specific cameras

### ISSUE THREAD

**Issue by JialianW** [nutonomy/nuscenes-devkit#466]
Dear author,

Appreciate your great dataset! 

Since I only trained my method on two cameras (front and back). May I know how to evaluate the results on the specific camera, e.g., CAM_FRONT&CAM_BACK? Is there any argument that we can manipulate in order to do that?

Thanks!

**Comment by holger-nutonomy** [comment]
Hi, unfortunately we don't directly support that.
If you want to evaluate on the val set (with publicly available annotations), you could modify the functions load_prediction and load_gt in https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/common/loaders.py.

**Comment by machengnan** [comment]
It seems that it is not very easy to make this change, Have you done this succesfully?
