### ISSUE TITLE
How did you do the image ROI cropped?

### ISSUE THREAD

**Issue by yanjanoo** [nutonomy/nuscenes-devkit#468]
Hi,How did you do the image ROI cropped?1600x1200 to 1600x900

**Comment by holger-nutonomy** [comment]
Hi. We remove the top 300 pixels.

**Comment by yanjanoo** [comment]
OK,Thanks.

**Comment by yanjanoo** [comment]
> Hi. We remove the top 300 pixels.

ok,Thanks.
