### ISSUE TITLE
Why the starting annotation is not included for the trajectory prediction challenge?

### ISSUE THREAD

**Issue by XHwind** [nutonomy/nuscenes-devkit#469]
The function [_get_past_or_future_for_agent](https://github.com/nutonomy/nuscenes-devkit/blob/d578e7f294ba4a333b079c4221ac3c9856d58d01/python-sdk/nuscenes/prediction/helper.py#L180) will only return a sequence that does not contain current annotation, which is shown in [__iterate](https://github.com/nutonomy/nuscenes-devkit/blob/d578e7f294ba4a333b079c4221ac3c9856d58d01/python-sdk/nuscenes/prediction/helper.py#L116) function. In other words, the future or past trajectories will not contain the position at the current timestamp. Why would it be in this way? Thank you!

**Comment by holger-nutonomy** [comment]
Hi @XHwind. I think both options (including or excluding the current annotation) have their use-cases. `_get_past_or_future_for_agent` is used in `get_past_for_agent` and `get_future_for_agent`. `get_past_for_agent` is only a convenience method for the user, we don't "use" it. What matters most to us is `get_future_for_agent`, which is used in https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/prediction/compute_metrics.py#L31 as ground-truth to compute the metrics. In this use case the current annotation is not relevant.
