### ISSUE TITLE
How are samples created?

### ISSUE THREAD

**Issue by emanther** [nutonomy/nuscenes-devkit#47]
The documentation doesn't discuss how samples are created. The `nusc` object contains 3,977 samples. Assuming they are taken at 2Hz (the same frequency as the labels, as mentioned in the dataset overview), the total number of seconds in the sample records, as computed in a modified `list_scenes` function, should be equivalent to 3,977 / 2. However, I got `total length: 1931.2375695705414` -> `3862 != 3977`. Here is the modified `list_scenes()` function I used to compute the length. The 13 second overlap as mentioned in #8 is not enough to account for the discrepancy. How are the extra samples created?
 
```python
    def list_scenes(self) -> None:
        """ Lists all scenes with some meta data. """

        def ann_count(record):
            count = 0
            sample = self.nusc.get('sample', record['first_sample_token'])
            while not sample['next'] == "":
                count += len(sample['anns'])
                sample = self.nusc.get('sample', sample['next'])
            return count

        recs = [(self.nusc.get('sample', record['first_sample_token'])['timestamp'], record) for record in
                self.nusc.scene]

        total_length = 0
        for start_time, record in sorted(recs):
            start_time = self.nusc.get('sample', record['first_sample_token'])['timestamp'] / 1000000
            length_time = self.nusc.get('sample', record['last_sample_token'])['timestamp'] / 1000000 - start_time
            location = self.nusc.get('log', record['log_token'])['location']
            total_length += length_time
            desc = record['name'] + ', ' + record['description']
            if len(desc) > 55:
                desc = desc[:51] + "..."

            print('{:16} [{}] {:4.0f}s, {}, #anns:{}'.format(
                desc, datetime.utcfromtimestamp(start_time).strftime('%y-%m-%d %H:%M:%S'),
                length_time, location, ann_count(record)))
        print("total length: {}".format(total_length))
```

**Comment by holger-nutonomy** [comment]
Hi. I agree that the numbers don't exactly match. The logic behind that is very complex. The camera are synced with the lidar to trigger as described in https://www.nuscenes.org/data-collection. Camera is captured at 12Hz, radar at 13Hz, lidar at 20Hz. For every 2Hz keyframe we check if the sensor readings are within a short time window around that keyframe (differs for every sensor, mostly relevant for the radar, which is not synced in time). If any keyframe in a scene is not well synced, we do not include that scene in nuScenes. If the data is synced, the scenes is included, but can have ~39-41 keyframes.

**Comment by emanther** [comment]
Thank you for your prompt response!
