### ISSUE TITLE
Helper methods sometimes return too long trajectories

### ISSUE THREAD

**Issue by igilitschenski** [nutonomy/nuscenes-devkit#472]
Thanks for the great work making all of this freely available! 

While playing around with the dataset and the devkit, I noticed that the helper methods `get_past_for_agent()` and `get_past_for_sample()` return sometimes longer trajectories than expected. Here is an example of reproducing the problem with `get_past_for_agent()`:

```python
import numpy as np
from nuscenes.eval.prediction.splits  import get_prediction_challenge_split
from nuscenes.nuscenes import NuScenes
from nuscenes.prediction import PredictHelper

dataroot = "/YOUR/DATA/ROOT"
nusc = NuScenes(version="v1.0-trainval", verbose=False, dataroot=dataroot)
helper = PredictHelper(nusc)
data_split = get_prediction_challenge_split("train", dataroot=dataroot)

past = list()
for sample in data_split:
    instance_token, sample_token = sample.split("_")
    past.append(helper.get_past_for_agent(
            instance_token, sample_token, seconds=3, 
            in_agent_frame=True))
num_past_timesteps = np.array([traj.shape[0] for traj in past])
np.sum(num_past_timesteps > 6)
```
I would expect each trajectory to have 6 or fewer timesteps (because of looking at most 3 sec into the past). However, for me, the output of the code above is 10. A similar example can be constructed for `get_past_for_sample()`. I use version 1.1.0 of the nuscenes-devkit package with Python 3.7.0 and numpy 1.19.1. I wonder whether I accidentally corrupted my data or am doing otherwise something wrong.

**Comment by emwolff** [comment]
@igilitschenski Thanks for the clear bug report. I can reproduce locally with a clean install of nuscenes from pip. We will investigate further.

**Comment by emwolff** [comment]
Note that `get_future_for_agent` appears to work as expected.

**Comment by igilitschenski** [comment]
Yes, `get_future_for_sample` seems also not to be affected.

**Comment by igilitschenski** [comment]
Yes, solves it for me. Thanks for super-fast fixing!

**Comment by emwolff** [comment]
Fixed in https://github.com/nutonomy/nuscenes-devkit/pull/475
