### ISSUE TITLE
Where are the IMU calibration parameters?

### ISSUE THREAD

**Issue by anyong298** [nutonomy/nuscenes-devkit#481]
To process the IMU data, we need the IMU calibration parameters. Where can I find it?

**Comment by holger-nutonomy** [comment]
Hi. What type of calibration parameters are you looking for? The extrinsics are given by the ego_pose translation of the vehicle.

**Comment by pwais** [comment]
is `ego_pose` derived from the raw IMU?  doesn't it include adjustment from the (unpublished?) localization system? (as mentioned here https://forum.nuscenes.org/t/detail-about-radar-data/173 and in the original paper https://arxiv.org/pdf/1903.11027.pdf )

similar question: are the lidar clouds de-warped due to ego-motion?

**Comment by holger-nutonomy** [comment]
Yes, the ego pose is in the IMU coordinate frame.
The localization system is primarily based on lidar, but uses the same IMU frame as a reference.
Yes, the lidar pointclouds are de-warped with said ego poses. You can see that from the visualizations, which do not look like ellipsoids, even when moving fast: https://www.nuscenes.org/nuscenes?tutorial=nuscenes

**Comment by pwais** [comment]
👍  ok just to be clear: the raw IMU / GPS data isn't available (like it is in KITTI), just the localized pose, correct?  thank you!

**Comment by holger-nutonomy** [comment]
We do provide the raw IMU data:
https://www.nuscenes.org/nuscenes?tutorial=can-bus
(linear_accel, q, rotation_rate)

However, we don't use GPS here, which does not work well in urban environments.

**Comment by ray401** [comment]
@holger-motional 
I want to know what is the imu coordinate?

for example, in can_bus/scene-0001_ms_imu file, the "rotation rate" value and "linear_accel" , what coordinate system is the value in ?

or in your settings, what is the navigation frame and body frame ?
Thanks in advance,
