### ISSUE TITLE
How to uninstall nuscenes-devikit?

### ISSUE THREAD

**Issue by gardenbaby** [nutonomy/nuscenes-devkit#482]
Hi Team, 

I installed nuscenes-devikit by the command `pip install nuscenes-devikit` and found that it changed the original torch version. So I intended to reinstall the old version of torch and uninstall the nuscenes-devikit.

However, when I tried to uninstall it by `pip uninstall nuscenes-devikit` the warning `WARNING: Skipping nuscenes-devikit as it is not installed.` popped out and the uninstallation was skipped.

How can it be fixed, thanks.

**Comment by holger-nutonomy** [comment]
Hi. You did the right thing, but I assume you were in the wrong environment. Did you do `conda activate nuscenes` before? In general, this is not a question specific to the devkit, but a general pip question.

**Comment by gardenbaby** [comment]
> Hi. You did the right thing, but I assume you were in the wrong environment. Did you do `conda activate nuscenes` before? In general, this is not a question specific to the devkit, but a general pip question.

Thank you. 

I didn't create an environment specifically for nuscenes-devkit but installed it in another one.

So the right thing to do is to create a specific environment for this devkit and remove the environment when it is not needed.

**Comment by holger-nutonomy** [comment]
Yes. That workflow is generally recommended in Python, as any package will come with its own set of dependencies.

**Comment by holger-nutonomy** [comment]
FYI, we will remove the torch requirement in https://github.com/nutonomy/nuscenes-devkit/pull/510.
