### ISSUE TITLE
[Motion Forecasting]Getting social context without rendering image.

### ISSUE THREAD

**Issue by felipecode** [nutonomy/nuscenes-devkit#484]
Hello is there a easy way to get social features a given agent without requiring rasterizing the scene ?

For example, lets say i get a given instance and sample token for a scene
"045cd82a77a1472499e8c15100cb5ff3_6bfd42cf0aba4f1a94ec11fa43e2dd92"
I know this is an specific sample for a vehicle instance.

How can I get all the other vehicles/objects that are in this same instant that is represented
by the sample token 6bfd42cf0aba4f1a94ec11fa43e2dd92 ? Do I need to search ? That would be
pretty inefficient and might require restructuring the data.

**Comment by holger-nutonomy** [comment]
Hi, please take a look at the nuScenes schema: https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/schema_nuscenes.md
sample_annotation points directly to sample, so this one is particularly easy.
You just get all sample_annotations for the current sample.
If you want to do this efficiently, I suggest you create a dictionary that for every sample_token maps to the list of sample_annotation_tokens in the same sample. You can create the list in O(n) and then every lookup is O(1).
