### ISSUE TITLE
how to transform ego pose to KITTI-style 

### ISSUE THREAD

**Issue by somebodyus** [nutonomy/nuscenes-devkit#486]
I am currently use the following code from `export_kitti.py` to get the lidar pose with respect to the world:
```
lid_to_ego = transform_matrix(cs_record_lid["translation"], Quaternion(cs_record_lid["rotation"]), inverse=False)
lid_ego_to_world = transform_matrix(ego_record_lid["translation"], Quaternion(ego_record_lid["rotation"]), inverse=False)
lid_to_world = np.dot(lid_ego_to_world, lid_to_ego)
```
and save the KITTI style lidar using the code:
```
kitti_to_nu_lidar = Quaternion(axis=(0, 0, 1), angle=np.pi / 2)
kitti_to_nu_lidar_inv = kitti_to_nu_lidar.inverse
pcl = LidarPointCloud.from_file(src_lid_path)
pcl.rotate(kitti_to_nu_lidar_inv.rotation_matrix)  # In KITTI lidar frame.
with open(dst_lid_path, "w") as lid_file:
        pcl.points.T.tofile(lid_file)
```
However, I cannot merge the lidar point clouds using the pose to a local map. But if I delete `pcl.rotate(kitti_to_nu_lidar_inv.rotation_matrix) `, the merge is perfect. I know there must need some processing on the `lid_to_world `. Could anyone tell me how to do?

I have tried the follow solutions, but all of them do not work.
`lid_to_world = np.dot(lid_ego_to_world, np.dot(kitti_to_nu_lidar.transformation_matrix, lid_to_ego))
`
`lid_to_world = np.dot(lid_ego_to_world, np.dot(kitti_to_nu_lidar_inv.transformation_matrix, lid_to_ego))
`
`lid_to_world = np.dot(lid_ego_to_world, np.dot(lid_to_ego,kitti_to_nu_lidar.transformation_matrix))
`
`lid_to_world = np.dot(lid_ego_to_world, np.dot(lid_to_ego,kitti_to_nu_lidar_inv.transformation_matrix))
`
I also tried the following, they also do not work
`lid_to_world = np.dot(lid_to_world, kitti_to_nu_lidar_inv.transformation_matrix)
`
`lid_to_world = np.dot(lid_to_world, kitti_to_nu_lidar.transformation_matrix)
`

Could anyone help me？

**Comment by somebodyus** [comment]
`lid_to_world = np.dot(lid_ego_to_world, np.dot(lid_to_ego,kitti_to_nu_lidar.transformation_matrix)) ` is correct.
Problem solved.

**Comment by holger-nutonomy** [comment]
Glad you managed to solve the problem.
