### ISSUE TITLE
How to understand the global coordinates?

### ISSUE THREAD

**Issue by guiyuliu** [nutonomy/nuscenes-devkit#487]
hello, I'm not familiar with coordinates calibration.
I see two parameters,  sensor2ego, ego2global,   I want to know what is the origin of global coordinates？
 I see the tranlation between global to lidar is about  400，500,...   is it measured in  meters?
 how to calibrate between ego and global ?

**Comment by holger-nutonomy** [comment]
Yes, they are meters on one of the 4 maps. You can see them rendered at https://www.nuscenes.org/nuscenes#data-collection .
Ego depends on the rotation and translation. I suggest you follow the code in https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py to try to understand better what we are doing.

**Comment by guiyuliu** [comment]
> Yes, they are meters on one of the 4 maps. You can see them rendered at https://www.nuscenes.org/nuscenes#data-collection .
> Ego depends on the rotation and translation. I suggest you follow the code in https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py to try to understand better what we are doing.

I know ego2global means the translation and rotation  between ego and global , if ego means car itself,   i want to know what is global ?

**Comment by holger-nutonomy** [comment]
Ego vehicle: The self-driving car, more exactly the center of the rear axle projected to the ground.
Global: See https://github.com/nutonomy/nuscenes-devkit/issues/56#issuecomment-471137287

**Comment by rockywind** [comment]
Hi, 
What’s the global coordinates definition? 
What's the X, Y and Z's orientation of global coordinates?

**Comment by whyekit-motional** [comment]
@rockywind pls see https://github.com/nutonomy/nuscenes-devkit/issues/687#issuecomment-970109514

**Comment by northeastsquare** [comment]
@whyekit-motional  @holger-motional  the question "how to calibrate between ego and global ?", have not answered, thank you

**Comment by whyekit-motional** [comment]
@northeastsquare an example of the transformation from ego frame to global frame can be found here: https://github.com/nutonomy/nuscenes-devkit/blob/9b165b1018a64623b65c17b64f3c9dd746040f36/python-sdk/nuscenes/nuscenes.py#L887-L890

**Comment by northeastsquare** [comment]
@whyekit-motional  Thank you for reply! I know use rotation and translation matrix to do it. But how to calibrate between ego and global? I mean how do you got the rotation and translation matrix? If use gps and IMU, but gps location error is several meters.

**Comment by whyekit-motional** [comment]
@northeastsquare this discussion might be useful for you: https://github.com/nutonomy/nuscenes-devkit/issues/481
