### ISSUE TITLE
Radars and Camera Specs

### ISSUE THREAD

**Issue by M-Hammod** [nutonomy/nuscenes-devkit#49]
Hi, 

Could you please share the following specification:
1- Radars Vertical and horizontal resolution and FOV
2- Cameras FOV

Best Regards,

**Comment by holger-nutonomy** [comment]
Hi, please have a look at: https://www.nuscenes.org/data-collection Some of the specifications can be found there, e.g. the camera FOVs are 70 degrees, except for the back camera which is 110 degrees.
The radar horizontal FOV is `-9.0°...+9.0° far range, -60°...+60° near range`, the vertical FOV is `14° far range, 20° near range `. If you need more detailed information, please contact us at: nuScenes@nuTonomy.com

**Comment by M-Hammod** [comment]
Awesome, thank you so much
