### ISSUE TITLE
Question: Getting incoming and outgoing lines for lane/road dividers

### ISSUE THREAD

**Issue by JeevanjotS** [nutonomy/nuscenes-devkit#490]
Hi,
I am interested in extracting the lane markings(which divide 2 lanes) from the map. I looked at the tutorial and the map files, and could not figure out a good way to get predecessor/successor for a lane divider or a road divider. Is there some way to extract this from the map files?

**Comment by holger-nutonomy** [comment]
Hi. Please refer to the maps tutorial. Note that at some point we added the arcline path and connectivity of lanes. These are very easy to work with. From the tutorial "You can also explore the connectivity of the lanes, with the get_outgoing_lanes and get_incoming_lane methods.".
