### ISSUE TITLE
how to get the distance？

### ISSUE THREAD

**Issue by hufangjian** [nutonomy/nuscenes-devkit#492]
hi, Thank you for your efforts. how can i get  the distance of object from the datasets,thanks!

**Comment by holger-nutonomy** [comment]
Just get the object annotations with this method: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L239
Then you can compute the Euclidean distance in 2d or 3d between (0, 0, 0) and the box center.
