### ISSUE TITLE
Invalid lane token

### ISSUE THREAD

**Issue by JeevanjotS** [nutonomy/nuscenes-devkit#493]
Hi, 
I came across the lane with token 8f23d3ed-1089-4fcf-a178-a174abc69938, which is part of the lane dictionary in singapore-hollandvillage, but when I try to do : lane_record = nusc_map.get_lane(way['token']), it returns a "not a valid lane" error. I manually checked that this lane is infact present in the map files, under lane, but not in arcline_path_3. This is the cause of this error message.

**Comment by holger-nutonomy** [comment]
@JeevanjotS I can confirm that for hollandvillage one entry is missing in arcline_path_3:
```
assert len(nusc_map.arcline_path_3) == len(nusc_map.lane) + len(nusc_map.lane_connector) # Fails
```
We will look into this more and see what we can do. For now you will need to code a workaround.

**Comment by holger-nutonomy** [comment]
@JeevanjotS We are removing the faulty lane in map expansion v1.3, which should be released today.
