### ISSUE TITLE
About torch version

### ISSUE THREAD

**Issue by yustaub** [nutonomy/nuscenes-devkit#494]
Hi, sir. I am using nuscenes dataset, and I can only use pytorch 1.1.0 at most, but in the requirements.txt, it requires torch>=1.3.1, does nuscenes-devkit support torch 1.1.0? Very appreciate for your reply.

**Comment by holger-nutonomy** [comment]
We haven't tested it, but it only affects a tiny part of the code used for the prediction task. If you don't use that, you may even uncomment the dependency entirely. We will likely remove the torch requirement soon (except for those that do prediction).

**Comment by yustaub** [comment]
thanks for your reply!!

**Comment by holger-nutonomy** [comment]
FYI, we will remove the torch requirement in https://github.com/nutonomy/nuscenes-devkit/pull/510.
