### ISSUE TITLE
How to evaluate on a specific scene?

### ISSUE THREAD

**Issue by alanwanga** [nutonomy/nuscenes-devkit#499]
Hi, thanks for the nice work.

(1) I'd like to draw the PR curve of a specific scene instead of all the spilt set.

<img width="613" alt="Screen Shot 2020-11-16 at 9 40 33 AM" src="https://user-images.githubusercontent.com/3997703/99209277-c594bb00-27fd-11eb-8ab1-dd2b41e9c219.png">

I have an idea to restrict the sample token in [load_prediction](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/common/loaders.py#L47) and [load_gt](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/common/loaders.py#L97), but not sure if it's the best approach.

(2) What should I do if I also want to run the detection/evaluate.py on the tracking_result to draw the PR curve? I think first  is to change the tracking_name to detection_name in the json file.

(3) Is it possible to evaluate the result only with metadata? Or it's necessary to download all the pointcloud binary and images.

Best,

**Comment by holger-nutonomy** [comment]
Hi,
1) Yes, that is a good idea. Note that the selected scene may be missing certain classes and therefore class-averaged metrics may fluctuate a lot.
2) You will need detection_name, detection_score and attribute_name. The latter can be dummy values, in which case some metrics will be lower, but mAP will still be the same.
3) It is possible, you just need to set plot_examples to 0: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/detection/evaluate.py#L275

**Comment by alanwanga** [comment]
Thanks for a quick reply.

For 2, I set the detection_name to be same as tracking_name, detection_score to be same as tracking_score, attribute_name to be vehicle_moving in the tracking_result, and run the detection/evaluate.py on the json file. Some errors pop up, any hints?

<img width="803" alt="Screen Shot 2020-11-16 at 10 27 42 PM" src="https://user-images.githubusercontent.com/3997703/99264490-7da48100-285b-11eb-8875-2bd7aa8042b5.png">

Best,

**Comment by holger-nutonomy** [comment]
@alanwanga This error seems to indicate that you forgot the detection_name for one box.
Also note that some classes are not allowed in tracking, e.g. cones and barriers.
Please compare these two pages in detail:
https://www.nuscenes.org/object-detection
https://www.nuscenes.org/tracking

**Comment by machengnan** [comment]
> Hi, thanks for the nice work.
> 
> (1) I'd like to draw the PR curve of a specific scene instead of all the spilt set.
> 
> <img alt="Screen Shot 2020-11-16 at 9 40 33 AM" width="613" src="https://user-images.githubusercontent.com/3997703/99209277-c594bb00-27fd-11eb-8ab1-dd2b41e9c219.png">
> 
> I have an idea to restrict the sample token in [load_prediction](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/common/loaders.py#L47) and [load_gt](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/common/loaders.py#L97), but not sure if it's the best approach.
> 
> (2) What should I do if I also want to run the detection/evaluate.py on the tracking_result to draw the PR curve? I think first is to change the tracking_name to detection_name in the json file.
> 
> (3) Is it possible to evaluate the result only with metadata? Or it's necessary to download all the pointcloud binary and images.
> 
> Best,

For 1, It seems that it is a little bit difficult to change the  load_prediction and load_gt code to specify the scene, have you done it?  If done, can you share the code? Thanks~
