### ISSUE TITLE
How to get the ground truth poses (trajectory).

### ISSUE THREAD

**Issue by ashesknight** [nutonomy/nuscenes-devkit#502]
Hi, thank you for your hard work.

I want to design some visual odometry experiments by using the lidar data provided by the nuScenes dataset. But I don't know how to use your toolkit to abtain the ground truth poses. And I want these poses to be in the same format as the KITTI odometry dataset. Please help me, thank you very much.

In the KITTI odometry dataset, the ground  truth pose is represented in the file as a single row:
`r11 r12 r13 tx r21 r22 r23 ty r31 r32 r33 tz`

**Comment by holger-nutonomy** [comment]
Hi. Please run this file:
https://github.com/nutonomy/nuscenes-devkit/blob/13879c564d9f1d7919ae6b1ed2b623030d5decfe/python-sdk/nuscenes/scripts/export_kitti.py
It will output the nuScenes data in KITTI format.

**Comment by bjajoh** [comment]
In case anyone is looking for a pose converter in the future, here is correctly working one. https://github.com/PRBonn/lidar_transfer/blob/main/auxiliary/convert/nuscenes2kitti.py
However, be aware that the coordinates of  are not correct.
