### ISSUE TITLE
File "nuscenes-devkit/python-sdk/nuscenes/eval/detection/evaluate.py", line 45 nusc: NuScenes,

### ISSUE THREAD

**Issue by vincentzhouwenqi** [nutonomy/nuscenes-devkit#506]
File "tools/nuscenes-devkit/python-sdk/nuscenes/eval/detection/evaluate.py", line 45
 nusc: NuScenes,
        ^
SyntaxError: invalid syntax

How to fix this problem

**Comment by vincentzhouwenqi** [comment]
"^" is under ":"

**Comment by emwolff** [comment]
Please check that you are using Python 3.5 or later. Type hints were introduced then: https://docs.python.org/3/library/typing.html
