### ISSUE TITLE
how can i get  Camera extrinsics?

### ISSUE THREAD

**Issue by hufangjian** [nutonomy/nuscenes-devkit#507]
run  
nusc.get('calibrated_sensor',cam_front_data['calibrated_sensor_token'])

{'camera_intrinsic': [[1266.417203046554, 0.0, 816.2670197447984],
  [0.0, 1266.417203046554, 491.50706579294757],
  [0.0, 0.0, 1.0]],
 'rotation': [0.4998015430569128,
  -0.5030316162024876,
  0.4997798114386805,
  -0.49737083824542755],
 'sensor_token': '725903f5b62f56118f4094b46a4470d8',
 'token': '1d31c729b073425e8e0202c5c6e66ee1',
 'translation': [1.70079118954, 0.0159456324149, 1.51095763913]}

Is 'rotation' and 'translation'  are Camera extrinsics?
I know that
R 3X3 C 3x1 matrix? how can i get them?

**Comment by holger-nutonomy** [comment]
Please see this conversation: https://github.com/nutonomy/nuscenes-devkit/issues/501
At http://kieranwynn.github.io/pyquaternion/#accessing-matrix-form you can see how to get the rotation matrix from the quaternion.
