### ISSUE TITLE
Questions about 3D Radar information

### ISSUE THREAD

**Issue by MMMHT** [nutonomy/nuscenes-devkit#511]
Hi, My question is that does 3D Radar information available in nuscenes?
In the tutorials, only 2D Radar map is available, is there any way we can obtain a 3D point cloud from Radar?
![image](https://user-images.githubusercontent.com/12952034/101162904-e9655700-366d-11eb-9066-ec8a676fe622.png)

Any help will be appreciated!

**Comment by holger-nutonomy** [comment]
Hi, it may seem like the data is 3d, but the height dimension is always set to 0. It is a 2d radar.
