### ISSUE TITLE
Contributing script to generate videos from annotations

### ISSUE THREAD

**Issue by EricWiener** [nutonomy/nuscenes-devkit#512]
I created a script that generates videos for instances of objects across a scene. I created it to generate data for a project on detecting brake and turn signals from vehicles. Here's the Github [repo](https://github.com/EricWiener/nuscenes-instance-videos). Is there any use in merging this into the scripts folder?

**Comment by holger-nutonomy** [comment]
Hi. The script looks nice. Perhaps you could create a Pull Request with only generate_videos.py in https://github.com/nutonomy/nuscenes-devkit/tree/master/python-sdk/nuscenes/scripts? You could add yourself as an author in that file and link to your repo for more information.
