### ISSUE TITLE
the intensity of point cloud in.pcb.bin file

### ISSUE THREAD

**Issue by yustaub** [nutonomy/nuscenes-devkit#515]
I read some the .pcb.bin files and find that the 4th col (intensity)  maximum is 255.0, the minimum is -94.988, compared to kitti that intensity is range from (0,1), does the intensity matter? Very appreciate for your reply!

**Comment by holger-nutonomy** [comment]
Hi. Since you and I don't know the exact mapping from the sensor to these values, I think it does not matter. KITTI uses a different lidar model, so I doubt that the mapping between the intensity distributions would be linear.

**Comment by yustaub** [comment]
Sorry for my late reply. I will ignore the intensity value.
