### ISSUE TITLE
List of ordered sample tokens of specific scene?

### ISSUE THREAD

**Issue by aydoo** [nutonomy/nuscenes-devkit#517]
A scene object has attributes `nbr_samples`, `first_sample_token` and `last_sample_token`. To access e.g. sample 15 (< `nbr_samples`), currently I iterate over the `next` sample tokens (starting at `first_sample_token`) 15 times, which requires linear time, assuming access is constant. Is there a way to see all (ordered) sample tokens linked to a scene? So I can just access the 15th one directly. Similar to how each sample has an attribute `anns` which is a list of `sample_annotation_token`s to see all annotations linked to that specific sample.

**Comment by holger-nutonomy** [comment]
Hi. You are right that it is currently somewhat inefficient. I suggest you run through all of the scenes and samples once to create an index. Then looking it up will be very fast.
