### ISSUE TITLE
Generate depth map using multi-frame measurements

### ISSUE THREAD

**Issue by kunw-18** [nutonomy/nuscenes-devkit#518]
Hello nuScenes Team,

Thanks for the excellent work.  I am trying to generate depth map for evaluation using offered _map_pointcloud_to_image_ function with Lidar measurement. However, the result seems very sparse using only keyframe measurement. And I think apply multi-frame scans, like kitti, may be a advisable way to increase the depth density. But I don't know how to perform it. Can you provide me with some advices? Thank you.

**Comment by holger-nutonomy** [comment]
Hi. We have a convenience method `from_file_multisweep` in https://github.com/nutonomy/nuscenes-devkit/blob/568762bdb507bf3fc3d7c028e1a6074208aa7675/python-sdk/nuscenes/utils/data_classes.py#L56 , which handles loading of multiple sweeps. For an example how to use it, see https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L1155 . Then you should be able to simply use your existing method.
