### ISSUE TITLE
Question about the point cloud and 3D box anno of ground truth

### ISSUE THREAD

**Issue by yustaub** [nutonomy/nuscenes-devkit#519]
Hi, sir. I visualize the point cloud and 3d bboxes using the method in tutorial, and there is a question about the 3D bboxes,
![Figure_1](https://user-images.githubusercontent.com/40256410/102300360-c604ab00-3f8f-11eb-8b2d-04d34c8779b1.png)
![test](https://user-images.githubusercontent.com/40256410/102300373-c9983200-3f8f-11eb-9c0f-2413205073a7.jpg)
on the left of the pic, there should not exist point cloud behind the black car because of the occlusion , why there are some boxes behind the black car, it confused me a lot. Vert appreciate for your reply!

**Comment by holger-nutonomy** [comment]
It is called parallax. The lidar is on located higher on the car than the cameras, therefore it sees "more", including some points behind the vehicle.

**Comment by yustaub** [comment]
so there are some point cloud on the behinded vehicle and they just "covered" on the image by the points that closer to ego car. @holger-nutonomy
