### ISSUE TITLE
Key error while rendering lane

### ISSUE THREAD

**Issue by harmanpreet93** [nutonomy/nuscenes-devkit#522]
I'm trying to render a lane on the Boston NuScenes map. But I'm getting the following error. Could you please help me understand why? 

```
from nuscenes.map_expansion.map_api import NuScenesMap
nusc_map = NuScenesMap(dataroot=DATAROOT, map_name='boston-seaport')

x_test, y_test = 654.6341469166431, 1605.5431136242184
closest_lane = nusc_map.get_closest_lane(x_test, y_test, radius=100) # returns: '101a5b41-3d93-442f-9229-31b97c410669'
nusc_map.render_record("lane", closest_lane);
```

Error: 
```
KeyError: '101a5b41-3d93-442f-9229-31b97c410669'
```

The rendering works for `x_test, y_test = 673.9613133067386, 1620.9530475461518` though, which is a nearby point.

**Comment by holger-nutonomy** [comment]
`get_closest_lane` returns a `lane` or `lane_connector`. Can you check if it's a `lane_connector` ?
