### ISSUE TITLE
question about convert quaternion to yaw

### ISSUE THREAD

**Issue by yustaub** [nutonomy/nuscenes-devkit#523]
Hi, sir. I have got 3D bbox in nuscenes lidar coords and transform it to kitti lidar coords by [kitti_to_nu_lidar_inv](https://github.com/nutonomy/nuscenes-devkit/blob/568762bdb507bf3fc3d7c028e1a6074208aa7675/python-sdk/nuscenes/utils/kitti.py#L139), and get **box_lidar_kitti**:
![微信图片_20201218163231](https://user-images.githubusercontent.com/40256410/102592688-c8613380-414e-11eb-9c0d-09c8b3d627e4.png)
and I want to use nuscenes data in kitti lidar coordinate system to train some 3D detection model which don't support nuscenes dataset, but I have no idea about converting quaternion to yaw; In [box_to_string](https://github.com/nutonomy/nuscenes-devkit/blob/60ce73af095fa84f1a4943e352ea9ae2714a3149/python-sdk/nuscenes/utils/kitti.py#L399), it converts quaternion to yaw in kitti image frame, and how to convert quaternion to yaw in kitti lidar frame? Can I use [quaternion_yaw](https://github.com/nutonomy/nuscenes-devkit/blob/60ce73af095fa84f1a4943e352ea9ae2714a3149/python-sdk/nuscenes/eval/common/utils.py#L112)? Appreciate for your reply!

**Comment by holger-nutonomy** [comment]
Please check
https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_kitti.py#L305

and specifically
https://github.com/nutonomy/nuscenes-devkit/blob/568762bdb507bf3fc3d7c028e1a6074208aa7675/python-sdk/nuscenes/utils/kitti.py#L314

**Comment by yustaub** [comment]
thanks for your quick reply! but I can not figure out what it means `quat_box = Quaternion(axis=(0, 1, 0), angle=yaw_camera) * Quaternion(axis=(1, 0, 0), angle=np.pi/2)`, and still have no idea about convert quaternion to yaw in kitti lidar coordiante system. Can you share some advice? @holger-nutonomy

**Comment by holger-nutonomy** [comment]
The first part `Quaternion(axis=(0, 1, 0), angle=yaw_camera)` is the standard definition of yaw in nuScenes. We rotate around the vertical (y) axis by yaw degrees. The second part is the conversion from KITTI to nuScenes - a rotation of 90 degrees around the x axis. Understanding the different coordinate systems is often tricky, but it is very easy to just try out the different options and visualize the result. E.g. there are only 6 possible 90 degree rotations (around an axis), 2 for each axis, so you can just try each.

**Comment by yustaub** [comment]
Thank you, sir. sorry for my late reply, I will try it.

**Comment by yustaub** [comment]
Hello,
I understand that quaternion to yaw in nuscenes lidar coordinate system: `v = np.dot(q.rotation_matrix, np.array([1, 0, 0]))
        yaw = np.arctan2(v[1], v[0])`, I convert nuscenes lidar data to kitti lidar coordinates system and it is **x front, y left, z up**, about its converting quaternion to yaw, should be `yaw = np.arctan2(v[0],-v[1])`? Very appreciate for your reply. @holger-nutonomy

**Comment by holger-nutonomy** [comment]
Unfortunately I don't remember the conventions of KITTI and don't have it installed to run some checks. You can see our conventions at https://www.nuscenes.org/public/images/data.png .

**Comment by yustaub** [comment]
There is another question that about quaternion condused me. kitti_to_nu_lidar = Quaternion(axis=(0, 0, 1), angle=np.pi / 2), as I known that in kitti, its lidar coordinate system is :  **x front, y left, z up**, and in nuscenes, its lidar coordinate system is :  **x right, y front, z up**, kitti_to_nu_lidar is rotate pi/2 around z axis, according to right-handed, x front will turn to x left, does the z axis point down?

**Comment by holger-nutonomy** [comment]
You can see whether z points up or down in https://www.nuscenes.org/public/images/data.png.
The circle with an X means downwards, the circle with a dot means upwards.
**x right, y front, z up** is correct for nuScenes.
KITTI: For your right hand, point the thumb forward, index finger left, middle finger up. 
Go to nuScenes: rotate your hand by 90 degrees clockwise around the middle finger.

**Comment by yustaub** [comment]
from [wiki](https://en.wikipedia.org/wiki/Right-hand_rule), right hand rule is **For right-handed coordinates the right thumb points along the Z axis in the positive direction and the curl of the fingers represents a motion from the first or X axis to the second or Y axis. When viewed from the top or Z axis the system is counter-clockwise.**, what I know about right hand rule is also this, and z is up in kitti lidar and nuscenes lidar, follow the right hand rule, **x front z up** in kitti lidar will turn to **x left** which is just opposite from **x right** in nuscenes, it confused me. If there are some errors, please tell me. Thanks!

**Comment by Petros626** [comment]
@yustaub did you succeed?
