### ISSUE TITLE
how to convert 3d box in lidar frame to image frame

### ISSUE THREAD

**Issue by Joseph-pt** [nutonomy/nuscenes-devkit#524]
Hi, I get the detection 3D box result in lidar coordinate system, I want to visualize the result in image, but have no code to refer to. How can I get the visualization result in image? Thanks.

**Comment by holger-nutonomy** [comment]
Hi. We don't provide such methods for the detection results, but for the ground-truth you can see the code at https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L1279 . Then you will need to adapt it to your boxes.

**Comment by Joseph-pt** [comment]
Hi. I have read the code you mentioned [https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L1279](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L1279), it provides box in camera coordinates, that is also what I want to get. And I follow [map_pointcloud_to_image](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L740) want to convert box in lidar to box in image plane and there are some error in **Third step: transform from global into the ego vehicle frame for the timestamp of the image** and **Fourth step: transform from ego into the camera**, how can I convert box correctly? thanks for your help!

**Comment by holger-nutonomy** [comment]
Yes, just copy that code and adapt t to the detection results.

**Comment by Joseph-pt** [comment]
hello, sir. I have converted it successfully! Thanks! @holger-nutonomy

**Comment by holger-nutonomy** [comment]
Great!

**Comment by jiaminglei-lei** [comment]
@Joseph-pt hello, I got the same trouble. could you share your code? or tell me how to finish this transformation. thank you.

**Comment by Petros626** [comment]
@Joseph-pt ?
