### ISSUE TITLE
Transform coordinates

### ISSUE THREAD

**Issue by Romansp12** [nutonomy/nuscenes-devkit#528]
Hello
I have implemented the tracking algorithm using only lidar data. At the output, I get a bounding box in lidar coordinates. And the sample annotation data, as I understand it, is given in some other coordinates, then to run your code by counting (https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/tracking/evaluate.py). How do I transform the coordinates of the bounding box so that we can start calculating metrics later?

**Comment by NMertsch** [comment]
There are multiple coordinate systems involved:
The sensor data (i.e. the `LidarPointCloud`) is centered around the lidar sensor.
The sensor pose with respect to the vehicle is stored in the `calibrated_sensor` of the `sample_data`.
The vehicle pose in absolute/map coordinates is stored in the `ego_pose` of the `sample_data`.

To transform a pointcloud from one coordinate system to the next (given by `pose`), you can use this:
```python
from pyquaternion.quaternion import Quaternion
from nuscenes.utils.geometry_utils import transform_matrix
pointcloud.transform(transform_matrix(pose["translation"], Quaternion(pose["rotation"])))
```

Note that `pointcloud.transform` transforms the points of the `PointCloud` object in-place.

**Comment by holger-nutonomy** [comment]
@NMertsch is correct.
