### ISSUE TITLE
Traffic Light Static Layer

### ISSUE THREAD

**Issue by govvijaycal** [nutonomy/nuscenes-devkit#529]
Hello,

I was trying out the prediction tutorial notebook with the following choice of layers for the static layer rasterizer:
static_layer_rasterizer = StaticLayerRasterizer(helper, layer_names=['ped_crossing', 'traffic_light'])

I looked at every 1000th instance in the training dataset and never saw any of the traffic lights, only the pedestrian crossings.

Is this because traffic lights are relatively rare in the dataset and only appear at a limited number of intersections, or is the traffic light layer not really annotated for the semantic map?  If the former, is there a good sample/instance token I could try out?

Also, am I correct in understanding that only the locations of the traffic lights are available, not their dynamic light state?

Thanks for the help!

**Comment by govvijaycal** [comment]
I took another look and it seems like None is returned for the geometry mask corresponding to traffic lights (if I'm understanding the Map API correctly).

https://github.com/nutonomy/nuscenes-devkit/blob/cee29523b8136692d98ae16fedd91b578f1164c9/python-sdk/nuscenes/map_expansion/map_api.py#L1926

So in that case, my understanding is that the traffic light support is not available for either the location (static) or light state (dynamic) cases.  Is this right?

**Comment by holger-nutonomy** [comment]
Hi @govvijaycal. We generally don't support traffic light states, as our map is entirely static.
Let's look at the definition of a traffic light:
```
  "traffic_light": [
    {
      "token": "00590fed-3542-4c20-9927-f822134be5fc",
      "line_token": "5bffb006-bce8-44a4-a466-5580f1d748fd",
      "traffic_light_type": "VERTICAL",
      "from_road_block_token": "71c79c48-819c-4b17-ad28-2a9e82ba1596",
      "items": [
      ....
```
You can see that the geometry is a line (line_token). Hence it is omitted when creating the polygon mask.
