### ISSUE TITLE
How to get the information like velocity of ego agent?

### ISSUE THREAD

**Issue by jingleFun** [nutonomy/nuscenes-devkit#531]
Hi, nuScenes provides a function to get the information of agent like below :
`print(f"Velocity: {helper.get_velocity_for_agent(instance_token_2, sample_token_2)}\n")`

But how can I get the instance_token of ego agent? Or is there any other function I can use to get the information like velocity and acceleration of the ego agent?

Thank you very much!

**Comment by NMertsch** [comment]
As far as I know, there is no such token.

`helper.get_velocity_for_agent(...)` uses the function `helper.velocity`:
```python
def velocity(current: Dict[str, Any], prev: Dict[str, Any], time_diff: float) -> float:
    """
    Helper function to compute velocity between sample annotations.
    :param current: Sample annotation record for the current timestamp.
    :param prev: Sample annotation record for the previous time stamp.
    :param time_diff: How much time has elapsed between the records.
    """
    diff = (np.array(current['translation']) - np.array(prev['translation'])) / time_diff
    return np.linalg.norm(diff[:2])
```

You can use `ego_pose`s as `current` and `prev`. The `time_diff` can be obtained from `sample_data['timestamp']`s, which is in milliseconds.

**Comment by holger-nutonomy** [comment]
@NMertsch is correct. The ego is not considered an "instance". Only other agents are instances. For ego velocity there are two approaches:
- Use nuscenes.py's `box_velocity`, but adapt it to the ego vehicle. Note that this is based on 2Hz keyframes and therefore very smooth.
- Work with the CAN bus data: https://www.nuscenes.org/nuscenes?tutorial=can-bus
-

**Comment by jingleFun** [comment]
@NMertsch, @holger-nutonomy, Thanks for your reply.
