### ISSUE TITLE
Why are the RCS values of some radar points negative?

### ISSUE THREAD

**Issue by ramdrop** [nutonomy/nuscenes-devkit#532]
According to [Radar cross-section](https://en.wikipedia.org/wiki/Radar_cross-section), RCS has units of area (meters squared). But why are some RCS values of radar points negative?
Here is an example on how to get a negative rcs value of a radar point. I did it by following the official tutorial:
```
from nuscenes import NuScenes
from nuscenes.utils.data_classes import RadarPointCloud
import os.path as osp

dataset = 'D:/Data/aDataset/nuScenes/data_mini'
nusc = NuScenes(version='v1.0-mini', dataroot=dataset, verbose=True)

my_scene = nusc.scene[0]

first_sample_token = my_scene['first_sample_token']
my_sample = nusc.get('sample', first_sample_token)

sensor = 'RADAR_FRONT'
my_radar_data = nusc.get('sample_data', my_sample['data'][sensor])

pcl_path = osp.join(dataset, my_radar_data['filename'])
pc = RadarPointCloud.from_file(pcl_path)
points = pc.points
```
![rcs_field](https://user-images.githubusercontent.com/73425467/103438015-1c2b4c80-4c26-11eb-91ef-703787aa337e.png)
![negative_rcs](https://user-images.githubusercontent.com/73425467/103438016-1c2b4c80-4c26-11eb-8042-6a5e5272fca3.png)

**Comment by holger-nutonomy** [comment]
Hi @ramdrop. Did you find the answer?

**Comment by ramdrop** [comment]
Hi, I found a reasonable explanation: the value in the dataset is RCS in dBsm, and RCS in dBsm = 10*log (RCS in m2 ). Am I right?

**Comment by holger-nutonomy** [comment]
Yes. Here is my earlier answer to a similar question (which is not visible to the public): 
The unit for radar cross section is typically given in dBsm (decibels referenced to a square meter). Due to the log in decibels, the values can indeed be negative. In this case they are in [-64, +64] I believe.

**Comment by ramdrop** [comment]
I see. Thank you Holger.
