### ISSUE TITLE
Non-keyframe detections for tracking?

### ISSUE THREAD

**Issue by aydoo** [nutonomy/nuscenes-devkit#537]
Hello, the (optional) detections (_Megvii_, _PointPillars_, _Mapillary_) that you offer for the tracking challenge only seem to cover samples/keyframes. I'm aware these were provided by third parties, but do you happen to also have detections for the non-keyframes and could make them available? Using only keyframe detections seems like an unneccesary handicap for tracking :D. But thank you for offering detections in the first place!

**Comment by holger-nutonomy** [comment]
Hi. Unfortunately we don't have the intermediate frame detections :-(.
You could work with the Det3D repo (Megvii, PointPillars, https://github.com/poodarchu/Det3D) or MMDetection3D (PointPillars, 40+ papers, https://github.com/open-mmlab/mmdetection3d). As it is 3d object detection at 2 Hz, interpolation should work pretty well. However, higher frame rate detections may still provide more confidence.

**Comment by aydoo** [comment]
Thanks for the response and suggestions. So consequently for the 3 baseline trackers (e.g. *Megvii-AB3DMOT*) listed in the scoreboard only keyframe detections were used?

**Comment by holger-nutonomy** [comment]
Hi. We didn't write the AB3DMOT code, but I would recommend to *run* the tracker on the full frame rate, but *compute the loss* on the 2Hz keyframes with ground-truth annotations. In the same way the inference runs on the full frame rate, but you only submits results for the keyframes.
