### ISSUE TITLE
Dynamic and hybrid trajectories for CoverNet

### ISSUE THREAD

**Issue by hobincar** [nutonomy/nuscenes-devkit#539]
Hello. Thank you for releasing the codes of various prediction models including CoverNet.

I saw that you also released the fixed trajectory sets for epsilon=2,4,8 in [the previous issue](https://github.com/nutonomy/nuscenes-devkit/issues/346). But I'd like to use the dynamic and hybrid trajectory sets and also the fixed sets for other epsilon values (the best-reported epsilon was 3 for the case of the fixed trajectory set, but only those for 2, 4, and 8 are released). Can you release those trajectory sets? I would more appreciate it even more if you release the code for generating the sets. Thanks in advance!

**Comment by emwolff** [comment]
@hobincar Thanks for the interest. We currently are not planning on releasing additional trajectory sets or the generation code. If you want to create your own sets, you can follow the greedy algorithm from the CoverNet paper and subsample from (say) the set of all training trajectories.
