### ISSUE TITLE
Would it be possible to use data formatting tools?

### ISSUE THREAD

**Issue by EricWiener** [nutonomy/nuscenes-devkit#544]
Hi,

I'm currently working with the University of Michigan's Autonomous Boat team (UM::Autonomy) and we are planning to use the nuscenes-devkit to work with our data (with some modifications to support our environment). I was wondering if there were any scripts available for creating the JSON data files (either from ROS bags or any other format). If not, I already started implementing some and would be happy to contribute them to the nuscenes-devkit once they are finished.

Thanks so much,
Eric

**Comment by liqi17thu** [comment]
It would be nice if the formatting tools can split the training and validation set according to https://github.com/nutonomy/nuscenes-devkit/issues/316#issuecomment-594319345!

**Comment by holger-nutonomy** [comment]
Hi. That's a very cool application! Which format exactly are you thinking of? There is code for [KITTI](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_kitti.py) and [COCO](https://github.com/open-mmlab/mmdetection3d/tree/master/configs/nuimages). We don't currently have ROS support. Note that each of these conversions loses a lot of information, so they are only workarounds. 
If you come up with something that has the potential to help the community, we'd be happy to integrate it.

**Comment by EricWiener** [comment]
@holger-nutonomy thanks for the response! I was planning on having the data be imported from folders similarly to how nuScenes structures its data (having sweeps and keyframes with sub-folders for each sensor). This way it wouldn't be ROS specific, and tools could be made to convert from a variety of formats into the uniform import format. I will definitely keep you posted as we make more progress on it.

**Comment by holger-nutonomy** [comment]
Thanks. Depending on how complex this gets, it will probably better to have an entirely separate repository, maybe "nuScenesROS" ? We should only add it to the core codebase if it is 1 or 2 files. We'd still be happy to spread the word about your work.
