### ISSUE TITLE
The orientation of car using Quaternion

### ISSUE THREAD

**Issue by liqi17thu** [nutonomy/nuscenes-devkit#545]
I am wondering how to get the orientation of the car using the rotation of the ego pose. Specifically, I want to get the map mask of the car using API  `nusc_map.render_map_mask` but I don't know how to set patch_angle so the map is in the same direction as the car (from the first one to the second one).

![image](https://user-images.githubusercontent.com/48043983/105331228-2a113380-5c0e-11eb-9e38-750eda44a907.png)

![image](https://user-images.githubusercontent.com/48043983/105331174-1d8cdb00-5c0e-11eb-917b-15e8378d4a15.png)

**Comment by holger-nutonomy** [comment]
Hi,

here is the code:
```
from pyquaternion import Quaternion

from nuscenes.nuscenes import NuScenes
from nuscenes.eval.common.utils import quaternion_yaw
from nuscenes.map_expansion.map_api import NuScenesMap

nusc = NuScenes(version='v1.0-mini', verbose=False)
sample = nusc.sample[70]  # Pick any sample
scene = nusc.get('scene', sample['scene_token'])
log = nusc.get('log', scene['log_token'])
nusc_map = NuScenesMap(dataroot='/data/sets/nuscenes', map_name=log['location'])

sample_data = nusc.get('sample_data', sample['data']['LIDAR_TOP'])
ego_pose = nusc.get('ego_pose', sample_data['ego_pose_token'])
translation = ego_pose['translation']
rotation = Quaternion(ego_pose['rotation'])
yaw = quaternion_yaw(rotation) / np.pi * 180
patch_box = (translation[0], translation[1], 80, 80)
patch_angle = yaw
layer_names = ['drivable_area']
canvas_size = (patch_box[2], patch_box[3])
fig, ax = nusc_map.render_map_mask(patch_box, patch_angle, layer_names, canvas_size, figsize=figsize, n_row=1)
```
As we can see, this looks like our other rendering methods:
![render](https://user-images.githubusercontent.com/39502217/105656343-f2033c80-5efc-11eb-850f-ac590939f1e3.png)
