### ISSUE TITLE
 AssertionError: Please use the category.json that comes with nuScenes-lidarseg, and not the old category.json.

### ISSUE THREAD

**Issue by tobimichigan** [nutonomy/nuscenes-devkit#547]
Hi there, 

I reproduced the setup of nuscenes dev kit and after setting up the initial algorithm, I encountered the following errors:

`======
Loading NuScenes tables for version v1.0-mini...
Loading nuScenes-lidarseg...

---------------------------------------------------------------------------

AssertionError                            Traceback (most recent call last)

<ipython-input-7-bba4e6dc39b3> in <module>()
      3 from nuscenes import NuScenes
      4 
----> 5 nusc = NuScenes(version='v1.0-mini', dataroot='/content/data/sets/nuscenes', verbose=True)

/usr/local/lib/python3.6/dist-packages/nuscenes/nuscenes.py in __init__(self, version, dataroot, verbose, map_resolution)
    100                 # Check that the category records contain both the keys 'name' and 'index'.
    101                 assert 'index' in lidarseg_category.keys(), \
--> 102                     'Please use the category.json that comes with nuScenes-lidarseg, and not the old category.json.'
    103 
    104                 self.lidarseg_idx2name_mapping[lidarseg_category['index']] = lidarseg_category['name']

AssertionError: Please use the category.json that comes with nuScenes-lidarseg, and not the old category.json.

`

Any pointers as to why this is happening?

**Comment by liqi17thu** [comment]
It seems that you can just follow the instruction to download the lidarseg dataset and replace the old category.json.

**Comment by holger-nutonomy** [comment]
Yes, please download nuScenes-lidarseg from https://www.nuscenes.org/download

**Comment by holger-nutonomy** [comment]
Note, you must have copied over the `lidarseg.json` (and other files). I assume you simply did not overwrite the existing files, which is necessary.
