### ISSUE TITLE
Body Frame Convention

### ISSUE THREAD

**Issue by ke-sun** [nutonomy/nuscenes-devkit#548]
First, thanks a lot for providing the dataset and the tools.

There may a bit inconsistency in the body frame convention between the dataset and the prediction tools.
Based on the calibration files, the data are recorded with the x-axis of the body frame aligned with the heading of the car.
In the prediction tools, y-axis of the body frame is aligned with the heading of the car (such as `get_future_for_agent`)
https://github.com/nutonomy/nuscenes-devkit/blob/5325d1b400950f777cd701bdd5e30a9d57d2eaa8/python-sdk/nuscenes/prediction/helper.py#L214
Although it's not a big issue, it can easily lead to confusions and possibly errors. 
Just want to point this out. It would be great if it can be fixed later.

**Comment by holger-nutonomy** [comment]
As far as I can tell, https://github.com/nutonomy/nuscenes-devkit/blob/5325d1b400950f777cd701bdd5e30a9d57d2eaa8/python-sdk/nuscenes/prediction/helper.py#L182 is using x and y from the sample_annotation. According to https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/schema_nuscenes.md#sample_annotation the sample_annotation is stored in *global coordinates*. So they are independent of the car heading.

**Comment by ke-sun** [comment]
The functions `get_future_for_agent` provides an option `in_agent_frame`.
It transforms the coordinates of the future path into the current body frame of the agent.
In Sec.2 of the prediction tutorial, it says
"The agent's coordinate frame is centered on the agent's current location and the agent's heading is aligned with the positive y axis."

**Comment by holger-nutonomy** [comment]
Okay, that's different. I assume the prediction team prefers to operate in the lidar-like coordinate system (https://www.nuscenes.org/public/images/data.png).
