### ISSUE TITLE
2D bounding box

### ISSUE THREAD

**Issue by bertoni9** [nutonomy/nuscenes-devkit#55]
Hello, 
Do you provide a 2D bounding box of the detected objects (xy coordinates in pixels)?
 I saw that _view points_ in _geometry utils.py_ allows to project the corners of the 3d bounding box into the image plane. However, projecting those corners (e.g all the 8 corners or only the frontal ones) does not match exactly a 2D bounding box, depending on the position of the instance in the image. 

Thank you

**Comment by holger-nutonomy** [comment]
Hi, you are correct that the 3D bounding boxes in nuScenes can be projected to the image. From those you *could* compute a 2d box, but this box would not be perfectly tight. I suggest you try to estimate the 3d geometry of the object (e.g. from images) to evaluate it in 3d space.
