### ISSUE TITLE
LiDAR for nuImages

### ISSUE THREAD

**Issue by Divadi** [nutonomy/nuscenes-devkit#550]
Hello, I was wondering if there were any LiDAR sweeps available for the nuImages frames, and if there were any correspondences between nuImages frames and any frames annotated with 3D boxes in nuScenes?

Thank you.

**Comment by holger-nutonomy** [comment]
Hi @Divadi. Unfortunately nuImages does not provide any lidar data. The overlap of logs between nuImages and nuScenes is negligible and we made sure that none are in the test set of the other. Furthermore, even if two logs overlap, the chance of even just one image being included in both datasets is very small. So you can assume they are non-overlapping.

Log: 10-20 minutes = 30-60 possible scenes
Scene: 20s, about 1440 images
