### ISSUE TITLE
Evaluation in KITTI format 

### ISSUE THREAD

**Issue by deepmeng** [nutonomy/nuscenes-devkit#551]
I converted the Nuscenes annotations to the KITTI label format by 'export_kitti.py'. To test the [KITTI eval kit](https://github.com/prclibo/kitti_eval) and the 'new KITTI labels', when I evaluated the ground truth with the ground truth by KITTI eval kit, the following result was returned.  Do you have any ideas?

```
car_detection AP: 0.027176 0.025802 0.025802
pedestrian_detection AP: 0.022784 0.022150 0.022150
bicycle_detection AP: 0.000000 0.000000 0.000000
car_detection_ground AP: 0.024155 0.022471 0.022471
pedestrian_detection_ground AP: 0.000000 0.000000 0.000000
bicycle_detection_ground AP: 0.000000 0.000000 0.000000
Eval 3D bounding boxes
car_detection_3d AP: 0.006540 0.005825 0.005825
pedestrian_detection_3d AP: 0.000000 0.000000 0.000000
bicycle_detection_3d AP: 0.000000 0.000000 0.000000
```

**Comment by deepmeng** [comment]
solved

**Comment by deeptibhegde** [comment]
Hi, how did you solve this?

**Comment by ZhangYu1ing** [comment]
Hi, may I ask how did you solve this? Where should I check? Thanks~

**Comment by holger-motional** [comment]
It does not seem like this is an issue with nuScenes, but rather with the user's code.

**Comment by Petros626** [comment]
@deepmeng enlighten the community, instead of keeping it for you.
