### ISSUE TITLE
line rendering support for render_map_in_image.

### ISSUE THREAD

**Issue by liqi17thu** [nutonomy/nuscenes-devkit#552]
I am wondering why we can't render line layers in the first view image?
https://github.com/nutonomy/nuscenes-devkit/blob/5325d1b400950f777cd701bdd5e30a9d57d2eaa8/python-sdk/nuscenes/map_expansion/map_api.py#L1083-L1085

**Comment by holger-nutonomy** [comment]
Hi. I suppose you could modify the code to render lines, but it would make it a bit more complicated. For aesthetic reasons we decided not to include lines, as our goal was to figure out for each pixel which layer it falls into.
