### ISSUE TITLE
Why lidar_points[1,:] is not as per the image size, while using "(lidar_points, coloring , image)=NuScenesExplorer.map_pointcloud_to_image(...)"

### ISSUE THREAD

**Issue by rrklearn2020** [nutonomy/nuscenes-devkit#554]
By using the depths, with  render_intensity=False, and show_lidarseg=False, in 'map_pointcloud_to_image' as per 
https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L805; works good, except for the Y values. for example, the Y values are in the range of 198 to 898. 

![image](https://user-images.githubusercontent.com/70491128/107247706-8f7f6580-69ff-11eb-9c15-457ede55f777.png)

But with an image dimension of 1600x 900 and using 'map_pointcloud_to_image'; as per my understanding the Y values should in the range of 0 to 899.  Please correct me if I am wrong. or how to map the 198 to 898 Y-values in lidar point to 0 to 899 in image plane?
Note: X values are correctly mapped with the range of 1 to 1595, for lidar with same image size.

**Comment by holger-nutonomy** [comment]
Hi. Strange, if you take a look at https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L899, the following should work out of the box:
```
        points, coloring, im = self.map_pointcloud_to_image(pointsensor_token, camera_token,
                                                            render_intensity=render_intensity,
                                                            show_lidarseg=show_lidarseg,
                                                            filter_lidarseg_labels=filter_lidarseg_labels,
                                                            lidarseg_preds_bin_path=lidarseg_preds_bin_path)
        ax.imshow(im)
        ax.scatter(points[0, :], points[1, :], c=coloring, s=dot_size)
```
Please try and compare if you did anything different.
