### ISSUE TITLE
What is the purpose of lane_connector in the dataset?

### ISSUE THREAD

**Issue by JeevanjotS** [nutonomy/nuscenes-devkit#555]
Hi all,

I am trying to get a sequence of connected lanes, but I see get_outgoing_lane_ids() also returns lane_connectors. Lane_connectors are also polygons it seems, but I don't see any visualization in the tutorial notebook. Could you explain why we have lane_connectors in the dataset, and how I can visualize them, preferably in a Bird's Eye view image?

**Comment by holger-nutonomy** [comment]
Hi. The lane connectors were added for the prediction challenge. They are parametrized lines that connect valid combinations of lanes at an intersection. They are not polygons. As in the tutorial, you can use `nusc_map.render_centerlines(resolution_meters=0.5, figsize=1, bitmap=bitmap)` to render both the lanes (center line) and lane connectors. These can be used for navigation.
