### ISSUE TITLE
Does "field2token()" return a ordered list?

### ISSUE THREAD

**Issue by huzjkevin** [nutonomy/nuscenes-devkit#556]
The method "field2token()" gives me the convenience to retrieve the records according to some criterion. For example:
```
instance = nusc.instance[0]:
ann_tokens = nusc.field2token("sample_annotation", "instance_token", instance["token"]
```
This will give me a list of annotation tokens for me to retrieve the annotation data. However, is this list ordered? What I mean by "ordered" is that the first element in the list refers to the first annotation of the instance, and the second refers to the second annotation, and so on... 

If it is not ordered, is there any way I can get the sequence of annotations of a particular instance that is temporally ordered?

**Comment by holger-nutonomy** [comment]
Hi. As you can see in https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L218, the output of field2token is in the same order as the dataset table. However, while most tables are sorted chronologically/temporally, you should not generally assume this. E.g. there could be two vehicles driving at the same time. It is better to use the `next` pointers in `sample` / `sample_data` / `sample_annotation` (see the [schema](https://www.nuscenes.org/public/images/nuscenes-schema.svg)).
