### ISSUE TITLE
Some questions about nuscenes/eval/prediction/splits.py

### ISSUE THREAD

**Issue by hobincar** [nutonomy/nuscenes-devkit#558]
Hi. I'm confused about the meanings of some lines.

Specifically,
1. In [line 24-27](https://github.com/nutonomy/nuscenes-devkit/blob/7222ced569e75c68e79dab8a31d05190bf813119/python-sdk/nuscenes/eval/prediction/splits.py#L24-L27), why do we use 'train' split when we want 'train_val' split? As far as I can understand, we should merge the 'train' and the 'val' split for the 'train_val' split.
2. In [line 34-37](https://github.com/nutonomy/nuscenes-devkit/blob/7222ced569e75c68e79dab8a31d05190bf813119/python-sdk/nuscenes/eval/prediction/splits.py#L34-L37), what is the meaning of NUM_IN_TRAIN_VAL? For the 'train' split, why do we use the first 200 scenes and exclude the last 150 scenes? Why 'train_val' split does not contain the 'train' split?

Thanks in advance :)

**Comment by pmlakner** [comment]
Just to add to this, the file 'prediction_scenes.json' on [line 29](https://github.com/nutonomy/nuscenes-devkit/blob/7222ced569e75c68e79dab8a31d05190bf813119/python-sdk/nuscenes/eval/prediction/splits.py#L29) seems to be missing from the dataset.

**Comment by holger-nutonomy** [comment]
@hobincar Good question. @emwolff any ideas?
@pmlakner Please download the map expansion, which contains that file.

**Comment by iyuner** [comment]
I also share the same doubt. Any idea?

> Hi. I'm confused about the meanings of some lines.
> 
> Specifically,
> 
> 1. In [line 24-27](https://github.com/nutonomy/nuscenes-devkit/blob/7222ced569e75c68e79dab8a31d05190bf813119/python-sdk/nuscenes/eval/prediction/splits.py#L24-L27), why do we use 'train' split when we want 'train_val' split? As far as I can understand, we should merge the 'train' and the 'val' split for the 'train_val' split.
> 2. In [line 34-37](https://github.com/nutonomy/nuscenes-devkit/blob/7222ced569e75c68e79dab8a31d05190bf813119/python-sdk/nuscenes/eval/prediction/splits.py#L34-L37), what is the meaning of NUM_IN_TRAIN_VAL? For the 'train' split, why do we use the first 200 scenes and exclude the last 150 scenes? Why 'train_val' split does not contain the 'train' split?
> 
> Thanks in advance :)

**Comment by whyekit-motional** [comment]
@iyuner do try reaching out to @emwolff
