### ISSUE TITLE
nuImages: Unable to render non-keyframe images

### ISSUE THREAD

**Issue by nobutoba** [nutonomy/nuscenes-devkit#559]
There seems to be a small bug in `nuimages.py`, for which non-keyframe images cannot be rendered:

https://github.com/nutonomy/nuscenes-devkit/blob/5325d1b400950f777cd701bdd5e30a9d57d2eaa8/python-sdk/nuimages/nuimages.py#L642-L643

The condition within the `assert` statement should be negated as follows:

```python
if not sample_data['is_key_frame']: 
     assert annotation_type == 'none', 'Error: Cannot render annotations for non keyframes!' 
 ```

I hope it will be fixed in a future release:+1:

**Comment by holger-motional** [comment]
Thanks. Problem should be fixed now.
