### ISSUE TITLE
How to get the 3D annotation by radar & project to CAM_FRONT image?

### ISSUE THREAD

**Issue by 184338740** [nutonomy/nuscenes-devkit#562]
For missing in lidar points but appearing in radar,  how to get the 3D-annotations by radar & project to CAM_FRONT 2D-image?

**Comment by holger-motional** [comment]
You can use `render_pointcloud_in_image` (https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L496) to project points to 2d.
Furthermore every `sample_annotation` has fields `num_lidar_pts` and `num_radar_pts`. So you can check that num_lidar_pts = 0 and num_radar_pts != 0.
