### ISSUE TITLE
Evaluate sub-set of samples using evaluate.py

### ISSUE THREAD

**Issue by deeptibhegde** [nutonomy/nuscenes-devkit#563]
I converted a certain number of samples into KITTI format using the `nuscenes_gt_to_kitti` function in **export_kitti.py** and generated predictions. I converted those predictions to Nuscenes format using the `kitti_res_to_nuscenes` function in **export_kitti.py** and saved it into a submissions json file. 

When I attempt to evaluate this file suing **evaluate.py**, I get the error 

`AssertionError: Samples in split doesn't match samples in predictions.
`

I understand it is because I am missing all the files in the `train` `val` or `train_detect` splits. Is there any way to evaluate on only the samples I have?

**Comment by holger-motional** [comment]
Hi. On the evaluation server that is not possible as you could use it to reconstruct the results. However, if you evaluate locally on the val set, you could modify the code in a few places (e.g. https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/common/loaders.py#L54) to only load the samples you desire.

**Comment by deeptibhegde** [comment]
Ah, yes apologies that is right. One more question, is there a way to select the samples for loading by the file name of the samples I have in my val folder? Can I get a hint about where to make that change in https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/common/loaders.py#L54 ?

**Comment by holger-motional** [comment]
Take a look at https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/splits.py, which tells you which log / scene is in which split.

**Comment by deeptibhegde** [comment]
Well there are many more files in the val split than the 150 or so listed in the splits.py file, correct? Also, is there a code to map the filename (e.g. 0a3de46504504b028132df207871842a.bin) to the scene name?

**Comment by holger-motional** [comment]
Try to familiarize yourself with the [nuScenes schema](https://www.nuscenes.org/public/images/nuscenes-schema.svg) and work through the provided [tutorials](https://www.nuscenes.org/nuscenes?tutorial=nuscenes). You can map from logs to scenes to samples to sample_data, which are your "files".
