### ISSUE TITLE
[Question] How to get the translation and rotation matrix between two lidar consecutive frames?

### ISSUE THREAD

**Issue by YoushaaMurhij** [nutonomy/nuscenes-devkit#564]
I want to overlap two consecutive  point clouds.  I need to write the translation and rotation matrix  for that. Can you please suggest me fast way to do that?
it is enough to provide 2d overlap (not considering the z axiz or projecting all the points to xy plane)

**Comment by holger-motional** [comment]
Hi. This is not a well-defined question because the two consecutive pointclouds will have subtle differences. That said, if they are sufficiently similar you should be able to use https://en.wikipedia.org/wiki/Iterative_closest_point.

**Comment by YoushaaMurhij** [comment]
Well, thanks for your response! I want to use the vehicle odometry to get the translation and rotation matrix of the vehicle between two frames. Can you refer to the part of code that can help me with that?

**Comment by holger-motional** [comment]
Take a look at the schema: https://www.nuscenes.org/public/images/nuscenes-schema.svg
Given a `sample`, you can get the `sample_data` of the LIDAR_TOP, then retrieve the `ego_pose` and it's `translation` / `rotation` (in global coordinates). From the `sample_data` you can also use `next` to jump to the consecutive pointcloud and ego get `ego_pose` and `translation` / `rotation`. Now you compare these.
