### ISSUE TITLE
Direction of Travel

### ISSUE THREAD

**Issue by semirelezovikj** [nutonomy/nuscenes-devkit#569]
I am able to tell whether agents are moving in opposite directions, however I am not able to determine how to get in which direction a given agent is headed. 

In the image below, I would like to determine the agent that is "in-front-of" the ego-agent (in red). However, that is relative to the direction in which the car is headed (does y coordinate increase as agent moves forward or decrease). The same would apply for left and right agents. 

P.S: This is not an issue, but a discussion. I don't see a "Discussion" tab in this repo - may be a good idea. 

![direction-of-travel](https://user-images.githubusercontent.com/1392807/111239975-b0c00c80-85d0-11eb-8824-95e611ba7d05.png)

**Comment by emwolff** [comment]
@semirelezovikj Sorry for the delay.

We don't have any specific code to do that computation. Here are a couple of options.

1. Do a geometric check based on the relative heading. Note that this could be misleading in the scenario above.
```
dx, dy = other_x - ego_x, other_y - ego_y
angle = atan2(dy, dx)
relative_angle = principal_value(angle - ego.heading)   # wrap it to (say) [-pi, pi)
if -0.5 * pi <= relative_angle <= 0.5* pi:
  other is in front
```

2. Use the lane geometry of the ego for the check.
Do something like `get_closest_lane` https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/map_expansion/map_api.py#L575 and then query for future lanes. Extract the lane centerlines (arcline paths) and compute the distance of each other track to the arcline path ahead of the ego by `project_pose_to_lane` https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/map_expansion/arcline_path_utils.py#L221 or similar.

Do these suggestions make sense for your problem? Contributions here are welcomed.
