### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by guo-pu** [nutonomy/nuscenes-devkit#570]
Is there a version that supports Python3.5?

**Comment by holger-motional** [comment]
Hi. We haven't tried, but I suppose most features should work. Could you try and report any errors here?

**Comment by guo-pu** [comment]
@holger-motional Thank you for your reply. I installed nuscenes-devkit in the Python 3.5 development environment and found that it could not be installed. The installation command is
` pip install nuscenes-devkit`

**Comment by holger-motional** [comment]
Could you try using the source code directly? Once you report that it works, we can modify the pip package to enable 3.5.

**Comment by guo-pu** [comment]
Thanks, I'll try it.

**Comment by holger-motional** [comment]
Let us know if it works.
