### ISSUE TITLE
Setting Camera parameters in OpenGL format

### ISSUE THREAD

**Issue by micaeltchapmi** [nutonomy/nuscenes-devkit#571]
Hi,

Thanks for this great dataset. I would like to render a pointcloud using Pyrender but I'm not sure how to set the camera parameters. Pyrender uses the Opengl format (+x points right, +y points up and +z points backward). Looking at the cameras in your [dataset](https://www.nuscenes.org/nuscenes#overview), +x points right, +y points down and +z points forward. Here are a few things I would like to understand.

1. To convert the camera translation to opengl format, I multiply the y and z values by -1. Is that right?
2. Given that the camera parameters are given with respect to egoframe, that means the lidar points I would like to project need to be in the egoframe before I can project using the given camera parameters right?

Some context:
I extracted the pointcloud in the egoframe (after the third stage in [map_pointcloud_to_image](https://github.com/nutonomy/nuscenes-devkit/blob/60ce73af095fa84f1a4943e352ea9ae2714a3149/python-sdk/nuscenes/nuscenes.py#L740)), cropped it using the 3d bbox to obtain the pointcloud for a single person and then turned it to a mesh using trimesh's convex_hull function. I then set the camera parameters(translation, rotation(converted to rotation matrix using Quaternion(rotation).rotation_matrix), camera intrinsics(fx,fy,cx,cy) in pyrender's [Intrinsic Camera](https://github.com/mmatl/pyrender/blob/dd6dbd895aada77f33975cedaad039ac58811ea4/pyrender/camera.py#L313) but the mesh is not in the camera's view in the scene.

3. Should the rotation matrix be transposed or not when projecting in pyrender? Your projection code uses the transposed rotation matrix.  
4. Is there anything I'm missing or anything else I should consider when projecting in a different system like Pyrender?

I will really appreciate your help with this.

Thank you.

**Comment by holger-motional** [comment]
**Hi. What are you trying to achieve? You are trying to render 3d meshes of pedestrians from the camera view? That sounds pretty cool, let us know of the results :-).

1. To convert the camera translation to opengl format, I multiply the y and z values by -1. Is that right?

Try to model the 3 axis with your first 3 fingers and go from one coordinate frame to the other. I don't think -1 does the job, you should rotate by 90 degrees around the x axis.

2. Given that the camera parameters are given with respect to egoframe, that means the lidar points I would like to project need to be in the egoframe before I can project using the given camera parameters right?

You should be able to copy that from https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L285.

3. Should the rotation matrix be transposed or not when projecting in pyrender? Your projection code uses the transposed rotation matrix.

I don't see a transpose in the [projection](https://github.com/nutonomy/nuscenes-devkit/blob/9b209638ef3dee6d0cdc5ac700c493747f5b35fe/python-sdk/nuscenes/utils/geometry_utils.py#L18). The only projection is in the transformations between the coordinate frames. An instructive example are the 4 paragraphs [here](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L782). For a rotation matrix the transpose corresponds to the inverse.** 

4. Is there anything I'm missing or anything else I should consider when projecting in a different system like Pyrender?

I would try to keep everything in nuScenes coordinate frames until the very last render step. This way you avoid confusion.
