### ISSUE TITLE
detection baseline

### ISSUE THREAD

**Issue by vobecant** [nutonomy/nuscenes-devkit#572]
Dear authors,

thank you very much for this dataset. I have read the accompanying paper where you mention a baseline model based on OFT model and others based on MonoDis and SSD+3D. I tried to search for it here but I haven't found it.  Do you provide it? If not, would it be possible to provide it?

I also noticed that in https://github.com/nutonomy/nuscenes-devkit/tree/master/python-sdk/nuscenes/eval/tracking#baselines , you provide a baseline detections from Mapillary but it contains only the actual detections and not the model or the code. Would it please be possible to get these?

Thank you very much in advance.

Best regards,
Antonin.

**Comment by holger-motional** [comment]
Hi. 
- For OFT the authors never published results on nuScenes. We only re-implemented it internally, but did not publish that codebase. Similarly for SSD+3D
-  For MonoDIS we got the predictions straight from the authors. I don't think they published the results.
