### ISSUE TITLE
Scenes in v1.0-trainval01_blobs

### ISSUE THREAD

**Issue by ngowilliam1** [nutonomy/nuscenes-devkit#573]
Is there any simple method to find out the scenes present in v1.0-trainval01_blobs.tgz?

I am aware of the splits.py file which indicates the samples present each of the train/val/test splits, but due to hardware constraints I am not able to download all the 850 scenes.

Would the v1.0-trainval01_blobs contain the scenes from 0001-0102 since scenes 0077-0091 are present in the test set?
![image](https://user-images.githubusercontent.com/46735044/111808646-945ef100-88aa-11eb-8c28-e49fbf729830.png)

**Comment by holger-motional** [comment]
Hi. the first archive contains the first 85 scenes, the second archive contains the next 85 scenes and so on. Just note that the naming of the scenes is not 1...1000, but 1...1200 (?) with some gaps.
