### ISSUE TITLE
export_kitti.py nuscenes_gt_to_kitti multi sweep 

### ISSUE THREAD

**Issue by donghyung87** [nutonomy/nuscenes-devkit#579]
I am going to convert nuscenes dataset to kitti data format and conduct a simple test, but the given code alone has some problems. It produces only ~30000 points. So I want to use multisweep to do this. 

I changed your code like below, but the code is not working well.

`            pcl, dum = LidarPointCloud.from_file_multisweep(self.nusc,sample,"LIDAR_TOP","LIDAR_TOP",nsweeps=10)
            pcl.rotate(kitti_to_nu_lidar_inv.rotation_matrix)  # In KITTI lidar frame.`

But this can not produce accurate point cloud bin file.

Please tell me the correct way to use Multisweep in nuscenes_gt_to_kitti.

**Comment by holger-motional** [comment]
Hi. 
- Why do you think the 30k points are a problem? Did you compare to the original file to check if any points are missing?
- How do you know that the multisweep output is not accurate? Also take a look at https://forum.nuscenes.org/t/fusing-lidar-sweeps-with-keyframe/533/7 . Maybe it's the same problem?
