### ISSUE TITLE
Converting nuscenes into kitti format?

### ISSUE THREAD

**Issue by Suri12990** [nutonomy/nuscenes-devkit#582]
Hey,

I am trying to convert nuscenes lidar data into kitti format. I downloaded the data from [here](https://www.nuscenes.org/download) extracted the data also, but I did not see any annotation or calib or images files. There are annotation files for mini data contains data of all cameras, lidar and radar. But annotations are trainVal1. Do I need to download whole blob to see the annotations?

Could someone help me with this?

**Comment by holger-motional** [comment]
Hi. Here is a screenshot from https://www.nuscenes.org/download:
![download](https://user-images.githubusercontent.com/39502217/114833984-b5abf200-9e02-11eb-8d8b-428ab58ecc0c.png)
Metadata contains all annotations, egoposes etc.
Samples are the annotated keyframes for all sensors.
Sweeps are the intermediate (non-keyframes) for all sensors.
