### ISSUE TITLE
Regarding meta files for trainval2,3,4,5,6?

### ISSUE THREAD

**Issue by Suri12990** [nutonomy/nuscenes-devkit#583]
Hey @holger-motional 

Hope you are doing good in this tough time. I need to convert nuscenes data into kitti format. I downloaded train and val 1,2,3,4,5,6. and also I convert trainval1 upto 2462 into kitti format(after that I got error FilenotFounderror in image). 

I used this python3 export_kitti.py nuscenes_gt_to_kitti --nusc_kitti_dir ~/Downloads/nuscences/nucsences/nu5/ --image_count 100000000   command to run the export_kitti.py file. 

I changed the data_dir as well. But I got only one v1.0-trainval folder for all trainval1,2,3,4,5,6 folders. 

These are the changes I am making for different trainval folders:

In nuscenes.py
```
  def __init__(self,
                 version: str = 'v1.0-trainval',
                 dataroot: str = '/home/surendra/Downloads/nuscences/nucsences/nu5',
                 verbose: bool = True,
                 map_resolution: float = 0.1):
```
Assume each trainval has its own folders like nu1,nu2,nu3,nu4,nu5, But annotation folder is only one v1.0-trainval. So I copied the v1.0-trainval to nu1,nu2,nu3,nu4,nu5 folders.

in export_kitti.py

```
  def __init__(self,
                 nusc_kitti_dir: str = '~/nusc_kitti',
                 cam_name: str = 'CAM_FRONT',
                 lidar_name: str = 'LIDAR_TOP',
                 image_count: int = 10,
                 nusc_version: str = 'v1.0-trainval',
                 split: str = 'train'):
```
Could you please help me how to convert all files ? am I doing anything wrong here?

Thanks in advance

**Comment by holger-motional** [comment]
Hi. See also https://forum.nuscenes.org/t/problem-with-conversion-from-nuscenes-into-kitti/548. 
In general the code was not designed to work with the different splits *separately*. They are supposed to all be merged into one folder and likewise there is only one annotation (v1.0-trainval) for all of them. Hence you would need to adjust the code to only operate on the images you are interested in.

**Comment by Suri12990** [comment]
Hey @holger-motional  

Thank you so much. I am doing it now. I have one more question regarding multiple sweeps. I read your multiple sweeps discussion [here](https://forum.nuscenes.org/t/fusing-lidar-sweeps-with-keyframe/533/2). You have mentioned kitti did not do multiple sweeps (technically Iterative closest point(ICP) algorithm to do the data association). But kitti has done it to increase the point cloud density, which in turn make the medium ranged objects to have more points, so network will work better on medium ranged objects for an example objects(Pedestrian and Cyclist mainly at 40m).   

Coming to the new Lidar which gives more points than old kitti lidar. Do you think models will performance better now if we use ICP (sweeps are depending upon performance of the network) or data association?  

Thanks in advance

**Comment by holger-motional** [comment]
I am not talking just about whether KITTI uses a good algorithm to register the pointclouds against another (ICP), but also simply that they don't provide the intermediate pointclouds for the labeled sequences (I believe there are other unlabeled sequences which are denser). 
Actually, despite KITTI being older, it uses a 64 beam lidar, while we use 32 beam lidar. Hence old Kitti lidar should be denser. 
I definitely think ICP becomes much easier with more points.

**Comment by maxxsuiii** [comment]
> Hey @holger-motional
> 
> Thank you so much. I am doing it now. I have one more question regarding multiple sweeps. I read your multiple sweeps discussion [here](https://forum.nuscenes.org/t/fusing-lidar-sweeps-with-keyframe/533/2). You have mentioned kitti did not do multiple sweeps (technically Iterative closest point(ICP) algorithm to do the data association). But kitti has done it to increase the point cloud density, which in turn make the medium ranged objects to have more points, so network will work better on medium ranged objects for an example objects(Pedestrian and Cyclist mainly at 40m).
> 
> Coming to the new Lidar which gives more points than old kitti lidar. Do not you think models will performance better now if we use ICP (sweeps are depending upon performance of the network) or data association?
> 
> Thanks in advance

Hi @GuidanceMantras

Hope you are doing good in this tough time. Do you already can convert nuscenes to kitti? I need to convert nuscenes data into kitti format. I have downloaded full dataset for mini version (v1.0-mini) but I cannot convert it. Maybe you can help me.

This is my email address: aimanpattah@gmail.com
