### ISSUE TITLE
Coordinate system conversion rules

### ISSUE THREAD

**Issue by qfwysw** [nutonomy/nuscenes-devkit#584]
Hi all:
I want to know how to use the rotation and transformation to achieve the coordinate system conversion.
`poserecord = self.nusc.get('ego_pose', cam['ego_pose_token'])
pc.translate(-np.array(poserecord['translation']))
pc.rotate(Quaternion(poserecord['rotation']).rotation_matrix.T)`
`box.translate(-np.array(pose_record['translation']))
box.rotate(Quaternion(pose_record['rotation']).inverse)`
Whether the matrix is orthogonal. Because I think box coordinate is the global coordinate,  the second code should use the transpose too.
Can you show me the formulas for the conversion of various coordinate systems？

**Comment by holger-motional** [comment]
You can see the different coordinate frames at: https://www.nuscenes.org/public/images/data.png
In general, if you just copy the relevant code snippest from nuscenes.py, you will never have to think about it yourself. Often people forget that there is also a time offset between the different sensor readings. Hence it is better to reuse proven code: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L782
