### ISSUE TITLE
Incomplete "road segment" data in Singapore Queenstown's map

### ISSUE THREAD

**Issue by zxc741852741** [nutonomy/nuscenes-devkit#592]
Hi, thanks nutonomy provide a wonderful dataset. 
I am trying to visualize "road segment" in Singapore Queenstown's map, but get a broken results. 
![singapore-queenstown0](https://user-images.githubusercontent.com/40080544/115852804-0e126d80-a45b-11eb-95d5-36731512c193.png)
I check the Singapore Queenstown map's json file. In my opinion, it seems lack of data.
I also visualize "road segment" in Boston Seaport's map and get a nice results.
![boston-seaport](https://user-images.githubusercontent.com/40080544/115855160-87ab5b00-a45d-11eb-8690-0edf4adc9ed7.png)

Here is my code
```
from nuscenes.nuscenes import NuScenes
from nuscenes.map_expansion.map_api import NuScenesMap
from nuscenes.map_expansion.bitmap import BitMap
from nuscenes.map_expansion import arcline_path_utils

import matplotlib.pyplot as plt

nusc_map = NuScenesMap(dataroot='/data/sets/nuscenes', map_name='singapore-queenstown')
nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=True)
bitmap = BitMap(nusc_map.dataroot, nusc_map.map_name, 'basemap')
fig, ax = nusc_map.render_layers(['road_segment'], figsize=1, bitmap=bitmap)
plt.show()
```
Do I neglect anything or it just has incomplete data?

**Comment by holger-motional** [comment]
Hi. You are right. AFAIK the annotator instructions changed to only label intersections with a `road_segment`. OneNorth and Boston still follow the old conventions. You should be able to emulate the new behavior by removing all road_segments with `is_intersection`==False.
