### ISSUE TITLE
Transfer predictions to global frame

### ISSUE THREAD

**Issue by ranran9991** [nutonomy/nuscenes-devkit#593]
I'm trying to train the MTP model for the prediction challenge, and I managed to make it converge.
I then try to calculate some metrics over the validation set. When using [`compute_metrics`](https://github.com/nutonomy/nuscenes-devkit/blob/57889ff20678577025326cfc24e57424a829be0a/python-sdk/nuscenes/eval/prediction/compute_metrics.py#L17) I suddenly got abnormally high results, with MinADE_5 of about 2000. I then checked at it seems the function calculates the metrics over the global frame coordinate system.

 I've been having trouble finding a simple way to transfer my prediction (given a sample and instance token) to the global system.

Would love some help!

**Comment by holger-motional** [comment]
Hi. Take a look at the lines https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L782-L791 to transform from local to global coordinates.

**Comment by ranran9991** [comment]
I'll leave the code here as it was hard to find for me
```

# given trajectory with size [num_modes, 12, 2]
trajectory = trajectory.reshape((-1, 2)) # conversion requires [num_coords, 2] 
annot = self.predict_helper.get_sample_annotation(instance_token, sample_token) # for translation and rotation
trajectory = convert_local_coords_to_global(trajectory,
                                            annot['translation'],
                                            annot['rotation']).reshape(num_modes, 12, 2)
```
