### ISSUE TITLE
Missing metadata 

### ISSUE THREAD

**Issue by Solacex** [nutonomy/nuscenes-devkit#594]
Hello, I am trying to config the nuScenes-lidasreg. I have downloaded the whole dataset and the all-meta-data (nuimages-v1.0-all-metadata.tgz). 
But I found some many .json files are missing, e.g. visibility.json.  where can I  get them?

![image](https://user-images.githubusercontent.com/12868455/117278375-0f548900-aea4-11eb-8497-32d753f0e6fa.png)

![image](https://user-images.githubusercontent.com/12868455/117278516-2eebb180-aea4-11eb-84c0-cb6c5f6d1679.png)

Thanks.

**Comment by holger-motional** [comment]
Hi. You also need to download the original nuScenes dataset. nuScenes-lidarseg just has new annotations for the same dataset.

**Comment by Solacex** [comment]
Hi， I have downloaded the full dataset. But these are still missing.,,

**Comment by Solacex** [comment]
I have downloaded the full dataset including the meta-data. After download lidarseg part, I could only found category.json and lidarseg.json.

**Comment by holger-motional** [comment]
In that case you probably overwrote the folder when you extracted the files? Download the nuScenes meta data again.

**Comment by xhangHU** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'data/nuscenes/v1.0-mini/visibility.json'
I also encountered this problem. I downloaded the original data but did not find the file.

**Comment by holger-motional** [comment]
The recommended path is `/data/sets/nuscenes..`. You are missing the leading slash and the sets folder. Double check it's correct.

**Comment by Zephyr-S** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'data/nuscenes/v1.0-mini/visibility.json' I also encountered this problem. I downloaded the original data but did not find the file.

Can try download Meta from the following link: [https://www.nuscenes.org/nuscenes]
![image](https://github.com/user-attachments/assets/020ea05a-02b5-4c5c-b093-e837594126c8)

**Comment by ckevar** [comment]
I guess you already solved the issue, but I was struggling with it, too. NuScene provides two datasets nuScene and nuImages and nuImages doesn't have the visibility.json file. So, i had to download the NuScenes dataset, they are in the same website you can find them in the top right-side of the page.
