### ISSUE TITLE
Questions about nuScenes detection evaluation metrics

### ISSUE THREAD

**Issue by pangsu0613** [nutonomy/nuscenes-devkit#595]
Hello! I found the following information from nuScenes website (detection, evaluation metrics, preprocessing section):
''All boxes (GT) without lidar or radar points in them are removed. The reason is that we can not guarantee that they are actually visible in the frame. We do not filter the predicted boxes based on number of points.'' and I have 2 questions related to this:

1. For "All boxes (GT) without lidar or radar points in them are removed.", I am not very clear about this. For example, if a box has lidar points = 2, but radar points = 0, will it be removed? 
2.For "We do not filter the predicted boxes based on number of points.", For example, if a GT box is removed, but we submit predicted box corresponding to that removed GT box, do we get punishment for a false positive, or this predicted box is ignored during evaluation?

Thank you.

**Comment by holger-motional** [comment]
1. It means `assert num_radar_pts + num_lidar_pts > 0`. So either of them is fine (radar is very sparse and 2d and likely to miss objects).
2. Yes, you get punished for false positives. If you are working with a lidar method it is very easy for you to do the filtering yourself. A vision-only method will have a small disadvantage in that respect.
