### ISSUE TITLE
Question concerning data statistics.

### ISSUE THREAD

**Issue by Solacex** [nutonomy/nuscenes-devkit#596]
Hello,

I am trying spherical projection on nuScenes dataset that project lidar data into five channels (xyz coordinate, remission, range). I want to know if this devkit provides the statistics for normalization (mean and std of each channel. )

Thanks in  advance.

**Comment by holger-motional** [comment]
Hi. Unfortunately we don't provide these stats. I suggest you write a simple script to load up a few thousand randomly(!) sampled pointclouds and compute the stats.
