### ISSUE TITLE
Access the Point Clouds not in the Key Frames

### ISSUE THREAD

**Issue by ziqipang** [nutonomy/nuscenes-devkit#598]
Hi! 

Thank you for your help on this dataset! It is very helpful to all the people! However, I have some questions that may need your help, and I indeed haven't found them in the tutorials.

I am wondering how to access the point clouds that are not in the key frames, i.e., samples. The original LiDAR scans the surrounding environment at a frequency of 10Hz, but the samples only have a frequency of 2Hz. Specifically, I am curious about the following two questions:

1. **How to access the data related to LIDAR_TOP but not in the key frames (samples), such as point clouds, ego poses, time stamps?**
2. **May I believe that "for every two key frames, there are four not-key frames," and no exceptions exist in the dataset?**

Thank you again for your time and help!

**Comment by holger-motional** [comment]
Hi. Please take a look at the schema (https://www.nuscenes.org/public/images/nuscenes-schema.svg) and the tutorial. `sample_data` either corresponds to a keyframe image/pointcloud or a non-keyframe image/pointcloud. There are several ways to access these:
- Go from `sample` to `sample_data` (keyframe) and then `next` or `prev` (non-keyframe).
- Directly go through `sample_data` and check if `is_key_frame` = False.

> May I believe that "for every two key frames, there are four not-key frames," and no exceptions exist in the dataset?

The dataset has 20Hz lidar and 2Hz keyframes. So for lidar there are (20-2)/2=9 non-keyframes per keyframe. For camera it's 12Hz and radar 13Hz.

**Comment by ziqipang** [comment]
Hi, Thank you so much for your help! 

I am just writing more so that later people can know better about how this works.

1. Access a `sample`, which indicates a first key frame.
2. Using the `sample`, access its `sample_data`, such as by the token of `LIDAR_TOP`
3. In the `sample_data`, there a `next` field for the data on the next frame. Note that the `next` in the `sample_data` is different from the `next` in the `sample`. Check the `is_key_frame` field to know if it is a key frame.

**Comment by a1600012888** [comment]
Hi, thanks for your clear comments, I am here to add more info for **bonding box in non-key frames**. 

https://github.com/nutonomy/nuscenes-devkit/blob/57889ff20678577025326cfc24e57424a829be0a/python-sdk/nuscenes/nuscenes.py#L310  the `NuScenes.get_boxes(sample_data_token)` function will interpolate bounding boxes for non-key frames. 
The interpolation takes 3 steps
1. use `sample_data_token` to access corresponding `sample_data`, and use `sample_data['sample']` to access `sample`
2. use `sample` to access previous or next **key frame**
3. Then interpolate the bounding box using the previous and next key frame
