### ISSUE TITLE
Relation between Prediction challenge and images from camera

### ISSUE THREAD

**Issue by ranran9991** [nutonomy/nuscenes-devkit#599]
Hey,
I'm trying to understand the relation between the prediction challenge and the cameras on the vehicle

In the prediction challenge, we're trying to predict the trajectories of some agent in the scene. 
Is this agent, the same agent that is taking pictures? or is it some other vehicle?
If they are not the same one, is the agent on which we predict trajectories present in the images? can we use them for the prediction challenge?

**Comment by holger-motional** [comment]
In the prediction challenge, you are provided the sensor data and ego pose of the "ego vehicle" and the goal is to predict the trajectories of all **other** agents.
