### ISSUE TITLE
Error: You are using an outdated map version (%s)! Please go to https://www.nuscenes.org/download to download the latest map!

### ISSUE THREAD

**Issue by malao98** [nutonomy/nuscenes-devkit#600]
Hi,

I encountered the following error while running the map expansion tutorial. 
Also, I used the lastest version Map expansion pack (v1.3) 

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-1-d72434e1bc2d> in <module>
      7 from nuscenes.map_expansion.bitmap import BitMap
      8 
----> 9 nusc_map = NuScenesMap(dataroot='/home/yihong/data/sets/nuscenes/', map_name='singapore-onenorth')

~/git_workspace/nuscenes-devkit/python-sdk/nuscenes/map_expansion/map_api.py in __init__(self, dataroot, map_name)
     99 
    100         if self.version < '1.3':
--> 101             raise Exception('Error: You are using an outdated map version (%s)! '
    102                             'Please go to https://www.nuscenes.org/download to download the latest map!')
    103 

Exception: Error: You are using an outdated map version (%s)! Please go to https://www.nuscenes.org/download to download the latest map!

------------------------------------------------------------------------------

Can someone help me with this problem? 
Thank you.

**Comment by holger-motional** [comment]
Apparently you did not successfully replace the files. Delete your maps folder and try again.
