### ISSUE TITLE
poor accuracy in 2d image when plot a lidar point cloud in an image

### ISSUE THREAD

**Issue by DuZzzs** [nutonomy/nuscenes-devkit#601]
Hi, I download dataset here: https://www.nuscenes.org/data/v1.0-mini.tgz. I want to project the 3d box and point cloud onto the image to verify the accuracy of the label.
code is :
```
from nuscenes.nuscenes import NuScenes

nusc = NuScenes(version='v1.0-mini', dataroot='D:/code/dataset/opendata/nuscenes/v1.0-mini/v1.0-mini', verbose=True)
nusc.list_scenes()
for i in range(10):
    my_scene = nusc.scene[i]

    first_sample_token = my_scene['first_sample_token']
    nusc.render_sample(first_sample_token, out_path="work_dirs/" + str(i))
    lidar = nusc.sample[i]
    nusc.render_pointcloud_in_image(lidar['token'], pointsensor_channel='LIDAR_TOP',
                                    out_path="work_dirs/lidar_" + str(i))
    nusc.render_sample_data(lidar['data']['LIDAR_TOP'], nsweeps=5, underlay_map=True,
                            out_path="work_dirs/lidar_dense_" + str(i))
```
The results seems not good.
1.  For example, the 3dbox does not fit the edge of the target well.
![image](https://user-images.githubusercontent.com/46736075/120134613-1780b980-c201-11eb-87ee-9d94d9a3f616.png)
2. The point cloud is also not well aligned, and there is a lot of overlap.
![image](https://user-images.githubusercontent.com/46736075/120134801-7cd4aa80-c201-11eb-96cb-f7888c7109fa.png)
Am i missing something? Does this mean that the accuracy of this dataset is not very high? Thank you.

**Comment by holger-motional** [comment]
> 1. For example, the 3dbox does not fit the edge of the target well.

It is very difficult to assess that from the camera view. You should look at the pointcloud representation. To me this looks good.

> 2. The point cloud is also not well aligned, and there is a lot of overlap.

You have to take into account the parallax. The lidar is at a different position than the camera. Some of these points are really behind the truck on the wall. Hence it looks wrong. Overall I think the calibration here is good.
