### ISSUE TITLE
Difference between the Point Clouds in sweeps and samples

### ISSUE THREAD

**Issue by ziqipang** [nutonomy/nuscenes-devkit#602]
Hi! I am recently trying to access the point clouds that are not in the key frames, and I am confused by the question below. Thank you for your help!

The paths to the LiDAR data are different when using different interfaces. When accessing the point cloud in a frame with `is_key_frame=False`, the Approach 1 refers to the point cloud in the folder `samples`, and the Approach 2 refers to the point cloud in the folder`sweeps`. Therefore, I am wondering **which approach is right and what are the differences**?

1. The first approach is by the following code. Specifically, 
``` python
    data = nusc.get(‘sample_data’, token)
    lidar_path = data['filename']
``` 

2. The second approach is by the function `get_sample_data_path`. Specifically,
``` python
    lidar_path = nusc.get_sample_data_path(token)
```

**Comment by holger-motional** [comment]
They are the basically same. It's just that `sample_data`s that correspond to a keyframe are stored in `samples`, whereas the others are stored in `sweeps`. The only purpose is that it allows you to download only the `samples` for *some* applications. 

```
    def get_sample_data_path(self, sample_data_token: str) -> str:
        """ Returns the path to a sample_data. """

        sd_record = self.get('sample_data', sample_data_token)
        return osp.join(self.dataroot, sd_record['filename'])
```

**Comment by ziqipang** [comment]
Thank you @holger-motional
