### ISSUE TITLE
Map expansion dataset

### ISSUE THREAD

**Issue by malao98** [nutonomy/nuscenes-devkit#603]
Hi,

I would like to ask how the dataset of map expansion was generated (both png file and json file. ) In map_api.py stated that the WGS 84 Web Mercator (EPSG:3857) projection as Google Maps/Earth was used. However, by using google earth I can only export map in kml data format instead of png format. Moreover, how could we find the detailed information of the map (e.g. non geometric layer, geometric layer, ....) and turn it into json file?

Hope that someone can help me with this problem.

Thank you.

**Comment by holger-motional** [comment]
Hi. The maps are developed by our internal teams, collecting vast amounts of lidar data and running SLAM to register them. Then human annotators add the semantic labels, which takes thousands of hours. 
The maps comes as json files, so if you want to export a part of that, you can always generate a new file with a subset of the map layers.
