### ISSUE TITLE
Exporting to KITTI Format 

### ISSUE THREAD

**Issue by kaancayli** [nutonomy/nuscenes-devkit#604]
Hello,
As part of my Bachelor's thesis, I'm currently working with nuScenes dataset and trying to convert the dataset into KITTI format. Indeed, I converted the dataset into KITTI format. However the 3D Boxes in the 2D images don't seem to be enclosing the object of interest correctly. Is this normal and expected? I know, it has been a while since you wrote the code but I would be delighted to have any suggestions from you, so that I can tweak the script a little bit. Below you can see my exemplary  results. Thanks in advance!

**In this image, green boxes are ground truth boxes and blue boxes are my prediction resuts**
The GT-box for the left-most car seems not to be correct. (Scene: 0593, Fifth sample in the scene _(sorry that I can not provide you with the sample token since I converted the dataset into tracking format of KITTI )_)
![000004](https://user-images.githubusercontent.com/38523756/120758399-1528a300-c512-11eb-93a8-0899096e28da.png)

**Comment by holger-motional** [comment]
Hi. The conversion into KITTI format is tricky for numerous reasons. Could you show what sample this is and provide a nuScenes rendering for comparison?

**Comment by kaancayli** [comment]
Thanks for the answer.
Here is the information: 
**scene:** scene-0593
**sample-token:** 9ddfc6a5908444a384e616dbca40ca98
**below you can find nuScenes rendering:**
![download](https://user-images.githubusercontent.com/38523756/120795799-3c936600-c53a-11eb-942d-061e434a9cd9.png)
I have the feeling that one of the dimensions of bbox should be reversed 180 degrees, so that the bottom of the boxes can be aligned better.

**Comment by kaancayli** [comment]
@holger-motional 
Here you can also find a nuScenes rendering, which has higher resolution:
![res](https://user-images.githubusercontent.com/38523756/120796908-af511100-c53b-11eb-9188-32e9a41a11a6.png)

**Comment by kaancayli** [comment]
Sorry my bad. Your script does a great job. Thanks for your support. @holger-motional

**Comment by holger-motional** [comment]
@kaancayli Thanks for clarification. What was the confusion?

**Comment by kaancayli** [comment]
@holger-motional Without looking at the original nuScenes rendering, I thought the conversion of nuScenes to KITTI causes that the GT-boxes are not enclosing their respective objects correctly, but after looking at the original nuScenes rendering, I become convinced that the bounding boxes are the same both in the original and in KITTI after the conversion.

**Comment by holger-motional** [comment]
Yeah. I think the issue is that the ground is slightly inclinated and therefore the boxes don't look good.
