### ISSUE TITLE
recall calculation

### ISSUE THREAD

**Issue by strongdeer** [nutonomy/nuscenes-devkit#606]
I have a question about the method for computing recall.
The recall is calculated as `recall = num_matches / num_objects` in function `motar` in module `nuscenes/eval/tracking/metrics.py` and the scores used for computing recall levels are also selected only by `matches = events[events.Type == 'MATCH']` in function `accumulate_threshold` in module `nuscenes/eval/tracking/algo.py`. 
However, in py-motmetrics, the recall is calculated as `num_detections / num_objects` in function `recall` in module `motmetrics/metrics.py` with `num_detections = num_matches + num_switches`, and this is the same as the method proposed in paper `Evaluating Multiple Object Tracking Performance: The CLEAR MOT Metrics`. 
So, why not to compute recall using the same method as py-motmetrics?  Thanks.

**Comment by holger-motional** [comment]
Hi. That's a good question. The authors of "A Baseline for 3D Multi-Object Tracking" proposed this improved definition of MOTA(R) for AMOTA, as described in https://www.nuscenes.org/tracking/ (AMOTA and AMOTP metrics).

**Comment by strongdeer** [comment]
Thanks for your answer. I have read the paper "A Baseline for 3D Multi-Object Tracking", but I did not find the explanation about the computation of `recall`. In my understanding, the computation of `recall` is the same in these two paper.
