### ISSUE TITLE
How do you define the yaw angle of traffic cones?

### ISSUE THREAD

**Issue by MagicRock100** [nutonomy/nuscenes-devkit#608]
Hello, could you tell me how you define the yaw angle of traffic cones? I didn’t understand why the yaw angles of these two traffic cones are different.

![f5ae26413ad44782a307bebb1216632d](https://user-images.githubusercontent.com/38135837/123364509-18f69500-d5a7-11eb-941a-14b61646f770.png)

Thank you!

**Comment by holger-motional** [comment]
Hi. For cones with a quadratic base the orientation is uniquely defined up to 90 degrees - the forward direction can point towards any of the 4 faces. For round or octogonal bases it becomes (close to) arbitrary, and you cannot assume anything.

**Comment by MagicRock100** [comment]
@holger-motional Thanks for your reply. We know, for the 3D object detection task, the network needs to predict the yaw angles of all traffic cones.  I still don't understand what the network should predict if the yaw angles cannot be uniquely defined. Sould the the network predict all the possible yaw angles of traffic cones?

**Comment by MagicRock100** [comment]
@holger-motional 
Thanks for your reply. I still have two questions：
1. We know, for the 3D object detection task, the network needs to predict the yaw angles of all traffic cones. I still don't understand what the network should predict if the yaw angles cannot be uniquely defined. Sould the the network predict all the possible yaw angles of traffic cones?
2. How do you define the yaw angles of barriers?

**Comment by holger-motional** [comment]
1. For some classes we ignore the yaw angle, so it does not matter: https://github.com/nutonomy/nuscenes-devkit/blob/9b209638ef3dee6d0cdc5ac700c493747f5b35fe/python-sdk/nuscenes/eval/detection/evaluate.py#L135

2. Barrier orientation is only determined up to 180 degree. https://github.com/nutonomy/nuscenes-devkit/blob/87b88fe37ad503e6e35dc2546ae1bf74f4ef6c01/python-sdk/nuscenes/eval/detection/algo.py#L106 . The front needs to point towards one of the longer sides (assuming barriers are typically rectangular).
