### ISSUE TITLE
Evaluate results

### ISSUE THREAD

**Issue by ZhangYu1ing** [nutonomy/nuscenes-devkit#609]
Hello nuscenes-devkit team.

I am trying to test my KITTI-trained model on v1.0-mini nuscenes dataset. And I have some question listed as follow:

1.  I used your export_kitti.py code to convert the nuscenes data into KITTI format. As I checked, there are only 10 nuscenes data is converted to KITTI format. Whether the small number of data is related to the v1.0-mini version of nuscenes?
2. Then, I used the converted data to test my model. The detector could get AP>80% when evaluated on KITTI dataset. Whereas, the detector tested on nuScenes the results weird, which is copied as below. Do you have any ideas why the results show like this? 
```
INFO  Car AP@0.70, 0.70, 0.70:
bbox AP:1.8182, 3.0303, 3.0303
bev  AP:1.8182, 1.2987, 1.2987
3d   AP:1.8182, 1.2987, 1.2987
aos  AP:1.41, 1.64, 1.64
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:0.0000, 0.7143, 0.7143
bev  AP:0.1163, 0.0943, 0.0943
3d   AP:0.0000, 0.0000, 0.0000
aos  AP:0.00, 0.45, 0.45
Car AP@0.70, 0.50, 0.50:
bbox AP:1.8182, 3.0303, 3.0303
bev  AP:2.5974, 2.0202, 2.0202
3d   AP:1.8182, 1.2987, 1.2987
aos  AP:1.41, 1.64, 1.64
Car AP_R40@0.70, 0.50, 0.50:
bbox AP:0.0000, 0.7143, 0.7143
bev  AP:0.8887, 0.6971, 0.6971
3d   AP:0.1163, 0.0943, 0.0943
aos  AP:0.00, 0.45, 0.45
Pedestrian AP@0.50, 0.50, 0.50:
bbox AP:0.2884, 0.2822, 0.2822
bev  AP:0.2506, 0.2711, 0.2711
3d   AP:0.0377, 0.0365, 0.0365
aos  AP:0.11, 0.11, 0.11
Pedestrian AP_R40@0.50, 0.50, 0.50:
bbox AP:0.2379, 0.1940, 0.1940
bev  AP:0.1705, 0.1861, 0.1861
3d   AP:0.0065, 0.0064, 0.0064
aos  AP:0.09, 0.08, 0.08
Pedestrian AP@0.50, 0.25, 0.25:
bbox AP:0.2884, 0.2822, 0.2822
bev  AP:1.4559, 1.7526, 1.7526
3d   AP:0.3108, 0.2856, 0.2856
aos  AP:0.11, 0.11, 0.11
Pedestrian AP_R40@0.50, 0.25, 0.25:
bbox AP:0.2379, 0.1940, 0.1940
bev  AP:1.3953, 1.6581, 1.6581
3d   AP:0.2533, 0.1959, 0.1959
aos  AP:0.09, 0.08, 0.08
Cyclist AP@0.50, 0.50, 0.50:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
aos  AP:0.00, 0.00, 0.00
Cyclist AP_R40@0.50, 0.50, 0.50:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
aos  AP:0.00, 0.00, 0.00
Cyclist AP@0.50, 0.25, 0.25:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
aos  AP:0.00, 0.00, 0.00
Cyclist AP_R40@0.50, 0.25, 0.25:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
aos  AP:0.00, 0.00, 0.00
```
When I further see the visualized result, it shows many objects are incorrectly detected, which leads to the low AP.
![image](https://user-images.githubusercontent.com/37301722/123510594-bf609a00-d67c-11eb-8c93-267f24aa876f.png)
 
3. As you illustrated in the export_kitti.py, the function kitti_res_to_nuscenes() could be used to convert kitti results. I am a little bit confused about what do you mean by the 'kitti results'. Do you mean the .pth model trained on kitti dataset? What kind of kitti result does this code need?

Thanks in advance.

**Comment by holger-motional** [comment]
Hi,

> 1. I used your export_kitti.py code to convert the nuscenes data into KITTI format. As I checked, there are only 10 nuscenes data is converted to KITTI format. Whether the small number of data is related to the v1.0-mini version of nuscenes?

Yes. Mini is 10 scenes out of 1000 in total.

> 2. Then, I used the converted data to test my model. The detector could get AP>80% when evaluated on KITTI dataset. Whereas, the detector tested on nuScenes the results weird, which is copied as below. Do you have any ideas why the results show like this?

Many things are different in nuScenes, e.g. different lidar etc. But your results look entirely broken to me:
```
INFO  Car AP@0.70, 0.70, 0.70:
bbox AP:**1.8182**, 3.0303, 3.0303
```
Better check the results format.

> 3. As you illustrated in the export_kitti.py, the function kitti_res_to_nuscenes() could be used to convert kitti results. I am a little bit confused about what do you mean by the 'kitti results'. Do you mean the .pth model trained on kitti dataset? What kind of kitti result does this code need?

The results format describes the detected boxes of your model in KITTI format, not the model itself.
