### ISSUE TITLE
Setting up nu-scenes on windows 

### ISSUE THREAD

**Issue by uditvaskar1991** [nutonomy/nuscenes-devkit#61]
Hi,
Need some help on how to set up nu-scenes in windows (I am stuck for several weeks ):
I have installed python 3.7 through anaconda prompt 
I have installed the packages from the requirements.txt
Completed the data download (meta, point_samples, point_sweep, image_samples, image_sweep, dev-kit)

From this point how to proceed further ?
Have tried working the solution by going through the existing reported issues but no luck so far.
will appreciate a lot if somebody can help.
I am a beginner in python.

**Comment by holger-nutonomy** [comment]
What is the error you are facing?
Try to run the tutorial as a Jupyter Notebook: 
https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/tutorial.ipynb

**Comment by holger-nutonomy** [comment]
Closing this issue for now. Feel free to reopen it.
