### ISSUE TITLE
How can I get the translation and rotation matrix between two consecutive frames?

### ISSUE THREAD

**Issue by zhangchbin** [nutonomy/nuscenes-devkit#610]
Hello,
    I noticed that the translation and rotation matrix is in global Coordinate system. Is there any scripts to get the pose between adjacent frames?

**Comment by holger-motional** [comment]
Hi. Look at these 4 steps https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L783-L801. The logic should be similar, except that you need a different frame, whereas this switches between sensor coordinates for the same frame.
