### ISSUE TITLE
How can I get the transformation matrix?

### ISSUE THREAD

**Issue by zhangchbin** [nutonomy/nuscenes-devkit#613]
Hi, @holger-motional 
Thanks for your help. How can I get the transform matrix? Am I right?
```
# rotation is quaternion, [q0, q1, q2, q3]
T = Quaternion(rotation).transform_matrix
T[:3, 3] = translation[0, :]
```

_Originally posted by @zhangchbin in https://github.com/nutonomy/nuscenes-devkit/issues/612#issuecomment-870437753_

**Comment by whyekit-motional** [comment]
Hi @zhangchbin, as @holger-motional has replied you [here](https://github.com/nutonomy/nuscenes-devkit/issues/612#issuecomment-871109590), I will proceed to close this issue
