### ISSUE TITLE
Image correspondence problem

### ISSUE THREAD

**Issue by Majiawei** [nutonomy/nuscenes-devkit#614]
Does the image in nuscenes correspond to the image in nuimage?
How can I generate depth map of image plane from LIDAR point cloud image?

**Comment by holger-motional** [comment]
No, the two datasets are disjoint.
As described previously, we don't provide depth maps.
For the projection, look at https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L740
