### ISSUE TITLE
2D target detection benchmark

### ISSUE THREAD

**Issue by Majiawei** [nutonomy/nuscenes-devkit#616]
Is there a method for 2D object detection on nuscense dataset?
Or is there a comparison of 2D object detection on nuimage?
I found that the 2D annotation converted from 3D annotation in nuscenes dataset can't fit the object well. Can I use the converted data for 2D detector training?

**Comment by holger-motional** [comment]
nuScenes did not come with 2d annotations. nuImages did.
As you saw, there is a script to project 3d boxes to 2d, but they are generally not tight *in 2d*.
You can definitely use it, but it will be slightly worse.
Better would be to use these models trained on nuImages: https://github.com/open-mmlab/mmdetection3d/tree/master/configs/nuimages
