### ISSUE TITLE
Complete depth map

### ISSUE THREAD

**Issue by Majiawei** [nutonomy/nuscenes-devkit#617]
When I map lidar data to the camera_front plane, a sparse depth map is generated.
But it seems that the generated depth map is so sparse that it is invalid for me to use the same depth completion method as Kitti.
How can I convert sparse depth map to dense depth map？
What is the range of the depth map？

**Comment by whyekit-motional** [comment]
Hi @Majiawei, we only provide a method to render a point cloud in an image color by it's distance from the camera (pls see https://github.com/nutonomy/nuscenes-devkit/blob/57889ff20678577025326cfc24e57424a829be0a/python-sdk/nuscenes/nuscenes.py#L863 for details)

We do not provide any code for generating depth maps

**Comment by MalazTamim** [comment]
Hi @Majiawei, did you manage to find a solution to this problem?
