### ISSUE TITLE
Export annotatations as text files

### ISSUE THREAD

**Issue by gokulesh-danapal** [nutonomy/nuscenes-devkit#619]
Hi @holger-motional ,
Is there a way to export annotations as text files?
I have seen the export to kitti  file. But velocity of each box is not included in the output.
I would like to have text files with velocity labels also.
Thanks.

**Comment by holger-motional** [comment]
Unfortunately not. Feel free to modify the KITTI export file or create your own.

**Comment by gokulesh-danapal** [comment]
Thanks for the Quick reply. How can I get then velocity of a box in an annotation? When I print a sample annotation velocity information is not there.

> 
> 
> Unfortunately not. Feel free to modify the KITTI export file or create your own.

Thanks for the Quick reply. How can I get then velocity of a box in an annotation? When I print a sample annotation velocity information is not there.

**Comment by whyekit-motional** [comment]
This method will probably help you: https://github.com/nutonomy/nuscenes-devkit/blob/57889ff20678577025326cfc24e57424a829be0a/python-sdk/nuscenes/nuscenes.py#L368
