### ISSUE TITLE
Homography matrix from ground plane to camera plane

### ISSUE THREAD

**Issue by aloukkal** [nutonomy/nuscenes-devkit#62]
Hello, 

I want to compute the homography matrix from the ground plane to the camera plane. To do so, I use the following matrix:
H = K * T * R * A 
where K is the intrinsic matrix, T the translation matrix, R the rotation matrix and A the 3d to 2d projection matrix. 
I got wrong results until I tweaked the values setting the focal length to a third of its value and setting the translation to values that do not correspond to the ones given. I know I am doing something wrong because your projection works perfectly fine when projecting the Lidar in the camera plane. 

Can you give me an idea of what could be possibly wrong in my approach. 
Many thanks.

**Comment by holger-nutonomy** [comment]
Hi @aloukkal. Unfortunately without more information I cannot help you. Perhaps you were missing the ego pose transformation? To transform (e.g. a box) from global coordinates to sensor coordinates you need to go:
- From the global frame to the ego pose frame at a particular timestep.
- From the ego pose frame to the sensor frame.
(https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L239)

If you have any more information, feel free to reopen this ticket.

**Comment by aloukkal** [comment]
Hello @holger-nutonomy, 

Thank you for your answer. Actually I am trying to project the map raster image in the camera plane. I crop a portion of the map around the ego-pose of the car and then I try to project it in the camera plane by computing the homography matrix. 

I am not using the 4 points methods to compute the homography but instead I am computing the translation, rotation and intrinsic matrices in order to obtain the homography for each sample of the dataset. I need to figure out the transformations between the ground plane (raster map bird view) and the camera plane.

From my understanding, I would need to know the translation and rotation between the on-board camera that took the images and the "virtual" camera that would have been use to obtain the raster map in bird view. 

Here is my code:

```
K = np.zeros((3,4))
K [2,2] = 1
#f is the focal length given in the camera intrinsic, for some reason it works when I divide it by 3
K [0,0] = f/3
K [1,1] = f/3
#w,h are the dimensions of the camera image
K[0,2] = w/2
K[1,2] = h/2
print ('Intrinsic',K)

print ('yaw:', yaw, 'pitch:', pitch, 'roll:', roll)
roll= 0
pitch= -1.56
yaw = np.pi

RX = np.zeros ((4,4))
RX[0,0] = 1
RX[3,3] = 1
RX[1, 1:3] = [np.cos(pitch), -np.sin (pitch)]
RX[2, 1:3] = [np.sin(pitch), np.cos (pitch)]
print ('rx',RX)

RY = np.zeros ((4,4))
RY[1,1] = 1
RY[3,3] = 1
RY[0, 0:3] = [np.cos(yaw),0, -np.sin (yaw)]
RY[2, 0:3] = [np.sin(yaw),0, np.cos (yaw)]
print ('ry',RY)

RZ = np.zeros ((4,4))
RZ[2,2] = 1
RZ[3,3] = 1
RZ[0, 0:2] = [np.cos(roll), -np.sin (roll)]
RZ[1, 0:2] = [np.sin(roll), np.cos (roll)]
print ('rz',RZ)

R = RX@RY@RZ
print ('R', R)

T = np.identity (4)
#here again I obtained these values by trying randomly
T[0, 3] = -25
T[1, 3] = -149+50
T[2, 3] = -w/2+275
print ('T',T)

A = np.zeros((4,3))
A[0,0] = 1
A[1,1] = 1
A[3,2] = 1
A[0:2,2] = [-w/2,-h/2]
print ('A',A)

H = K @ T @ R @ A
```
These values give a rather good projection of the raster map in the camera plane. I would like to do it precisely by understanding the transformations. 
Is it clearer? 
Many thanks.

**Comment by holger-nutonomy** [comment]
Unfortunately I don't have time to think this through in detail. Here are some thoughts:
- Keep in mind that the map image uses an orthographic transformation. So you may have trouble figuring out the location / transformation of the "raster map" camera. 
- An alternative approach would be to compute where a "ray" from the camera hits the ground, then you can just lookup what the map mask value is in that point.
- Please update to nuScenes v1.0 and the latest devkit. We included a number of improvements to the map files and code.

**Comment by aloukkal** [comment]
Thank you for the advice, this was my understanding as well, computing the transformation is not straightforward. 
I will update to v1.0, I was waiting for the release of the traffic and stop sign layers in the map.
