### ISSUE TITLE
Does this repo contains the code of projecting point clouds into range view images

### ISSUE THREAD

**Issue by gujiaqivadin** [nutonomy/nuscenes-devkit#620]
Hello, the staff of nutonomy!
    I am working on the lidar-seg dataset in my project. And I want to get the range view image of current frame by projecting point clouds into front-view. As range image is the native form of rotated lidar data, I want to know whether there is a official transformation code about the process. Thanks a lot !

**Comment by whyekit-motional** [comment]
Hi @gujiaqivadin, this should do what you want:
```
my_sample = nusc.sample[10]
nusc.render_pointcloud_in_image(my_sample['token'], pointsensor_channel='LIDAR_TOP')
```

For more details, pls check out our nuScenes tutorials at https://www.nuscenes.org/nuscenes?tutorial=nuscenes
