### ISSUE TITLE
Scenes present in trainval06

### ISSUE THREAD

**Issue by Balazizo** [nutonomy/nuscenes-devkit#624]
Hello, I'm trying to evaluate a model trained and tested on nuScenes on only the blobs of part 06. However, I'm uncertain from which scene (Scene number) does part 06 start and at which scene does it end? Can you please inform me? Thanks, in advance.

**Comment by whyekit-motional** [comment]
Hi, the first archive contains the first 85 scenes, the second archive contains the next 85 scenes and so on. But do note that the numbering of the scenes may not necessarily be continuously consecutive (e.g. rather than `i, i+1, i+2, i+3, ...`, they might be `i, i+1, i+3, i+4, ...`)
