### ISSUE TITLE
Detection eval script output is misleading

### ISSUE THREAD

**Issue by demmerichs** [nutonomy/nuscenes-devkit#625]
The Detection eval script prints along the lines the following statement:
```
=> After LIDAR points based filtering: X
```
This is very misleading because it sounds like only LIDAR points are counted. When e.g. manually filtering ground truths via LIDAR points and then feeding this back to the eval routine results in a non-perfect score. This is very irritating, and a simple code inspection does not easily reveal that actually RADAR points are taken also into account, as it is hidden behind the variable name "num_pts".

I would suggest to simply update the printed statement to
```
=> After (LI+RA)DAR points based filtering: X
=> After LIDAR+RADAR points based filtering: X
```

https://github.com/nutonomy/nuscenes-devkit/blob/bfb57a4e5b044a9f448a3412b23966821f695aaf/python-sdk/nuscenes/eval/common/loaders.py#L258

**Comment by whyekit-motional** [comment]
Hi @demmerichs, thanks for pointing this out.

The `load_gt` method does count both the number of lidar points and number of radar points for `num_pts`:
https://github.com/nutonomy/nuscenes-devkit/blob/bfb57a4e5b044a9f448a3412b23966821f695aaf/python-sdk/nuscenes/eval/common/loaders.py#L163

And then `filter_eval_boxes` operates based on that value in `num_pts`:
https://github.com/nutonomy/nuscenes-devkit/blob/bfb57a4e5b044a9f448a3412b23966821f695aaf/python-sdk/nuscenes/eval/common/loaders.py#L232

@holger-motional do you think we should update the print statement as per the suggest by @demmerichs?

**Comment by holger-motional** [comment]
Sure. Can you create a PR @whyekit-motional ?
