### ISSUE TITLE
How to transform nuscenes 3D point cloud to 2D range image？

### ISSUE THREAD

**Issue by tpzou** [nutonomy/nuscenes-devkit#626]
Hello, I'm trying to transform nuscenes 3D point cloud to 2D range image referencing semantic-kitti [https://github.com/PRBonn/semantic-kitti-api/blob/c2d7712964a9541ed31900c925bf5971be2107c2/auxiliary/laserscan.py](url). I set [H=32, W=1024, fov_up=10.0, fov_down=-30.0](url). But it seems not right. Is there are something different with semantic-kitti ?

Thanks, in advance.

**Comment by whyekit-motional** [comment]
Hi, for nuScenes, this should do what you want:
```
my_sample = nusc.sample[10]
nusc.render_pointcloud_in_image(my_sample['token'], pointsensor_channel='LIDAR_TOP')
```
For more details, pls check out our nuScenes tutorials at https://www.nuscenes.org/nuscenes?tutorial=nuscenes

**Comment by holger-motional** [comment]
Please see also this thread: https://github.com/nutonomy/nuscenes-devkit/issues/617
We do not provide any code for generating depth maps, we only have code to render them.

**Comment by fengjiang5** [comment]
> Hello, I'm trying to transform nuscenes 3D point cloud to 2D range image referencing semantic-kitti [https://github.com/PRBonn/semantic-kitti-api/blob/c2d7712964a9541ed31900c925bf5971be2107c2/auxiliary/laserscan.py](url). I set [H=32, W=1024, fov_up=10.0, fov_down=-30.0](url). But it seems not right. Is there are something different with semantic-kitti ?
> 
> Thanks, in advance.

Hello, did you solve this problem? Could you please share your setting when projection? Thanks a lot.

**Comment by whyekit-motional** [comment]
@fengjiang5 note that for nuScenes, the lidar has:
```
32 beams, 1080 (+-10) points per ring
```
Pls see https://www.nuscenes.org/nuscenes#data-collection for more details

**Comment by polars05** [comment]
Just sharing something I tried:

1. Get an arbitrary pointcloud from nuScenes
```python
import os.path as osp

import matplotlib.pyplot as plt
import numpy as np
from pyquaternion import Quaternion

from nuscenes.nuscenes import NuScenes
from nuscenes.utils.data_classes import LidarPointCloud


# Load up the nuScenes mini split.
nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=False)

# Load some random sample token.
sd_record = nusc.get('sample', 'ca9a282c9e77460f8360f564131a8af5')
ref_sd_token = sd_record['data']['LIDAR_TOP']
ref_sd_record = nusc.get('sample_data', ref_sd_token)

# Load pointcloud.
pcl_path = osp.join(nusc.dataroot, ref_sd_record['filename'])
pc = LidarPointCloud.from_file(pcl_path)
points = pc.points.T  # < num_points, num_features >
```
2. Use code from SemKITTI to construct the range-view image
```python
from semantic_kitti_api.auxiliary.laserscan import LaserScan


nbr_rows = 32
nbr_cols = 1070

laser_scan = LaserScan(project=True, H=nbr_rows, W=nbr_cols, fov_up=10.0, fov_down=-30.0)

laser_scan.set_points(points=points[:, :3], remissions=points[:, 3])

rv_image = laser_scan.proj_range
```
3. Visualize the range-view image
```python
fig, axs = plt.subplots(1, figsize=(nbr_cols // 8, nbr_rows // 8))
pos = axs.imshow(rv_image, interpolation='none')
plt.show()
```
