### ISSUE TITLE
How to get dense segmentation in BEV?

### ISSUE THREAD

**Issue by sunnyHelen** [nutonomy/nuscenes-devkit#627]
Hi, thanks for your great work in building and sharing the dataset. I want to ask how to get the dense segmentation in BEV instead of the sparse result. Is there any function to realize it? Or do you have any suggestions about it?
Thanks a lot~

**Comment by sunnyHelen** [comment]
![image](https://user-images.githubusercontent.com/28101548/126988690-3dd200da-1797-4ed5-9ab3-4780ae22e238.png)
now the result is sparse.

**Comment by whyekit-motional** [comment]
Hi, by "dense segmentation", I suppose you mean that you wish to aggregate the pointclouds of a few past sweeps. However, do note that lidar segmentation labels are only available for keyframes which means that you will not be able to aggregate non-keyframe sweeps

This is also indicated in our devkit, e.g. https://github.com/nutonomy/nuscenes-devkit/blob/2c6a752319f23910d5f55cc995abc547a9e54142/python-sdk/nuscenes/nuscenes.py#L1147
