### ISSUE TITLE
Ignorance of interior point converting in render_map_in_image

### ISSUE THREAD

**Issue by HuangJunJie2017** [nutonomy/nuscenes-devkit#629]
In function  'render_map_in_image', the interior points of polygon are ignored and only the exterior points are processed.
https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/map_expansion/map_api.py

**Comment by whyekit-motional** [comment]
I believe you are referring to this line of code: https://github.com/nutonomy/nuscenes-devkit/blob/c44366daea8bba29673943c1fc86d0bfbfb7a99e/python-sdk/nuscenes/map_expansion/map_api.py#L1135

**Comment by holger-motional** [comment]
Hi @HuangJunJie2017. That is correct. At the moment we are only rendering the exterior nodes of a polygon in the image: https://github.com/nutonomy/nuscenes-devkit/blob/c44366daea8bba29673943c1fc86d0bfbfb7a99e/python-sdk/nuscenes/map_expansion/map_api.py#L1135

**Comment by HuangJunJie2017** [comment]
@holger-motional  It will generate incorrect visualization result, when there is interior lane in a polygon.

**Comment by holger-motional** [comment]
We will try to have someone look into it.

**Comment by HuangJunJie2017** [comment]
@holger-motional That's great! Some info is provided here for reference:
Visualization the first sample in mini-set can review the problem. 
Here is an optional revision which can solve this problem.  
`class NuScenesMapExplorer_New(NuScenesMapExplorer):
    def render_map_in_image(self,
                            nusc: NuScenes,
                            sample_token: str,
                            camera_channel: str = 'CAM_FRONT',
                            alpha: float = 0.3,
                            patch_radius: float = 10000,
                            min_polygon_area: float = 1000,
                            render_behind_cam: bool = True,
                            render_outside_im: bool = True,
                            layer_names: List[str] = None,
                            verbose: bool = True,
                            out_path: str = None) -> Tuple[Figure, Axes]:
        """
        Render a nuScenes camera image and overlay the polygons for the specified map layers.
        Note that the projections are not always accurate as the localization is in 2d.
        :param nusc: The NuScenes instance to load the image from.
        :param sample_token: The image's corresponding sample_token.
        :param camera_channel: Camera channel name, e.g. 'CAM_FRONT'.
        :param alpha: The transparency value of the layers to render in [0, 1].
        :param patch_radius: The radius in meters around the ego car in which to select map records.
        :param min_polygon_area: Minimum area a polygon needs to have to be rendered.
        :param render_behind_cam: Whether to render polygons where any point is behind the camera.
        :param render_outside_im: Whether to render polygons where any point is outside the image.
        :param layer_names: The names of the layers to render, e.g. ['lane'].
            If set to None, the recommended setting will be used.
        :param verbose: Whether to print to stdout.
        :param out_path: Optional path to save the rendered figure to disk.
        """
        near_plane = 1e-8

        if verbose:
            print('Warning: Note that the projections are not always accurate as the localization is in 2d.')

        # Default layers.
        if layer_names is None:
            layer_names = ['road_segment', 'lane', 'ped_crossing', 'walkway', 'stop_line', 'carpark_area']

        # Check layers whether we can render them.
        for layer_name in layer_names:
            assert layer_name in self.map_api.non_geometric_polygon_layers, \
                'Error: Can only render non-geometry polygons: %s' % layer_names

        # Check that NuScenesMap was loaded for the correct location.
        sample_record = nusc.get('sample', sample_token)
        scene_record = nusc.get('scene', sample_record['scene_token'])
        log_record = nusc.get('log', scene_record['log_token'])
        log_location = log_record['location']
        assert self.map_api.map_name == log_location, \
            'Error: NuScenesMap loaded for location %s, should be %s!' % (self.map_api.map_name, log_location)

        # Grab the front camera image and intrinsics.
        cam_token = sample_record['data'][camera_channel]
        cam_record = nusc.get('sample_data', cam_token)
        cam_path = nusc.get_sample_data_path(cam_token)
        im = Image.open(cam_path)
        im_size = im.size
        cs_record = nusc.get('calibrated_sensor', cam_record['calibrated_sensor_token'])
        cam_intrinsic = np.array(cs_record['camera_intrinsic'])

        # Retrieve the current map.
        poserecord = nusc.get('ego_pose', cam_record['ego_pose_token'])
        ego_pose = poserecord['translation']
        box_coords = (
            ego_pose[0] - patch_radius,
            ego_pose[1] - patch_radius,
            ego_pose[0] + patch_radius,
            ego_pose[1] + patch_radius,
        )
        records_in_patch = self.get_records_in_patch(box_coords, layer_names, 'intersect')

        # Init axes.
        fig = plt.figure(figsize=(9, 16))
        ax = fig.add_axes([0, 0, 1, 1])
        ax.set_xlim(0, im_size[0])
        ax.set_ylim(0, im_size[1])
        ax.imshow(im)

        # Retrieve and render each record.
        for layer_name in layer_names:
            for token in records_in_patch[layer_name]:
                record = self.map_api.get(layer_name, token)
                if layer_name == 'drivable_area':
                    polygon_tokens = record['polygon_tokens']
                else:
                    polygon_tokens = [record['polygon_token']]

                for polygon_token in polygon_tokens:
                    polygon = self.map_api.extract_polygon(polygon_token)

                    # Convert polygon nodes to pointcloud with 0 height.
                    points = np.array(polygon.exterior.xy)
                    points = np.vstack((points, np.zeros((1, points.shape[1]))))

                    # Transform into the ego vehicle frame for the timestamp of the image.
                    points = points - np.array(poserecord['translation']).reshape((-1, 1))
                    points = np.dot(Quaternion(poserecord['rotation']).rotation_matrix.T, points)

                    # Transform into the camera.
                    points = points - np.array(cs_record['translation']).reshape((-1, 1))
                    points = np.dot(Quaternion(cs_record['rotation']).rotation_matrix.T, points)

                    # Remove points that are partially behind the camera.
                    depths = points[2, :]
                    behind = depths < near_plane
                    if np.all(behind):
                        continue

                    if render_behind_cam:
                        # Perform clipping on polygons that are partially behind the camera.
                        points = NuScenesMapExplorer._clip_points_behind_camera(points, near_plane)
                    elif np.any(behind):
                        # Otherwise ignore any polygon that is partially behind the camera.
                        continue

                    # Ignore polygons with less than 3 points after clipping.
                    if len(points) == 0 or points.shape[1] < 3:
                        continue

                    # Take the actual picture (matrix multiplication with camera-matrix + renormalization).
                    points = view_points(points, cam_intrinsic, normalize=True)

                    # Skip polygons where all points are outside the image.
                    # Leave a margin of 1 pixel for aesthetic reasons.
                    inside = np.ones(points.shape[1], dtype=bool)
                    inside = np.logical_and(inside, points[0, :] > 1)
                    inside = np.logical_and(inside, points[0, :] < im.size[0] - 1)
                    inside = np.logical_and(inside, points[1, :] > 1)
                    inside = np.logical_and(inside, points[1, :] < im.size[1] - 1)
                    if render_outside_im:
                        if np.all(np.logical_not(inside)):
                            continue
                    else:
                        if np.any(np.logical_not(inside)):
                            continue

                    points = points[:2, :]
                    points = [(p0, p1) for (p0, p1) in zip(points[0], points[1])]

                    # process interior
                    points_interior = []
                    interiors = list(polygon.interiors)
                    if len(interiors)>0:
                        for interior in interiors:
                            points_interior_i = np.array(interior.xy)
                            points_interior_i = np.vstack((points_interior_i,
                                                           np.zeros((1, points_interior_i.shape[1]))))
                            points_interior.append(points_interior_i)
                        num_points = [array.shape[1] for array in points_interior]
                        points_interior = np.concatenate(points_interior, axis=1)

                        # Transform into the ego vehicle frame for the timestamp of the image.
                        points_interior = points_interior - np.array(poserecord['translation']).reshape((-1, 1))
                        points_interior = np.dot(Quaternion(poserecord['rotation']).rotation_matrix.T, points_interior)

                        # Transform into the camera.
                        points_interior = points_interior - np.array(cs_record['translation']).reshape((-1, 1))
                        points_interior = np.dot(Quaternion(cs_record['rotation']).rotation_matrix.T, points_interior)

                        # Transform into the camera.
                        points_interior = view_points(points_interior, cam_intrinsic, normalize=True)

                        points_interior = points_interior[:2, :]
                        points_interior_all = [(p0, p1) for (p0, p1) in zip(points_interior[0], points_interior[1])]
                        start = 0
                        points_interior = []
                        for num in num_points:
                            points_interior.append(points_interior_all[start:start + num])
                            start += num
                    polygon_proj = Polygon(points, points_interior)

                    # Filter small polygons
                    if polygon_proj.area < min_polygon_area:
                        continue

                    label = layer_name
                    ax.add_patch(descartes.PolygonPatch(polygon_proj, fc=self.color_map[layer_name], alpha=alpha,
                                                        label=label))

        # Display the image.
        plt.axis('off')
        ax.invert_yaxis()

        if out_path is not None:
            plt.tight_layout()
            plt.savefig(out_path, bbox_inches='tight', pad_inches=0)

        return fig, ax`
