### ISSUE TITLE
Type of Lidar.bin file

### ISSUE THREAD

**Issue by UZIyygod** [nutonomy/nuscenes-devkit#631]
Hello:

I want to read the bin file of Lidar in Matlab, and i am wondering which kind of type is it.

Float or int? or sth else?

Thanks

**Comment by whyekit-motional** [comment]
Hi, for our devkit, we read from the `.bin` files as `np.float32`: https://github.com/nutonomy/nuscenes-devkit/blob/c44366daea8bba29673943c1fc86d0bfbfb7a99e/python-sdk/nuscenes/utils/data_classes.py#L256

Perhaps that can inspire you for your own usage in Matlab

**Comment by UZIyygod** [comment]
Aha, thanks. I have correctly released the file, but i got 5 parameters.

And i know the first three parameters are the 3D-location information, but what are the other two parameters? 

These two parameters are shown as Integer.

**Comment by whyekit-motional** [comment]
Hi, the remaining two parameters should be intensity and ring index; do take a look at our docstring for that method: https://github.com/nutonomy/nuscenes-devkit/blob/c44366daea8bba29673943c1fc86d0bfbfb7a99e/python-sdk/nuscenes/utils/data_classes.py#L249
