### ISSUE TITLE
Scenes in Blobs

### ISSUE THREAD

**Issue by programmeeer** [nutonomy/nuscenes-devkit#636]
How i can know which scenes are available in different downloadable blobs. I want to train in parts with full dataset.

**Comment by whyekit-motional** [comment]
Hi, the first archive contains the first 85 scenes, the second archive contains the next 85 scenes and so on. But do note that the numbering of the scenes may not necessarily be continuously consecutive (e.g. rather than i, i+1, i+2, i+3, ..., they might be i, i+1, i+3, i+4, ...)

**Comment by programmeeer** [comment]
Is there any specific way to find out which scenes are in blobs? to train network accurately?

This is rather confusing -( *rather than i, i+1, i+2, i+3, ..., they might be i, i+1, i+3, i+4, ...)

**Comment by whyekit-motional** [comment]
Here's a code snippet to figure out which blob a given scene is in: https://github.com/nutonomy/nuscenes-devkit/issues/980#issuecomment-1715566828
