### ISSUE TITLE
Hybrid or Dynamic trajectory sets

### ISSUE THREAD

**Issue by srikanthmalla** [nutonomy/nuscenes-devkit#638]
Hi, Does the current covernet from nuscenes api support dynamic or hybrid trajectory sets for inference?

Thank you,
Srikanth

**Comment by holger-motional** [comment]
Hi. As you can see we don't provide the code to compute the sets, but provide them for different settings:
https://www.nuscenes.org/nuscenes?tutorial=prediction
https://www.nuscenes.org/public/nuscenes-prediction-challenge-trajectory-sets.zip
I am not one of the paper authors, but I believe these were generated by clustering the ground truth trajectories in the dataset.
