### ISSUE TITLE
How can I get the drivable_area?

### ISSUE THREAD

**Issue by zhangchbin** [nutonomy/nuscenes-devkit#639]
Hi, I want to get the mask of "drivable_area" in Bird-Eye-View. 
For road, I know I should fill the poly of "lane" and "road_segment", but for drivable_area?

**Comment by whyekit-motional** [comment]
Hi @zhangchbin, this should do what you want:
```
patch_box = (300, 1700, 100, 100)
patch_angle = 0  # Default orientation where North is up
canvas_size = (1000, 1000)
fig, ax = nusc_map.render_map_mask(patch_box, patch_angle, ['drivable_area'], canvas_size, figsize=(12, 4), n_row=1)
```

For more details, do check out our tutorial at: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/tutorials/map_expansion_tutorial.ipynb
