### ISSUE TITLE
Different category.json of v1.0-mini

### ISSUE THREAD

**Issue by EthanZhangYi** [nutonomy/nuscenes-devkit#640]
The `category.json` of the `nuScenes-v1.0-mini` has 116 lines.
The `category.json` of the `nuScenes-lidarseg-v1.0-mini` and  `nuScenes-panoptic-v1.0-mini` has 193 lines.

Why are they different? 
When I unzip the downloaded files, one `category.json` will cover another.

**Comment by whyekit-motional** [comment]
Hi @EthanZhangYi, do note that there are more classes in nuScenes-lidarseg and nuScenes-panoptic as these cover both foreground (things) and background (stuff) classes. Pls see here for details: https://www.nuscenes.org/nuscenes#lidarseg

And yes, if you wish to use nuScenes-lidarseg and / or nuScenes-panoptic, the `category.json` from `nuScenes-v1.0-mini` should be overwritten.
