### ISSUE TITLE
Test set file error

### ISSUE THREAD

**Issue by XuyangBai** [nutonomy/nuscenes-devkit#642]
Hi thanks for sharing this excellent dataset and toolbox. I am trying to download the test set, but I find although I get the .tar file with exactly the same size, the md5 values are different. And the zipping process exits with the following error, after which I find only 1200 .bin in the `LIDAR_TOP` folder instead of 6008. I have tried downloading the file again but still met such a problem. Any idea on this problem? 
![image](https://user-images.githubusercontent.com/15166089/128794992-dfab61b6-85d8-4cb6-bd96-24e188c6da5e.png)

**Comment by whyekit-motional** [comment]
Hi @XuyangBai, that's strange and should not be the case. Is it the `Lidar blobs only` that's giving you the above issue, or other archives as well?:
![test_set](https://user-images.githubusercontent.com/62535720/128851620-b1b5c6f6-1124-4fcc-b382-921d1bba528e.png)

**Comment by Liuliuliuyikou** [comment]
Thank you for your outstanding work, I had the same problem and I checked the md5 of the file and it is exactly the same as the official website, may I ask what was the follow up to fix it? Also, I would like to ask if missing a part (ten parts in total, one of which is faulty) is possible to train?

**Comment by whyekit-motional** [comment]
@Liuliuliuyikou there wasn't any fix required as there wasn't any issue :smile: 

If you have some issues with the download, pls share a screenshot / some code to reproduce

**Comment by Liuliuliuyikou** [comment]
Yes, I unzipped it again and there was no problem.Thank you again!
