### ISSUE TITLE
radar params

### ISSUE THREAD

**Issue by chiyukunpeng** [nutonomy/nuscenes-devkit#644]
Hi, this is a good job!

Can you provide some parameters of radar, such as range resolution, the number of chirps in one sequence, the number of samples on each chirp, and so on?

Thanks!

**Comment by whyekit-motional** [comment]
Hi @chiyukunpeng, thanks and we are glad you enjoy the nuScenes dataset and devkit!

For details regarding the radar, pls send an email to nuScenes@motional.com :)
