### ISSUE TITLE
Trying to understand the mini-version of the Full dataset

### ISSUE THREAD

**Issue by yanmiao2** [nutonomy/nuscenes-devkit#645]
Hi developers,

I'm new to nuscenes and tried to make some sense out of the dataset. I downloaded the `mini` version of the `Full dataset` from [nuscenes](https://www.nuscenes.org/download) and followed the tutorial. I did the following code:

```
nusc = NuScenes(version='v1.0-mini', dataroot='/home/user/data/sets/nuscenes/v1.0-mini/', verbose=True)
cfg = config_factory('detection_cvpr_2019')
nusc_eval = DetectionEval(nusc, config=cfg, result_path='./example_submission.json', 
                     eval_set='mini_train', output_dir='./res', verbose=True)

s = nums_eval.sample_tokens[0]  # first sample
print(s)
print(nums_eval.gt_boxes.boxes[s], nums_eval.pred_boxes.boxes[s])
```

And I get as the printed value:
```
ca9a282c9e77460f8360f564131a8af5
33 1
```

About the above results, I have several questions:
1. Is `nusc_eval.sample_tokens` equivalent to timestamp? If so, is it an ordered list(by ascending time)?
2. Is `nums_eval.gt_boxes.boxes[s]` a dictionary with `{timestamp: [obstacle_1_box, obstacle_2_box...]}` structure?
3. Why is  the length of `nums_eval.pred_boxes.boxes[s]` always 1? Are the length not supposed to be the number of obstacles detected? (E.g. the length of `nums_eval.gt_boxes.boxes[s]` always differ)

**Comment by whyekit-motional** [comment]
Hi @yanmiao2, welcome to nuScenes!

Regarding your queries:
1. Each sample is an annotated snapshot of a scene at a particular timestamp. The naming of the sample tokens themselves are not ordered, but you can easily go back and forth in "time" by using the `prev` and `next` keys respectively, like so:
```
my_sample_token = nusc_eval.sample_tokens[0]
my_sample = nusc.get('sample', my_sample_token)
print('Current timestamp: ', my_sample['timestamp'])

my_next_sample_token = my_sample['next']
my_next_sample = nusc.get('sample', my_next_sample_token)
print('Next timestamp: ', my_next_sample['timestamp'])
```
2. `nusc_eval.gt_boxes.boxes[s]` is a list of dictionaries, where each dictionary corresponds to a box, like so:
```
[
{'sample_token': str, 'translation': List[float], 'size': List[float], ... 'num_pts': int, 'detection_name': str, 'detection_score': float, ...},
{'sample_token': str, 'translation': List[float], 'size': List[float], ... 'num_pts': int, 'detection_name': str, 'detection_score': float, ...},
...
]
```
3. Yes, `len(nusc_eval.pred_boxes.boxes[s])` should be the number of objects detected. If you are seeing `1` for the all samples, then you might want to check on your model.

**Comment by yanmiao2** [comment]
Hi @whyekit-motional,

Thanks for the rapid response, it's very helpful!

I have some 3 more follow-up questions:
1. With your hint, I was able to get the timestamp(E.g. `1532402938197897`). Now I'm trying to visually inspect what is happening in the scenario at that timestamp. However, the only file in `v1.0-mini/` which has that timestamp is a LIDAR file, there's no corresponding CAM/RADAR data, is this expected? If so, how could I visualize the scenario at that timestamp?
2. How is the CAM/RADAR/LIDAR file in the v1.0-mini dataset named? I assume it's `prefix__sensorName__timestamp`(E.g. `n008-2018-08-01-15-16-36-0400__CAM_BACK__1533151603537558.jpg`). However, it seems like the images captured in the same location by different sensors(E.g. `CAM_FRONT_LEFT` and `CAM_FRONT`) will have different timestamps. Am I missing anything here?
3. I also assume that `v1.0-mini/sample` is a subset of `v1.0-mini/sweep`; however, the filename in `sweep` folder doesn't contain any timestamp in the `sample` folder, why is this?

**Comment by whyekit-motional** [comment]
Here you go, @yanmiao2:

1. I've provided you a working code snippet to both get the corresponding sensor data for the timestamp you indicated above, as well as how to visualize it:
```
my_sample_token = 'fedfb3a6cb804635a0f47143f9ca8d6f'
my_sample = nusc.get('sample', my_sample_token)
assert my_sample['timestamp'] == 1532402938197897

sensor = 'CAM_FRONT'
cam_front_data = nusc.get('sample_data', my_sample['data'][sensor])
print(cam_front_data['filename'])

nusc.render_sample_data(cam_front_data['token'])
```

2. We synchronize the sensor data (image, LIDAR, RADAR) at 2Hz to make up a keyframe (which is what you see in `nusc.sample`), so while the timestamps across sensors for the same sample will not be exactly the same, they should be very close to each other.

3. We separate out the data that belong to samples (a.k.a. the keyframes mentioned in my 2. above) and the remainder of the data. This makes it convenient for users who want to download only the data for samples.

**Comment by yanmiao2** [comment]
I see, now it makes much sense to me. Thank you for being so helpful and patient.
