### ISSUE TITLE
Question about the range of sensors in Zoe Sensors

### ISSUE THREAD

**Issue by zqh0253** [nutonomy/nuscenes-devkit#648]
In the README file of can-bus, it is shown that the range of **Zoe Sensors/brake-sensor** is [0.375,0.411].
![image](https://user-images.githubusercontent.com/32608622/130411163-10a54275-7228-4895-9858-407c0458c01a.png)
But I find out that the brake sensor is not in that range [0.375,0.411].
![image](https://user-images.githubusercontent.com/32608622/130410864-968fc345-e326-4381-b40d-1d8d5d826dad.png)

Steering-sensor and throttle-sensor have the same question that do not has the same range stated in README.
I am confused about this point and want to know the exact range of these three sensors.

**Comment by holger-motional** [comment]
Hi. You are right. Somehow those values are not correct. I wrote this snippet to check all scenes:
```
all_values = []
for scene_id in range(2000):
    scene_name = f'scene-{scene_id:04}'
    try:
        messages = nusc_can.get_messages(scene_name, 'zoesensors')
        values = [m['brake_sensor'] for m in messages]
        all_values.extend(values)
    except:
        continue
        
min(all_values), max(all_values)
```
Result is:
```
(0.16606074571609497, 0.6306231021881104)
```
I'll update the readme to:
```
[0.166, 0.631]
```

Thanks.
