### ISSUE TITLE
How to filt out moving objects like vehicle in point cloud?

### ISSUE THREAD

**Issue by DRosemei** [nutonomy/nuscenes-devkit#650]
Thanks for your great work! I want to know how to filt out moving objects like vehicle in point cloud. I could only find lidar-seg tutorials to render labels I have chosen. But I could not get the **point cloud coordinates.** I follow the code from [lift-spalt-shoot](https://github.com/nv-tlabs/lift-splat-shoot/blob/07b77905c04b590fd17f3ae2b9e312089854504b/src/tools.py#L23)
![image](https://user-images.githubusercontent.com/27892562/131058496-74255307-6677-413a-bb67-7d119d74fc2c.png)
So could someone tell me how to filt the points that I do not need?

**Comment by whyekit-motional** [comment]
Hi @DRosemei,
Here's how I would approach it:
```
import os.path as osp

import matplotlib.pyplot as plt
import numpy as np

from nuscenes.lidarseg.lidarseg_utils import colormap_to_colors
from nuscenes.nuscenes import NuScenes
from nuscenes.utils.data_classes import LidarPointCloud


# Indices of the classes which are dynamic (i.e. objects which can move / be moved).
dynamic_classes = list(range(1, 24))

# Load the nuScenes dataset (mini-split, in this case).
nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=False)

# Get the colors to paint the points with later.
colors = colormap_to_colors(nusc.colormap, nusc.lidarseg_name2idx_mapping)

# Load some random sample token.
sd_record = nusc.get('sample', 'ca9a282c9e77460f8360f564131a8af5')
ref_sd_token = sd_record['data']['LIDAR_TOP']
ref_sd_record = nusc.get('sample_data', ref_sd_token)

# Load pointcloud.
pcl_path = osp.join(nusc.dataroot, ref_sd_record['filename'])
pc = LidarPointCloud.from_file(pcl_path)
points = pc.points.T

# Load labels.
lidarseg_labels_filename = osp.join(nusc.dataroot, nusc.get('lidarseg', ref_sd_token)['filename'])
points_label = np.fromfile(lidarseg_labels_filename, dtype=np.uint8)
assert len(points) == len(points_label)

# Let's render to see what the original pointcloud and its corresponding labels look like.
coloring = colors[points_label]
plt.scatter(points[:, 0], points[:, 1], c=coloring, s=0.2)
plt.gca().set_aspect('equal', adjustable='box')
plt.xlim([-30, 30])
plt.ylim([-30, 30])
plt.show()
plt.close()

# Now, let's filter.
filtered_points = points[~np.isin(points_label, dynamic_classes)]  # `filtered_points` will contain the coordinates of the points of only background classes (i.e. no more moving objects).

print('After filtering {} points, there are {} points left.'.format(len(points), len(filtered_points)))
filtered_points_label = points_label[~np.isin(points_label, dynamic_classes)]
assert len(filtered_points) == len(filtered_points_label)

# Let's render again to confirm that the points belonging to the pointcloud are no longer in `filtered_points`.
coloring = colors[filtered_points_label]
plt.scatter(filtered_points[:, 0], filtered_points[:, 1], c=coloring, s=0.2)
plt.gca().set_aspect('equal', adjustable='box')
plt.xlim([-30, 30])
plt.ylim([-30, 30])
plt.show()
plt.close()

"""
# Do what you want with `filtered_points_label`
"""
```

As an example, you can see that the vehicle (in orange) in front of the ego is now gone:
<img src="https://user-images.githubusercontent.com/62535720/131115842-1f4e88fd-2d8f-4c6b-bfec-3e35812cd6e0.png" width="350">

**Comment by DRosemei** [comment]
@whyekit-motional thanks for your great help!  I have solved it yesterday, and I will do more about point cloud for multi-sweeps

**Comment by Gatsby23** [comment]
> Hi @DRosemei, Here's how I would approach it:
> 
> ```
> import os.path as osp
> 
> import matplotlib.pyplot as plt
> import numpy as np
> 
> from nuscenes.lidarseg.lidarseg_utils import colormap_to_colors
> from nuscenes.nuscenes import NuScenes
> from nuscenes.utils.data_classes import LidarPointCloud
> 
> 
> # Indices of the classes which are dynamic (i.e. objects which can move / be moved).
> dynamic_classes = list(range(1, 24))
> 
> # Load the nuScenes dataset (mini-split, in this case).
> nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=False)
> 
> # Get the colors to paint the points with later.
> colors = colormap_to_colors(nusc.colormap, nusc.lidarseg_name2idx_mapping)
> 
> # Load some random sample token.
> sd_record = nusc.get('sample', 'ca9a282c9e77460f8360f564131a8af5')
> ref_sd_token = sd_record['data']['LIDAR_TOP']
> ref_sd_record = nusc.get('sample_data', ref_sd_token)
> 
> # Load pointcloud.
> pcl_path = osp.join(nusc.dataroot, ref_sd_record['filename'])
> pc = LidarPointCloud.from_file(pcl_path)
> points = pc.points.T
> 
> # Load labels.
> lidarseg_labels_filename = osp.join(nusc.dataroot, nusc.get('lidarseg', ref_sd_token)['filename'])
> points_label = np.fromfile(lidarseg_labels_filename, dtype=np.uint8)
> assert len(points) == len(points_label)
> 
> # Let's render to see what the original pointcloud and its corresponding labels look like.
> coloring = colors[points_label]
> plt.scatter(points[:, 0], points[:, 1], c=coloring, s=0.2)
> plt.gca().set_aspect('equal', adjustable='box')
> plt.xlim([-30, 30])
> plt.ylim([-30, 30])
> plt.show()
> plt.close()
> 
> # Now, let's filter.
> filtered_points = points[~np.isin(points_label, dynamic_classes)]  # `filtered_points` will contain the coordinates of the points of only background classes (i.e. no more moving objects).
> 
> print('After filtering {} points, there are {} points left.'.format(len(points), len(filtered_points)))
> filtered_points_label = points_label[~np.isin(points_label, dynamic_classes)]
> assert len(filtered_points) == len(filtered_points_label)
> 
> # Let's render again to confirm that the points belonging to the pointcloud are no longer in `filtered_points`.
> coloring = colors[filtered_points_label]
> plt.scatter(filtered_points[:, 0], filtered_points[:, 1], c=coloring, s=0.2)
> plt.gca().set_aspect('equal', adjustable='box')
> plt.xlim([-30, 30])
> plt.ylim([-30, 30])
> plt.show()
> plt.close()
> 
> """
> # Do what you want with `filtered_points_label`
> """
> ```
> 
> As an example, you can see that the vehicle (in orange) in front of the ego is now gone: <img alt="" width="350" src="https://user-images.githubusercontent.com/62535720/131115842-1f4e88fd-2d8f-4c6b-bfec-3e35812cd6e0.png">

Could I get the vehicle.moving label and directly remove the "true" moving object？

**Comment by whyekit-motional** [comment]
@Gatsby23 that should be possible as well - just note that the attributes are at the box-level, so you would need to find out which points belong to the boxes you are interested in, and then drop them
