### ISSUE TITLE
How to interpret the covernet fix trajectory set?

### ISSUE THREAD

**Issue by xiaofengz93** [nutonomy/nuscenes-devkit#651]
Hey,
I see there is only 11 points (i assume that they are x, y) in each mode, are they of interval 1 second? it's really large intervals to be considered as trajectory output if they are. And what about the other states like velocity? 
thanks!

**Comment by holger-motional** [comment]
Yes, as you can see on https://www.nuscenes.org/prediction (Results format), the output is:
```
instance: Instance token for agent.
sample: Sample token for agent.
prediction: Numpy array of shape [num_modes, n_timesteps, state_dim]
probabilities: Numpy array of shape [num_modes]
```
and state_dim = 2.

Internally you are free to work with more timesteps, but these are the timesteps sampled for *evaluation*. We don't have any metrics for velocities.
