### ISSUE TITLE
The rotation angle format of ground-truth boxes

### ISSUE THREAD

**Issue by Son-Goku-gpu** [nutonomy/nuscenes-devkit#652]
For the ground truths, the rotation angle starts counting from the negative y axis (for TOP LiDAR coordinate system), when the object rotate clockwisely, the angle becomes positive, otherwise it becomes negative. The range of the angle is [-pi, pi], am I right? Thank you.

**Comment by holger-motional** [comment]
Hi. The rotations are in global coordinates. An angle of 0 degrees around the axis [0, 0, 1] corresponds to looking East (positive x axis). For higher angles we rotate counter clockwise (e.g. 90 degrees is North).

**Comment by Son-Goku-gpu** [comment]
So, the rotation angles are in [-pi, pi], right? Thanks!

**Comment by holger-motional** [comment]
The dataset is stored using quaternions. See also https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/schema_nuscenes.md
