### ISSUE TITLE
Get instances clouds for panoptic segmentation

### ISSUE THREAD

**Issue by owoshch** [nutonomy/nuscenes-devkit#654]
Thank you for your wonderful work!

I'm trying to reuse the training code for SemanticKITTI for Panoptic-PolarNet to train the network on NuScenes (https://github.com/edwardzhou130/Panoptic-PolarNet/blob/main/train.py)

To do so, I need to be able to get a cloud representing particular instance on a certain scene.
I see that I can get instances tokens via `nusc.sample_annotation` but it's still not quite clear for me how can I get the list of all instances on a certain scene with its pointcloud and instance label.

Thank you!

**Comment by owoshch** [comment]
Seems that I got it:
Instead of `nusc.get('lidarseg', sample_token)['filename']` get `nusc.get('panoptic', sample_token)['filename']`

**Comment by holger-motional** [comment]
Hi. 
Glad you managed to fix it.
The issue was that you used uint8, not float32.
See also https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/data_classes.py#L256.
