### ISSUE TITLE
How to split scenes by citys?

### ISSUE THREAD

**Issue by DRosemei** [nutonomy/nuscenes-devkit#657]
I know the data is collected from Boston Seaport, Singapore’s One North, Queenstown and Holland Village districts. But how to split it for each city?  (e.g. scenes-0001~scenes-1111 are from Boston Seaport),

**Comment by holger-motional** [comment]
Take a look at the schema: https://www.nuscenes.org/public/images/nuscenes-schema.svg
The log table has an entry location that you can filter by. Scenes are linked to logs.
