### ISSUE TITLE
get_prediction_challenge_split does not seem to retrieve all data. 

### ISSUE THREAD

**Issue by Juan-Baldelomar** [nutonomy/nuscenes-devkit#661]
I'm currently working with the NuScenes dataset for trajectory forecasting. There is just one thing I don't fully understand.

I'm using the get_prediction_challenge_split to get the <instance_token>_<sample_token> to be able to identify the agents, I've seen your code and it seems like those strings are saved in a .json file and the function retrieves them according to the name of the split ( in my case I am using the mini-train)

But there are only 742 observations of <instance_token>_<sample_token> with 68 differente instances.  

In the other hand, if I traverse the dataset with the nuscenes.sample_annotation and I filter those results by all the agents that are vehicles and all the agents that belong to the mini-train split scenes, I get 6604 unique observations of the form <instance_token>_<sample_token> with 338 different instances. 

That's a huge difference, is there any reason  why the data retrieved by the get_prediction_challenge_split retrieves only those 742 observations saved in the .json file and ignores the other ones? 

Thanks in advance.

**Comment by Juan-Baldelomar** [comment]
I already got the answer from Freddy Boulton, is because of the minimum 6 seconds of horizon in the future.

**Comment by npu-wkl** [comment]
Will there be a situation where the instance has no historical track？

**Comment by whyekit-motional** [comment]
@npu-wkl you could try running `get_prediction_challenge_split` to check: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/prediction/splits.py#L14
