### ISSUE TITLE
artifacts when transforming point clouds into range view

### ISSUE THREAD

**Issue by xyaochen** [nutonomy/nuscenes-devkit#666]
I am trying to convert xyz points into spherical coordinates with LiDAR as the origin, in which x=r * cos(phi) * cos(theta), y=r * cos(phi) * sin(theta), z=r * sin(theta). And want to visulize point clouds that they are arranged as LiDAR beams.

the transforming and visulizing codes as follows:

    radius = torch.sqrt(pts[:, 0].pow(2) + pts[:, 1].pow(2) + pts[:, 2].pow(2))
    sine_theta = pts[:, 2] / radius
    # theta [-pi/2, pi/2]
    theta = torch.asin(sine_theta)
    # phi [-pi, pi]
    phi = torch.atan2(pts[:, 1], pts[:, 0])
    im = torch.zeros(2001, 2001, 3)
    y_img = (phi + math.pi) * 1000 / math.pi
    y_img = y_img.round()
    x_img = (sine_theta + 1) * 1000
    im[x_img, y_img] = 1
    im = im.permute(2, 0, 1)
    vutils.save_image(im, 'rangeview/' + 'sample' + '.jpg')

the results are confusing: 
some range views are exactly arranged well as 32 LiDAR beams
![image](https://user-images.githubusercontent.com/73167393/136490533-5eaa19e4-daee-49eb-8dea-b36329cdcd7a.png)

but many range views have artifacsts that top right corner beams are upwards inclined
![5026501a2f1a5c77864b42cc755b474](https://user-images.githubusercontent.com/73167393/136490488-5a787ee0-9db2-4d90-a132-2c4b0b613a48.png)

Is the inherent noise in nuscenes datasets or are there some wrong in my code or my understanding?

**Comment by holger-motional** [comment]
Hi. Try to work with the provided function https://github.com/nutonomy/nuscenes-devkit/blob/bff4462f0f1b80cf95610aafa409a0c57787560a/python-sdk/nuscenes/nuscenes.py#L834. There are some subtleties here, like:
- Filter by minimum distance, otherwise the vast majority of points will be reflections on the ego car https://github.com/nutonomy/nuscenes-devkit/blob/bff4462f0f1b80cf95610aafa409a0c57787560a/python-sdk/nuscenes/nuscenes.py#L964
- This also removes points *behind* the car.

**Comment by xyaochen** [comment]
> Hi. Try to work with the provided function
> 
> https://github.com/nutonomy/nuscenes-devkit/blob/bff4462f0f1b80cf95610aafa409a0c57787560a/python-sdk/nuscenes/nuscenes.py#L834
> 
> . There are some subtleties here, like:
> * Filter by minimum distance, otherwise the vast majority of points will be reflections on the ego car https://github.com/nutonomy/nuscenes-devkit/blob/bff4462f0f1b80cf95610aafa409a0c57787560a/python-sdk/nuscenes/nuscenes.py#L964
> * This also removes points _behind_ the car.

Thanks for your reply. I haved figured it out. I visulize the curve beam points separately and find it all reflected by ego-vehicle as you point out.

**Comment by jingyibo123** [comment]
> * moves points _behind_ the car.

Upon experiments, I noticed quite a few points beneath the ground, which turn out to be from the 2nd return detection of beams first reflected on ego-vehicle, this could not be filtered by setting a minimum distance. 
We could apply a filter using channel/ring_index and yaw/azimuth angle.
Concern is does that apply to different car setups / surveys? @holger-motional 

Thanks a lot.

**Comment by whyekit-motional** [comment]
@jingyibo123 I suppose, with different cars setups and survey routes, you would have to tune which values to set for those channel / ring _index and yaw / azimuth angle filters
