### ISSUE TITLE
Camera geometry and BEV from multiple camera views.

### ISSUE THREAD

**Issue by VishnuGopireddy** [nutonomy/nuscenes-devkit#672]
Hi,

I am trying to get the camera geometry of all the cameras and lidar (plot their centers and X, Y, Z-axis in a 3D plane). Also trying out Birds Eye View surrounding from the camera parameters. Can anyone please help me out?

**Comment by daohu527** [comment]
@holger-motional We'd better have a picture to illustrate the above coordinate transformation relationship
![Task](https://user-images.githubusercontent.com/10419854/203930601-2233fc6a-7329-4fb3-89a0-6f9ffa4490ad.jpg)
