### ISSUE TITLE
How to build a data loader for tensorflow2 network

### ISSUE THREAD

**Issue by gkd2020** [nutonomy/nuscenes-devkit#673]
Hi, Thanks for your great datasets. I am a new for this research area.
My network is designed for object detection.  And I want to load nuScenes datasets to my network to replace the Kitti datasets. 
I'm confused about how to load the data and evaluate the model. I need to load pointcloud (keyframes and sweeps), label, calibration files. Can you give me some suggestions, such as whether there are specific examples.
Thanks!

**Comment by whyekit-motional** [comment]
@gkd2020 you could take inspiration from the `load_gt` method which is used for the nuScenes detection challenge: https://github.com/nutonomy/nuscenes-devkit/blob/fcc41628d41060b3c1a86928751e5a571d2fc2fa/python-sdk/nuscenes/eval/common/loaders.py#L53
