### ISSUE TITLE
Possible wrong rotation is used in NuScenesExplorer.render_sample_data

### ISSUE THREAD

**Issue by daizhirui** [nutonomy/nuscenes-devkit#674]
Hi, I think L1323 to L1325 in `python-sdk/nuscenes/nuscenes.py` might use the wrong `rotation_vehicle_flat_from_vehicle`. If my understanding is correct, `rotation_vehicle_flat_from_vehicle` is the transformation (without translation) from the ego body frame `E` to an ego body frame `E'` with a zero yaw such that the z-axis is parallel to the world frame `W`. 

The current code is

```python
rotation_vehicle_flat_from_vehicle = np.dot(
                    Quaternion(scalar=np.cos(ego_yaw / 2), vector=[0, 0, np.sin(ego_yaw / 2)]).rotation_matrix,
                    Quaternion(pose_record['rotation']).inverse.rotation_matrix)
```

I think L1323 to L1325 should be

```python
rotation_vehicle_flat_from_vehicle = np.dot(
                    Quaternion(scalar=np.cos(ego_yaw / 2), vector=[0, 0, np.sin(ego_yaw / 2)]).inverse.rotation_matrix,
                    Quaternion(pose_record['rotation']).rotation_matrix)
```

instead of your version,

to firstly map the points in `E` to `W`, then `W` to `E'`.

If I am right, this mistake is not obvious to catch because the roll and pitch are very close to zeros such that `rotation_vehicle_flat_from_vehicle` is almost an identity matrix. But you can still observe the small difference in the visualization.

Thanks!

**Comment by whyekit-motional** [comment]
Hi @daizhirui, the ego pose information within nuScenes is already in the global coordinate frame:
```
`ego_pose` contains information about the location (encoded in translation) and the orientation (encoded in rotation) of the ego vehicle body frame, with respect to the global coordinate system.
```
(Pls see [section 11 of the nuScenes tutorial](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/tutorials/nuscenes_tutorial.ipynb))

So you do not need to map the point from the ego to the world

**Comment by daizhirui** [comment]
The world frame I mention is the global coordinate frame. We need to map the point from the ego to the global coordinate frame, then from the global coordinate frame to the frame that we use for visualization. This is exactly what L1323 to L1325 is doing. However, I think there is a mistake.
