### ISSUE TITLE
bitmap image not aligned with labels

### ISSUE THREAD

**Issue by Young-woong-Cho** [nutonomy/nuscenes-devkit#678]
Hi. Thank you for all the great works.

I have found out that the layers and the bitmap image are not quite well aligned.
Below is the code that I used.

```
import matplotlib.pyplot as plt

from nuscenes.map_expansion.map_api import NuScenesMap
from nuscenes.map_expansion.bitmap import BitMap

nusc_map = NuScenesMap(dataroot='/home/sr/dev/hdmap_parser', map_name='boston-seaport')
bitmap = BitMap(nusc_map.dataroot, nusc_map.map_name, 'basemap')
fig, ax = nusc_map.render_layers(['drivable_area'], figsize=1, bitmap=bitmap)
plt.show()
```
And I see that the bmp image and the layers are not aligned well, as it can be seen from the snipshot below.
![image](https://user-images.githubusercontent.com/84299390/139797909-15500c1b-23c8-400f-b34d-1663e61107e9.png)

**Comment by holger-motional** [comment]
Hi @Young-woong-Cho. You could try whether a simple vertical offset can fix your issue (by eyeballing).
However, generally speaking it may not be possible to do so, since we combined multiple map versions with very small non-linear deformations between them.
