### ISSUE TITLE
Memory leak in render.py 

### ISSUE THREAD

**Issue by chucktang98** [nutonomy/nuscenes-devkit#679]
I believe there's a memory leak in [render.py](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/detection/render.py#L23). My computer crashes when I run this script for 8000 lidar samples (profiled by tracking htop memory usage). I resolved it by changing this [line](https://github.com/nutonomy/nuscenes-devkit/blob/864d0a207539e5383cd3eb26ebb1d7a44622f09d/python-sdk/nuscenes/eval/detection/render.py#L68) from 
`_, ax = plt.subplots(1, 1, figsize=(9, 9))` to `fig, ax = plt.subplots(1, 1, figsize=(9, 9))` and then closing the figure created.

**Comment by holger-motional** [comment]
Hi. Did you set `savepath` ? If you look at https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/detection/render.py#L99-L103, there are two options:
- With savepath: Saves to disk and closes the window.
- Without savepath: Opens the window for you to look at and expects that you will close it.

**Comment by chucktang98** [comment]
Hi, I set savepath and I get the memory issue... if you run with a large enough set of samples you should be able to reproduce?
