### ISSUE TITLE
yaw, pitch, and roll per frame in Kitti_format

### ISSUE THREAD

**Issue by zeina-abuaisheh** [nutonomy/nuscenes-devkit#680]
I used export_kitti.py to convert NuScenes data to Kitti format,
I used the following to get yaw, pitch and roll of the camera (which is the same for all of the frames):

```
            cs_record_cam = self.nusc.get('calibrated_sensor', sd_record_cam['calibrated_sensor_token'])
            angles_camera = np.array(Quaternion(cs_record_cam['rotation']).yaw_pitch_roll) / np.pi * 180

```

How do I get yaw, pitch and roll per frame?

Thanks

**Comment by holger-motional** [comment]
The vehicle translation and rotation are stored in the ego_pose.
Take a look at the tutorial: https://www.nuscenes.org/nuscenes?tutorial=nuscenes
