### ISSUE TITLE
Link to annotator instructions is broken in the nuscenes webpage

### ISSUE THREAD

**Issue by fabrizioschiano** [nutonomy/nuscenes-devkit#681]
I noticed that the link to the annotator instructions on this (https://nuscenes.org/nuscenes#data-format) page is broken. 

It should probably be fixed and link to this (https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/instructions_nuimages.md) page

**Comment by holger-motional** [comment]
Thanks. We will try to fix it in the next few days. The correct link is https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/instructions_nuscenes.md (nuScenes, not nuImages).

**Comment by fabrizioschiano** [comment]
Sorry, I meant to link to that page but got the two pages open and (of course) pasted the wrong link here.

**Comment by holger-motional** [comment]
No worries. Thanks for the feedback!
