### ISSUE TITLE
wrong local camera pose?

### ISSUE THREAD

**Issue by DRosemei** [nutonomy/nuscenes-devkit#682]
I have ploted camera poses of scene-655 and I found that 6 camera poses were not symmetric which could be seen below. 
![image](https://user-images.githubusercontent.com/27892562/140722171-4fc06cbb-0fc3-40b5-87b7-f919ea2239a0.png)
How could I fix this? Thanks in advance.

**Comment by holger-motional** [comment]
How did you plot them? Is it symmetric for other scenes?

**Comment by DRosemei** [comment]
> How did you plot them? Is it symmetric for other scenes?
I choose one pose of scene-0655 as reference and compute all lobal poses according to it. Then I plot translations of these poses. No, it is not symmtric for other scenes.

**Comment by whyekit-motional** [comment]
Perhaps you can post a working code snippet to take a look at how the visualization was done
