### ISSUE TITLE
Issue in project_pose_to_lane

### ISSUE THREAD

**Issue by winckrc** [nutonomy/nuscenes-devkit#683]
The computation for distance_along_lane is:
    distance_along_lane = closest_pose_index * 0.5
I believe the 0.5 should be resolution_meters. The default value for resolution_meters is 0.5, but the distance will be incorrect if the input is change.

**Comment by whyekit-motional** [comment]
Hi @winckrc, thanks for pointing that out! We have fixed it in https://github.com/nutonomy/nuscenes-devkit/pull/685
