### ISSUE TITLE
how are discretize_centerlines created?

### ISSUE THREAD

**Issue by winckrc** [nutonomy/nuscenes-devkit#684]
Both discretize_centerlines and discretize_lanes use arcline_path_3. According to 

https://forum.nuscenes.org/t/lane-path-not-matching-lane-polygon-length/377

arcline_path_3 gives the path of an AV assuming no obstacles instead of true center lines. How were these paths created? Are they based on a path planning algorithm, actual AV motion, or something else?

**Comment by whyekit-motional** [comment]
Hi @winckrc, those paths were manually annotated
