### ISSUE TITLE
Questions about the leaderboard results.

### ISSUE THREAD

**Issue by XuyangBai** [nutonomy/nuscenes-devkit#686]
Hi, thanks for sharing the great database and the toolkit. Several days ago I submited a result with the wrong metadata for the nuScenes tracking benchmark. My method actually uses both LiDAR and camera but I only set use_lidar to True. Is it possible to change the metadata or I have to resubmit a correct .zip file?  

Besides, I would like to know when will the leaderboard (for both tracking and detection) be updated on the main website? Thanks in advance.

Best,
Xuyang.

**Comment by whyekit-motional** [comment]
Hi @XuyangBai, pls send an email to nuScenes@motional.com  with the required submission details: https://github.com/nutonomy/nuscenes-devkit/tree/master/python-sdk/nuscenes/eval/tracking#participation

Also, do state your issue about having made a submission with wrong metadata in that email
