### ISSUE TITLE
Question about transform labels into lidar coordinates

### ISSUE THREAD

**Issue by gkd2020** [nutonomy/nuscenes-devkit#687]
Thanks!
I have two questions about coordinates transform.
1. Labels are in the global coordinate system. Which is the global coordinate system？

![image](https://user-images.githubusercontent.com/59494593/141674057-9a070dd4-cc3c-4719-b3ee-52d195e30470.png)

2. I want to get labels in lidar coordinates, I did the following steps：
```
  ref_lidar_path, ref_boxes, _ = get_sample_data(nusc, ref_sd_token) 
  locs = np.array([b.center for b in ref_boxes]).reshape(-1, 3)
  dims = np.array([b.wlh for b in ref_boxes]).reshape(-1, 3)
  rots = np.array([quaternion_yaw(b.orientation) for b in ref_boxes]).reshape(-1, 1)
  gt_boxes = np.concatenate([locs, dims,  -rots - np.pi / 2], axis=1) ###
  # gt_boxes = np.concatenate([locs, dims, rots], axis=1)                 ###
```
I use `get_sample_data`. Has it converted the yaw angle to the lidar coordinate system? 
Maybe `-rots - np.pi / 2` is no use?I just need to use `gt_boxes = np.concatenate([locs, dims, rots], axis=1)`
```
def get_sample_data(
    nusc, sample_data_token: str, selected_anntokens: List[str] = None
) -> Tuple[str, List[Box], np.array]:
    """
    Returns the data path as well as all annotations related to that sample_data.
    Note that the boxes are transformed into the current sensor's coordinate frame.
    :param sample_data_token: Sample_data token.
    :param selected_anntokens: If provided only return the selected annotation.
    :return: (data_path, boxes, camera_intrinsic <np.array: 3, 3>)
    """

    # Retrieve sensor & pose records
    sd_record = nusc.get("sample_data", sample_data_token)
    cs_record = nusc.get("calibrated_sensor", sd_record["calibrated_sensor_token"])
    sensor_record = nusc.get("sensor", cs_record["sensor_token"])
    pose_record = nusc.get("ego_pose", sd_record["ego_pose_token"])

    data_path = nusc.get_sample_data_path(sample_data_token)

    if sensor_record["modality"] == "camera":
        cam_intrinsic = np.array(cs_record["camera_intrinsic"])
        imsize = (sd_record["width"], sd_record["height"])
    else:
        cam_intrinsic = None
        imsize = None

    # Retrieve all sample annotations and map to sensor coordinate system.
    if selected_anntokens is not None:
        boxes = list(map(nusc.get_box, selected_anntokens))
    else:
        boxes = nusc.get_boxes(sample_data_token)

    # Make list of Box objects including coord system transforms.
    box_list = []
    for box in boxes:

        # Move box to ego vehicle coord system
        box.translate(-np.array(pose_record["translation"]))
        box.rotate(Quaternion(pose_record["rotation"]).inverse)

        #  Move box to sensor coord system
        box.translate(-np.array(cs_record["translation"]))
        box.rotate(Quaternion(cs_record["rotation"]).inverse)

        box_list.append(box)

    return data_path, box_list, cam_intrinsic
```

**Comment by whyekit-motional** [comment]
Hi @gkd2020

1. The global coordinate system is with respect to the map, where `[0, 0, 0]` would be the "top left" corner of the map.

2. The `get_sample_data` [method](https://github.com/nutonomy/nuscenes-devkit/blob/05d05b3c994fb3c17b6643016d9f622a001c7275/python-sdk/nuscenes/nuscenes.py#L255) should already return the bounding boxes in the sensor frame (both for translation and rotation), so I don't think you need to do any extra transformations

**Comment by gkd2020** [comment]
hi, @whyekit-motional 
Sorry，I am still confused about  “ the map ” and  " top left ".  Does the map refer to maps folder？ How to define the XYZ axis of the global coordinate system？Could you give more details？

Thanks！

**Comment by whyekit-motional** [comment]
@gkd2020 yes, you are exactly right - the map refers to one of the maps in the `maps` folder

You can determine which map a sample belongs to by doing:
```
from nuscenes import NuScenes

nusc = NuScenes('v1.0-mini', dataroot='/data/sets/nuscenes', verbose=False)

sample = nusc.sample[0]
scene = nusc.get('scene', sample['scene_token'])
log = nusc.get('log', scene['log_token'])
map_ = nusc.get('map', log['map_token'])
print(map_['filename'])
```

Since the map is a rectangle, then the origin of that map is simply the top left corner of that rectangle, whereby:

- The positive x-direction would be going from the top left corner to the top right corner along the top edge of that rectangle
- The positive y-direction would be going from the top left corner to the bottom left corner along the left edge of that rectangle
- The positive z-direction would be towards you perpendicular to the plane of that rectangle

Here's an illustration as well:

<img src="https://user-images.githubusercontent.com/62535720/141963702-10fb523f-a70e-42de-a3fd-709492d43efc.png" height=250px>

**Comment by gkd2020** [comment]
@whyekit-motional  I got it. Thank you for your clear reply！

**Comment by Petros626** [comment]
@yutong-yang-mb did you find it out?
