### ISSUE TITLE
Tracking Challenge PointPillars Detection Baseline, Too Many Detections

### ISSUE THREAD

**Issue by CalvinKroese** [nutonomy/nuscenes-devkit#688]
I am attempting to utilize the PointPillars Detections (https://www.nuscenes.org/tracking?externalData=all&mapData=all&modalities=Any, Detections download. pointpillars-val.json) to analyze the performance of my deterministic tracking system, and am running into a case where there are hundreds of detections, but only a single annotated object in the sample sample frame. 

I am utilizing ijson to parse the raw json file provided, splitting up the detected objects in a given sample frame and writing it to a ROS bagfile which I can then utilize for evaluating my tracking system. 

The problem I am having is that per sample token I am seeing upwards of 400 detected objects with detection_name 'car' or 'pedestrian' in a sample with only one object.

For example sample token: b9c60cfaf1814c8bb363037dec7abd35

with the following camera views:
![image](https://user-images.githubusercontent.com/21249830/142909372-7730722f-bbf7-4104-81f8-fe55bd49ea1e.png)
![image](https://user-images.githubusercontent.com/21249830/142909473-9d704230-71a0-4d37-9cf6-def3b58ad6ae.png)
![image](https://user-images.githubusercontent.com/21249830/142909508-f64a9b44-027d-4af5-8126-c06106e263e6.png)
![image](https://user-images.githubusercontent.com/21249830/142909544-651498e4-1e9a-4b25-811c-7b9b6f66ba64.png)
![image](https://user-images.githubusercontent.com/21249830/142909576-9c4062e2-b1d5-4ca7-af70-7e01614b8632.png)
![image](https://user-images.githubusercontent.com/21249830/142909609-110e96b5-1fc9-466f-8c13-906601abc842.png)

results 396 'cars' or 'pedestrians' in the sample frame. Which I am then visualizing in rviz displays the following:
![image](https://user-images.githubusercontent.com/21249830/142909784-1e828d07-5773-47f3-909a-513e5dd13610.png)
Where each blue cube is a detection of the size, orientation and translation provided from the json. This large number of detections can also be verified by simply running:

 grep -nr 'b9c60cfaf1814c8bb363037dec7abd35*' .

In the directory where the files are located. Since each detection begins with the sample_token it will show all the scene results frame and all detections from that frame. Which also displays this high number of results.

I would highly appreciate some help with this, as I am assuming I am making some incorrect assumption about the data provided.

Thanks,

Calvin

**Comment by whyekit-motional** [comment]
Hi @CalvinKroese, try filtering the json with a threshold on `detection_score` (i.e. get only objects with `detection_score` more than, say, `0.9`)

**Comment by CalvinKroese** [comment]
Ahhhh. Yes, that worked... Thanks so much, should have thought of that!
