### ISSUE TITLE
3D to 2D projection in pixel coordinates on camera image

### ISSUE THREAD

**Issue by abadithela** [nutonomy/nuscenes-devkit#689]
Hi!

I'm trying to match bounding boxes from a pertained YoLo network to the 2D projections of bounding boxes in NuScenes. I'm getting the pixel corners of the image using the viewpoints and post_process_coords functions:

```  
    %Project 3d box to 2d.
    corner_coords = view_points(corners_3d, camera_intrinsic, True).T[:, :2].tolist()
    corner_coords_list.append(corner_coords)
    box_2D = post_process_coords(corner_coords)
    box_pixel_nuscene.append(box_2D)
```

These are the ground truth annotation boxes (in 3D) for the detection challenge
![3d_image](https://user-images.githubusercontent.com/13437374/142960932-cf602167-8f85-4c3c-bbfc-185b3f3db537.png)
:

However, when I try to render the 2D projections onto the image frame, I do not get the right results:

<img width="535" alt="Screen Shot 2021-11-22 at 6 15 11 PM" src="https://user-images.githubusercontent.com/13437374/142962029-3b14c694-27ee-459b-8008-94574706fc08.png">

Specifically, I render the 2D boxes as follows:

1. Load the image:
`img = cv2.imread(data_path_f) # Successfully reading data`

2. Function to render 2D boxes (in pixel coordinates) on the image frame. Note that box argument in the following functions represents in pixel dimensions: (x,y, wx, wy), where (x,y) are the pixel coords of the lower-left corner, and wx is the width of the 2D bounding box in the x-dimension and wy is the width of the bounding box along the y-dimension. On the image, x-axis points to the right and y-axis points upward.

```
def plot_pixel_boxes(box, img, a, plot_labels=True, color = None):
    colors = torch.FloatTensor([[1,0,1],[0,0,1],[0,1,1],[0,1,0],[1,1,0],[1,0,0]])
    
    def get_color(c, x, max_val):
        ratio = float(x) / max_val * 5
        i = int(np.floor(ratio))
        j = int(np.ceil(ratio))
        
        ratio = ratio - i
        r = (1 - ratio) * colors[i][c] + ratio * colors[j][c]
        return int(r * 255)
    
    width = img.shape[1]
    height = img.shape[0]
    
    a.imshow(img)
    
    % Set the default rgb value to red
    rgb = (1, 0, 0)
    x1 = box[0]
    y2 = box[1]
    
    % Use the same color to plot the bounding boxes of the same object class
    if len(box) >= 7 and class_names:
        cls_conf = box[5]
        cls_id = box[6]
        classes = len(class_names)
        offset = cls_id * 123457 % classes
        red   = get_color(2, offset, classes) / 255
        green = get_color(1, offset, classes) / 255
        blue  = get_color(0, offset, classes) / 255

        % If a color is given then set rgb to the given color instead
        if color is None:
            rgb = (red, green, blue)
        else:
            rgb = color

    % Calculate the width and height of the bounding box relative to the size of the image.
    width_x = box[2]
    width_y = box[3]
        
    rect = patches.Rectangle((x1, y2),
                                     width_x, width_y,
                                     linewidth = 2,
                                     edgecolor = rgb,
                                     facecolor = 'none')

    % Draw the bounding box on top of the image
    a.add_patch(rect)
    plt.show()
```

3. We use the same plot_boxes function to plot the YoLo  (pertained; not trained on nuscenes) detection boxes and they find the objects quite well:
<img width="556" alt="Screen Shot 2021-11-22 at 6 15 30 PM" src="https://user-images.githubusercontent.com/13437374/142962009-4df45560-aeb6-41bd-a116-6d048b49c8c4.png">

I'm using the same plot_pixel_boxes function to get the third image. 

So, my questions are:
1. How do I properly render the 2D bounding boxes on the image? 
   A) Do I use the render_cv2 function? However, this seems to deal with radar or lidar point clouds and not just image data. Still, would render_cv2 give me the 2d bounding box given by the pixel coordinates?
   B) I'm perhaps not downloading the image properly; it seems like the pixel coordinates are very off from the second figure. 

**My goal is to match the bounding boxes from the perception algorithm (ex: yoLo) to the 2d pixel bounding boxes from the nuscenes dataset to count whether or not that object has been properly detected.**

Thanks!

**Comment by whyekit-motional** [comment]
Hi @abadithela, there is a script which you can use to convert 3D boxes to 2D in nuScenes: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_2d_annotations_as_json.py 

This should save you time and effort having to re-invent the wheel :)

**Comment by abadithela** [comment]
Hi @whyekit-motional, thanks, I will take a closer look at that function. I believe I am using the 2D coordinates found by that function (if you look at lines 148 and 151 of that file, which is exactly what I use in my code for getting the 2D projections). However, my question is on **rendering that 2D projection on an image**. Is there a function that does this? Does render_cv2 do this? I've tried rendering it above with my function plot_box_pixels but that doesn't seem to give the right bounding boxes. I think its a small issue regarding the image resizing but I cannot see what the error is.

**Comment by whyekit-motional** [comment]
@abadithela you might want to check on the format of the box coordinates

E.g. the output of L151 is `(min_x, min_y, max_x, max_y)` as can be inferred from:
https://github.com/nutonomy/nuscenes-devkit/blob/05d05b3c994fb3c17b6643016d9f622a001c7275/python-sdk/nuscenes/scripts/export_2d_annotations_as_json.py#L157

However, your function ingests boxes with `(x,y, wx, wy)` format

So if you are using the outputs of L148 and L151 exactly, then you may need to convert between the two box formats.

**Comment by abadithela** [comment]
@whyekit-motional I did convert between the 2 box coordinates but the output is still off. I'm pretty sure the issue is with how the image is loaded. I'm using cv2.imread; perhaps I'm loading it at a different resolution than the pixel coordinates of the 2D bounding box. Do you know which resolution these pixel coordinates correspond to?

**Comment by whyekit-motional** [comment]
@abadithela the image resolution should be `W x H = 1600 x 900`:
https://github.com/nutonomy/nuscenes-devkit/blob/05d05b3c994fb3c17b6643016d9f622a001c7275/python-sdk/nuscenes/scripts/export_2d_annotations_as_json.py#L29
