### ISSUE TITLE
Do we have left/right connectivity for lanes?

### ISSUE THREAD

**Issue by gobear6212** [nutonomy/nuscenes-devkit#690]
Hi, how can I retrieve the lane on the left/right of the target lane? In map_api the connectivity only tells incoming and outgoing lanes, but I somehow need to access neighbouring lanes as well - any idea how I can achieve that?

Update: the way I approach this is by retrieving all lanes in a patch, then store the node tokens of all of their lane divider segments and look for matches in another loop (e.g. find if any lane `lane_a` has a right_lane_divider_segments overlapping with some other lane `lane_b`'s left_lane_divider_segments, if yes then I call `lane_b` the right neighbour of `lane_a`). However, I'm not sure if I'd miss any pairs.

**Comment by whyekit-motional** [comment]
@gobear6212 I think your approach makes sense
