### ISSUE TITLE
getting the height of the camera

### ISSUE THREAD

**Issue by zeina-abuaisheh** [nutonomy/nuscenes-devkit#691]
Hello,

where could I find the height of the camera in meters for NuScenes videos?

Thanks a lot

**Comment by holger-motional** [comment]
Hi. The sensor extrinsics are with respect to the base link, which is at the center of the rear axle, but projected to the ground. Hence you can read the camera height straight from the calibrated_sensor.json. You just need to check sensor.json to find out which token corresponds to which camera, e.g.:
```
{
"token": "725903f5b62f56118f4094b46a4470d8",
"channel": "CAM_FRONT",
"modality": "camera"
},
```
Then we can search for that with `cat /data/sets/nuscenes/v1.0-mini/calibrated_sensor.json | grep -A 4 725903f5b62f56118f4094b46a4470d8`:
```
"sensor_token": "725903f5b62f56118f4094b46a4470d8",
"translation": [
1.72200568478,
0.00475453292289,
1.49491291905
--
"sensor_token": "725903f5b62f56118f4094b46a4470d8",
"translation": [
1.70079118954,
0.0159456324149,
1.51095763913
...
```
So the height of the front camera is about 1.50m.

**Comment by zeina-abuaisheh** [comment]
thanks so much

**Comment by sunnyHelen** [comment]
So, the height of ego frame is 0 or 0.12m? if the height of the rear axle is 0.12m.
