### ISSUE TITLE
TP, FP, TN, FN and confusion matrix

### ISSUE THREAD

**Issue by mfafi** [nutonomy/nuscenes-devkit#693]
Hello,

Thanks a lot for the code. I'm a little confused on how to get the total number of true positives, false positives, true negatives and false negatives per class. In addition to that, I would to print the confusion matrix. Do you happen to have a function to perform that? 

PS I've found TP and FP in here [(https://github.com/nutonomy/nuscenes-devkit/blob/05d05b3c994fb3c17b6643016d9f622a001c7275/python-sdk/nuscenes/eval/detection/algo.py#L127 ] but the shape doesn't correspond to what I'm expecting.

Thank you for your help :)

**Comment by whyekit-motional** [comment]
@mfafi there isn't a method that prints the confusion matrix, but if you share what you are seeing with regards to `but the shape doesn't correspond to what I'm expecting`, we can work through it together
