### ISSUE TITLE
The polygon token retrive invalid shapely polygon

### ISSUE THREAD

**Issue by Mrmoore98** [nutonomy/nuscenes-devkit#694]
Hi

When I call the `_get_layer_polygon` function in `NuScenesMapExplorer`, I have found a polygon is invalid.
the polygon token is `43e22c72-d1bf-4f95-a1cf-81ea98b3e778` and the layer name is `road_segement` in `boston-seaport`.

However I haven't found any reason for why this polygon is invalid by visualization.

**Comment by Mrmoore98** [comment]
FYI, when I set the buffer of aformentioned polygon to zero and the polygon becomes valid. So I think this may be a bug in `_get_layer_polygon `.

**Comment by whyekit-motional** [comment]
@Mrmoore98 the road segment you mentioned looks ok on my end; here's some code to reproduce it:
```
from nuscenes.map_expansion.map_api import NuScenesMap


nusc_map = NuScenesMap(dataroot='/data/sets/nuscenes', map_name='boston-seaport')

for pp in nusc_map.road_segment:
    if pp['polygon_token'] == '43e22c72-d1bf-4f95-a1cf-81ea98b3e778':
        fig, ax = nusc_map.render_record('road_segment', pp['token'], other_layers=[])
        break
```
![polygon](https://user-images.githubusercontent.com/62535720/146746838-a69831e6-272e-4347-94c8-b3241de348d9.png)

Without a code snippet to reproduce the error you are seeing, I can't say for sure what's causing the error for you
