### ISSUE TITLE
Does nuImages dataset provide scene descriptions?

### ISSUE THREAD

**Issue by QiuJueqin** [nutonomy/nuscenes-devkit#695]
Scene descriptions (weather/night/...) are provided for nuScenes, but I didn't find similar schema for nuImages. Is it possible to get such descriptions for images in nuImages?

**Comment by holger-motional** [comment]
Hi. Unfortunately not. nuScenes has 1000 scenes, so it was easy to have a human expert review them and write descriptions.
nuImages has nearly 100k annotated images/clips, so we considered this unfeasible.

**Comment by QiuJueqin** [comment]
@holger-motional Thanks. I filtered out night images by conditioning the timestamp recorded in the filename.
