### ISSUE TITLE
Confusion about the process of lane discretization

### ISSUE THREAD

**Issue by ultimatedigiman** [nutonomy/nuscenes-devkit#696]
This issue is about `arcline_path_utils.py`

So far as I know, each `arcline_path` is divided into 3 segment. To get the coordinates of  a pose at `s` meters along the arcline path, first find out which of the 3 segment this pose is located, then calculate the arcline path distance from the starting point of the segment found.
Let's denote the radius of the curvature of the segment as `r` and assume the shape of the segment is `L` (left). 

Then function `get_transformation_at_step()`  will output the `xy` distance from the starting point of the segment after **Rotation Transformation**：(`sin\theta` * `r`,   `(1-cos\theta)` * `r`, `theta` )

Finally, function `apply_affine_transformation()` will output the final coordinates.
My confusion is indeed about the `apply_affine_transformation()` function:
My understanding is `pose[2]` is the **yaw** of  the starting pose，why does this function rotate the distance (`sin\theta` * `r`,   `(1-cos\theta)` * `r`)  by  `pose[2]` radians counterclockwise? why rotate the distance? why rotate `pose[2]` radians?
https://github.com/nutonomy/nuscenes-devkit/blob/05d05b3c994fb3c17b6643016d9f622a001c7275/python-sdk/nuscenes/map_expansion/arcline_path_utils.py#L79-L92

Is there any tutorial or illustration of this process?

**Comment by whyekit-motional** [comment]
@ultimatedigiman perhaps try plotting the poses before and after `apply_affine_transformation` to visualize what is going on

**Comment by ultimatedigiman** [comment]
I've already figured this out. Just leave it here to help others in need.

`get_transformation_at_step(pose, step)` will return (x, y) in the local coordinate system of the input `pose`, the coordinate origin of the local coordinate system is the starting point of the segment.

Then `apply_affine_transformation(pose, transformation)` first rotates the local coordinate system to global coordinate system while keeping the coordinate origin at  the starting point of the segment. Finally add the global coordinate of the starting point of the segment to move the origin to global origin.
