### ISSUE TITLE
Tracking challenge: Only <= 500 boxes per sample allowed!

### ISSUE THREAD

**Issue by BaiLiping** [nutonomy/nuscenes-devkit#697]
Hi, when i submit the json file for the tracking challenge as specified by the webisite, i got the following error prompt. Yet i checked the result, there are at most 58 bounding boxes per sample, so not sure why it says i have over 500 bboxes per sample?

Traceback (most recent call last):
  File "/code/scripts/workers/submission_worker.py", line 491, in run_submission
    submission_metadata=submission_serializer.data,
  File "/tmp/tmppdezx0d_/compute/challenge_data/challenge_476/main.py", line 98, in evaluate
    verbose=verbose)
  File "/usr/local/lib/python3.7/site-packages/nuscenes/eval/tracking/evaluate.py", line 84, in __init__
    verbose=verbose)
  File "/usr/local/lib/python3.7/site-packages/nuscenes/eval/common/loaders.py", line 48, in load_prediction
    "Error: Only <= %d boxes per sample allowed!" % max_boxes_per_sample
AssertionError: Error: Only <= 500 boxes per sample allowed!

**Comment by whyekit-motional** [comment]
@BaiLiping the above error seems to belong to [submission 174353](https://evalai.s3.amazonaws.com/media/submission_files/submission_174353/2d228a07-53b4-495f-bafb-85737230ed9a.txt) on EvalAI.

I did some debugging on your behalf and it seems that there are multiple sample tokens in your `submission.json` which have > 500 boxes.

For reproducibility, here's the code snippet which I used to parse and debug your submission:
```
import json
from typing import Dict, Tuple

from nuscenes.eval.common.config import config_factory
from nuscenes.eval.common.data_classes import EvalBoxes
from nuscenes.eval.tracking.data_classes import TrackingBox


def load_prediction(result_path: str, max_boxes_per_sample: int, box_cls, verbose: bool = False) \
        -> Tuple[EvalBoxes, Dict]:
    """
    Loads object predictions from file.
    :param result_path: Path to the .json result file provided by the user.
    :param max_boxes_per_sample: Maximim number of boxes allowed per sample.
    :param box_cls: Type of box to load, e.g. DetectionBox or TrackingBox.
    :param verbose: Whether to print messages to stdout.
    :return: The deserialized results and meta data.
    """

    # Load from file and check that the format is correct.
    with open(result_path) as f:
        data = json.load(f)
    assert 'results' in data, 'Error: No field `results` in result file. Please note that the result format changed.' \
                              'See https://www.nuscenes.org/object-detection for more information.'

    # Deserialize results and get meta data.
    all_results = EvalBoxes.deserialize(data['results'], box_cls)
    meta = data['meta']
    if verbose:
        print("Loaded results from {}. Found detections for {} samples."
              .format(result_path, len(all_results.sample_tokens)))

    # Check that each sample has no more than x predicted boxes.
    for sample_token in all_results.sample_tokens:
        if len(all_results.boxes[sample_token]) >= max_boxes_per_sample:
            print(f'There are {len(all_results.boxes[sample_token])} boxes for sample token {sample_token}')

    return all_results, meta



cfg_ = config_factory('tracking_nips_2019')

load_prediction('submission.json', 500, TrackingBox)
```

The output looks something like:
```
There are 501 boxes for sample token b84954bdd6f44145ae25d66d3a36fe61
There are 761 boxes for sample token 1e4818b3b2354b87ba1b40b7a8d13ed5
There are 732 boxes for sample token afbb06fbf80a4d53a5435456801c6b67
...
```
