### ISSUE TITLE
How can I identify the train set and the validation set in the 850 scenes of the full dataset?

### ISSUE THREAD

**Issue by Cheungki** [nutonomy/nuscenes-devkit#698]
Thanks for attention.

**Comment by whyekit-motional** [comment]
@Cheungki you can simply do this:
```
from nuscenes.utils.splits import create_splits_scenes


splits = create_splits_scenes()
print(f'These are the splits in nuScenes: {list(splits.keys())}')
```

You can then check out the scenes belonging to, say, the validation split by doing:
```
splits['val']
```
This gives:
```
['scene-0003',
 'scene-0012',
 'scene-0013',
 'scene-0014',
 'scene-0015',
 ...]
```

**Comment by Cheungki** [comment]
thx a lot

**Comment by wannapg** [comment]
How do we do this in nuImages dataset?

**Comment by holger-motional** [comment]
@wannapg The splits are in the DB files. They take different names:
https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuimages/nuimages.py#L37
