### ISSUE TITLE
the relationship between the coordinate system ? 

### ISSUE THREAD

**Issue by ray401** [nutonomy/nuscenes-devkit#699]
hi, i have some questions about the relationship between the coordinate systems.
1. Is the calibrated_sensor.json depicts the extrinsic parameter between the sensor coordinate and the ego coordiante ? if the origin the ego coordinate is the center of the rear axle projected onto the ground, so where does the axes point to ? is it fixed orientation ?
2. Is the orientation of imu coordinate fixed ? does the x. y. z axes always point to east. north. sky direction ?
3. Does the 'rotation' and 'translation' in the ego_pose.json file depicts the relationship between world coordinate and ego coordinate ?
or between world coordinate and imu coordinate ?

**Comment by whyekit-motional** [comment]
@ray401, I hope the following will help in clarifying your queries:

> 1. Is the calibrated_sensor.json depicts the extrinsic parameter between the sensor coordinate and the ego coordiante ? if the origin the ego coordinate is the center of the rear axle projected onto the ground, so where does the axes point to ? is it fixed orientation ?

As can be seen from [the `calibrated_sensor` schema of nuScenes](https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/schema_nuscenes.md#calibrated_sensor), 
```
All extrinsic parameters are given with respect to the ego vehicle body frame. All camera images come undistorted and rectified.
```
For the global coordinate system x and y points along the ground, z straight up in the direction of gravity.
<br>
<br>


> 2. Is the orientation of imu coordinate fixed ? does the x. y. z axes always point to east. north. sky direction ?

For the coordinate frame orientation of the IMU, please refer to https://www.nuscenes.org/public/images/data.png (the same image can also be found under "Car Setup" under https://www.nuscenes.org/nuscenes#data-collection).
<br>
<br>


> 3. Does the 'rotation' and 'translation' in the ego_pose.json file depicts the relationship between world coordinate and ego coordinate? Or between world coordinate and imu coordinate ?

`ego_pose` contains information about the location (encoded in translation) and the orientation (encoded in rotation) of the ego vehicle, with respect to the global coordinate system.

**Comment by ray401** [comment]
@whyekit-motional thanks a lot. but i still have some confusion.
Is the axes direction of the ego coordinate consistent with imu coordinate direction ?
in another word, there is only a distance in z axes between ego coordinate and imu coordinate ?

**Comment by whyekit-motional** [comment]
@ray401, yes the reference is the IMU which is located roughly at the center of the rear axle.

**Comment by ray401** [comment]
@whyekit-motional thanks a lot.
I want to know what is the imu coordinate?

for example, in can_bus/scene-0001_ms_imu file, the "rotation rate" value and "linear_accel" ,  what coordinate system is the value in ?
-----
or in your settings, what is the navigation frame and body frame ? 
Thanks in advance,
