### ISSUE TITLE
Render scene without bboxes

### ISSUE THREAD

**Issue by eeeeenchanted** [nutonomy/nuscenes-devkit#702]
Hi, I tried to render the video using `render_scene_channel` function, but it would also render all the bounding boxes of objects in the scene. I'm wondering is there a way I can render the video without bboxes, i.e., just the original video? Or can you please add an option to the `render_scene_channel` function to let user decide whether to render bboxes or not? Thank you!

**Comment by whyekit-motional** [comment]
@eeeeenchanted if there is sufficient demand for `render_scene_channel` to have an option to disable rendering of bboxes, that can be considered in future. 

Meanwhile, it should be fairly straightforward for you to do so locally by simply commenting out this line of code:
https://github.com/nutonomy/nuscenes-devkit/blob/05d05b3c994fb3c17b6643016d9f622a001c7275/python-sdk/nuscenes/nuscenes.py#L1758

**Comment by kajc10** [comment]
Can I render sample data without bounding boxes?
used: `nusc.render_sample_data(sample['data']['CAM_FRONT'])`
