### ISSUE TITLE
How to use bbox data in sample_annotation.json?

### ISSUE THREAD

**Issue by yyxssm** [nutonomy/nuscenes-devkit#703]
Hi, thanks for attention! I'm new in using Lidar data to machine learning,  so my problem may be trivial to you, or even some don't make sense.

I want to do object detection mission, and I am trying giving 3D bounding box to the raw Lidar data. And I use  `v1.0-mini`. My questions are:

1. Do every point clouds in  `.pcd.bin` file have labels? For example, the exact point cloud is a vehicle. Or they only have the ground truth boxes data like:
```
{
"token": "70aecbe9b64f4722ab3c230391a3beb8",
"sample_token": "cd21dbfc3bd749c7b10a5c42562e0c42",
"instance_token": "6dd2cbf4c24b4caeb625035869bca7b5",
"visibility_token": "4",
"attribute_tokens": [
"4d8821270b4a47e3a8a300cbec48188e"
],
"translation": [
373.214,
1130.48,
1.25
],
"size": [
0.621,
0.669,
1.642
],
"rotation": [
0.9831098797903927,
0.0,
0.0,
-0.18301629506281616
],
"prev": "a1721876c0944cdd92ebc3c75d55d693",
"next": "1e8e35d365a441a18dd5503a0ee1c208",
"num_lidar_pts": 5,
"num_radar_pts": 0
}
```

2. How to use the bounding box to train the model?   
      I want give bounding boxes to point clouds, just like what we do in CV object detection mission. But the difference between point clouds and pictures is that point clouds stored in `.pcd.bin` file are unordered. So my question is: how to train a model that can give bounding box to raw point clouds, so that I can let the computer know that this point clouds cluster forms a vehicle, and the others forms a motor?   Is there any code sample?

3. Is it possible for me to make a dataset that every point cloud is labeled?

**Comment by holger-motional** [comment]
1.+3. To use the point level labels, refer to Panoptic nuScenes: https://www.nuscenes.org/nuscenes#lidarseg
2. That's a complex research topic. I suggest you read some papers like our https://arxiv.org/pdf/1812.05784.pdf or look at 3rd party code like https://github.com/open-mmlab/mmdetection3d.
