### ISSUE TITLE
Understanding the nuScenes for GNNs

### ISSUE THREAD

**Issue by ekurtgl** [nutonomy/nuscenes-devkit#704]
Hi all,

Thank you for the wonderful dataset. I followed the tutorials to better understand it. I am kind of new to point clouds and trying to understand how to use LiDAR pointcloud dataset with graph neural networks (GNNs). What should be the right workflow for such an application? (e.g. loading all the point clouds, storing them in an array, forming a graph, training the model etc.). As there are lots of modules and methods in the repo, I am kind of lost. I don't know which function to use for what. If you can provide me some starting points, guidelines or refer some tutorials/github repos that would be great. Thanks in advance!

Best,
Emre

**Comment by whyekit-motional** [comment]
@ekurtgl your question isn't directly related to the devkit, but I'll still try to answer it :smile: 

I've previously come across some GNN-related papers which make use of nuScenes:

- https://arxiv.org/pdf/1910.08233.pdf
- https://openaccess.thecvf.com/content/ICCV2021W/AVVision/papers/Meyer_Graph_Convolutional_Networks_for_3D_Object_Detection_on_Radar_Data_ICCVW_2021_paper.pdf

You could try reaching out to the authors of those papers to understand how they made use of nuScenes in their workflow
