### ISSUE TITLE
the relationship between ego, global and IMU

### ISSUE THREAD

**Issue by qfwysw** [nutonomy/nuscenes-devkit#706]
Is ego coordinate system the same as IMU coordinate system?
Whether the world coordinate system and IMU coordinate system have the same direction and different positioning points?

**Comment by whyekit-motional** [comment]
@qfwysw hopefully these helps you:

- the ego frame is with reference to the center of the rear axle (approximately where the IMU is at) projected to the ground
- the world (aka global frame) is with reference to the top left corner of the respective maps, and the direction of the axes can be different from that of the IMU's
