### ISSUE TITLE
distribution of 3d bounding box size(distribution) across all classes

### ISSUE THREAD

**Issue by TianhaoFu** [nutonomy/nuscenes-devkit#707]
Hi,
I want to knoe the distribution of 3d bounding box size(distribution) distribution, how can i get it？Can you give me some visualization results or code？

I read the original paper of nuscenes and found that there is only a size distribution for cars, not a bounding box distribution for all categories.

Thanks!
:)

**Comment by whyekit-motional** [comment]
@TianhaoFu getting the distribution of the widths, lengths and heights across all the boxes in nuScenes should be pretty trivial; one possible way to do it could be:
```
import numpy as np
import matplotlib.pyplot as plt

from nuscenes.nuscenes import NuScenes


# Load the nuScenes dataset (mini-split, in this case).
nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=False)

sizes = np.array([sample_ann['size'] for sample_ann in nusc.sample_annotation])

for i in range(sizes.shape[-1]):
    n, bins, patches = plt.hist(sizes[:, i])
    plt.show()
```
