### ISSUE TITLE
The meaning of ArcLinePath shape and how to find neighbor lanes

### ISSUE THREAD

**Issue by sepehrilami** [nutonomy/nuscenes-devkit#708]
Hello
Thanks for your open-source code. It is greatly useful.
I have two problems with data. First, each lane is a list of ArcLinePath objects. Each ArcLinePath has a "shape" attribute which is a 3-letter string. What exactly is this "shape" indicating? (I have visualized the lanes and didn't get their meaning.) Why isn't this attribute the same for all ArcLinePaths of a specific lane?
Second, is there any way to distinguish left/right neighbor lanes of a lane (if there is)? I understand that we can use trajectories for this task, but I'm asking if there is a more reliable solution.

Thank you very much!

**Comment by whyekit-motional** [comment]
@sepehrilami based on this, I think `L`, `S` and `R` represent `left`, `straight` and `right` respectively: https://github.com/nutonomy/nuscenes-devkit/blob/05d05b3c994fb3c17b6643016d9f622a001c7275/python-sdk/nuscenes/map_expansion/arcline_path_utils.py#L28

I'm not the original author of the code, so I can't say for sure though
