### ISSUE TITLE
Radar velocity from multi-sweep

### ISSUE THREAD

**Issue by dbm9741** [nutonomy/nuscenes-devkit#710]
I am trying to figure out how to load multiple radar sweeps with the correct velocities.
In viewing multi radar sweeps:
https://github.com/nutonomy/nuscenes-devkit/blob/05d05b3c994fb3c17b6643016d9f622a001c7275/python-sdk/nuscenes/nuscenes.py#L1299-L1310
The code here is just transforming all the velocity from the radar coordinate to lidar. But shouldn't each previous sweep's velocity be first converted to the current frame using their own previous ego_pose? Or it doesn't make a difference?

So do I need to convert my previous sweep velocity to the current velocity, by rotating from previous_sensor to previous_ref to world and then to current?

Thank you for your help

**Comment by whyekit-motional** [comment]
@dbm9741 do take a look at `from_file_multisweep`: https://github.com/nutonomy/nuscenes-devkit/blob/05d05b3c994fb3c17b6643016d9f622a001c7275/python-sdk/nuscenes/utils/data_classes.py#L58

The transformations are happening in there
