### ISSUE TITLE
About Download the Dataset

### ISSUE THREAD

**Issue by zhangchbin** [nutonomy/nuscenes-devkit#711]
Hi, how can I download the dataset by ```wget``` on Linux Server? It will be ```ERROR 403 : Forbidden``` when I use ```wget link```.

**Comment by whyekit-motional** [comment]
@zhangchbin pls take a look at https://github.com/nutonomy/nuscenes-devkit/issues/110#issuecomment-480072630

**Comment by ShoufaChen** [comment]
hello @whyekit-motional 

Failed with wget:

```
--2022-03-30 20:07:33--  https://s3.amazonaws.com/data.nuscenes.org/public/v1.0/v1.0-mini.tgz%5C?AWSAccessKeyId%5C=AKIA6RIK4RxxxKM7AM2%5C&Signature%5C=WrPxxxxSXoBxqMf9u%2BiD6LuE%3D%5C&Expires%5C=1649073766
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.217.172.240
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.217.172.240|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2022-03-30 20:07:34 ERROR 403: Forbidden.
```

**Comment by ShoufaChen** [comment]
Thanks very much for @whyekit-motional help.

The problem is that when I copy-paste the link to the iTerm terminal, some `\`s  are automatically inserted into the link.

Solved by remove these `\`.

**Comment by weixi234** [comment]
When I click on "US" or "Asia" and there is no response, I don't know how to handle it.

**Comment by whyekit-motional** [comment]
@weixi234 the links for both US and Asia are working on my end - you could check if you have a stable connection and whether you are behind a firewall
