### ISSUE TITLE
Do I need to guarantee the order of the test data when testing?

### ISSUE THREAD

**Issue by qfwysw** [nutonomy/nuscenes-devkit#712]
Do I need to guarantee the order of the test data when testing?
I have the data sorted by time.
![image](https://user-images.githubusercontent.com/53482524/151283193-e27f9804-c7fb-4cfe-9c4c-234b89c20057.png)

**Comment by whyekit-motional** [comment]
@qfwysw no, you do not need to guarantee the order of the test data (I'm assuming you are submitting to one of the nuScenes challenges on EvalAI)
