### ISSUE TITLE
Evaluate Tracking Results on a few scenes ONLY

### ISSUE THREAD

**Issue by rmooreRD** [nutonomy/nuscenes-devkit#713]
I am trying to evaluate my tracker results using the nuscenes 'evaluate.py' script. I am using the v1.0-trainval version but I am only running my tracker on the first scene (of the pointPillars-val.json). As a result, I am getting an error (AssertionError: Samples in split don't match samples in predicted tracks.) when running the evaluate script. I believe this is because the script is trying to evaluate over the entire data set while I am only inputting tracking results for the first scene. How can I modify the 'evaluate.py' script to evaluate over a select number of scenes ONLY? If I am mistaken, what might the issue be? Thanks in advance!

**Comment by whyekit-motional** [comment]
@rmooreRD one possible way to evaluate on only certain scenes is to load only the ground truth from the scenes you desire:
https://github.com/nutonomy/nuscenes-devkit/blob/05d05b3c994fb3c17b6643016d9f622a001c7275/python-sdk/nuscenes/eval/tracking/evaluate.py#L85

This can be done by replacing this line with a list of the sample tokens you wish to evaluate on:
https://github.com/nutonomy/nuscenes-devkit/blob/05d05b3c994fb3c17b6643016d9f622a001c7275/python-sdk/nuscenes/eval/common/loaders.py#L69

**Comment by rmooreRD** [comment]
Hi, there. Thank you for your response! I have a few follow-up questions: If I were to evaluate over the first scene, for example, what would 'sample_tokens_all' look like to get the corresponding list of sample tokens? Additionally, I have tried to make your recommended changes to the common/loaders.py script but they have no effect. Its like an old version of loaders.py is running when I run evaluate.py. On the other hand any changes I make to evaluate.py do work. Do you know why this might be the case?

**Comment by whyekit-motional** [comment]
1. > If I were to evaluate over the first scene, for example, what would 'sample_tokens_all' look like to get the corresponding list of sample tokens?

   One possible way to get all the sample tokens of a single scene would be:
   ```
   sample_tokens_of_scene = []

   scene_idx = 0
   num_sample_tokens_in_scene = nusc.scene[scene_idx]['nbr_samples']   
   scene_first_sample_token = nusc.scene[scene_idx]['first_sample_token']
   scene_last_sample_token = nusc.scene[scene_idx]['last_sample_token']

   current_token = scene_first_sample_token
   keep_looping = True 
   while keep_looping:
       sample_tokens_of_scene.append(current_token)
    
       if current_token == scene_last_sample_token:
           keep_looping = False
       
       sample_record = nusc.get('sample', current_token)
    
       next_token = sample_record['next']
       current_token = next_token

   assert len(sample_tokens_of_scene) == num_sample_tokens_in_scene
   print(sample_tokens_of_scene)
   ```



2. > Additionally, I have tried to make your recommended changes to the common/loaders.py script but they have no effect.

   It is possible that your script is still importing `common/loaders.py` from the version of `nuscenes-devkit` which you installed via `pip install`. A possible workaround could be to add this line to the top of your `evaluate.py` script:
   ```
   import sys
   sys.path.insert(0, PATH_TO_YOUR_MODIFIED_VERSION_OF_NUSCENES)
   ```
