### ISSUE TITLE
Does nuscenes dataset provide tracking IDs ?

### ISSUE THREAD

**Issue by LisaBernhardt** [nutonomy/nuscenes-devkit#715]
Hi,

Thank you for this powerful dataset. I have seen that you have a leader board for tracking (https://www.nuscenes.org/tracking?externalData=all&mapData=all&modalities=Any), however when I looked through your annotation jsons and the data annotation scheme you provide, I haven't found any tracking IDs for the annotated objects. Could you please tell me how to find them or how to generate them ?

Thank you for your help!

**Comment by whyekit-motional** [comment]
@LisaBernhardt, the tracking IDs which you describe above are essentially instance tokens within the context of nuScenes. You can retrieve the instance token of an instance by doing:
```
from nuscenes.nuscenes import NuScenes


nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=False)

my_instance = nusc.instance[599]
```
`my_instance` will looking something like:
```
{'token': '9cba9cd8af85487fb010652c90d845b5',
 'category_token': 'fedb11688db84088883945752e480c2c',
 'nbr_annotations': 16,
 'first_annotation_token': '77afa772cb4a4e5c8a5a53f2019bdba0',
 'last_annotation_token': '6fed6d902e5e487abb7444f62e1a2341'}
```

Do check out section 5 (`instance`) of the [nuScenes tutorial](https://www.nuscenes.org/nuscenes?tutorial=nuscenes) for further details

**Comment by LisaBernhardt** [comment]
Hi @whyekit-motional, Thank you for your answer. Maybe I need to rephrase my question a little bit. I am struggling to match an instance ID with the corresponding bounding box values.

I have seen that the nuimage scheme provides me bounding box values, however here I can't find instance ids. When I download the nuscenes scheme it provides me the instance id, but here I can't find a link to the bounding boxes.

Can you please help me on this topics ?
Thank you very much!

**Comment by whyekit-motional** [comment]
@LisaBernhardt one possible way to get the 3D bounding boxes for each sample annotation of the instance would be:
```
from nuscenes.nuscenes import NuScenes


nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=False)

my_instance = nusc.instance[599]

first_token_of_instance = my_instance['first_annotation_token']
last_token_of_instance = my_instance['last_annotation_token']
nbr_samples_for_instance = my_instance['nbr_annotations']

current_token = first_token_of_instance

i = 0
keep_looping = True 
while keep_looping:
    
    if current_token == last_token_of_instance:
        keep_looping = False
        
    current_ann = nusc.get('sample_annotation', current_token)
    print(f"instance: {my_instance['token']}\t sample_annotation: {current_token}\t size: {current_ann['size']}")
    
    next_token = current_ann['next']
    current_token = next_token
    i += 1

assert i == nbr_samples_for_instance
```

That should give you something like:
```
instance: 9cba9cd8af85487fb010652c90d845b5	 sample_annotation: 77afa772cb4a4e5c8a5a53f2019bdba0	 size: [2.846, 12.9, 4.581]
instance: 9cba9cd8af85487fb010652c90d845b5	 sample_annotation: 6efa8fae3ca04c58a5f40e78c3a0d912	 size: [2.846, 12.9, 4.581]
instance: 9cba9cd8af85487fb010652c90d845b5	 sample_annotation: a123c0dd6550413eb629fd7c01dc9715	 size: [2.846, 12.9, 4.581]
...
```
