### ISSUE TITLE
map pixel in image to point cloud.

### ISSUE THREAD

**Issue by INF800** [nutonomy/nuscenes-devkit#716]
Hi I need a function that can map all the pixels in an image to point cloud using `hfov_image`, `vfov_image`, `heading`, `phi`, `theta` and `(x,y,z)` of camera / car

**Comment by holger-motional** [comment]
Hi. We don't provide such a function, so you'll need to write it yourself. More straightforward would be to project all points to the image and see what pixels they land on.
