### ISSUE TITLE
ego_pose -  z is always 0

### ISSUE THREAD

**Issue by bjajoh** [nutonomy/nuscenes-devkit#721]
Hi,

I'm trying to accumulate point clouds over whole scenes to recover the scene geometry.
However as noted in the documentation tz is always zero and results noticeable surface errors in the z direction.
Is there any workaround for this issue? Has anyone tried this before and got good results?
What is the reason to set tz to zero?

Thanks for your help! 
Bjarne

**Comment by demmerichs** [comment]
I would also be quite interested in the reasoning behind this choice? This constraint seems quite arbitrary and only makes sense in an environment, where one can assume that the ego vehicle drives on a quite perfect planar surface. This is surely not the case for the nuScenes dataset, as there are scenes with quite a slope in it, where the vehicle drives from lower to higher ground.

Also, maybe someone could give some pointers to existing work, which aggregates nuScenes point clouds more accurately or at least can provide details on some algorithm and hyperparamter choice for aligning the LiDAR scans.

**Comment by holger-motional** [comment]
Hi. That is correct. As described on https://www.nuscenes.org/nuscenes#data-format the localization is in 2d + yaw. At that time that was a useful over-simplification, but obviously it is not as accurate as 6d localization. Furthermore the object annotations also do not have a pitch and roll. You will find that this is also the case in many of the other AV datasets out there.

You could try the standard [ICP](https://en.wikipedia.org/wiki/Iterative_closest_point) algorithm to align consecutive pointclouds, but typically point cloud aggregation over smaller time windows (<20s) works pretty well. Here are some examples:
https://www.nuscenes.org/static/media/gallery-10.57dd41f1.png
https://www.nuscenes.org/gallery
