### ISSUE TITLE
Visualization of 3D tracking results

### ISSUE THREAD

**Issue by zzm-hl** [nutonomy/nuscenes-devkit#723]
I have got the json file of the tracking task and got the metrics like AMOTA by evalute.py, if I want to display the tracking result as 3Dbbox on the image in a video as well as display the BEV tracking result,how can I do it? looking forward to your reply

**Comment by whyekit-motional** [comment]
@zzm-hl while there isn't an off-the-shelf function that can do what you are looking for, you can consider writing your own by taking inspiration from the `render_scene_channel` method of the `nuscenes-devkit`

In particular, you would need to replace this part with a method that gets the boxes from the sample token:
https://github.com/nutonomy/nuscenes-devkit/blob/f94dcd313feb8adc91e7d01312fb7d27cc77098e/python-sdk/nuscenes/nuscenes.py#L283
