### ISSUE TITLE
Validation with lidar sweeps not being keyframes

### ISSUE THREAD

**Issue by ahmedius2** [nutonomy/nuscenes-devkit#725]
Hello,

AFAIK, the time difference between keyframes is approximately 500 ms. However, the lidar is being sampled within a 50 ms period. I want to run validation for not only keyframes but also for the sweeps in the middle. For example, if S-1 and S-11 are two consecutive keyframes, I want to include the sweeps in the middle with a 100 ms period, so the validation processes the samples [S-1, S-3, S-5, S-7, S-9] instead of processing S-1 only. I think, only the keyframes have annotations, but the devkit has the capability to interpolate the annotations for the sweeps between keyframes. Please let me know how can I do this.

Best regards,

**Comment by whyekit-motional** [comment]
@ahmedius2 if you want to interpolate between the boxes of two consecutive keyframes, you take inspiration from `interpolate_tracking_boxes`: https://github.com/nutonomy/nuscenes-devkit/blob/f94dcd313feb8adc91e7d01312fb7d27cc77098e/python-sdk/nuscenes/eval/tracking/loaders.py#L17

Subsequently, you would need to modify this part to not only load the ground truth of the keyframes, but also the interpolated ground truth which you have generated for the sweeps: https://github.com/nutonomy/nuscenes-devkit/blob/05b601f363a96deadb60123103b9011110a1ca82/python-sdk/nuscenes/eval/common/loaders.py#L114

**Comment by ahmedius2** [comment]
Thanks, could you explain the right_ratio? For example, if I have two corresponding boxes having timestamps x and x + 0.5 seconds, respectively, and I want to interpolate the box for timestamp x + 0.4, do I need to set the right_ratio to 0.8?

**Comment by whyekit-motional** [comment]
`right_ratio` is essentially a weighting factor which determines the extent to which the interpolation is influenced by the right box (as opposed to the left box). Concretely, if your left box has its center at 0m while your right box has its center at 5m, then, as examples:
- `right_ratio=0.5` means that the interpolated box has its center at 0.5 * (5 - 0) = 2.5m
- `right_ratio=0.8` means that the interpolated box has its center at 0.8 * (5 - 0) = 4m
