### ISSUE TITLE
BEV Visualization 

### ISSUE THREAD

**Issue by zzm-hl** [nutonomy/nuscenes-devkit#727]
In tracking task, is it possible to draw a series of frames of the same video continuously on the same picture in BEV? The original function can only display each frame of the picture frame by frame. I have inquired about fig, plt and other functions, but it seems that I have not been able to solve this problem。looking forward to your reply.

**Comment by whyekit-motional** [comment]
@zzm-hl this might be tricky as you would need to establish which ego pose (among those of the entire scene) you would want to render around. Also, you might need to differentiate the agents from each frame if you decide to plot all the frames on a single canvas.

**Comment by Cola-666** [comment]
@zzm-hl Hi, have you got the solution to the problem yet?
