### ISSUE TITLE
Potential bug in mtp.py 

### ISSUE THREAD

**Issue by IaroslavElistratov** [nutonomy/nuscenes-devkit#728]
Hi, in MTP [model definition](https://github.com/nutonomy/nuscenes-devkit/blob/f94dcd313feb8adc91e7d01312fb7d27cc77098e/python-sdk/nuscenes/prediction/models/mtp.py#L51-L54) or its [`forward()`](https://github.com/nutonomy/nuscenes-devkit/blob/f94dcd313feb8adc91e7d01312fb7d27cc77098e/python-sdk/nuscenes/prediction/models/mtp.py#L72) method it appears that a nonlinearity is missing between the linear layers. Or you might not need it, in which case it seems that the two linear layers can be combined into:
```python
self.lin = nn.Linear(backbone_feature_dim + ASV_DIM, int(num_modes * predictions_per_mode + num_modes))
```
Please let me know if I'm missing something.

**Comment by emwolff** [comment]
Ooops, that looks like an error. Good catch. @whyekit-motional do you have a few min to add the nn.ReLU block between the two linear layers?
