### ISSUE TITLE
how to extract all radar data

### ISSUE THREAD

**Issue by liukr001** [nutonomy/nuscenes-devkit#729]
The PCD file contains all the information about the target detected by the radar, such as speed, azimuth, etc. What tools are needed to extract all this data.tks for your help:)

**Comment by whyekit-motional** [comment]
@liukr001 do check out the `from_file` method of `RadarPointCloud`: https://github.com/nutonomy/nuscenes-devkit/blob/c44366daea8bba29673943c1fc86d0bfbfb7a99e/python-sdk/nuscenes/utils/data_classes.py#L298-L302
