### ISSUE TITLE
Repeated samples

### ISSUE THREAD

**Issue by asvath** [nutonomy/nuscenes-devkit#73]
Hi,

There are a few repeated samples. The images and annotations are the same (occasionally additional annotations). 

e.g sample 343 and sample 369  (the camera keys point to the same filenames)

This issue extends from samples 343 -357 which are the same as these samples: 369-383

Was this intentional? If so, why?

Thank you.

**Comment by holger-nutonomy** [comment]
Hey :-). See also https://github.com/nutonomy/nuscenes-devkit/issues/8. Going forward we will delete scene 169 to avoid confusion. Stay tuned for the full release on March 25. Let me know if you have any more questions.

**Comment by asvath** [comment]
Thank you! (:
