### ISSUE TITLE
How do we do this in nuImages dataset?

### ISSUE THREAD

**Issue by wannapg** [nutonomy/nuscenes-devkit#734]
How do we do this in nuImages dataset?

_Originally posted by @wannapg in https://github.com/nutonomy/nuscenes-devkit/issues/698#issuecomment-1073511079_

**Comment by holger-motional** [comment]
@wannapg The nuImage splits are in the DB files. They have different names:
https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuimages/nuimages.py#L37
