### ISSUE TITLE
How to visualize the results of object detection

### ISSUE THREAD

**Issue by gkd2020** [nutonomy/nuscenes-devkit#735]
Hello，
I implemented my network in [OpenPCDet](https://github.com/open-mmlab/OpenPCDet) framework. Now I want to visualize the object detection results.  Specifically，I want save the results, and select some good pictures for my paper. 
I have two ways： 
1.  Use open3d or mayavi for visualization, but I don't know how to save 3D results as pictures on a large scale.
2. Project the result of  detection onto the camera image, but I don't know how to coordinate the six cameras and how to project.

I want to know if there is a tool similar to [kitti-viewer](https://github.com/hailanyi/3D-Detection-Tracking-Viewer) for nuscenes dataset to directly complete visualization
Is there a visualization tool in nuscenes-devkit？

**Comment by whyekit-motional** [comment]
@gkd2020 for option 2, you could consider modifying the `get_box` method to read the predictions from your model: https://github.com/nutonomy/nuscenes-devkit/blob/85b918050644964731bdfc8d8f1d53012a34b96a/python-sdk/nuscenes/nuscenes.py#L315

Then you could possibly use `render_sample_data` to render your predictions in, say, `CAM_FRONT`: https://github.com/nutonomy/nuscenes-devkit/blob/85b918050644964731bdfc8d8f1d53012a34b96a/python-sdk/nuscenes/nuscenes.py#L548

**Comment by NorthSummer** [comment]
> get_box

Hi, it seems that this method can only render one bounding box in a scene. How to render all of them?

**Comment by whyekit-motional** [comment]
@NorthSummer you can get multiple boxes via something like this: https://github.com/nutonomy/nuscenes-devkit/blob/85b918050644964731bdfc8d8f1d53012a34b96a/python-sdk/nuscenes/nuscenes.py#L279-L283
