### ISSUE TITLE
What about having `pycocotools` or `requirements_XXX.txt` other than `requirements_base.txt` in extra requirements?

### ISSUE THREAD

**Issue by huxuan** [nutonomy/nuscenes-devkit#736]
Cases that we only need `nuscenes`, it may not be necessary to have `pycocotools` as requirements.

We can have it as something like `pip install nuscenes-devkit` for nuscenes only  and `pip install nuscenes-devkit[nuimages]` for `pycocotools`.

If OK, I will submit a PR for this.

**Comment by holger-motional** [comment]
Hi. What issues are you seeing with pycocotools? I think it would be good if the basic dataset features are supported out of the box.

**Comment by huxuan** [comment]
Hi @holger-motional, thanks for the quick reply.

The problem is that when I try to play ONLY with nuscenes there is some dependency conflict.
