### ISSUE TITLE
Problems of the camera  extrinsic and calibrated_sensor parameters

### ISSUE THREAD

**Issue by exiawsh** [nutonomy/nuscenes-devkit#737]
Hello,
    Does the camera extrinsic matrix equals the inverse matrix from calibrated_sensor?
    The extrinsic of the camera should be the matrix from the points in the vehicle coordinate system to the camera coordinate system.
     But  The definition of calibrated_sensor seems to be the rigid body transformation matrix from camera to vehicle coordinate system.

**Comment by whyekit-motional** [comment]
@exiawsh with regards to your question:
> But The definition of calibrated_sensor seems to be the rigid body transformation matrix from camera to vehicle coordinate system.

If you take a look at `calibrated_sensor` [here](https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/schema_nuscenes.md#calibrated_sensor), it says that:
```
All extrinsic parameters are given with respect to the ego vehicle body frame.
```
