### ISSUE TITLE
City Name for Each Tracking Sequence

### ISSUE THREAD

**Issue by ziqipang** [nutonomy/nuscenes-devkit#738]
Hi,

I am recently trying to couple the tracking data with the HD-Map. However, I cannot find any API that shows the city of a tracking scene. Therefore, I am wondering (1) if it is possible to link the tracking data and HD-Map; (2) if so, what functions/API may I use?

Please point out if I am missing anything. Thank you for your help!

**Comment by whyekit-motional** [comment]
@ziqipang do check out the schema [here](https://www.nuscenes.org/public/images/nuscenes-schema.svg) - the `scene` table is linked to the `log` table which has an entry location that you can filter by

Here's an example code snippet to further guide you:
```
from nuscenes.nuscenes import NuScenes


# Load the nuScenes dataset (mini-split, in this case).
nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=False)

nusc.get('log', nusc.scene[0]['log_token'])
```
The above would give:
```
{'token': '7e25a2c8ea1f41c5b0da1e69ecfa71a2',
 'logfile': 'n015-2018-07-24-11-22-45+0800',
 'vehicle': 'n015',
 'date_captured': '2018-07-24',
 'location': 'singapore-onenorth',
 'map_token': '53992ee3023e5494b90c316c183be829'}
```
