### ISSUE TITLE
Could you provide radar data in Range-Doppler-Azimuth Tensor format?

### ISSUE THREAD

**Issue by 304886938** [nutonomy/nuscenes-devkit#739]
Hello,
I'm currently working on a object detection method based on radar, and I need radar data in range-Doppler -Azimuth Tensor format, instead of sparse point cloud format.  I wonder if you can provide point cloud data in this format?  
Looking forward to your reply!

**Comment by whyekit-motional** [comment]
@304886938 you would likely have to write a script to convert the data to your desired format. A good starting point might be to take a look at the format of the radar data in nuScenes here: https://github.com/nutonomy/nuscenes-devkit/blob/85b918050644964731bdfc8d8f1d53012a34b96a/python-sdk/nuscenes/utils/data_classes.py#L315

**Comment by 304886938** [comment]
Maybe I didn't clear the problem，The Radar data provided by the Nuscenes is sparse point clouds that has been handled by a  CFAR (Constant False Alarm Rate) algorithm. I want to guide whether you can provide the original data that has not been processed without CFAR (Range-Doppler) -Azimuth).
In addition, can we get dense data after transitioning of your method?
Thank you for your answer!

**Comment by whyekit-motional** [comment]
@304886938 unfortunately, we do not have the raw radar data

**Comment by 304886938** [comment]
Thank your for your answer!
