### ISSUE TITLE
Coordinate system transformation

### ISSUE THREAD

**Issue by mishrap9** [nutonomy/nuscenes-devkit#741]
Hi,

The boxes we get from the function 'get_sample_data' is wrt sensor frame of reference, right?

Also, I want to change the data of the box to a different frame of reference without using Box(as given in the repo code)
Please suggest what mistake I am making as it doesn't give correct result.

```
# Transforming box data from sensor to ego vehicle frame 
    veh_with_ego = np.dot(sens_rotation_m,(veh_translation)) + sens_translation
# Transforming data from ego to global frame
    veh_ = np.dot(ego_rotation_m, (veh_with_ego)) + ego_translation
# Transforming global data to ref_ego frame
    veh_with_ref_ego = np.dot(np.linalg.inv(ref_ego_rotation_m),((veh_ - ref_ego_translation)))
# Transforming data from ref_ego frame to ref_sensor frame
    veh_with_ref_sens = np.dot(np.linalg.inv(ref_sens_rotation_m), ((veh_with_ref_ego - ref_sens_translation)))
```
Note: veh_translation is an array of location of vehicle and I am using rotation matrix from quaternions. 

Please suggest if the above method is correct?
If not, what needs to be changes as I don't want to use Box features.

Thanks

**Comment by whyekit-motional** [comment]
@mishrap9 perhaps you can take reference from this code snippet, and replace the translation and rotation matrices from `pose_record` with those of your use case: https://github.com/nutonomy/nuscenes-devkit/blob/85b918050644964731bdfc8d8f1d53012a34b96a/python-sdk/nuscenes/nuscenes.py#L294-L300

**Comment by mishrap9** [comment]
Hi, I have done the same thing if you see it. The only difference is I used rotation matrix (obtained from quaternion) and I want all the boxes wrt new ego vehicle which I named as ref_ego_veh.
Can you please suggest changes in the code is I want the box data wrt new ref ego and new ref sens ? 

` # Move box to ego vehicle coord system. 
 box.translate(-np.array(pose_record['translation'])) 
 box.rotate(Quaternion(pose_record['rotation']).inverse) 
  
 #  Move box to sensor coord system. 
 box.translate(-np.array(cs_record['translation'])) 
 box.rotate(Quaternion(cs_record['rotation']).inverse)
`

**Comment by mishrap9** [comment]
Hi, I have done the same thing if you see it. The only difference is I used rotation matrix (obtained from quaternion) and I want all the boxes wrt new ego vehicle which I named as ref_ego_veh.
Can you please suggest changes in the code if I want the box data wrt new ref ego and new ref sens ? 
```

# Move box to ego vehicle coord system. 
 box.translate(-np.array(pose_record['translation'])) 
 box.rotate(Quaternion(pose_record['rotation']).inverse) 
  
 #  Move box to sensor coord system. 
 box.translate(-np.array(cs_record['translation'])) 
 box.rotate(Quaternion(cs_record['rotation']).inverse)

````
