### ISSUE TITLE
difference between ego_pose in different sensor

### ISSUE THREAD

**Issue by wenjie710** [nutonomy/nuscenes-devkit#744]
Hi, I am confused about the meaning of 'ego_pose' in different sensors.
For  a specific sample, I can get ego_pose respect to the CAM_FRONT by:  
`cam_front_pose= self.nusc.get('ego_pose', self.nusc.get('sample_data', record['data']['CAM_FRONT'])['ego_pose_token']))`
At the same time, I can get ego_pose respect to the LIDAR_TOP by
`lidar_pose = self.nusc.get('ego_pose', self.nusc.get('sample_data', record['data']['LIDAR_TOP'])['ego_pose_token'])`
And I can get ego_pose w.r.t CAM_BACK, CAM_FRONT_LEFT in the same way.
Here comes the question. 
1. What's the difference of these ego_poses? What's the meaning of these ego_poses of the same sample? They look quite similar with little differences. 
2. I observe that in many cases where coordinate system transformation is need, points coordinates are first transformed to global and then transformed back to ego coordinates system, finally transform to specific sensor.  E.g. lidar -> global -> ego -> cam. Why not transform by ego coordinates system since all the sensors are calibrated respected to ego coordinate system, like lidar - > ego -> cam? This is related to the first problem because the ego_pose w.r.t. different sensors are slightly different.

**Comment by whyekit-motional** [comment]
@wenjie710 

> 1. What's the difference of these ego_poses? What's the meaning of these ego_poses of the same sample? They look quite similar with little differences.

All the sensors on the ego do not necessarily take their respective readings at the exact same time. So to be very accurate, every sensor reading has an `ego_pose` associated with the timestamp the reading was taken at.

As an example:
```
from nuscenes.nuscenes import NuScenes


# Load the nuScenes dataset (mini-split, in this case).
nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=False)

record = nusc.sample[0]
cam_front_pose = nusc.get('ego_pose', nusc.get('sample_data', record['data']['CAM_FRONT'])['ego_pose_token'])
print(cam_front_pose)
lidar_pose = nusc.get('ego_pose', nusc.get('sample_data', record['data']['LIDAR_TOP'])['ego_pose_token'])
print(lidar_pose)
```
You would see that the timestamps between `CAM_FRONT` and `LIDAR_TOP` are very close to each other (but not exactly the same), and within that small delta in duration, the ego would have moved slightly. Hence, you would notice that the `ego_pose` is slightly different
```
{'token': 'e3d495d4ac534d54b321f50006683844', 'timestamp': 1532402927612460, 'rotation': [0.5720063498929273, -0.0021434844534272707, 0.011564094980151613, -0.8201648693182716], 'translation': [411.4199861830012, 1181.197175631848, 0.0]}
{'token': '9d9bf11fb0e144c8b446d54a8a00184f', 'timestamp': 1532402927647951, 'rotation': [0.5720320396729045, -0.0016977771610471074, 0.011798001930183783, -0.8201446642457809], 'translation': [411.3039349319818, 1180.8903791765097, 0.0]}
```

> 2. I observe that in many cases where coordinate system transformation is need, points coordinates are first transformed to global and then transformed back to ego coordinates system, finally transform to specific sensor. E.g. lidar -> global -> ego -> cam. Why not transform by ego coordinates system since all the sensors are calibrated respected to ego coordinate system, like lidar - > ego -> cam? This is related to the first problem because the ego_pose w.r.t. different sensors are slightly different.

I believe you are referring to this part of the devkit: https://github.com/nutonomy/nuscenes-devkit/blob/85b918050644964731bdfc8d8f1d53012a34b96a/python-sdk/nuscenes/nuscenes.py#L881-L900

The crucial part here is using the calibrated sensor data of the lidar (at the beginning of the transformation) and the calibrated sensor data of the camera (at the end of the transformation) - this helps to account for that slight difference in `ego_pose`
