### ISSUE TITLE
About non key-frame image poses

### ISSUE THREAD

**Issue by DRosemei** [nutonomy/nuscenes-devkit#746]
I want to know where non key-frame image poses get from. Are they interpolated poses between key-frames? I found that there are some mistakes when I use non key-frame image poses. Thanks in advance :)

**Comment by whyekit-motional** [comment]
The ego pose is published at 50 Hz, so it is possible to just select the one which is the closest to the timestamp of the frame from the camera (which is at 12 Hz)
