### ISSUE TITLE
What is "vx_comp" and "vy_comp" means ?

### ISSUE THREAD

**Issue by joeking11829** [nutonomy/nuscenes-devkit#748]
Hi nuScenes teams,

Radar have two velocity column

vx, vy: in m/s. Radial velocity measured for this detection
vr_comp, vy_comp in m/s: Radial velocity for this detection but compensated for the ego-motion
Because I am not familiar with Radar, I have not idea why Radial Velocity need to compensate with ego-motion.

I use the **"vx, xy"** to plot radial velocity, the direction of radial velocity for each radar point **is not point to radar** itself.
when I use the **"vx_comp, vy_comp"** to plot radial velocity, and the direction of radial velocity for each radar point **is point to radar** itself

Could you explain that ?
Thanks !!

**Comment by whyekit-motional** [comment]
@joeking11829 do take a look at the following: https://forum.nuscenes.org/t/radar-vx-vy-and-vx-comp-vy-comp/283

**Comment by joeking11829** [comment]
> @joeking11829 do take a look at the following: https://forum.nuscenes.org/t/radar-vx-vy-and-vx-comp-vy-comp/283
<br>

Hi @whyekit-motional ,

I read the article, but I could not get any conclusion.

In the disscussion, 
the vector compose of "vx" and "vy" must point from radar origin to radar point
[ reference from "isrohutama" ]
![image](https://user-images.githubusercontent.com/5969040/168737033-02609c8f-331f-428d-b9ea-c863acb68084.png)


But it seems to me that nuScenes's radar data ( vx and vy ) does not behave that way.
And it make me confused that how the compensated velocities are compensated by ego motion,
it make the vector compose of "vx_comp" and "vy_comp" point from radar origin to radar point, but the vector compose of "vx" and "vy" does not.

Any ideas ?

Thanks !!

**Comment by whyekit-motional** [comment]
@joeking11829, there may some misunderstanding here:

> the vector compose of "vx" and "vy" must point from radar origin to radar point

`vr` (the radial velocity) is the component that points from the radar point to the radar origin, while `vx` and `vy` are components which point in the global frame (you can of course transform between the radial-tangential frame and xy frame)
