### ISSUE TITLE
Render ego centric map (layers)

### ISSUE THREAD

**Issue by ShiluYang96** [nutonomy/nuscenes-devkit#750]
Hi, 

I want to ask, if it is possible to render the centric HD map according to the sample data token? 

Similar with `render_ego_centric_map`, but i need the HD map layer information (using the map extension packet).

**Comment by whyekit-motional** [comment]
@ShiluYang96 you could use `render_map_mask` (from the map expansion) like so:
```
patch_box = (ego_center_x, ego_center_y, 40, 40)
patch_angle = 0  # Default orientation where North is up
layer_names = ['drivable_area', 'walkway']
canvas_size = (1000, 1000)
fig, ax = nusc_map.render_map_mask(patch_box, patch_angle, layer_names, canvas_size, figsize=figsize, n_row=1)
```
