### ISSUE TITLE
Data format conversion

### ISSUE THREAD

**Issue by wangxiyang2022** [nutonomy/nuscenes-devkit#753]
Hi, Thank you for your open source dataset.

My current research is multi-object tracking based on the fusion of camera and lidar. Before, it was tested on Kitti, and our method has achieved good results[KITTI]( http://www.cvlibs.net/datasets/kitti/eval_tracking_detail.php?result=5a93530d8296e670c99ff5fa751efa3d235ead5d). And our work is [open source](https://github.com/wangxiyang2022/DeepFusionMOT). 

At present, we want to test on the large dataset nuscence, but we find a problem. 

Because the previous debugging is for the format of Kitti dataset, and the format of nuscence dataset is different from that of Kitti dataset, especially when fusing the detection data of lidar and camera, I want to ask whether there is a corresponding script to convert the detection results of nuscence into the format of Kitti dataset, Then it is converted to the format of nuscence to submit the evaluation.

**Comment by whyekit-motional** [comment]
@wangxiyang2022 do check this script out: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_kitti.py
