### ISSUE TITLE
Data Format

### ISSUE THREAD

**Issue by wangxiyang2022** [nutonomy/nuscenes-devkit#754]
Hi, thanks for your code.

What is the data format of 2D detection for nuScence tracking？

for example:

![image](https://user-images.githubusercontent.com/71493146/165306582-758f7aa9-c1ec-4e8e-b9a1-6eded1c069be.png)

"7e351605549547f8af19432917f23b73"（blue box）: that means frame?

"df3af96318c945c3b23080ced7720aa7"（red box）: I don't know what this is...

“0”：that means pedestrian？and "2" means car?

Thank you for your reply.

**Comment by whyekit-motional** [comment]
@wangxiyang2022 for nuScenes tracking, you can check out the description of results format here: https://github.com/nutonomy/nuscenes-devkit/tree/master/python-sdk/nuscenes/eval/tracking#results-format
