### ISSUE TITLE
Visual box orientation and value in orientation.degrees/ yaw does not match

### ISSUE THREAD

**Issue by SM1991CODES** [nutonomy/nuscenes-devkit#755]
Hello,

I am trying to convert point clouds and boxes to ego frame using the built in methods

`sample_data_lidar_top_token = sample_obj["data"]["LIDAR_TOP"]

                calibrated_lidar_token = nusc.get("sample_data", sample_data_lidar_top_token)["calibrated_sensor_token"]  # get calibraton params using the lidar token for this sample
                lidar_calibs_rot_quat = pyquaternion.Quaternion(nusc.get("calibrated_sensor", calibrated_lidar_token)["rotation"])  # rotation as quaternion
                lidar_calibs_trans = nusc.get("calibrated_sensor", calibrated_lidar_token)["translation"]
                trans_mat_rotate_z = gutils.transform_matrix(rotation=lidar_calibs_rot_quat, translation=lidar_calibs_trans, inverse=False)  # 19/04/22 -> full transform to ego frame

                # a sensor's token is used to get the actual data path and annotations, boxes converted to vehicle frame
                pcl_path, box_obj_list, cam_intrins = nusc.get_sample_data(sample_data_lidar_top_token, use_flat_vehicle_coordinates=True)`

Now when I plot the point cloud with boxes, some boxes do not seem to be aligned the way that the orientation.degrees angle returns.

![image](https://user-images.githubusercontent.com/69435296/165825776-c3085af0-ad5e-4f87-bf18-24ecf951d5ae.png)

![image](https://user-images.githubusercontent.com/69435296/165825963-e508d3f4-7542-4caa-b886-a5cb4bdf477b.png)

As we can see, the degrees reports 27 degrees approx whereas visually the box looks like almost 90 degrees.

So what am I missing?

Concretely, 

1) What is the axis convention when representing box orientation in ego frame? (I assume x (0 degrees) is pointing right, counter clockwise is +ve and clockwise is -ve)

2) What is the correct way to project point clouds and boxes to vehicle frame and read the rotation about z axes for the boxes?

Please help.

Best Regards
Sambit

**Comment by SM1991CODES** [comment]
I also tried plotting the point cloud and boxes in velodyne frame.
![image](https://user-images.githubusercontent.com/69435296/165836523-bca5cc29-25b3-416d-af06-b07e27820661.png)

This reads orientation.degrees = -20.54

The frame is: LIDAR_TOP/n015-2018-07-18-11-07-57+0800__LIDAR_TOP__1531883530449377.pcd.bin'

**Comment by whyekit-motional** [comment]
@SM1991CODES looking at the code snippet you provided above, I think the issue lies here:
```
# a sensor's token is used to get the actual data path and annotations, boxes converted to vehicle frame
pcl_path, box_obj_list, cam_intrins = nusc.get_sample_data(sample_data_lidar_top_token, use_flat_vehicle_coordinates=True)`
```

`get_sample_data` gives you the boxes in the sensor frame, not the vehicle frame - do check out the docstring for more details:
https://github.com/nutonomy/nuscenes-devkit/blob/85b918050644964731bdfc8d8f1d53012a34b96a/python-sdk/nuscenes/nuscenes.py#L248-L255

**Comment by SM1991CODES** [comment]
Thanks for the quick reply.
However, I have set the flat_vehicle_coordinates flag to true in that
method and the documentation for the method says this should project boxes
to vehicle coordinates.

Also, as you see in the attached plots, the boxes are plotted correctly,
indicating that the transform from sensor to vehicle frame is probably
working fine. It is just the number in degrees that seems wrong.

Please have a look.

I need some more digging and feel that a vertical box is actually 0 degrees
in nuscenes and horizontal box is 90 degrees, unlike kitti where the case
is reverse.

Also, what is the range of rotation angles for boxes?

Furthermore, when projected to vehicle frame, the box rotation is always
wrt present ego frame. So it depends on orientation of ego frame in present
sample. Is that correct?

Best Regards
Sambit

**Comment by whyekit-motional** [comment]
> However, I have set the flat_vehicle_coordinates flag to true in that method and the documentation for the method says this should project boxes to vehicle coordinates.

Ah yes, I missed that you have `flat_vehicle_coordinates=True` in your above code snippet - indeed the boxes are now in the ego frame

**Comment by whyekit-motional** [comment]
Now, to make the direction of the various orientations clear, let's use this sample as an example:
```
from nuscenes.nuscenes import NuScenes


nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=False)

sample = nusc.sample[10]

nusc.render_sample_data(sample_data_token, nsweeps=1, underlay_map=True)
```
<img src="https://user-images.githubusercontent.com/62535720/165938679-80108229-bc73-4b75-933e-33aca757897f.png" alt="mini_sample_10" width="400"/>



Here's a code snippet to render, in black, all vehicles which have a yaw within a certain rage:
```
import matplotlib.pyplot as plt
import numpy as np
from pyquaternion import Quaternion

from nuscenes.nuscenes import NuScenes


min_yaw_deg = -180  # Tinker around with this value
max_yaw_deg = -90  # Tinker around with this value


# Load up the nuScenes mini split.
nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=False)


# Select the 10th sample.
sample = nusc.sample[10]
sample_data_token = sample['data']['LIDAR_TOP']

# Get the boxes belonging to the sample in the ego frame.
_, boxes, _ = nusc.get_sample_data(sample_data_token, use_flat_vehicle_coordinates=True)

# Filter for only boxes which belong to vehicles (these boxes are bigger compared to other classes like pedestrians and 
# cones, which makes it easier to observe them)
boxes = [bb for bb in boxes if 'vehicle' in bb.name]

_, ax = plt.subplots(1, 1, figsize=(9, 9))

# Go through each box.
for box in boxes:
    # For boxes which have a yaw within the desired range, render them in black.
    if min_yaw_deg < np.rad2deg(Quaternion(box.orientation).yaw_pitch_roll[0]) < max_yaw_deg:
        c = [0, 0, 0]
    else:
        c = np.array(nusc.explorer.get_color(box.name)) / 255.0
    box.render(ax, view=np.eye(4), colors=(c, c, c))

axes_limit = 40
ax.set_xlim(-axes_limit, axes_limit)
ax.set_ylim(-axes_limit, axes_limit)
```


By tinkering around with the values of `min_yaw_deg`  and `max_yaw_deg`, we can get:
<td colspan="x">
      <table>
          <tr>
             <td>
                 <p> min_yaw_deg: -180 &#176; <br>  max_yaw_deg: -90 &#176; </p>
             </td>
             <td>
                 <p> min_yaw_deg: -90 &#176; <br> max_yaw_deg: 0 &#176;</p>
             </td>
             <td>
                 <p> min_yaw_deg: 0 &#176; <br> max_yaw_deg: +90 &#176;</p>
            </td>
          </tr>
          <tr>
              <td style="width:50%"><img src="https://user-images.githubusercontent.com/62535720/165939382-92e7ae8a-8918-4b68-bb0c-d3c9ab18636a.png" alt="-180_-90" width="400"/></td>
              <td style="width:50%"><img src="https://user-images.githubusercontent.com/62535720/165939388-78c29db3-6998-4ba2-86e4-adef759c9b21.png" alt="-90_0" width="400"/></td>
               <td style="width:50%"><img src="https://user-images.githubusercontent.com/62535720/165939392-150baea2-8c05-4a7f-9f49-b6125e5d22d2.png" alt="0_90" width="400"/></td>
          </tr>
      </table>
</td>



Thus, 0 &deg; to +90 &deg; corresponds to the front-left quadrant of the ego while -90 &deg; to 0 &deg; corresponds to the front right quadrant of the ego, like so:
<img src="https://user-images.githubusercontent.com/62535720/165954434-3ab94f24-30ef-4e38-b9ce-5154e1ea49b0.png" alt="orientation" width="400"/>

**Comment by SM1991CODES** [comment]
Thank you for the explanation.
I see that the plot you have uses the convention y -ve to left and +ve to right, is that correct?
I follow the KITTI convention and make a BEV out of the point cloud where y is +ve to left and -ve to right.
So would this have an impact?

Best Regards
Sambit

**Comment by whyekit-motional** [comment]
Yes, if your convention differs from that of nuScenes, then there is likely to be an impact

If you are interested in converting between nuScenes and KITTI, you could check this out: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_kitti.py
