### ISSUE TITLE
missing a bin file

### ISSUE THREAD

**Issue by poodarchu** [nutonomy/nuscenes-devkit#756]
cannot access sweeps/LIDAR_TOP/n008-2018-08-30-15-31-50-0400__LIDAR_TOP__1535657812199943.pcd.bin: No such file or directory

**Comment by poodarchu** [comment]
I cannot find this file when running evaluation, and this will cause an error. 
Can you help me to locate this file?

**Comment by whyekit-motional** [comment]
@poodarchu pls make sure you have downloaded the data for the sweeps

Also, you can check which sample and scene that file belongs to by doing:
```
from tqdm import tqdm

for sd in tqdm(nusc.sample_data):
    if sd['filename'] == 'sweeps/LIDAR_TOP/n008-2018-08-30-15-31-50-0400__LIDAR_TOP__1535657812199943.pcd.bin':
        sample = nusc.get('sample', sd['sample_token'])
        scene = nusc.get('scene', sample['scene_token'])
        
        print(sample)
        print(scene)
    
        break
```

**Comment by poodarchu** [comment]
> @poodarchu pls make sure you have downloaded the data for the sweeps
> 
> Also, you can check which sample and scene that file belongs to by doing:
> 
> ```
> from tqdm import tqdm
> 
> for sd in tqdm(nusc.sample_data):
>     if sd['filename'] == 'sweeps/LIDAR_TOP/n008-2018-08-30-15-31-50-0400__LIDAR_TOP__1535657812199943.pcd.bin':
>         sample = nusc.get('sample', sd['sample_token'])
>         scene = nusc.get('scene', sample['scene_token'])
>         
>         print(sample)
>         print(scene)
>     
>         break
> ```

I'm sure I've downloaded the full dataset.
There's another way to reproduce this error.
just execute `ls sweeps/ | wc`, and ls will also rise this error, this specific file is missing.

**Comment by whyekit-motional** [comment]
@poodarchu the file seems to be present in the dataset:
```
cd /data/sets/nuscenes/sweeps/LIDAR_TOP
ls | grep 0400__LIDAR_TOP__1535657812199943
```
And the above gives:
```
n008-2018-08-30-15-31-50-0400__LIDAR_TOP__1535657812199943.pcd.bin
```

**Comment by poodarchu** [comment]
> @poodarchu the file seems to be present in the dataset:
> 
> ```
> cd /data/sets/nuscenes/sweeps/LIDAR_TOP
> ls | grep 0400__LIDAR_TOP__1535657812199943
> ```
> 
> And the above gives:
> 
> ```
> n008-2018-08-30-15-31-50-0400__LIDAR_TOP__1535657812199943.pcd.bin
> ```

can you tell me where is this file locate in the zipped file, the blob files name?

**Comment by whyekit-motional** [comment]
Unfortunately, I no longer have the individual compressed files on my local machine

However, do note that you shouldn't need the sweeps for evaluation
