### ISSUE TITLE
Is there any plan supporting loading files from aws s3?

### ISSUE THREAD

**Issue by poodarchu** [nutonomy/nuscenes-devkit#759]

**Comment by whyekit-motional** [comment]
@poodarchu for downloading of the dataset from AWS, pls take a look at https://github.com/nutonomy/nuscenes-devkit/issues/110#issuecomment-480072630

**Comment by poodarchu** [comment]
> @poodarchu for downloading of the dataset from AWS, pls take a look at [#110 (comment)](https://github.com/nutonomy/nuscenes-devkit/issues/110#issuecomment-480072630)

I'm not talking about download the original dataset. 

I'm asking, for example, how to do evaluation using data from aws storage, or how to initialise `NuScenes` class from a aws s3 uri path?

**Comment by whyekit-motional** [comment]
No, there are currently no plans to introduce either of those functionalities
