### ISSUE TITLE
Not found 'attribute.json' in nuScenes-lidarseg-all-v1.0

### ISSUE THREAD

**Issue by HangWu2020** [nutonomy/nuscenes-devkit#763]
Hi,

Thank you for the great work! I have downloaded nuScenes-lidarseg from [`this link`](https://www.nuscenes.org/download) and tried to follow this [`instruction`](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/tutorials/nuscenes_lidarseg_panoptic_tutorial.ipynb) to read point cloud. However, it seems that the dataset is supposed to include `attribute.json` file in `v1.0-*` folders, while I only get `category.json` and `lidarseg.json` in them. Here is the folder structure on my computer:

├── nuScenes-lidarseg-all-v1.0
│   ├── lidarseg
│   │   ├── v1.0-mini
│   │   ├── v1.0-test
│   │   └── v1.0-trainval
│   ├── v1.0-mini
│   │   ├── category.json
│   │   └── lidarseg.json
│   ├── v1.0-test
│   │   ├── category.json
│   │   └── lidarseg.json
│   └── v1.0-trainval
│       ├── category.json
│       └── lidarseg.json
├── nuScenes-lidarseg-all-v1.0.tar.bz2
└── nuscenes_lidarseg_panoptic_tutorial.ipynb

Could you help find whether I have downloaded the correct dataset, or do I need to download other datasets (up to now I only download nuScenes-lidarseg)?

**Comment by whyekit-motional** [comment]
@HangWu2020 you are on the right track :+1: you just need to download the original nuScenes datatset as well, in addition to the nuScenes-lidarseg dataset which you have already downloaded

And then just ensure that your folder structure looks like the one show under `Setup` here: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/tutorials/nuscenes_lidarseg_panoptic_tutorial.ipynb

**Comment by HangWu2020** [comment]
I got it, thanks for the great work and quick reply!
