### ISSUE TITLE
can I test 3d object detection performance without velocity?

### ISSUE THREAD

**Issue by TianhaoFu** [nutonomy/nuscenes-devkit#767]
hi, 

can I get the NDS  without velocity result?

thanks!

**Comment by whyekit-motional** [comment]
@TianhaoFu NDS is calculated by computing a weighted sum of mAP, mATE, mASE, mAOE, mAVE and mAAE: https://github.com/nutonomy/nuscenes-devkit/blob/28765b8477dbd3331bacd922fada867c2c4db1d7/python-sdk/nuscenes/eval/detection/evaluate.py#L31

Thus, velocity cannot be ignored
