### ISSUE TITLE
Unzip and merge dataset (v1.0)

### ISSUE THREAD

**Issue by tuan97anton** [nutonomy/nuscenes-devkit#768]
I just download 10 file dataset .tgz ( v1.0-trainval01_blobs.tgz , v1.0-trainval02_blobs.tgz ,.. ) .
How do I unzip and merge them automatically
├── data
│   ├── nuscenes
│   │   │── v1.0-trainval
│   │   │   │── samples
│   │   │   │── sweeps
│   │   │   │── maps
│   │   │   │── v1.0-trainval

**Comment by whyekit-motional** [comment]
@tuan97anton do take a look at https://github.com/nutonomy/nuscenes-devkit/issues/732#issuecomment-1072922319
