### ISSUE TITLE
how to get ego routing point?

### ISSUE THREAD

**Issue by longjianquan** [nutonomy/nuscenes-devkit#769]

**Comment by whyekit-motional** [comment]
@longjianquan pls provide more details as what you mean by "ego routing point"

**Comment by longjianquan** [comment]
i  want to get routing points in ego frame with  each frame ,all routing points transform to ego frame image.

**Comment by whyekit-motional** [comment]
@longjianquan can you elaborate more on what you mean by "routing points"? Do you mean ego poses?
