### ISSUE TITLE
Nuscenes compatibility

### ISSUE THREAD

**Issue by saumil-kapadia-ola** [nutonomy/nuscenes-devkit#770]
Is nuscenes annotation can be converted to and from CVAT, COCO, VOC or any other annotated data formats?

**Comment by whyekit-motional** [comment]
@saumil-kapadia-ola the annotation format used in nuScenes can be converted to that of KITTI via https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_kitti.py

In additional, there are other conversion scripts which can be found here: https://github.com/nutonomy/nuscenes-devkit/tree/master/python-sdk/nuscenes/scripts
