### ISSUE TITLE
Nuscenes as nosql database document

### ISSUE THREAD

**Issue by saumil-kapadia-ola** [nutonomy/nuscenes-devkit#771]
Can nuscenes be done using nosql database as a document having all the relevant details rather having multiple tables and joining them?

**Comment by whyekit-motional** [comment]
@saumil-kapadia-ola there are currently no plans to provide the database in nuScenes as a NoSQL database

**Comment by Qiang-Xu** [comment]
@saumil-kapadia-ola can you elaborate more, for example, what you're trying to achieve

**Comment by saumilsdk** [comment]
@Qiang-Xu we need to extract camera images and annotate those using nuscenes or nuimages schema. For this we only have nosql db.
