### ISSUE TITLE
labels of 3d detection and semantic segmentation

### ISSUE THREAD

**Issue by mc171819** [nutonomy/nuscenes-devkit#773]
Hi, I'm a new user of nuscenes. I heard that nuscenes contains labels for semantic segmentation. Does one pointcloud has both labels for semantic segmentation and 3d detection? Or it likes KITTI that different pointcloud and labels for different tasks? @whyekit-motional

**Comment by whyekit-motional** [comment]
@mc171819 yes, for each point cloud, there are both 3D bounding boxes (from nuScenes) and point-level semantic labels (from Panoptic nuScenes)

**Comment by mc171819** [comment]
> @mc171819 yes, for each point cloud, there are both 3D bounding boxes (from nuScenes) and point-level semantic labels (from Panoptic nuScenes)

Yes, i see. However, following the totorial, if I want to use lidarseg or panoptic, the original catgory.json will be overwritten. So does it means that I can't use the labels of lidarseg/panoptic and 3d detection at the same time? @whyekit-motional
