### ISSUE TITLE
Why is the cycle different between camera and lidar

### ISSUE THREAD

**Issue by jongmokim7** [nutonomy/nuscenes-devkit#775]
first of all, thanks for the data!

You mentioned that the exposure of a camera is triggered when the top LIDAR sweeps across the center of the camera’s FOV.
If then, I think the capture cycle of the camera should be the same as the that of lidar at 20Hz. It seems contradictory. 
Can you tell me what I'm misunderstanding?

**Comment by whyekit-motional** [comment]
@jongmokim7 the cameras operate at 12 Hz while the lidar operates at 20 Hz, hence the capture cycle of the camera is not exactly the same as that of the lidar
