### ISSUE TITLE
Sample images without annotations

### ISSUE THREAD

**Issue by ocissor** [nutonomy/nuscenes-devkit#776]
Hello, I was trying to use your dataset for my college project and I would like to get sample images without annotations. How to get those images because in the render_sample function I don't see a way to get rid of those annotations whereas in render_image function there is an option for it, but I cannot use token from nuscenes in nuimages(gives a KeyError). Can you please help me?

**Comment by whyekit-motional** [comment]
@ocissor you could use `render_sample_data` and set `with_anns` to `False`: https://github.com/nutonomy/nuscenes-devkit/blob/28765b8477dbd3331bacd922fada867c2c4db1d7/python-sdk/nuscenes/nuscenes.py#L1220-L1222
