### ISSUE TITLE
Vehicle model of nuscenes dataset

### ISSUE THREAD

**Issue by chucktang98** [nutonomy/nuscenes-devkit#777]
Hey motional team, wondering what vehicle model you all used to collect the nuScenes dataset? Thanks!

**Comment by whyekit-motional** [comment]
@chucktang98 the [Renault Zoe](https://en.wikipedia.org/wiki/Renault_Zoe) is used in nuScenes (for more details, do check out https://www.nuscenes.org/nuscenes#data-collection)

**Comment by chucktang98** [comment]
Got it, I'm guessing this is the Zoe Preview (2010)?

**Comment by whyekit-motional** [comment]
@chucktang98 apologies, we no longer have the information about whether it was the Zoe Preview or the ZE 40 that was used for nuScenes

**Comment by chucktang98** [comment]
Hey @whyekit-motional it seems that Zoe Preview and ZE 40 only differed by battery so going to use the ZE 40 for now. Also, the [nuscenes.com/gallery](https://nuscenes.org/gallery) image seems like it is a ZE 40
