### ISSUE TITLE
radar dataset convert RadarObjects to PointCloud2

### ISSUE THREAD

**Issue by Nitinsn29** [nutonomy/nuscenes-devkit#778]
In nuscences dataset, inside sweeps the radar pointcloud data is in RadarObjects datatype format, how to convert them to PointCloud2 datatype format?

**Comment by whyekit-motional** [comment]
@Nitinsn29 there isn't a method within nuScenes that performs this conversion from `pcd` format to `PointCloud2` format (I assume your are referring to http://docs.ros.org/en/lunar/api/sensor_msgs/html/msg/PointCloud2.html), but you could definitely write something up based on the information in each `pcd` file: https://github.com/nutonomy/nuscenes-devkit/blob/28765b8477dbd3331bacd922fada867c2c4db1d7/python-sdk/nuscenes/utils/data_classes.py#L313-L323

**Comment by Nitinsn29** [comment]
Is there any reference code to modify inside the .pcd file?

**Comment by whyekit-motional** [comment]
@Nitinsn29 I would strongly recommend you to not modify anything within the .pcd files
