### ISSUE TITLE
radar dataset early fusion

### ISSUE THREAD

**Issue by Nitinsn29** [nutonomy/nuscenes-devkit#779]
In nuscences dataset, there are 5 radars used, so we are having radar_top, radar_front_left, radar_front_right, radar_back_left, radar_back_right, is there any common timestamp for those 5 radar to fuse the data? 
otherwise how to perform the early fusing using these 5 radar data's?

**Comment by whyekit-motional** [comment]
@Nitinsn29 if you are working with keyframes, the timestamps of the data from all the sensors should be very close to each other
