### ISSUE TITLE
Tracking: Matching tracking results with NuScenes Ground Truth

### ISSUE THREAD

**Issue by sfxsalem** [nutonomy/nuscenes-devkit#780]
I have results from running a tracking algorithm CenterPoint on Nuscenes data.
How do I perform matching then between the results and ground truth (most importantly re-assign the instance_token to each result to take place of the existing tracking_id in the results file)

**Comment by whyekit-motional** [comment]
@sfxsalem there is an evaluation script for the nuScenes tracking task which you can use directly: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/tracking/evaluate.py
