### ISSUE TITLE
Do I need the whole dataset (samples and sweeps) to read maps and trajectories?

### ISSUE THREAD

**Issue by Lionel-Lee** [nutonomy/nuscenes-devkit#787]
I only need the map and trajectory information, which I believe is included in the meta data. However, when I tried to use v1.0-trainval with only meta and map extension, the program got killed when creating the NuScenes object. Do I really need to download all the camera/lidar /radar files?

**Comment by whyekit-motional** [comment]
To instantiate a `NuScenes` object, you would really only need the metadata files (e.g. `attribute.json`, `calibrated_sensor.json`, `category.json`, etc.)
