### ISSUE TITLE
nuScenes LiDAR velodyne hdle 32 return mode Strongest or Last?

### ISSUE THREAD

**Issue by chucktang98** [nutonomy/nuscenes-devkit#789]
Did the velodyne 32e model use a return mode of strongest or last? 

For reference:
https://velodynelidar.com/wp-content/uploads/2019/09/63-9277-Rev-D-HDL-32E-Application-Note-Packet-Structure-Timing-Definition.pdf

**Comment by chucktang98** [comment]
Also is Dual Return enabled on the velodyne LiDAR?

**Comment by whyekit-motional** [comment]
For the lidar in nuScenes (Velodyne HDL32E), it was single return and in strongest mode
