### ISSUE TITLE
Error when unzip the nuscenes dataset

### ISSUE THREAD

**Issue by BoPang1996** [nutonomy/nuscenes-devkit#791]
Hi, thanks for the dataset.

I have trouble when unzipping the v1.0-trainvalxx_blobs.tgz files. I have tried to unzip on Ubuntu with "tar -xf" and unzip on Windows with WinRAR, but they all say the file is not complete. I have checked the md5 of all the blobs. They are different from the mentioned ones but the size of the files are the same. I have tried to download the data with wget for 3 times. The results are all the same. Do I do something wrong?
 
![截图](https://user-images.githubusercontent.com/17980676/180377490-7d57e092-2a88-4e86-977e-b6b68ba9187d.PNG)
![截图2](https://user-images.githubusercontent.com/17980676/180377512-80314635-604b-4dfe-9a76-c30b81f7bdbd.PNG)

**Comment by whyekit-motional** [comment]
@BoPang1996 it is possible that WinRAR does not recognize the `.tar` file format properly - pls try renaming the `.tar` files to `.tbz2` and extracting them

**Comment by BoPang1996** [comment]
but the md5 code are different. Is this all right? Is there a way to solve this on Ubuntu?

**Comment by whyekit-motional** [comment]
If you have an ubuntu machine, you can simply keep the files in the `.tgz` format, and extract them like so: https://github.com/nutonomy/nuscenes-devkit/issues/732#issuecomment-1072922319

**Comment by BoPang1996** [comment]
Maybe there is something wrong with Asia links. Previously, I downloaded from the Asia links and there always are problems. When I changed to the US links, everything is all right.
