### ISSUE TITLE
convert KITTI dataset into nuscenes dataset

### ISSUE THREAD

**Issue by liyejlu** [nutonomy/nuscenes-devkit#792]
Hello, is there any way to convert KITTI dataset into nuscenes dataset?

**Comment by whyekit-motional** [comment]
@liyejlu do take a look at https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_kitti.py

**Comment by kkrl1111** [comment]
> @liyejlu do take a look at https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_kitti.py

This file seems to only convert nuscenes to Kitti datasets. I want to convert Kitti to nuscenes, but I can't find this function

**Comment by whyekit-motional** [comment]
@kkrl1111 in that same script, see the [`kitti_res_to_nuscenes`](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_kitti.py#L274) method
