### ISSUE TITLE
Question about calibration

### ISSUE THREAD

**Issue by konyul** [nutonomy/nuscenes-devkit#793]
Is there any calibration matrix that maps 3D bounding box in lidar coordinate to image???
I tried map_pointcloud_to_image function that maps pcd to image, however it did not work.

**Comment by whyekit-motional** [comment]
@konyul pls see this part of the code for an example that projects the 3D bounding boxes on to a 2D image: https://github.com/nutonomy/nuscenes-devkit/blob/28765b8477dbd3331bacd922fada867c2c4db1d7/python-sdk/nuscenes/nuscenes.py#L1437-L1453

**Comment by konyul** [comment]
I understand that this code can be used to generate 2d bounding box from 3d bounding box. however, the output 2d bounding box is not set to original image size. It is set to some other size. is there any idea to resolve this?
