### ISSUE TITLE
Syntax error 

### ISSUE THREAD

**Issue by ParkJunYeop** [nutonomy/nuscenes-devkit#795]
`import os
import json
import numpy as np

from tqdm import tqdm
from nuscenes import NuScenes`

I imported nuscenes devkit from this page and I tried to import nuscenes.py using from nuscenes import NuScenes

But I have the following error

Traceback (most recent call last):
  File "/home/yeop/Nuscenes/nuscenes-devkit/python-sdk/nuscenes/nuscene_processing_ex1.py", line 6, in <module>
    from nuscenes import NuScenes
  File "/home/yeop/Nuscenes/nuscenes-devkit/python-sdk/nuscenes/nuscenes.py", line 46
    version: str = 'v1.0-mini',
           ^
SyntaxError: invalid syntax

Can anyone please tell me what's wrong with this?
I haven't touched any contents of the nuscenes.py

**Comment by ParkJunYeop** [comment]
I',m currently using python version 3.6.9

**Comment by whyekit-motional** [comment]
@ParkJunYeop based on the error msg you pasted above, `version: str = 'v1.0-mini',` is on L46 while the source code has it on L45: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L45

My guess is that you changed something in the source code

If you have no need to modify the source code, I would suggest installing the devkit via:
```
pip install nuscenes-devkit
```

And then simply doing this will work:
```
from nuscenes.nuscenes import NuScenes


nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=False)
```

**Comment by ParkJunYeop** [comment]
Oh I'm sorry I actually wrote one line which is:
from __future__ import annotations

And even if I erase this and run the file, I still get the same error...

![code_screen_shot](https://user-images.githubusercontent.com/61575966/181230072-b87dbb75-d878-4164-b9bd-04ee6133c0e0.png)

![error_screen_shot](https://user-images.githubusercontent.com/61575966/181230097-03322441-80fc-47d4-9b20-83a7ca97a4c7.png)

Could you tell me why that happens?

**Comment by whyekit-motional** [comment]
@ParkJunYeop I can't reproduce your error even when I do `pip install nuscenes-devkit` on python 3.6.9:
```
import platform

import nuscenes
from nuscenes.nuscenes import NuScenes


print(f'python version: {platform.python_version()}')  # This prints "3.6.9"

nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=False)
```

Perhaps you can try doing this to see where you have installed `nuscenes-devkit`:
```
import nuscenes


print(nuscenes.__path__)
```
There could have been some issue when you installed it

You can also try doing `pip install nuscenes-devkit` in a fresh virtual environment

**Comment by ParkJunYeop** [comment]
Thanks! I figured out what the problem was!
