### ISSUE TITLE
where are the noisy LiDAR points from the velodyne sensor

### ISSUE THREAD

**Issue by chucktang98** [nutonomy/nuscenes-devkit#796]
For most LiDAR sensors, a large portion of points (~10% give or take) will fall below the signal to noise ratio/hit air and will be classified as noise. This either results in a) the LiDAR point clouds varying significantly in size and/or b) a lot of points being classified as the same NOISE value e.g. [0, 0, 0] in the LIDAR point cloud. 

For the nuScenes data, it seems that all LiDAR scans are around 35000 points and there are no repeated common NOISE values. I'm curious where these noisy LiDAR point clouds are/were they filtered by the LiDAR sensor itself?

**Comment by whyekit-motional** [comment]
@chucktang98 if you refer to [Panoptic nuScenes](https://arxiv.org/abs/2109.03805), you will be able to find these `noise` points: https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/instructions_lidarseg.md#1-noise-class-0

**Comment by chucktang98** [comment]
@whyekit-motional it seems that the noisy values don't get filtered and that they still come back with return intensity.  Also, it seems that for most lidar scans only ~1% of the points are noisy e.g: 50 / 34000

Curious if you know what the minimum signal to noise ratio threshold it is for a LiDAR point sent to be classified as noise or not? Or is that not how you guys evaluate noisy LiDAR Points?

```
import nuscenes 
import os 
from nuscenes.utils.data_io import load_bin_file
from collections import Counter
import numpy as np

nusc = nuscenes.NuScenes('v1.0-mini', '/data/sets/nuscenes/')
noise_counter = Counter()
noise_intensity_counter = Counter()
for p in nusc.panoptic:
    panoptic_label_file = os.path.join(nusc.dataroot, p['filename'])
    sd_rec = nusc.get('sample_data', p['sample_data_token'])
    lidar_path = os.path.join(nusc.dataroot, sd_rec['filename'])
    lidar_cloud = np.fromfile(lidar_path, dtype=np.float32).reshape((-1, 5))
    panoptic_label_npz = load_bin_file(panoptic_label_file, 'panoptic')
    num_lidar_pts_noise = sum(panoptic_label_npz == 0)
    noise_counter[num_lidar_pts_noise] += 1
    intensity_noise = lidar_cloud[(panoptic_label_npz == 0), 4]
    num_intensity_greater_than_zero = sum(intensity_noise > 0)
    noise_intensity_counter[num_intensity_greater_than_zero] += 1
    print(f"num lidar points noise {num_lidar_pts_noise} num non-zero intensity points noise {num_intensity_greater_than_zero}")
    

print(noise_intensity_counter)
print(noise_counter)
print(noise_counter.most_common()[0])
print("Any greater than 1000", any(np.array(noise_counter.keys()) > 1000))
```

**Comment by chucktang98** [comment]
another way to rephrase this question is how does the lidar point cloud store points that hit nothing? do we filter it, store it as a common value, mark it as noise? I think the noise class has too little counts in panoptic segmentation @whyekit-motional

**Comment by whyekit-motional** [comment]
@chucktang98 if a given lidar point hits nothing, then there would not be a return. As such, no point will appear in the point cloud.

**Comment by jingyibo123** [comment]
@chucktang98  It does seems that all `.bin` files contain exactly `N * 32` points, and the ring_index is always continuous from 0 to 31, if there's a  point with no return (eg. sky), that shouldn't be the case.
