### ISSUE TITLE
What is the velodyne hdle32 lidar scan pattern serialization format

### ISSUE THREAD

**Issue by chucktang98** [nutonomy/nuscenes-devkit#797]
Hi motional team, I'm curious what is the velodyne hdle32 lidar scan pattern serialization format? 

Concretely, do you guys have a datasheet that explains more in depth how these lidar points get serialized out? E.g: similar to [this](https://hexagondownloads.blob.core.windows.net/public/AutonomouStuff/wp-content/uploads/2019/05/HDL-32E_Datasheet_whitelabel.pdf) datasheet from velodyne but a bit more fleshed out on the serialization format. 

Concretely, at every scan we have around 695000 / 20 = 34000 lidar points. 
- point 1 is the first channel ring index at 0 degrees azimuth and 10 degrees vertical elevation angle
- point 2 is the first channel ring index at 0 degrees azimuth and 9.9 degrees vertical elevation angle.
...
- point 34000 is the last channel ring index at 360 degrees azimuth and -30 degrees vertical elevation angle?

**Comment by whyekit-motional** [comment]
@chucktang98 there are a bunch of resources on Velodyne's product page for the HDL-32E: https://velodynelidar.com/products/hdl-32e/#downloads

Perhaps one of the documents listed there will have what you want
