### ISSUE TITLE
Converting 3D bounding Box in LiDAR coordinate to 3D bounding Box in Camera coordinate

### ISSUE THREAD

**Issue by konyul** [nutonomy/nuscenes-devkit#798]
I want to project 3D bounding box in lidar coordinate to image. However, I see there is a code that projects 3D bounding box in camera coordinate to image. Is there any codes that can convert 3D bounding Box in LiDAR coordinate to 3D bounding Box in Camera coordinate?

**Comment by whyekit-motional** [comment]
@konyul do take a look at the `get_sample_data` method: https://github.com/nutonomy/nuscenes-devkit/blob/28765b8477dbd3331bacd922fada867c2c4db1d7/python-sdk/nuscenes/nuscenes.py#L248-L255

As stated in the docstring, the boxes returned by that method will be in the camera coordinate frame (as long as you pass in a `sample_data_token` that belongs to a camera)
