### ISSUE TITLE
AssertionError: Database version not found:

### ISSUE THREAD

**Issue by ParkJunYeop** [nutonomy/nuscenes-devkit#799]
Due to its huge amount data, I'm currently working on to separate json file with respect to scene.
I'm working on for Mapillary and Megvii json file(train, validation, test)

On the way for that, I got an Assertion error as follows:
AssertionError: Database version not found: /Home/Nuscenes/nuscenes-devkit/python-sdk/nuscenes/v1.0-mini

nusc = NuScenes(version='v1.0-mini', dataroot=data_root, verbose=False)
data_root = '/Home/Nuscenes/nuscenes-devkit/python-sdk/nuscenes'

I actually couldn't understand how this file catches the version(should I make a folder?? Cuz in the tutorial there was mini folder  I downloaded all the files through github and there was no v1.0-mini folder in nuscenes folder)

Should set dataroot to the location that has Mapillary and Megvii json file? And how do I set the version?

**Comment by whyekit-motional** [comment]
@ParkJunYeop your folder structure for nuScenes should look like this:
```
/data/sets
└── nuscenes  
    ├── maps
    │
    ├── samples
    │    ├── CAM_{BACK*, FRONT*} --> contains .png images 
    │    ├── LIDAR_TOP --> contains .bin files
    │    └── RADAR_{BACK*, FRONT*} --> contains .pcd files
    │
    ├── sweeps
    │    ├── CAM_{BACK*, FRONT*} --> contains .png images 
    │    ├── LIDAR_TOP --> contains .bin files
    │    └── RADAR_{BACK*, FRONT*} --> contains .pcd files
    │
    └── v1.0-{mini, test, trainval}       
        └── attribute.json, calibrated_sensor.json, category.json, etc. 
```
As you can see from the above, `/data/sets/nuscenes` is the folder path for `dataroot` (you should make this folder path on your machine, if it does not already exist) - so as long as you stick with the above folder structure, the following should work:
```
nusc = NuScenes(version="v1.0-mini", dataroot="/data/sets/nuscenes", verbose=False)
```

**Comment by ParkJunYeop** [comment]
I downloaded mini file from nuscene official site and made the same structure shown below.


home/Nuscene/data/sets
└── nuscenes  
    ├── maps
    │
    ├── samples
    │    ├── CAM_{BACK*, FRONT*} --> contains .png images 
    │    ├── LIDAR_TOP --> contains .bin files
    │    └── RADAR_{BACK*, FRONT*} --> contains .pcd files
    │
    ├── sweeps
    │    ├── CAM_{BACK*, FRONT*} --> contains .png images 
![cap](https://user-images.githubusercontent.com/61575966/181491604-b865bebf-a936-4fce-a07a-eb85dfc9dc44.png)

    │    ├── LIDAR_TOP --> contains .bin files
    │    └── RADAR_{BACK*, FRONT*} --> contains .pcd files
    │
    └── v1.0-{mini, test, trainval}       
        └── attribute.json, calibrated_sensor.json, category.json, etc. 

but the code below still doesn't work!

`nusc = NuScenes(version="v1.0-mini", dataroot="/home/Nuscene/data/sets/nuscenes", verbose=False)`

![cap](https://user-images.githubusercontent.com/61575966/181491657-300a8bfb-0172-4fbd-a3a5-3f26508f5872.png)
could you tell me what's wrong with that?

**Comment by ParkJunYeop** [comment]
Oh yes now it finally works!

But may I ask you one more thing sir?

How can I load Mapillary, Megvii files? which is the json files of camera and lidar detection file from the following link:
https://www.nuscenes.org/tracking?externalData=all&mapData=all&modalities=Any

**Comment by ParkJunYeop** [comment]
Even if I try to load files, due to its huge dataset I cannot see them.... Is there any way to slice with respect to each scene?

**Comment by whyekit-motional** [comment]
@ParkJunYeop I'm glad `nuscenes-devkit` is now working for you!

As for loading the Mapillary and Megvii baselines, you can simply use the `json` package to parse the files

**Comment by ParkJunYeop** [comment]
Thanks for your advice!
