### ISSUE TITLE
len(nusc.sample) doesn't equal to the numbers in file numbers in nuscenes/samples/LIDAR_TOP

### ISSUE THREAD

**Issue by JSRGFJZ** [nutonomy/nuscenes-devkit#8]
Hi, I just run your tutorial.ipynb, and I notice that : 
len(nusc.sample) = 3977
while
actually in nuscenes/samples/LIDAR_TOP, we just see 3962 .bin files

and why is that?

**Comment by holger-nutonomy** [comment]
Hi Jean, thank you for bringing this up. It turns out the scenes 169 and 170 overlap by 13s., which is why they use the same pointcloud files. For the teaser release that should not be a problem. Going forward we will delete scene 169 to avoid confusion.

**Comment by JSRGFJZ** [comment]
@holger-nutonomy thanks for your quick reply!
