### ISSUE TITLE
How are pedestrians on bicycles labelled in nuImages?

### ISSUE THREAD

**Issue by utkutpcgl** [nutonomy/nuscenes-devkit#800]
Thanks for your great contribution!

I have a simple question about nuImages bounding box annotation.

I am aware when that when a person is on a motorcycle, the bounding box covers them both with the label "vehicle.motorcycle". I am confused if the same applies to `vehicle.bicycle`. 

So, when a person is on a bicycle does the bounding box cover both the person and bicycle while the label is `vehicle.bicycle`?

Thanks in advance.

**Comment by whyekit-motional** [comment]
@utkutpcgl yes, both the rider on the bicycle and the bicycle itself would be bounded with a single box with the class `vehicle.bicycle`

As an example:
```
import json

from nuscenes.nuscenes import NuScenes


nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=False)

sample_ann_token ='1796f2adb80543d7a90ac9b62e11f79d'

print(json.dumps(nusc.get('sample_annotation', sample_ann_token), indent=4))
nusc.render_annotation(sample_ann_token)
```
The above code snippet will give you:
```
{
    "token": "1796f2adb80543d7a90ac9b62e11f79d",
    "sample_token": "1c9a906c40f6417bbe1cea06d6e55501",
    ...
    "visibility_token": "4",
    "attribute_tokens": [
        "a14936d865eb4216b396adae8cb3939c"
    ],
    "translation": [
        683.746,
        1588.663,
        0.89
    ],
    "size": [
        0.717,
        1.864,
        1.932
    ],
    ...
    "num_lidar_pts": 106,
    ...
    "category_name": "vehicle.bicycle"
}
```
![cycle_with_rider](https://user-images.githubusercontent.com/62535720/181752499-b511d383-29eb-47a4-9073-d591b029e186.png)

**Comment by utkutpcgl** [comment]
Thank you very much, I was about to do the same :)

**Comment by whyekit-motional** [comment]
@utkutpcgl I just realized you were asking about nuImages (not nuScenes) above, but you can use the same concept I suggested above to check if a single bounding box encompasses both a bike and its rider when it comes to nuImages

**Comment by utkutpcgl** [comment]
If it helps to others, I noticed that there is another extra annotation for bicycles showing the rider state:

![f4fb531b-b706-492e-90f8-a4241520f3f7](https://user-images.githubusercontent.com/18088068/182841272-65205007-6e70-44e1-908f-211b981fa8f6.jpg)

with_rider and without_rider annotations was what I was looking for.
