### ISSUE TITLE
LiDAR points by "render_point_cloud_in_image" seems misaligned.

### ISSUE THREAD

**Issue by seb-le** [nutonomy/nuscenes-devkit#802]
Hi, first thank you for sharing this dataset and its devkit.

I have faced a misalignment issue when I run the official render code.

The code snippets are below:

```python
sample_token = '7c0aa537b98344bea85226ba8148ae98'
nusc.render_pointcloud_in_image(sample_token, dot_size=1, out_path='./out.png', verbose=False)
```

As I know, if I run the code, the point cloud is scattered on the image with colors by depth values.

However, As described in the below image, there are some misaligned points as in the red boxes.

How can I solve this problem?

![image](https://user-images.githubusercontent.com/74757131/181914119-14a82901-35d2-4ef5-b86e-2488af06ac2c.png)

**Comment by whyekit-motional** [comment]
@seb-le it is difficult to assess any alignment (or lack thereof) from the camera view, as you have to take into account the parallax (the lidar is at a different position than the camera).

Using one of the areas you have pointed out as an example:
![image](https://user-images.githubusercontent.com/62535720/182024875-67721aa4-7653-49f2-87f9-50f9b0275904.png)

Some of these points (e.g. the green points which make up a line, in my above picture) are really on the building behind the electric box, and hence they look wrong. 

A better way to judge the alignment would be to look at the point cloud itself.
