### ISSUE TITLE
What is the global coordinate system? Is the global coordinate system equal to the world coordinate system?

### ISSUE THREAD

**Issue by lvxuanxuan123** [nutonomy/nuscenes-devkit#803]

**Comment by whyekit-motional** [comment]
@lvxuanxuan123 the global coordinate system is with respect to the map, where [0, 0, 0] would be the "top left" corner of the map.

**Comment by admyxs** [comment]
> @lvxuanxuan123 the global coordinate system is with respect to the map, where [0, 0, 0] would be the "top left" corner of the map.

thank for you hard work, about global coordinate system, I have two question:
1、what is the origin of the z-axis?
2、Is x pointing to the right?

**Comment by whyekit-motional** [comment]
@admyxs pls refer to https://github.com/nutonomy/nuscenes-devkit/issues/687#issuecomment-970109514
