### ISSUE TITLE
Occluded Labeling Questions

### ISSUE THREAD

**Issue by moon5ye** [nutonomy/nuscenes-devkit#804]
Thank you so much for the impressive dataset.

We recently wanted to label a dataset and want to learn some strategies from Nuscene.

Here is one question related to the dataset labeling. I noticed the Nuscene dataset also labels the occluded part of the objects. On the Nuscene webpage "If an object is occluded, then draw the bounding box to include the occluded part of the object according to your best guess."

The question is why do we label the occluded parts? Because I noticed some datasets only label the visible parts of the objects. Will it cause some difference for the deep learning model if we choose different occlusion labeling methods? Personally, I feel we should label the occluded part if the occluded parts are important for the objective.

**Comment by whyekit-motional** [comment]
@moon5ye a possible reason for drawing a bounding box even around the occluded parts of an object, would be to maintain a "reasonable" distribution of size for the object's class. 

As an example, the length of cars follow some sort of distribution in the real world - for the purpose of discussion, let's say the length of cars follow a normal distribution centered at 4.5 m in the real world. 

Now, if in your dataset, you only label the un-occluded part of cars, the resulting distribution of the length of cars in your dataset is unlikely to match that of the real world.

This may or may not be important to you, depending on the aim of your dataset (e.g. if your dataset is intended to train models to simply determine whether there is a car in an image, the lack of an identical distribution between your dataset and the real world may not be as important to you / the users of your dataset).
