### ISSUE TITLE
Radar vx_comp, vy_comp; x_rms, y_rms meaning? 

### ISSUE THREAD

**Issue by chucktang98** [nutonomy/nuscenes-devkit#805]
Hey motional team, two questions:
-  What is vx_comp and vy_comp's difference from  vx vy for the radar field? In this [line](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/data_classes.py#L329-L331 ) it says that vx_comp is compensated by ego motion velocity but what does that mean? 

- Also, wondering what x_rms and y_rms mean: 
https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/data_classes.py#L315

**Comment by whyekit-motional** [comment]
@chucktang98 here are some clarifications to your questions:

- > What is vx_comp and vy_comp's difference from vx vy for the radar field? In this [line](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/data_classes.py#L329-L331) it says that vx_comp is compensated by ego motion velocity but what does that mean?

`vx` and `vy` are the component velocities in the current radar frame (e.g. if the ego vehicle moves forward at 10m/s, a stationary vehicle in front of it should have a velocity of -10m/s). `v*_comp` are the component velocities after adjustment for the movement of the ego vehicle (in my preceding example, `v*_comp` should be 0m/s for the stationary vehicle).

- > Also, wondering what x_rms and y_rms mean:
https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/data_classes.py#L315

rms is "root mean square"
