### ISSUE TITLE
Result format issue

### ISSUE THREAD

**Issue by ParkJunYeop** [nutonomy/nuscenes-devkit#806]
Hello sir, I'd like to ask you my issue about Result format

Q 1 Rotation Issue

As I saw from the result format, I need four values to run the evaluation code(tracking).
From the result format, It says I need estimated rotation value. 

Does it mean that I need to run kalman flter to estimate the rotation value for the next time step?
Or
Can I just bring the value from the dataset and apply it directly to the evaluation code?

Q 2 Velocity Issue

From the mapillary dataset(camera), there's no velocity value. 
Then do I just have to put zeros for the evaluation code?

Meanwhile, megvii dataset(lidar) has!
In this case, can I just put the same value?

Q3 Size Issue
what does Estimated size means? (size cannot be changed??)

**Comment by whyekit-motional** [comment]
@ParkJunYeop here are the clarifications to your various queries:

- > Does it mean that I need to run kalman flter to estimate the rotation value for the next time step? Or can I just bring the value from the dataset and apply it directly to the evaluation code?

There isn't any ground truth provided for the test set, so you would not be able to simply copy the rotation value of each agent and submit that. Running a kalman filter is a possibility.

- > From the mapillary dataset(camera), there's no velocity value. Then do I just have to put zeros for the evaluation code? Meanwhile, megvii dataset(lidar) has! In this case, can I just put the same value?

I'm not sure how copying the values from another model would help you - your model should produce the velocity values.

- > what does Estimated size means? (size cannot be changed??)

It simply means the size of an agent, as inferred by your model.

**Comment by ParkJunYeop** [comment]
For the first question:
Yes, there's no GT for the test set, I'm actually trying to run the evaluation code for the validation set.
So in the tracking result format, it says I'll need to use rotation value which needs to be like the format below:

 "rotation":       <float> [4]   -- Estimated bounding box orientation as quaternion in the global frame: w, x, y, z.

I'm actually going to use Kalman Filter to predict for the next step for every time step.
Can I apply rotation values from the mapillary_val, megvii_val directly to my json file?(which I'll run for the evaluation code) 
Or do I have to do something for the rotation ?
