### ISSUE TITLE
road block records in singapore-queenstown haven't got polygon token

### ISSUE THREAD

**Issue by Mrmoore98** [nutonomy/nuscenes-devkit#809]
Hi
I found that polygon tokens in roadblock all records are all None and the exterior and holes attributes of each record have an extremely large number of node tokens. I found these abnormal records only in roadblock records of hollandvillage and queenstown. Other locations do not have this issue.

**Comment by whyekit-motional** [comment]
@Mrmoore98 do provide a code snippet to reproduce your observation pls, thanks!

**Comment by Mrmoore98** [comment]
The code to reproduce the problem is shown below.

    import numpy as np
    from nuscenes.map_expansion.map_api import NuScenesMap
    location = 'singapore-queenstown'
    nuscenes_map = NuScenesMap(dataroot='/mnt/datasets/nuScenes', map_name=location)
    count = 0
    exterior_nodes = []
    for rc in nuscenes_map.road_block:
        if rc['polygon_token'] is None:
            count += 1
        
        exterior_nodes.append(len(rc['exterior_node_tokens']))
    
    print('polygon None num:', count)
    exterior_nodes = np.array(exterior_nodes)
    print('exterior_node statistics: mean({}), max({})'.format(exterior_nodes.mean(), exterior_nodes.max()))


the outputs are:

  
      polygon None num: 676
      exterior_node statistics: mean(7748.0), max(7748)

**Comment by whyekit-motional** [comment]
Duplicate of https://github.com/nutonomy/nuscenes-devkit/issues/810
