### ISSUE TITLE
how to find the corresponding camera type only through "sample_annotation"

### ISSUE THREAD

**Issue by yushengjiexy** [nutonomy/nuscenes-devkit#811]
I got the sample_annotation "1408af8e897d40fbbd78c33b59f8821f", then i render the annotation.
![image](https://user-images.githubusercontent.com/63044657/185361000-8be3e007-8b82-4006-93b1-09008fde5847.png)
![image](https://user-images.githubusercontent.com/63044657/185361001-c44a2569-27ce-43a8-b5b1-3caa42186d25.png)
You can see the picture captured by "CAM_FRONT_LEFT".
I want to ask you how to get the camera type by code.

**Comment by yushengjiexy** [comment]
Because i want to convert "obj_pose_in_world" to "obj_pose_in_cam".

**Comment by whyekit-motional** [comment]
@yushengjiexy you could try something like this:
```
from typing import Optional
from nuscenes.nuscenes import NuScenes


def get_cam_of_sample_annotation_token(nusc: NuScenes, sample_ann_token: str) -> Optional[str]:
    """
    Figure out which camera the object is fully visible in.
    """
    sample_ann = nusc.get('sample_annotation', sample_ann_token)
    sample = nusc.get('sample', sample_ann['sample_token'])

    # Figure out which camera the object is fully visible in (this may return nothing).
    cams = [key for key in sample['data'].keys() if 'CAM' in key]
    for cam in cams:
        _, boxes, _ = nusc.get_sample_data(sample['data'][cam], selected_anntokens=[sample_ann_token])
        if len(boxes) > 0:
            return cam  # We found an image that matches. Let's abort.
        

nusc_ = NuScenes(version='v1.0-trainval', dataroot='/data/sets/nuscenes', verbose=False)

print(get_cam_of_sample_annotation_token(nusc_, '1408af8e897d40fbbd78c33b59f8821f'))
```


Note that this was modified from [`render_annotation`](https://github.com/nutonomy/nuscenes-devkit/blob/28765b8477dbd3331bacd922fada867c2c4db1d7/python-sdk/nuscenes/nuscenes.py#L1473)
