### ISSUE TITLE
Question about box_in_image

### ISSUE THREAD

**Issue by s-ryosky** [nutonomy/nuscenes-devkit#814]
Why are you repeating similar actions with different thresholds?

https://github.com/nutonomy/nuscenes-devkit/blob/28765b8477dbd3331bacd922fada867c2c4db1d7/python-sdk/nuscenes/utils/geometry_utils.py#L73-L75

**Comment by whyekit-motional** [comment]
@s-ryosky these two lines are not necessarily similar - in addition to a different threshold, the first line also compares `corners_3d[2, :]` against a `visible` mask
