### ISSUE TITLE
what`s the differents between translation and ego_translation?

### ISSUE THREAD

**Issue by qingzhouzhen** [nutonomy/nuscenes-devkit#815]
I got an infence result like 
`   {'sample_token': '3e8750f331d7499e9b5123e9eb70f2e2', 'translation': [637.141, 1636.252, -0.235], 
    'size': [0.621, 0.647, 1.778], 'rotation': [0.3495370229501108, 0.0, 0.0, 0.9369225526088982], 
    'velocity': array([-0.82728047,  0.65143342]), 
    'ego_translation': (37.020786205233094, -11.238776275174132, -0.235), 'num_pts': 1, 
    'detection_name': 'pedestrian', 'detection_score': -1.0, 'attribute_name': 'pedestrian.moving'}`
what is the different between translation and ego_translation?

**Comment by whyekit-motional** [comment]
@qingzhouzhen `translation` refers to the position of an agent (in the global frame), while I belive `ego_translation` would be the position of the ego (in the global frame)

Do note that `ego_translation` is not required to be inferred (see [here](https://github.com/nutonomy/nuscenes-devkit/tree/master/python-sdk/nuscenes/eval/detection#results-format)), if you are submitting your inference results as part of the nuScenes detection challenge
