### ISSUE TITLE
missing so many jsons

### ISSUE THREAD

**Issue by sainttelant** [nutonomy/nuscenes-devkit#816]
hello, everyone, i am so confused that  when i tried to construct  the instance of nusences, i inited  the nusences' class by calling the __init__ function in nuscenes.py file , however, i found there are so many json files missing on foldersof v1.0-* which i downloaded from website, namely, the lastest version of nuimages-v1.0-all-metadata.tgz,  i checked the foloders on the path, these missing files really don't exist...

i installed the nuscenes-devlit version 1.1.9,  but i noticed the nuscenes.py , it still tried to construct instance of nuscenes' class by __load_table__("visibilty") and ("scene:) where couldn't be found on the path

**Comment by sainttelant** [comment]
so,  where can i download the full trainval datasets which contains visibility.json, scene.json so far??

**Comment by whyekit-motional** [comment]
@sainttelant your folder structure for nuScenes should look like this:
```
/data/sets
└── nuscenes  
    ├── maps
    │
    ├── samples
    │    ├── CAM_{BACK*, FRONT*} --> contains .png images 
    │    ├── LIDAR_TOP --> contains .bin files
    │    └── RADAR_{BACK*, FRONT*} --> contains .pcd files
    │
    ├── sweeps
    │    ├── CAM_{BACK*, FRONT*} --> contains .png images 
    │    ├── LIDAR_TOP --> contains .bin files
    │    └── RADAR_{BACK*, FRONT*} --> contains .pcd files
    │
    └── v1.0-{mini, test, trainval}       
        └── attribute.json, calibrated_sensor.json, category.json, etc. 
```
As you can see from the above, `/data/sets/nuscenes` is the folder path for `dataroot` (you should make this folder path on your machine, if it does not already exist) - so as long as you stick with the above folder structure, the following should work:
```
nusc = NuScenes(version="v1.0-mini", dataroot="/data/sets/nuscenes", verbose=False)
```

**Comment by sainttelant** [comment]
@whyekit-motional , sorry for that, you still don't solve the issue of missing files, like visibility.json,  i couldn't find any folders which contain the visibility.json by manually searching on each folder.    however , the nuscenes.py file still tries to __load_table__ ('visibility') on line 71.   when i sorted  all folders as you mentioned above.

**Comment by sainttelant** [comment]
@whyekit-motional         self.visibility = self.__load_table__('visibility')  in line 71 for nuscenes.py,  it means it tries to open the visibility.json on searching the folder path

**Comment by whyekit-motional** [comment]
@sainttelant I also noticed one other thing - in your [initial question](https://github.com/nutonomy/nuscenes-devkit/issues/816#issue-1364015083), you mentioned that you downloaded the dataset for nuImages:

> i found there are so many json files missing on foldersof v1.0-* which i downloaded from website, namely, the lastest version of nuimages-v1.0-all-metadata.tgz

However, it seems that you instantiated the `NuScenes` class:
> i inited the nusences' class

If you are interested in nuImages, you should be using the `NuImages` class, e.g.:
```
from nuimages import NuImages

nuim = NuImages(dataroot='/data/sets/nuimages', version='v1.0-mini', verbose=True, lazy=True)
```
(Pls the [nuImages tutorial](https://www.nuscenes.org/nuimages#tutorials) for more details)

**Comment by sainttelant** [comment]
@whyekit-motional Thanks you very much, it seems that the issue has been located, i will check the folders to make them correspond correctly.
