### ISSUE TITLE
Calculating false positives through gt and preds boxes that are very close by but wrong class

### ISSUE THREAD

**Issue by ytan101** [nutonomy/nuscenes-devkit#818]
I would like to check if it is possible to calculate false positives by considering ground truth and predicted bounding boxes that are very close by but are the wrong class.

From what I understand, the current evaluation (https://github.com/nutonomy/nuscenes-devkit/blob/87b88fe37ad503e6e35dc2546ae1bf74f4ef6c01/python-sdk/nuscenes/eval/detection/algo.py) finds the closest bounding box of the same class (line 81) and checks if it is close to the ground truth box. Using the distance threshold, we can tweak the sensitivity of the prediction being a true or false positive.

However, is it possible to consider boxes that aren't the same class to be false positives as well? For example, if a `bus` box is predicted right on top of a `car` ground truth, can this be used as an indication of a false positive too? I would like to build a multi-class confusion matrix along this thought process.

Thank you very much

**Comment by whyekit-motional** [comment]
@ytan101 creating a multi-class confusion matrix for object detection should be possible - do check out [this post](https://stackoverflow.com/questions/46110545/whats-the-correct-way-to-compute-a-confusion-matrix-for-object-detection/52732119#52732119) for more details, and [this code](https://github.com/svpino/tf_object_detection_cm/blob/master/confusion_matrix.py) for inspiration
