### ISSUE TITLE
Points per second for HDL-32e LiDAR sensor is 69500 or 1.4 million? 

### ISSUE THREAD

**Issue by chucktang98** [nutonomy/nuscenes-devkit#820]
The nuScenes paper reports that the HDLE-32 LiDAR sensor emits up to 1.4 million points per second, 70000 points per scan, and has a range of up to 70 meters. 
![image](https://user-images.githubusercontent.com/88674452/189728009-48644bee-9bc9-4555-8f0d-c6e0f9b6dbd0.png)

However, in practice we see around 650,000 points per second, 34,500 points per LiDAR scan, with a range of 100 meters maximum xyz-distance in the real data. 
![image](https://user-images.githubusercontent.com/88674452/189747516-6b6b5cbb-6cc0-4461-a80f-b6994dc38134.png)

I'm curious which LiDAR sensor spec was actually used? If we are trying to recreate the nuScenes lidar sensor in simulation, how many points should we simulate per second, 34500 * 20 = 69500 or the nuScenes paper's reported value of 1.4 million points per second? 

https://www.mapix.com/wp-content/uploads/2018/07/97-0038_Rev-M_-HDL-32E_Datasheet_Web.pdf Here is the LiDAR spec that I found for the HDL-32E sensor which has sensor specs for both 1.4 million points per second and 695000 points per second.

**Comment by whyekit-motional** [comment]
@chucktang98 you could get the specs of the lidar used in nuScenes directly from https://www.nuscenes.org/nuscenes#data-collection

As for the number of points per second you should use in your simulation: the Velodyne HDL32E emits `up to ~1.39 Million Points per Second`, so 69,500 points per second is still within that stated range
