### ISSUE TITLE
AssertionError: Samples in split don't match samples in predicted tracks.

### ISSUE THREAD

**Issue by ParkJunYeop** [nutonomy/nuscenes-devkit#823]
I'm having the following error:
AssertionError: Samples in split don't match samples in predicted tracks.

Can anyone please explain why this happens?
What's samples in split?

**Comment by whyekit-motional** [comment]
@ParkJunYeop for evaluation, the scenes are split into "buckets" (e.g. `train`, `val`, `test`, etc.) - pls see [here](https://github.com/nutonomy/nuscenes-devkit/issues/698#issuecomment-999959657) for details on how to get the scenes which belong to each split. Each scene is made up of samples, so the samples in a given split are essentially the samples which belong to the scenes in that split.

If the sample tokens you provide for evaluation are not from the correct split, the assertion which you showed above will be triggered: https://github.com/nutonomy/nuscenes-devkit/blob/28765b8477dbd3331bacd922fada867c2c4db1d7/python-sdk/nuscenes/eval/tracking/evaluate.py#L87-L88

**Comment by ParkJunYeop** [comment]
I understood what split means from your comment. Thanks!
But then what should I do to run my evaluation code?
I'm actually using only validation file for evaluation.

Should I change the default value trainval?

parser.add_argument('--version', type=str, default='v1.0-trainval',
                        help='Which version of the nuScenes dataset to evaluate on, e.g. v1.0-trainval.')


`if __name__ == "__main__":

    # Settings.
    parser = argparse.ArgumentParser(description='Evaluate nuScenes tracking results.',
                                     formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('--result_path', type=str, default = '/home/yeop/Nuscene1/data/sets/nuscenes/json_save/UKF_lidar_please.json', help='The submission as a JSON file.')  ##이거
    parser.add_argument('--output_dir', type=str, default='~/nuscenes-metrics',
                        help='Folder to store result metrics, graphs and example visualizations.')
    parser.add_argument('--eval_set', type=str, default='val',
                        help='Which dataset split to evaluate on, train, val or test.')
    parser.add_argument('--dataroot', type=str, default= '/home/yeop/Nuscene1/data/sets/nuscenes',   ##이거
                        help='Default nuScenes data directory.')
    parser.add_argument('--version', type=str, default='v1.0-trainval',
                        help='Which version of the nuScenes dataset to evaluate on, e.g. v1.0-trainval.')
    parser.add_argument('--config_path', type=str, default='',
                        help='Path to the configuration file.'
                             'If no path given, the NIPS 2019 configuration will be used.')
    parser.add_argument('--render_curves', type=int, default=1,
                        help='Whether to render statistic curves to disk.')
    parser.add_argument('--verbose', type=int, default=1,
                        help='Whether to print to stdout.')
    parser.add_argument('--render_classes', type=str, default='', nargs='+',
                        help='For which classes we render tracking results to disk.')
    args = parser.parse_args()

    result_path_ = os.path.expanduser(args.result_path)
    output_dir_ = os.path.expanduser(args.output_dir)
    eval_set_ = args.eval_set
    dataroot_ = args.dataroot
    version_ = args.version
    config_path = args.config_path
    render_curves_ = bool(args.render_curves)
    verbose_ = bool(args.verbose)
    render_classes_ = args.render_classes

    if config_path == '':
        cfg_ = config_factory('tracking_nips_2019')
    else:
        with open(config_path, 'r') as _f:
            cfg_ = TrackingConfig.deserialize(json.load(_f))

    nusc_eval = TrackingEval(config=cfg_, result_path=result_path_, eval_set=eval_set_, output_dir=output_dir_,
                             nusc_version=version_, nusc_dataroot=dataroot_, verbose=verbose_,
                             render_classes=render_classes_)
    nusc_eval.main(render_curves=render_curves_)
`

which one should I fix to run my code?

**Comment by whyekit-motional** [comment]
@ParkJunYeop pls try:
```
...
--version v1.0-trainval
--eval_set val
...
```

**Comment by ParkJunYeop** [comment]
`parser.add_argument('--version', type=str, default='v1.0-trainval',
                    help='Which version of the nuScenes dataset to evaluate on, e.g. v1.0-trainval.')
parser.add_argument('--eval_set', type=str, default='val',
                    help='Which dataset split to evaluate on, train, val or test.')`

I tried but it doesn't work... I get the same error

**Comment by whyekit-motional** [comment]
@ParkJunYeop try printing the first, say, 10 sample tokens from your **inferences** (not ground truth) - I can help you to take a look

**Comment by ParkJunYeop** [comment]
I have the following first 10 sample tokens below:
000681a060c04755a1537cf83b53ba57, 00185acff6094c4da3858d78bf462b94, 005d3e821c4e4e0ab03f1ea1dcbf9cc8, 006cbdb235c64999b6f5cfbb63ec88c4, 007c057cac8b490fa8b67e72e630b18a, 00a9b6fdf99143c4aabaaca13004c2be, 
00bb84f140c943059a9a1e8e372ddabe, 00fa4bf2e838438dbf9902b201a26b59, 0102262f8ef34b89a1bc8390629c9390,
0106a9b8e65f4ad1867b44591aeed8b0

**Comment by whyekit-motional** [comment]
@ParkJunYeop as part of debugging, I would suggest to add the following to the top of `nuscenes-devkit/python-sdk/nuscenes/eval/common/loaders.py`:
```
from nuscenes.utils.splits import create_splits_scenes


splits = create_splits_scenes()
val_split = splits['val']

nusc = NuScenes(version='v1.0-trainval', dataroot='/data/sets/nuscenes', verbose=False)
```

And then add the following to [this loop](https://github.com/nutonomy/nuscenes-devkit/blob/28765b8477dbd3331bacd922fada867c2c4db1d7/python-sdk/nuscenes/eval/common/loaders.py#L46):
```
for sample_token in all_results.sample_tokens:
    sample_record = nusc.get('sample', sample_token)
    scene_record = nusc.get('scene', sample_record['scene_token'])
    assert scene_record['name'] in val_split, f'sample_token {sample_token} not in val split.'
```
