### ISSUE TITLE
About rotation matrix of ego pose

### ISSUE THREAD

**Issue by wxiangxiaow** [nutonomy/nuscenes-devkit#824]
Hi :) Thanks for your all great job!

I want to ask why the "rotation" matrix in ego_post.json file is not orthogonal? Or it should not be an orthogonal matrix?

**Comment by whyekit-motional** [comment]
@wxiangxiaow the `rotation` entry in `ego_pose` is a quaternion vector (see [here](https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/schema_nuscenes.md#ego_pose) for details), not a matrix

```
from pyquaternion import Quaternion

from nuscenes.nuscenes import NuScenes


nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=False)

ego_pose_record = nusc.ego_pose[0]

ego_pose_rotation = Quaternion(ego_pose_record['rotation'])
ego_pose_rotation_inverse = ego_pose_rotation.inverse

print(ego_pose_rotation)
print(ego_pose_rotation_inverse)
```
