### ISSUE TITLE
Associate non-keyframe camera and lidar

### ISSUE THREAD

**Issue by DianCh** [nutonomy/nuscenes-devkit#826]
Hi! Since the frequency of Lidar (20hz) is higher than the cameras (12hz), is it possible to find a well-aligned lidar sweep (which is likely to be non-keyframe as well) for a non-keyframe camera image, such that the lidar points can be projected and used as depth?

Thank you!

**Comment by whyekit-motional** [comment]
@DianCh you could possibly iterate through the non-keyframe camera images and non-keyframe lidar sweeps to find pairs which have close enough timestamps that are close to each other. However, I do not think they will be as close as that of the keyframes
