### ISSUE TITLE
No reaction of Asia or US download button

### ISSUE THREAD

**Issue by Zhimin-C** [nutonomy/nuscenes-devkit#828]
I had registered nuscenes account before and downloaded the dataset many times successfully. However, when I try to download the data today, there is no reaction when I click the asia or us button. I  used a new browser, utilized another computer, and even registered a new account but all failed. May you tell me how to solve this problem. Thanks!

**Comment by Heart-eartH** [comment]
+1, I have the same question...

**Comment by sunnyHelen** [comment]
I also got the same error... 
Please help us to figure it out.
Thanks a lot.

**Comment by AICVlearner** [comment]
I also got the same error
Please advise
Thanks

**Comment by sunnyHelen** [comment]
Or can you give us the Linux wget command for nuImages dataset, Plz?

**Comment by whyekit-motional** [comment]
Hi all, pls be patient while we investigate this issue

**Comment by whyekit-motional** [comment]
@Zhimin-C @Heart-eartH @sunnyHelen @AICVlearner the issue should have been fixed now - pls give the download another try

**Comment by sabir-1010** [comment]
The same thing happened. Have anyone solved this problem?

Only can download the "Full dataset (v1.0)". However, I can not download "nuPlan v1.1 Dataset" and "nuPlan v1.0 Dataset". After clicking US or ASIA, it is not downloading anything.

**Comment by whyekit-motional** [comment]
@sabir-1010 for issues pertaining to nuPlan, pls post them here: https://github.com/motional/nuplan-devkit/issues
