### ISSUE TITLE
Evaluation result with respect to each scene

### ISSUE THREAD

**Issue by ParkJunYeop** [nutonomy/nuscenes-devkit#829]
Hi I have some issues about evaluating results.

I actually already used evaluation.py file using my tracking result json file. But Is there any ways that I can see results with respect to each scene?

**Comment by whyekit-motional** [comment]
@ParkJunYeop one possible way to do that would be to modify these lines of code to load the annotations and predictions only for a given scene: https://github.com/nutonomy/nuscenes-devkit/blob/28765b8477dbd3331bacd922fada867c2c4db1d7/python-sdk/nuscenes/eval/tracking/evaluate.py#L83-L85
