### ISSUE TITLE
how object without lidar or radar points annotated?

### ISSUE THREAD

**Issue by codeman-24** [nutonomy/nuscenes-devkit#831]
![image](https://user-images.githubusercontent.com/25739094/197140620-3705edd5-bd13-4441-b1a6-c1bfa34bd35e.png)
https://github.com/open-mmlab/mmdetection3d/blob/14c5ded49dd5df7a52368bd54c32a003c2521e1d/tools/data_converter/nuscenes_converter.py#L237
I find here exist annotations for object without lidar or radar points，how these annotations captured? Thank you !

**Comment by polars05** [comment]
@codeman-24 these annotations were likely interpolated (do see https://github.com/nutonomy/nuscenes-devkit/issues/808#issuecomment-1212690618 for more details)
