### ISSUE TITLE
Test split not available in get_prediction_challenge_split

### ISSUE THREAD

**Issue by tedhuang96** [nutonomy/nuscenes-devkit#832]
I checked out [prediction tutorial](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/tutorials/prediction_tutorial.ipynb), and tried to run
`nuscenes = NuScenes('v1.0-test', dataroot=DATAROOT)`
`get_prediction_challenge_split("test", dataroot=DATAROOT)`
and got error. I saw `create_splits_scenes()` used in `get_prediction_challenge_split` can return test split, but when I tried to modify `get_prediction_challenge_split` to accept `split` as `'test'`, the output `list(chain.from_iterable(token_list_for_scenes))` is an empty list. 

I assume we should train on 'v1.0-trainval' and then evaluate on 'v1.0-test'. I did not see anywhere teaching how to load test data from 'v1.0-test' in order to load input and generate submissions for the prediction challenge.

**Comment by polars05** [comment]
@tedhuang96 do check out this related comment: https://github.com/nutonomy/nuscenes-devkit/issues/833#issuecomment-1289084178

**Comment by tedhuang96** [comment]
Thanks!
