### ISSUE TITLE
Bad weather images of nuimages

### ISSUE THREAD

**Issue by DanHalp** [nutonomy/nuscenes-devkit#834]
Hey there!
We're working on a project at the Technical University of Munich that involves segmentation of driving scenarios images and trying to deal with the problem of bad weather conditions.

Is there any way to select the rainy / snowy images from the nuImages dataset?

Thanks!

**Comment by whyekit-motional** [comment]
@DanHalp  nuImages does not have such tags, but nuScenes has scene descriptions which mention if a scene is rainy / snowy
