### ISSUE TITLE
No such file or directory: 'nuScenes/nuscenes-devkit/data/sets/nuscenes/nuScenes-panoptic-v1.0-all/v1.0-trainval/attribute.json

### ISSUE THREAD

**Issue by dt-boringtao** [nutonomy/nuscenes-devkit#835]
Hi, 

I wanted to load the v1.0 trainval for evaluation, but cannot find attribute.json file. I checked the folder and can only find category.json and panoptic.json. 

Can you help? thanks!

Tao

**Comment by whyekit-motional** [comment]
@dt-boringtao to use Panoptic nuScenes, you would need to download the data from both `nuScenes-panoptic` and `Full dataset (v1.0)`: 

![image](https://user-images.githubusercontent.com/62535720/199478278-2607ca7c-f77c-41be-9069-ec5274e520f1.png)
![image](https://user-images.githubusercontent.com/62535720/199478165-1cb23709-4353-4ce6-92aa-0cd886868d8e.png)
