### ISSUE TITLE
How to visualize json file tracking result for validation set?

### ISSUE THREAD

**Issue by ParkJunYeop** [nutonomy/nuscenes-devkit#836]
Hi, I recently successfully made tracking result to run the evaluation code.(which is validation set)

I actually want to visualize in a specific time as an image file.(camera)
How can I visualize the result as an image file for both data which is my tracking result(json file) and the data provided?

I'd be grateful if you reply.
Thanks.

**Comment by whyekit-motional** [comment]
@ParkJunYeop you can try the `TrackingRenderer` provided in the devkit: https://github.com/nutonomy/nuscenes-devkit/blob/28765b8477dbd3331bacd922fada867c2c4db1d7/python-sdk/nuscenes/eval/tracking/render.py#L109-L112
