### ISSUE TITLE
ModuleNotFoundError: No module named 'nuscenes.map_expansion.bitmap'

### ISSUE THREAD

**Issue by dt-boringtao** [nutonomy/nuscenes-devkit#837]
hi

other modules can be found. just not bitmap. 

can you help? thanks!

Tao

**Comment by dt-boringtao** [comment]
I installed nuscense-devkit via pip install

**Comment by whyekit-motional** [comment]
@dt-boringtao I can't seem to reproduce your error on my end. I would suggest creating a fresh virtual environment and try installing `nuscenes-devkit` again
