### ISSUE TITLE
nuScenes lane connector center line?

### ISSUE THREAD

**Issue by szu3sgh** [nutonomy/nuscenes-devkit#839]
Hello, we are currently working on motion prediction problems using nuScenes dataset.

We are interested in the nuScenes dataset because it has rich semantic information of the environment in its map expansion with 11 layers of non-geometric diving data. One thing we are currently looking into is the lane data of the map, especially the lane connectivity. What we found is that nuScenes has the concept of “lane_connector”, which is used to connect lanes in special road areas like intersections. However, this lane_connector has rather less semantic information, and current map_api in nuscenes dev-kit does not have a good support for visualizing the lane_connector.

We made some changes in the map api to visualize the polygon associated with the lane_connector. It seems to us that the shape of the lane connector is rather like a patch box, not a road element. 

So we have three questions as shown below.
1. Do you have an idea that how the lane_connector is generated ?
2. How to generate the center lines of lane_connector as normal lane? (For normal lane, it has get_arcline_path function to get centerlines or baseline paths)
3. Can lane_connector represents turning information, we notice that in the intersection area, one lane can have two lane connectors (Does this mean that these two lane connectors are representing two different turning directions?)

Great Thanks

**Comment by Qiang-Xu** [comment]
@whyekit-motional do you have the answers?

**Comment by whyekit-motional** [comment]
@Qiang-Xu @szu3sgh I'm still checking on these, as these are quite legacy

**Comment by whyekit-motional** [comment]
@szu3sgh 

1. The lane connectors are generally manually annotated
2. Unfortunately, there isn't an easy way to go from a `lane_connector` record to a `lane` record, since a `lane_connector` does not necessarily have a one-to-one correspondence with lanes
3. If you could share an example of a lane having two lane connectors as a reference, that would be great
