### ISSUE TITLE
Regarding meta files, camera image not found at {}.format(cam_path) error!

### ISSUE THREAD

**Issue by Soodep** [nutonomy/nuscenes-devkit#840]
Hi. See also https://forum.nuscenes.org/t/problem-with-conversion-from-nuscenes-into-kitti/548. 
In general the code was not designed to work with the different splits *separately*. They are supposed to all be merged into one folder and likewise there is only one annotation (v1.0-trainval) for all of them. Hence you would need to adjust the code to only operate on the images you are interested in.

_Originally posted by @holger-motional in https://github.com/nutonomy/nuscenes-devkit/issues/583#issuecomment-820201814_
      For e.g in Full dataset (v1.0) : Trainval, if I want to use only the part 1 file blobs of 85 scenes, what changes do I have to make so I dont get this error and where should those changes be? I am trying my best to figure it out, I would really appreciate if anyone could guide me through the process.

**Comment by whyekit-motional** [comment]
@Soodep for a start, I would suggest to try instantiating `NuScenes` with those 85 scenes and see what errors come up. Do feel free to post (to this thread) the ones that you can't resolve for discussion.
