### ISSUE TITLE
Greetings, where can I find the relative pose between the IMU sensor and the Ego Reference Frame?

### ISSUE THREAD

**Issue by pragyandahal** [nutonomy/nuscenes-devkit#841]

**Comment by whyekit-motional** [comment]
@pragyandahal the IMU sensor is actually located (roughly) at the center of the rear axle of the ego, which is equivalent to the ego origin (see https://github.com/nutonomy/nuscenes-devkit/issues/56#issuecomment-558555994 for more details)

**Comment by AitorIglesias** [comment]
@whyekit-motional What you just said and what I see in the dataset makes me think that the IMU is underneath the ego-vehicle. I mean, you say the vehicle pose is aligned with the IMU. But in calibrated_sensor.json I see that the Lidar (which is on top of the vehicle) is approximately 1.8 meters away from the vehicle position in the z-axis. 

This means that either the Lidar position is with respect to the vehicle and not with respect to the IMU or that the IMU is on the underside of the vehicle.

If it is the first option I would like to know if there is any way to know the actual position of the IMU with respect to the ego-vehicle. I am not an expert but I think the IMU should be on the top of the vehicle.
