### ISSUE TITLE
Transform global coordinate of map to world coordinate

### ISSUE THREAD

**Issue by moon5ye** [nutonomy/nuscenes-devkit#842]
Hi,

Thanks for the great dataset.

It seems the global coordinate corresponds to the each map, like 0,0,0 is the top left of the map.

So, I am wondering how to transform the global coordinate (x, y, z) to the world coordinate, like longitude and latitude.

Also, the z value of the map is 0, I think we will never get the height/altitude info, right?

**Comment by whyekit-motional** [comment]
@moon5ye do take a look at https://github.com/nutonomy/nuscenes-devkit/issues/144#issuecomment-505377023 for the origins of the various maps in latlon

**Comment by moon5ye** [comment]
Thank you so much!
