### ISSUE TITLE
Ego Vehicle Lateral Velocity always zero.

### ISSUE THREAD

**Issue by pragyandahal** [nutonomy/nuscenes-devkit#844]
Greetings, The lateral velocity of the ego vehicle is always given as zero, even when we have significant lateral acceleration as shown by the IMU and in the pose messages. Is this an error or I am missing something here?   Thanks in advance.

**Comment by whyekit-motional** [comment]
@pragyandahal based on the graphs you have shown above, "Pose velocity Vy" (from the graph in the top-left corner) does not seem to be zero

Also, do share a code snippet, if you would like more help on checking it

**Comment by pragyandahal** [comment]
Greetings, @whyekit-motional . Thank you for your answer. Sorry but the vy component always seems zero. Here, I attach an image for the scene 900 and the code snippet used to generate the image. 
![Screenshot from 2022-12-01 15-34-51](https://user-images.githubusercontent.com/48767163/205081127-208788b7-329c-419e-9784-efcdfda6162b.png)
![Screenshot from 2022-12-01 15-38-04](https://user-images.githubusercontent.com/48767163/205081133-2306fc6a-d3f0-40ac-80cd-28138c87a9b5.png)
![Screenshot from 2022-12-01 15-39-05](https://user-images.githubusercontent.com/48767163/205081135-af4aef77-0d0d-47f0-8f37-d86ae222ee19.png)

**Comment by pragyandahal** [comment]
Furthermore, is it possible to get the vehicle parameters such as Cornerning Stiffness, Vehicle Moment of Inertia etc?

**Comment by whyekit-motional** [comment]
@pragyandahal 
- It does seem like the lateral velocity is always zero. Interestingly, the velocity is given in the ego frame according to the [README](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/can_bus/README.md#pose). Perhaps you could estimate the lateral velocity (in the global frame) by numerical differentiation using the `pos` and timestamp.
- The [Renault Zoe](https://en.wikipedia.org/wiki/Renault_Zoe) was used for data collection in nuScenes. For such mechanical specifics, I think you will have to reach out to the vehicle manufacturer itself.

**Comment by pragyandahal** [comment]
Greetings @whyekit-motional, could it possibly be that the IMU is not correctly aligned with the Ego Reference Frame?

**Comment by whyekit-motional** [comment]
@pragyandahal the origin of the ego reference frame should be roughly where the IMU is: https://github.com/nutonomy/nuscenes-devkit/issues/841#issuecomment-1318085618
