### ISSUE TITLE
creating a Box object raises an error

### ISSUE THREAD

**Issue by breadbread1984** [nutonomy/nuscenes-devkit#847]
create a Box object results in an error occurring at the following line

https://github.com/nutonomy/nuscenes-devkit/blob/28765b8477dbd3331bacd922fada867c2c4db1d7/python-sdk/nuscenes/utils/data_classes.py#L553

the score is a vector, np.isnan(score) returns a vector. condition on a vector of bools is invalid.

**Comment by whyekit-motional** [comment]
@breadbread1984 `score` is a single value, not a vector - you can see the typing for `score` here: https://github.com/nutonomy/nuscenes-devkit/blob/28765b8477dbd3331bacd922fada867c2c4db1d7/python-sdk/nuscenes/utils/data_classes.py#L529
