### ISSUE TITLE
Submit to nuScenes

### ISSUE THREAD

**Issue by Townjj** [nutonomy/nuscenes-devkit#848]
Hello, thanks to your excellent work.
I can't find the entrance of submit about test set (3D Object Detection) in the nuScenes websit. Can you tell me how to submit to the nuScenes or the detailed entrance link?
Thanks.

**Comment by whyekit-motional** [comment]
@Townjj the details of how to participate in the nuScenes detection challenge can be found at https://github.com/nutonomy/nuscenes-devkit/tree/master/python-sdk/nuscenes/eval/detection#participation
