### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './v1.0-mini/attribute.json'

### ISSUE THREAD

**Issue by zyx5256** [nutonomy/nuscenes-devkit#849]
Download link: https://www.nuscenes.org/download, nuScenes-lidarseg, All, Asia

Error accurred when running the first block in the tutorial: [nuscenes-devkit](https://github.com/nutonomy/nuscenes-devkit)/[python-sdk](https://github.com/nutonomy/nuscenes-devkit/tree/master/python-sdk)/[tutorials](https://github.com/nutonomy/nuscenes-devkit/tree/master/python-sdk/tutorials)/nuscenes_lidarseg_panoptic_tutorial.ipynb:

```
nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=True)
```

says

```
FileNotFoundError: [Errno 2] No such file or directory: './v1.0-mini/attribute.json'
```

**Comment by whyekit-motional** [comment]
@zyx5256 in order to use Panoptic nuScenes (which includes lidarseg), you also need to download the nuScenes dataset
