### ISSUE TITLE
A question about keyframes when downloading

### ISSUE THREAD

**Issue by ZhouZijie-BIT** [nutonomy/nuscenes-devkit#851]
Hi, thanks to your excellent work.
I'm trying to fusion the data of lidar and cameras. Can I just download the keyframes? Do I need to download the full dataset?
![屏幕截图 2022-12-20 171613](https://user-images.githubusercontent.com/73010947/208629661-183c1315-bd2e-4ce8-aa5f-17929b2fe985.jpg)

**Comment by whyekit-motional** [comment]
@ZhouZijie-BIT if you are only looking to perform fusion for the keyframes, then you don't need to download the full dataset

However, if you require other non-keyframe data during fusion (e.g. accumulating sweeps), then you would likely need the full dataset

**Comment by ZhouZijie-BIT** [comment]
Thank you！
