### ISSUE TITLE
convert box in global frame into ego frame

### ISSUE THREAD

**Issue by zjr-bit** [nutonomy/nuscenes-devkit#853]
Hi, thanks for your great work！
I'm trying to convert box in global frame into ego frame by the below code

```
box = Box(center=[1.0, 1.0, 1.0], size=[2.0, 1.0, 0.5], 
           orientation=Quaternion([0.7155792275171129, 0.0, 0.0, 0.6985315806361313]))
ego_pose = {'token': '0a369944x909o86mz552b76y1xk2736f', 
                     'timestamp': 6, 'rotation': [3.9947416358725856e-07, 0.0, 0.0, 0.9999999999999202], 
                     'translation': [-11.506108283996582, 125.10550689697266, 0.1524023413658142]}
# first translate the center of box
box.translate(-np.array(ego_pose['translation']))
# second rotate the box
rotation_matrix = Quaternion(ego_pose['rotation']).rotation_matrix.T
box.center = np.dot(rotation_matrix, box.center)
w, x, y, z = ego_pose['rotation']
box.orientation = Quaternion([w, -x, -y, -z]) * box.orientation
```

Could you please tell me does it work? I am confused by the transformation of box between different frames. Maybe it needs to get the corner of box according to the (x, y, z, w, l, h) and then translate and rotate the corners?
Looking forward to your reply, thank you!

**Comment by whyekit-motional** [comment]
@zjr-bit for conversion of a box from global frame into the ego frame, you could refer to: https://github.com/nutonomy/nuscenes-devkit/blob/d9c36a603898965fc2c8111f4bdf4ed1f8f10aa7/python-sdk/nuscenes/nuscenes.py#L294-L296
