### ISSUE TITLE
Wrong lane label in map visualization

### ISSUE THREAD

**Issue by mxcheeto** [nutonomy/nuscenes-devkit#855]
![CAM_BACK](https://user-images.githubusercontent.com/40545261/209671123-4cd4dc29-3694-4a60-b9ac-5f59d513f167.png)
![MAP](https://user-images.githubusercontent.com/40545261/209671106-277f801e-2c2e-467a-87c4-a75967da9e1a.png)
In this map visulazation case, the arrows are depicted from the map via projection. What may cause the lane to be incomplete (the middle lane), and to be rebundant ( the lane near the right contour)?

**Comment by whyekit-motional** [comment]
@mxcheeto perhaps you could share the relevant lane IDs for reproducibility

**Comment by mxcheeto** [comment]
I'm afraid I cannot provide lane IDs so far, but the filename of this group of images is `n008-2018-08-01-15-52-19-0400_1533153678898290`, if this is helpful. I'll try find out lane ID later.
