### ISSUE TITLE
How is the lidar basemap computed

### ISSUE THREAD

**Issue by lasnik** [nutonomy/nuscenes-devkit#856]
Hi,

thanks for releasing this great dataset and the accompanying benchmarks, they have had significant impact on the community.

I am interested in using the 'basemap' as an additional feature in a static/map feature grid as input to my model. Qualitatively it looks useful for the task I am investigating, but I could not find a lot of information on how it was computed. Is it lidar scans of multiple drives projected to the ground plane and stripped of dynamic objects?

Some more detail would be greatly appreciated!

Thanks and all the best,
Nik

**Comment by whyekit-motional** [comment]
@lasnik yes, what you mentioned is the general idea behind how the basemap was constructed

**Comment by weimengchuan** [comment]
Hi. Could you please share the details of basemap construction?
In addition, Is the coordinate system of basemap global coord?

**Comment by whyekit-motional** [comment]
@weimengchuan the basemap is constructed using a proprietary graph-SLAM engine

And yes, the coordinate system of the basemap is the global frame

**Comment by whyekit-motional** [comment]
@weimengchuan the map annotations and basemap may not match exactly due to the reason given in #678:

> we combined multiple map versions with very small non-linear deformations between them.

**Comment by weimengchuan** [comment]
> @weimengchuan the map annotations and basemap may not match exactly due to the reason given in #678:
> 
> > we combined multiple map versions with very small non-linear deformations between them.

I wonder what do you label the map gt based on, semantic_prior or something unreleased?
I believe that it is supposed to be aligned very well with gt.
Thanks!

**Comment by whyekit-motional** [comment]
I believe the map labeling was done on something unreleased
