### ISSUE TITLE
about the map

### ISSUE THREAD

**Issue by Heart-eartH** [nutonomy/nuscenes-devkit#857]
Hello,
Thanks for the nice work! I a new user of nuscenes and have some questions. I'm not sure if my understanding is correct.

I know that we can get the map of sample data by the nuscenes api 'get_map_mask', I wonder if we can get the map of sweep data in a similar way. It seems that some parameters are missing for using 'get_map_mask' on sweep data, e.g.  ‘lidar2ego_translation’.

Thanks again for the help!

**Comment by whyekit-motional** [comment]
@Heart-eartH the `get_map_mask` method is independent of whether the data is of a sample or of a sweep: https://github.com/nutonomy/nuscenes-devkit/blob/d9c36a603898965fc2c8111f4bdf4ed1f8f10aa7/python-sdk/nuscenes/map_expansion/map_api.py#L825-L829

So you should be able to get the map mask for sweep data, I think
