### ISSUE TITLE
How to train the model using a smaller dataset?

### ISSUE THREAD

**Issue by Yiir-1** [nutonomy/nuscenes-devkit#858]
Hi! I am a undergraduate student and first exposure to autonomous driving. I am trying to get bev feature from this dataset, but I don't  have too much gpu ,so it is difficult for me to use the whole v1.0 dataset,but mini is too small to the model , do you have the method to transform the nuscenes whole dataset (v1.0) to a smaller one? Thank you very much!

**Comment by whyekit-motional** [comment]
@Yiir-1 welcome to the world of autonomous driving! While your question is outside the scope of the devkit, I'll try my best at answering it.

There are some possibilities to "transform the nuscenes whole dataset ... to a smaller one":
- Use a smaller portion of the dataset for training
- If you are only using image data, you could use images of a lower resolution
- Slice up the data (i.e. use only certain parts of the images / point clouds)

There are probably more ways, but this is what I can think of so far - feel free to share, if you do think up more
