### ISSUE TITLE
What is the height of the LiDAR relative to the ground and the height of the LiDAR itself?

### ISSUE THREAD

**Issue by Ryyyc** [nutonomy/nuscenes-devkit#859]
Thank you for your excellent work!

I am now interested in the following information.
1. What is the height of the LiDAR relative to the ground?
2. How is the height of the LiDAR relative to the ground calculated? i.e., is it the distance from the ground to the bottom or top of the LiDAR?
3. What is the height of the LiDAR itself?

I have checked the previous related issues and according to [issues/618#issuecomment-874388148](https://github.com/nutonomy/nuscenes-devkit/issues/618#issuecomment-874388148), I got the coordinates of the LiDAR relative to the rear axle (`'translation ': [0.943713, 0.0, 1.84023]`). According to [issues/161#issuecomment-507984392](https://github.com/nutonomy/nuscenes-devkit/issues/161#issuecomment-507984392), the height of the rear axle is about 12 cm. However, according to [issues/161#issuecomment-508015958](https://github.com/nutonomy/nuscenes-devkit/issues/161#issuecomment-508015958), the height of the LiDAR should be `The "ego vehicle body frame" refers to the center of the rear axle projected onto the ground`.
So I am not sure if the height of the LiDAR relative to the ground is `1.84023` or `1.84023+0.12=1.96023`

Thanks for your replies!

**Comment by whyekit-motional** [comment]
@Ryyyc for the `calibrated_sensor` data, `All extrinsic parameters are given with respect to the ego vehicle body frame` (ref. [here](https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/schema_nuscenes.md#calibrated_sensor)), which implies that the lidar is `1.84023` meters above the ground in your example above

**Comment by Ryyyc** [comment]
@whyekit-motional  Thank you for your reply.
