### ISSUE TITLE
Lidar and camera correspondence in export_pointclouds_as_obj.py

### ISSUE THREAD

**Issue by skmadan** [nutonomy/nuscenes-devkit#860]
In the function export_scene_pointcloud in the script export_pointclouds_as_obj.py I was wondering why the lidar point cloud at a particular sample gets the intensities from the images at the next sample and not the same sample? Am I reading the code incorrectly? I did not see the timepoint deltas to be closer between lidar and camera when picking camera samples from the next timepoint instead of the same.

1. Lidar point cloud:https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_pointclouds_as_obj.py#L70-L72
2. Camera samples: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_pointclouds_as_obj.py#L68-L69
3. "sd_token" in "sd_tokens" is one sample ahead: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_pointclouds_as_obj.py#L58

**Comment by whyekit-motional** [comment]
@skmadan [L58](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_pointclouds_as_obj.py#L58) is part of a loop which accumulates all the sample data tokens, like so:
```python
while cur_sd_rec['next'] != '':
    cur_sd_rec = nusc.get('sample_data', cur_sd_rec['next'])
    sd_tokens.append(cur_sd_rec['token'])
```
Whereas [L68-72](https://github.com/nutonomy/nuscenes-devkit/blob/d9c36a603898965fc2c8111f4bdf4ed1f8f10aa7/python-sdk/nuscenes/scripts/export_pointclouds_as_obj.py#L68-L72) is part of another loop which gets the lidar and image data from those accumulated sample data tokens:
```python
with open(out_path, 'w') as f:
    ...

    for sd_token in tqdm(sd_tokens):
        sc_rec = nusc.get('sample_data', sd_token)
        sample_rec = nusc.get('sample', sc_rec['sample_token'])
        lidar_token = sd_rec['token']
        lidar_rec = nusc.get('sample_data', lidar_token)
        pc = LidarPointCloud.from_file(osp.join(nusc.dataroot, lidar_rec['filename']))
```
Thus, the lidar and image data come from the sample

**Comment by skmadan** [comment]
@whyekit-motional  Yes, I understand the logic. However, if you see line 58 (https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_pointclouds_as_obj.py#L58) the code skips the first sample when defining "sd_tokens" by the using "cur_sd_rec['next']" instead of "cur_sd_rec". Skipping of the first sample does not happen for the lidar data.

Possible this a small bug in the tool?
