### ISSUE TITLE
render_pointcloud_in_image() method shows matplotlib error

### ISSUE THREAD

**Issue by erivera1802** [nutonomy/nuscenes-devkit#861]
Hi,
using the tutorial notebook for the devkit, I am having trouble to render the point cloud in an image. The problem arises with the following commands:
    
    my_sample = nusc.sample[0]
    nusc.render_pointcloud_in_image(my_sample['token'], pointsensor_channel='LIDAR_TOP')

And the error is:

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    Cell In[97], line 2
          1 my_sample = nusc.sample[200]
    ----> 2 nusc.render_pointcloud_in_image(my_sample['token'], pointsensor_channel='LIDAR_TOP')
    
    File ~/ki_gpu/lib/python3.8/site-packages/nuscenes/nuscenes.py:524, in NuScenes.render_pointcloud_in_image(self, sample_token, dot_size, pointsensor_channel, camera_channel, out_path, render_intensity, show_lidarseg, filter_lidarseg_labels, show_lidarseg_legend, verbose, lidarseg_preds_bin_path, show_panoptic)
        515 def render_pointcloud_in_image(self, sample_token: str, dot_size: int = 5, pointsensor_channel: str = 'LIDAR_TOP',
        516                                camera_channel: str = 'CAM_FRONT', out_path: str = None,
        517                                render_intensity: bool = False,
       (...)
        522                                lidarseg_preds_bin_path: str = None,
        523                                show_panoptic: bool = False) -> None:
    --> 524     self.explorer.render_pointcloud_in_image(sample_token, dot_size, pointsensor_channel=pointsensor_channel,
        525                                              camera_channel=camera_channel, out_path=out_path,
        526                                              render_intensity=render_intensity,
        527                                              show_lidarseg=show_lidarseg,
        528                                              filter_lidarseg_labels=filter_lidarseg_labels,
        529                                              show_lidarseg_legend=show_lidarseg_legend,
        530                                              verbose=verbose,
        531                                              lidarseg_preds_bin_path=lidarseg_preds_bin_path,
        532                                              show_panoptic=show_panoptic)
    
    File ~/ki_gpu/lib/python3.8/site-packages/nuscenes/nuscenes.py:1028, in NuScenesExplorer.render_pointcloud_in_image(self, sample_token, dot_size, pointsensor_channel, camera_channel, out_path, render_intensity, show_lidarseg, filter_lidarseg_labels, ax, show_lidarseg_legend, verbose, lidarseg_preds_bin_path, show_panoptic)
       1026         fig.canvas.set_window_title(sample_token + '(predictions)')
       1027     else:
    -> 1028         fig.canvas.set_window_title(sample_token)
       1029 else:  # Set title on if rendering as part of render_sample.
       1030     ax.set_title(camera_channel)
    
    AttributeError: 'FigureCanvasAgg' object has no attribute 'set_window_title'

I have the latest matplotlib version (3.6.3), so I don't know what is going on.

Thanks!

**Comment by whyekit-motional** [comment]
@erivera1802 perhaps try version `3.5.2` of matplotlib:
```
$ pip show matplotlib

Name: matplotlib
Version: 3.5.2
...
```

**Comment by pyun-ram** [comment]
It is found that this problem has not been fixed even the matplotlib == 3.5.2.
The problem can be reproduced in the [colab script](https://colab.research.google.com/github/nutonomy/nuscenes-devkit/blob/master/python-sdk/tutorials/nuscenes_tutorial.ipynb#scrollTo=PriS0HkWgOOm&line=2&uniqifier=1):
```python
nusc.render_pointcloud_in_image(my_sample['token'], pointsensor_channel='LIDAR_TOP')
```

**Comment by whyekit-motional** [comment]
@pyun-ram I can't seem to reproduce your error even in Colab:
![image](https://user-images.githubusercontent.com/62535720/227098651-f66ad989-0a43-4880-b980-d0eb14df4df5.png)

I don't see any issues on a local Jupyter notebook either:
![image](https://user-images.githubusercontent.com/62535720/227098884-14292606-d46b-418b-898b-7a687c87712c.png)

You could see if commenting out `%matplotlib inline` helps you

**Comment by pyun-ram** [comment]
Thanks for your prompt reply! 
Here is the minimum code block to reproduce the error:
```python
!mkdir -p /data/sets/nuscenes  # Make the directory to store the nuScenes dataset in.
!wget https://www.nuscenes.org/data/v1.0-mini.tgz  # Download the nuScenes mini split.
!tar -xf v1.0-mini.tgz -C /data/sets/nuscenes  # Uncompress the nuScenes mini split.
!pip install nuscenes-devkit &> /dev/null  # Install nuScenes.
!pip show matplotlib

%matplotlib inline
from nuscenes.nuscenes import NuScenes
nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=True)
my_sample = nusc.sample[10]
nusc.render_pointcloud_in_image(my_sample['token'], pointsensor_channel='LIDAR_TOP')
```
<img width="962" alt="img1" src="https://user-images.githubusercontent.com/43157631/227101172-99c4cfe9-6ad9-4577-af9e-181b30cb1d03.png">
<img width="1332" alt="img2" src="https://user-images.githubusercontent.com/43157631/227101182-d5c1f82c-a36f-4304-a40e-83438efa7d4e.png">

**Comment by TedLentsch** [comment]
I got the same error as @pyun-ram. When I uninstall matplotlib 3.5.2 and install matplotlib 3.5.1, it does work for me. I used the line ``!pip install matplotlib==3.5.1`` for this.

**Comment by s7ev3n** [comment]
Hi,

May I ask why matplotlib version is this old ?  

One dependent package of my project requires matplotlib > 3.7.3, and conflicts with nuscenes-devkit. Is there anyway to upgrade matplotlib version ?

**Comment by whyekit-motional** [comment]
@s7ev3n pls refer to the description in this PR which limited the version of matplotlib: https://github.com/nutonomy/nuscenes-devkit/pull/984

If you really require newer version of matplotlib, you could try - in your local env - running matplotlib > 3.7.3 with `nuscenes-devkit` and see if that gives you any issues

**Comment by fgz-ai** [comment]
For whom uses a newer version of matplotlib, this is a workaround this bug. 

Modify the line 1028 as trigger an exception in the post above as follows. 

old version:
fig.canvas.set_window_title(sample_token)

to new version: 
**fig.canvas.manager.set_window_title(sample_token)**
