### ISSUE TITLE
Ill-formed maps "singapore-queenstown" and "singapore-hollandvillage"

### ISSUE THREAD

**Issue by lam206** [nutonomy/nuscenes-devkit#862]
Dear nuScenes maintainers,

I have analysed the map data and have found several problems I would like to bring your attention to. I have discovered severe issues with "singapore-queenstown" and "singapore-hollandvillage". The other two maps are well-formed and do not have these issues. The following statements apply to the ill-formed maps only:

1) All of the hundreds of road_blocks on each ill-formed map are of the exact same shape (exterior node tokens and holes are identical). The shape is a huge one that goes almost across the entire map. The only difference between each record are the different to_edge_line_tokens and from_edge_line_tokens. In a visualisation of the maps one can also see that the road_segments are off. They are only small little scattered pieces.

2) The nuScenes map expansion tutorial reads "Each pedestrian crossing record has to be on a road segment. It has the road_segment_token field which denotes the road_segment record it is associated with." However, none of the ped_crossings on each ill-formed map have a road_segment_token. It is always the empty string (''). This is in clear contrast to the statement that all ped_crossings have to be on a road_segment. In addition, the same little scatteredness of road_segments means that not even on the visualisation there is a road_segment that can be identified to belong to any given ped_crossing.

3) Road_dividers also do not have the road_segment_token they should have.

Please find proof of problems 1) and 2) in the following notebook: https://github.com/lam206/public_notebooks/blob/main/Road%20blocks%20on%20hollandvillage%20and%20queenstown.ipynb. It includes a rendering of the only real road_block that exists. Again, all other road_blocks have the same shape so there's really only one road_block in the data.

Are you aware of these issues? Are they in the process of being fixed?

**Comment by whyekit-motional** [comment]
@lam206 thanks for bringing these issues up, and providing a notebook with proof of your findings!

We will take a deeper look into these

**Comment by whyekit-motional** [comment]
@lam206 I've investigated the various issues you have mentioned for `singapore-hollandvillage` and `singapore-queenstown` and can confirm them:

1. All the road blocks in the two ill-formed maps are exactly the same:
   ```python
   from nuscenes.map_expansion.map_api import NuScenesMap


   nusc_map = NuScenesMap(
     dataroot='/data/sets/nuscenes', 
     map_name='singapore-hollandvillage', 
   )

   sample_road_block = nusc_map.road_block[133]
   nusc_map.extract_polygon(sample_road_block['polygon_token'])

   print(f'There are {len(sample_road_block["exterior_node_tokens"])} exterior nodes')
   for node_token in sample_road_block['exterior_node_tokens']:
     print(nusc_map.get('node', node_token))
   ```

   ![image](https://user-images.githubusercontent.com/62535720/216287544-c105f686-ff40-476e-b97d-1d8f226e9226.png)
   ```
   There are 7748 exterior nodes
   ```

2. In the ill-formed maps, `ped_crossing`s do not come with a `road_segment_token`
   ```python
   num_ped_crossing_with_no_road_segment_token = 0
   for ped_crossing in nusc_map.ped_crossing:
       if ped_crossing['road_segment_token'] is None:
           num_ped_crossing_with_no_road_segment_token += 1
        
   print(
       f'Out of {len(nusc_map.ped_crossing)} `ped_crossing`s, '
       f'{num_ped_crossing_with_no_road_segment_token} of them have no `road_segment_token`.'
   )
   ```
   ```
   Out of 28 `ped_crossing`s, 28 of them have no `road_segment_token`.
   ```

3. In the ill-formed maps, `road_dividers` do not come with a `road_segment_token`

These are legitimate issues with the map that you have brought up, but unfortunately, the team currently does not have bandwidth to fix these maps. I've tagged your issue with the `map issue` label, and we will give it priority once we get around to fixing these maps.

**Comment by lam206** [comment]
Thank you for confirming the issue, @whyekit-motional.
