### ISSUE TITLE
too many indices for array: array is 0-dimensional, but 2 were indexed

### ISSUE THREAD

**Issue by NoOneUST** [nutonomy/nuscenes-devkit#863]
Hello, I follow the [tutorial](https://www.nuscenes.org/tutorials/map_expansion_tutorial.html) to load the map expansion.

The code I use is:
<img width="882" alt="image" src="https://user-images.githubusercontent.com/48406286/214310840-4c90235e-1a00-45e1-968c-ee3a3531e1b0.png">

Then the error occurs.

Here I provide more details about the processed object:
<img width="899" alt="image" src="https://user-images.githubusercontent.com/48406286/214310278-40a56db5-2bbe-4b2c-ac48-6911554cc356.png">

**Comment by whyekit-motional** [comment]
@NoOneUST your code seems to work for me:
```python
from nuscenes.map_expansion.map_api import NuScenesMap
from nuscenes.map_expansion import arcline_path_utils
from nuscenes.map_expansion.bitmap import BitMap

nusc_map = NuScenesMap(dataroot='/data/sets/nuscenes', map_name='singapore-onenorth')
nusc_map.render_layers(nusc_map.non_geometric_layers, figsize=1)
```
Based on the screenshot you have provided, I see that the error is thrown by the `descartes` library - you could check if your version of `descartes` matches mine:
```
Name: descartes
Version: 1.1.0
Summary: Use geometric objects as matplotlib paths and patches
Home-page: http://bitbucket.org/sgillies/descartes/
Author: Sean Gillies
Author-email: sean.gillies@gmail.com
License: BSD
Location: /home_shared/whyekit/.conda/envs/nuenv/lib/python3.9/site-packages
Requires: matplotlib
Required-by: nuscenes-devkit
```

**Comment by secret104278** [comment]
downgrade shapely works for me
```
pip install shapely==1.8.5
```
