### ISSUE TITLE
Radar PCD files data are unreadble

### ISSUE THREAD

**Issue by boazMgm** [nutonomy/nuscenes-devkit#864]
Hi,
The actual data in the .pcd files of the radars in the data sets is unreadable:
![image](https://user-images.githubusercontent.com/89138398/214783569-a79fbba2-bd0a-49c3-9c15-5d172c35d9de.png)

is that on purpose?

Thanks a lot.

**Comment by whyekit-motional** [comment]
@boazMgm you should be able to read the data in the .pcd files for the radar using the `from_file` method of `RadarPointCloud`: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/data_classes.py#L298
