### ISSUE TITLE
results for different range

### ISSUE THREAD

**Issue by mc171819** [nutonomy/nuscenes-devkit#865]
Hi, I am wondering how to test my model in different range like 0-10m, 10-30m, 30-50m. The overall results is correct but when I modify the point cloud range in my config file, the resuls are almost 0. Do you know where else shoud I modify to get the correct answer?

**Comment by whyekit-motional** [comment]
@mc171819 I believe if you modify the ranges in this config, the evaluation should be ok: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/eval/detection/configs/detection_cvpr_2019.json
