### ISSUE TITLE
leaderboard submission

### ISSUE THREAD

**Issue by mc171819** [nutonomy/nuscenes-devkit#866]
Hi, I have successfully public my results on EvalAI https://eval.ai/web/challenges/challenge-page/356/leaderboard but I still cannot see it on NuScenes official network https://www.nuscenes.org/object-detection?externalData=all&mapData=all&modalities=Any, how can I add my result from EvalAI to NuScenes official network?

**Comment by whyekit-motional** [comment]
@mc171819 pls take a look at the [readme for the nuScenes detection challenge](https://github.com/nutonomy/nuscenes-devkit/tree/master/python-sdk/nuscenes/eval/detection):

> We require that all participants send the following information to [nuScenes@motional.com](mailto:nuScenes@motional.com) after submitting their results on EvalAI
