### ISSUE TITLE
How to eval 2d-detection performance on nuImages test set?

### ISSUE THREAD

**Issue by Forever518** [nutonomy/nuscenes-devkit#867]
Hello, thanks for your contribution to automatic driving dataset!

I have found the entrance of nuScene 3d-detection test on EvalAI, but no nuImages 2d-detection task found yet. Where can I submit my result to test nuImages 2d-detection?

**Comment by whyekit-motional** [comment]
@Forever518 there is currently no official evaluation server for the 2D detection task on nuImages
