### ISSUE TITLE
Shapely>=2.x Incompatibility

### ISSUE THREAD

**Issue by RazvanHas** [nutonomy/nuscenes-devkit#870]
As stated in the [documentation of Shapely](https://shapely.readthedocs.io/en/stable/migration.html), "_Multi-part geometries will no longer be “sequences” (length, iterable, indexable)"_ starting with Version 2.x. This results in incompatibilities and errors when using the [NuScenesMap.get_map_mask](https://github.com/nutonomy/nuscenes-devkit/blob/9cba5925dc51b5c855252ee031eee5d6422f556b/python-sdk/nuscenes/map_expansion/map_api.py#L379) for example.

I suggest two possible solutions:

- either redefine the dependency to Shapely to solve to version 1.8.5 (last version before 2.x)
- modify code to re-establish compatibility with new Shapely by using  _"the `geoms` property to access the constituent parts of a multi-part geometry."_

**Comment by whyekit-motional** [comment]
@RazvanHas `Shapely<=1.8.5` is now specified in `requirements_base.txt`
