### ISSUE TITLE
'FigureCanvasTkAgg' object has no attribute 'set_window_title'

### ISSUE THREAD

**Issue by dandon223** [nutonomy/nuscenes-devkit#872]
Hi, I installed dev-kit with pip.
I get the error 'FigureCanvasTkAgg' object has no attribute 'set_window_title' when I use render_pointcloud_in_image method.
It is because of nuscenes.py file on 1026 and 1028 line:
I changed it to:

            if lidarseg_preds_bin_path:
                fig.canvas.manager.set_window_title(sample_token + '(predictions)')
            else:
                fig.canvas.manager.set_window_title(sample_token)

After the change it works.
Could you update the file?
Thank you

**Comment by whyekit-motional** [comment]
@dandon223 perhaps try version 3.5.2 of matplotlib:
```
$ pip show matplotlib

Name: matplotlib
Version: 3.5.2
...
