### ISSUE TITLE
How to transform one point cloud on the time of t-1 to the point cloud coordinate on the time of t?

### ISSUE THREAD

**Issue by emilyemliyM** [nutonomy/nuscenes-devkit#873]
HI, how to transform one point cloud on the time of t-1 to the point cloud coordinate on the time of t?

**Comment by whyekit-motional** [comment]
@emilyemliyM an example of how to transform a point cloud from some time t<sub>n</sub> to t<sub>0</sub> can be found here: https://github.com/nutonomy/nuscenes-devkit/blob/9cba5925dc51b5c855252ee031eee5d6422f556b/python-sdk/nuscenes/utils/data_classes.py#L115

Modifying it to work for transforming a point cloud from from t<sub>n</sub> to some other time t<sub>m</sub> should be relatively trivial - in particular, you would need to get `ref_from_car` and `car_from_global` from t<sub>m</sub> (rather than t<sub>0</sub>)

**Comment by emilyemliyM** [comment]
> @emilyemliyM an example of how to transform a point cloud from some time tn to t0 can be found here:
> 
> https://github.com/nutonomy/nuscenes-devkit/blob/9cba5925dc51b5c855252ee031eee5d6422f556b/python-sdk/nuscenes/utils/data_classes.py#L115
> 
> Modifying it to work for transforming a point cloud from from tn to some other time tm should be relatively trivial - in particular, you would need to get `ref_from_car` and `car_from_global` from tm (rather than t0)



Hi, really thanks to the reply.

I have another question about the param in the setting:
what's the meaning of the "ref_chan"?  Does it mean "Lidar" string or a token , or anything else?   How to use it?
Could I have an example of the use of the function?

![image](https://user-images.githubusercontent.com/88700988/221399163-10f0f42d-bef4-4aec-bcf8-1d14d3674733.png)

**Comment by whyekit-motional** [comment]
@emilyemliyM the input for `ref_chan` would be the sensor name (as a `str`) you want to map the point clouds to (e.g. `LIDAR_TOP`, `RADAR_FRONT`)

You can see an example usage here: https://github.com/nutonomy/nuscenes-devkit/blob/9bc2f9e74d8a3dd27ef6ce83336508dd8926f867/python-sdk/nuscenes/nuscenes.py#L1293

**Comment by emilyemliyM** [comment]
> @emilyemliyM an example of how to transform a point cloud from some time tn to t0 can be found here:
> 
> https://github.com/nutonomy/nuscenes-devkit/blob/9cba5925dc51b5c855252ee031eee5d6422f556b/python-sdk/nuscenes/utils/data_classes.py#L115
> 
> Modifying it to work for transforming a point cloud from from tn to some other time tm should be relatively trivial - in particular, you would need to get `ref_from_car` and `car_from_global` from tm (rather than t0)

Thanks for the reply!
I want to know that does this method work for two keyframes of point cloud data as well?  I want to conduct the coordinate transform between two key frames.

Thanks !

**Comment by whyekit-motional** [comment]
Yes, it should work for two keyframes, as long as your provide the appropriate transformation matrices

**Comment by emilyemliyM** [comment]
> Yes, it should work for two keyframes, as long as your provide the appropriate transformation matrices

Thanks for the reply, I follow the command, but I got a strange transformation.
Suppose the recieve_field =2 ， so I have 2 key frames.

The code is shown below:

![image](https://user-images.githubusercontent.com/88700988/227476530-89037a5a-6013-4333-b89e-69f53cc8e464.png)

![image](https://user-images.githubusercontent.com/88700988/227476662-fe6e7028-7f07-4908-8882-466a4062e4a3.png)

![image](https://user-images.githubusercontent.com/88700988/227477052-0d52fe4a-d2ac-442b-b167-75e2a12e8d71.png)

I want to transform the past into the recent current frame.

How can I do it ?
