### ISSUE TITLE
Why is a lane defined as a list of List[ArcLinePath]?

### ISSUE THREAD

**Issue by AngelosSE** [nutonomy/nuscenes-devkit#879]
Or equivalently, why can a lane token correspond to multiple curve segments?

Example where a token corresponds to two curve segments:
```
    nusc_map = NuScenesMap(
        dataroot=datasets/nuscenes/v1.0-mini', 
        map_name ='singapore-onenorth',
        )
    lane_token = '0a3f11ca-70af-4ab0-af23-bf61152ab0af'
    lanes = nusc_map.get_arcline_path(lane_token)
    _,ax = plt.subplots()
    colors = ['b','r']
    for lane,color in zip(lanes,colors):
        poses = arcline_path_utils.discretize_lane([lane],resolution_meters=0.1)
        poses = np.array(poses)
        ax.plot(*poses[:,:2].T,color)
        pose = arcline_path_utils.pose_at_length(lane,1e-6)
        ax.plot(*pose[:2],'o'+color) 
```

**Comment by whyekit-motional** [comment]
@AngelosSE I believe it was part of the annotation protocol to use a set of segments (rather than one continuous segment) to describe the lane, e.g. for your example:

![image](https://user-images.githubusercontent.com/62535720/218609647-f58b80ee-4702-431d-bf2f-cd85b7b37db2.png)

**Comment by whyekit-motional** [comment]
@AngelosSE curves can be composed using multiple arcs, where each arc is from a circle of a certain radius R and intersecting angle D. Here's a visualization of a single arc (credits to [here](https://ez-pdh.com/construction-surveying-curves-help/)):

<p align="center"><img src="https://user-images.githubusercontent.com/62535720/218612559-5652b450-f8b1-4114-9fe6-85243e58ce00.png"  width="20%"></p>

Now, you could use different arcs to compose different curves, like so (credits to [here](https://ez-pdh.com/construction-surveying-curves-help/) once again): 

<p align="center"><img src="https://user-images.githubusercontent.com/62535720/218612445-936df936-460f-4f98-90df-a5080d12aab5.png"  width="50%"></p>

Applying this concept to the visualization generated by your code snippet:

<p align="center">
<img src="https://user-images.githubusercontent.com/62535720/218611056-f22fa146-4667-4b2f-911e-c33e4cdf2a9d.png" 
 width="50%">
</p>

You can see that the lane is made of two arcs, where the red one is of radius 13.47 m and the blue one is of radius 10.22 m

**Comment by AngelosSE** [comment]
I understand your explanation, but the curves in my plot do not look like arcs from a circle. For example, if one traverses the red curve starting from the red dot, then tangent is first changing and then it becomes approximately constant. 

Perhaps there is some settings in my plotting. I have tried using `ax.set_aspect('equal')` but I get the same result. 

Is it possible to determine the center point of a circle? Then one can plot also the circles corresponding to the segments.
