### ISSUE TITLE
how should i get the correct yaw value relative to current sensor?

### ISSUE THREAD

**Issue by qianmin** [nutonomy/nuscenes-devkit#882]
Dear officers:
       I want to get the yaw value of the box relative to the current sensor (front camera), but as shown in the figure below, the yaw value of two opposite objects should differ by 180 °, but they only differ by 90 °, which is obviously wrong. So how can I get the yaw value of the 3dbox in the current sensor coordinate system?
my code is:
```
curent_data_token_cam=sample["data"]["CAM_FRONT"]
data_path, src_boxes, camera_in = nu.get_sample_data(curent_data_token_cam)
for box in src_boxes:
    print(box)
```
![R8P0B4X7}89 C47 G_` Q T](https://user-images.githubusercontent.com/28757482/218727021-b38a7a00-55ab-4ee8-bccd-e5220de98958.png)
![5FV5 LW(QEC8XT 9QN_A41T](https://user-images.githubusercontent.com/28757482/218727090-927b1490-ebda-4bb5-a882-064ed8dcb7dc.png)

**Comment by whyekit-motional** [comment]
@qianmin the rotation axis of the two objects you showed above are different (see the `rot axis` entry for each of them), and so you cannot simply compare the `ang(degrees)`

Instead you should try something like this:
```python
from nuscenes.eval.common.utils import quaternion_yaw


sample = nusc.get('sample', '44237858a539457da65822bfcf58c414')
                  
curent_data_token_cam=sample["data"]["CAM_FRONT"]
data_path, src_boxes, camera_in = nusc.get_sample_data(
    curent_data_token_cam, 
    selected_anntokens=['2f269aaffa314f039897d2fe7de533df', 'f758dafda4b64af39dcb29f9b6ecb288']
)
for box in src_boxes:
    print(f'{box.token}: {np.rad2deg(quaternion_yaw(box.orientation))} degrees')
```
The above should give you:
```
2f269aaffa314f039897d2fe7de533df: -179.86046886151587 degrees
f758dafda4b64af39dcb29f9b6ecb288: 0.15581525315434624 degrees
```
You can see that the yaw of the two objects differ by about 180&deg; (in the front camera coordinate frame)
