### ISSUE TITLE
Reason for value error in map_api.get_arcline_path?

### ISSUE THREAD

**Issue by AngelosSE** [nutonomy/nuscenes-devkit#885]
For lane token bb915717-f84f-47e4-8bf1-a852894b2334, in the map singapore-onenorth, the value error in map_api.get_arcline_path gets raised. Why does some lanes lack an arcline path?

**Comment by AngelosSE** [comment]
By running `grep -rnw . -e bb915717-f84f-47e4-8bf1-a852894b2334` inside the folder `v1.0-trainval` returns 
```
./maps/expansion/singapore-onenorth.json:438378:        "bb915717-f84f-47e4-8bf1-a852894b2334"
./maps/expansion/singapore-onenorth.json:440275:        "bb915717-f84f-47e4-8bf1-a852894b2334"
```
I checked these lines in the json file and it appears that the token only appears as an incoming and outcoming token but not as anything else. Perhaps this issue is related to Issue #493.

**Comment by AngelosSE** [comment]
The following script should detect all such "dead" tokens:

```
def find_tokens_in_connectivity_that_does_not_exist_as_a_lane():
    dataset = 'v1.0-trainval'
    DATAROOT = f'/datasets/nuscenes/{dataset}/'
    map_names = ('boston-seaport','singapore-hollandvillage','singapore-onenorth','singapore-queenstown')
    faulty_tokens = {}
    for map_name in map_names:
        nusc_map = NuScenesMap(DATAROOT,map_name)
        tokens = []
        for d in nusc_map.connectivity.values():
            for ID in ('incoming','outgoing'):
                tokens.extend(d[ID])
        faulty_tokens[map_name] = []
        for token in tokens:
            if nusc_map.arcline_path_3.get(token) is None:
                faulty_tokens[map_name].append(token)
    print(json.dumps(faulty_tokens,indent=4))
```

There appears to be a 15 such tokens.

**Comment by AngelosSE** [comment]
My current solution to avoid this error is to remove the "dead" tokens from the json file. However, I notice that this leaves some lanes disconnected from the road network, meaning that no lane points to them and they do not point to any lane.

**Comment by whyekit-motional** [comment]
@AngelosSE thanks for your detailed analysis - there are indeed some [known issues with the maps](https://github.com/nutonomy/nuscenes-devkit#known-issues), in particular:

> Some lanes are disconnected from the rest of the lanes. We chose to keep these as they still provide valuable information.
