### ISSUE TITLE
Token key error

### ISSUE THREAD

**Issue by mc171819** [nutonomy/nuscenes-devkit#886]
Hi, I met this error when I run testset:
![image](https://user-images.githubusercontent.com/81420309/219824523-81d76dbf-27d6-4d26-a51e-eed8e26ea860.png)
However, in my v1.0-testset, samply.json do have this token:
![image](https://user-images.githubusercontent.com/81420309/219824549-133b150d-5cfc-4203-b2ea-af0d4e6fc378.png)
Is this mean my test .pkl generation has some error?

**Comment by whyekit-motional** [comment]
@mc171819 based on your screenshot, you are loading `v1.0-trainval`, but you mentioned that you checked the `sample.json` for `v1.0-test`. You might want to load `v1.0-test` instead, if your predictions are for the test set.
