### ISSUE TITLE
TypeError: ‘MultiPolygon’ object is not iterable

### ISSUE THREAD

**Issue by chantsss** [nutonomy/nuscenes-devkit#887]
I got an error when submitting the result of **Nuscenes prediction challenge**. It seems the **shapely version is too old**. I post the details here [https://evalai-forum.cloudcv.org/t/nuscenes-prediction-challenge-submission-error/1475](https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fevalai-forum.cloudcv.org%2Ft%2Fnuscenes-prediction-challenge-submission-error%2F1475&data=05%7C01%7Cswangei%40connect.ust.hk%7Ca5528a2cf74248d27fe908db1047a11d%7C6c1d415239d044ca88d9b8d6ddca0708%7C1%7C0%7C638121672058383833%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=20ksE%2BcGpSdjPuju7QRVIyLcVFNGNUkFLfWRJamAyi8%3D&reserved=0). Could you please check it?

Traceback (most recent call last):
File “/code/scripts/workers/submission_worker.py”, line 491, in run_submission
submission_metadata=submission_serializer.data,
File “/tmp/tmp0njjksxy/compute/challenge_data/challenge_591/main.py”, line 69, in evaluate
cfg_ = load_prediction_config(helper, config_name)
File “/usr/local/lib/python3.7/site-packages/nuscenes/eval/prediction/config.py”, line 56, in load_prediction_config
return PredictionConfig.deserialize(config, helper)
File “/usr/local/lib/python3.7/site-packages/nuscenes/eval/prediction/config.py”, line 37, in deserialize
return cls([deserialize_metric(metric, helper) for metric in content[‘metrics’]],
File “/usr/local/lib/python3.7/site-packages/nuscenes/eval/prediction/config.py”, line 37, in
return cls([deserialize_metric(metric, helper) for metric in content[‘metrics’]],
File “/usr/local/lib/python3.7/site-packages/nuscenes/eval/prediction/metrics.py”, line 440, in deserialize_metric
return OffRoadRate(helper, [deserialize_aggregator(agg) for agg in config[‘aggregators’]])
File “/usr/local/lib/python3.7/site-packages/nuscenes/eval/prediction/metrics.py”, line 325, in init
self.drivable_area_polygons = self.load_drivable_area_masks(helper)
File “/usr/local/lib/python3.7/site-packages/nuscenes/eval/prediction/metrics.py”, line 343, in load_drivable_area_masks
canvas_size=None)[0]
File “/usr/local/lib/python3.7/site-packages/nuscenes/map_expansion/map_api.py”, line 392, in get_map_mask
return self.explorer.get_map_mask(patch_box, patch_angle, layer_names=layer_names, canvas_size=canvas_size)
File “/usr/local/lib/python3.7/site-packages/nuscenes/map_expansion/map_api.py”, line 870, in get_map_mask
map_mask = self.map_geom_to_mask(map_geom, local_box, canvas_size)
File “/usr/local/lib/python3.7/site-packages/nuscenes/map_expansion/map_api.py”, line 819, in map_geom_to_mask
layer_mask = self._layer_geom_to_mask(layer_name, layer_geom, local_box, canvas_size)
File “/usr/local/lib/python3.7/site-packages/nuscenes/map_expansion/map_api.py”, line 1803, in _layer_geom_to_mask
return self._polygon_geom_to_mask(layer_geom, local_box, layer_name, canvas_size)
File “/usr/local/lib/python3.7/site-packages/nuscenes/map_expansion/map_api.py”, line 1890, in _polygon_geom_to_mask
map_mask = self.mask_for_polygons(new_polygon, map_mask)
File “/usr/local/lib/python3.7/site-packages/nuscenes/map_expansion/map_api.py”, line 1823, in mask_for_polygons
exteriors = [int_coords(poly.exterior.coords) for poly in polygons]
TypeError: ‘MultiPolygon’ object is not iterable

**Comment by whyekit-motional** [comment]
@chantsss the Shapely version in `nuscenes-devkit==1.1.10` has already been limited to `1.8.5`: https://github.com/nutonomy/nuscenes-devkit/blob/master/setup/requirements/requirements_base.txt#L12

I believe the workers on EvalAI have been updated to use `nuscenes-devkit==1.1.10` as well

**Comment by chantsss** [comment]
Hi, I submitted it again just now, and the workers on EvalAI still returned me the same error. Could you please check it again?

**Comment by whyekit-motional** [comment]
@chantsss we have reached out to EvalAI to investigate this issue

**Comment by whyekit-motional** [comment]
@chantsss your submissions on EvalAI seem to have finished evaluation now - pls give them a check on your end

**Comment by chantsss** [comment]
Yes, I just found it, thanks a lot
