### ISSUE TITLE
Eval AI Submission Stuck at “Submitted”

### ISSUE THREAD

**Issue by Haiyang-W** [nutonomy/nuscenes-devkit#889]
Hi,

We recently submitted a zip file on the Eval AI server for the nuScenes 3D Object Detection Challenge, but the submission remains “Submitted” and never evaluates for one day, is there something more we need to do?

Thank you so much!
![1221677211779_ pic](https://user-images.githubusercontent.com/54112784/221089748-62ec8c80-a7ab-4683-8976-0886d9ecee95.jpg)

**Comment by whyekit-motional** [comment]
@Haiyang-W a few teams are facing this issue as well - we have reached out to the EvalAI folks but there hasn't been any response from them so

We are continuing to try to reach them, so pls hang on in the meantime

**Comment by Haiyang-W** [comment]
Great! Thanks very much. I will try it in the meantime.

**Comment by whyekit-motional** [comment]
@Haiyang-W this issue has been resolved on EvalAI - pls check if your submissions have finished evaluating on EvalAI

**Comment by wyf0414** [comment]
@whyekit-motional
Hello, I met the same problem.
Please help.
Thanks very much!
The challenge: nuScenes detection challenge
The challenge page: https://eval.ai/web/challenges/challenge-page/356/overview
My submitted file: https://evalai.s3.amazonaws.com/media/submission_files/submission_512088/e5605c04-a601-46a7-97b3-8c70c4bf5b2c.zip
