### ISSUE TITLE
How to evaluate part of the dataset?

### ISSUE THREAD

**Issue by Crayon-new** [nutonomy/nuscenes-devkit#890]
Hi, how can I evaluate part of the dataset? Cause I want to check the performance in some special cases,
but this assert was trigged.

<img width="956" alt="uTools_1677229513169" src="https://user-images.githubusercontent.com/56301098/221137666-6d071cd4-6da3-4034-ab1d-492a800cbbfc.png">

**Comment by whyekit-motional** [comment]
@Crayon-new you could modify the `load_gt` method here: https://github.com/nutonomy/nuscenes-devkit/blob/28765b8477dbd3331bacd922fada867c2c4db1d7/python-sdk/nuscenes/eval/common/loaders.py#L69

Concretely, you would want to replace `[s['token'] for s in nusc.sample] ` with a list of sample tokens you are interested in instead
