### ISSUE TITLE
plotting covernet predictions on instance,sample token for which the prediction was made

### ISSUE THREAD

**Issue by sharmasushil** [nutonomy/nuscenes-devkit#891]
i have been following this [tutorial](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/tutorials/prediction_tutorial.ipynb) 

```
# Print 5 most likely predictions
likely_trajectory = trajectories[logits.argsort(descending=True)[:5]]
```
after above predictions, i now need to plot these trajectories in the same map/rastered image that was used for prediction. 

the predicted coordinates looks to be in  in the agent's local coordinate frame, how to transform it to global format or any way to be able to plot the predictions.

**Comment by whyekit-motional** [comment]
@sharmasushil `convert_local_coords_to_global` might be useful for you: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/prediction/helper.py#L58

**Comment by sharmasushil** [comment]
Thank you so much for your prompt response
