### ISSUE TITLE
trying to plot global coordinates on the raster image

### ISSUE THREAD

**Issue by sharmasushil** [nutonomy/nuscenes-devkit#892]
i converted local predicted coordinates from covernet models, the values for 1 mode looks like 

```
[[1294.25056023  849.92651663]
 [1293.07510061  847.32654597]
 [1292.1643306   844.1924689 ]
 [1291.66113059  841.09348702]
 [1291.64307512  837.78882864]
 [1292.04628698  834.60075981]
 [1292.61060609  831.38409106]
 [1293.57270104  828.13732327]
 [1295.4184521   823.98473711]
 [1297.2024306   820.1345274 ]
 [1299.04088379  816.31120306]
 [1301.03305766  812.39031502]]
yaw = 3.7078152365245884
```

my objective is to be able to plot these prediction on the original rastered image that was used as input for prediction. 
```
img = mtp_input_representation.make_input_representation(instance_token_img, sample_token_img)  # this image
```
image is so size (500,500,3) is there any function implemented in prediction module to make this happen or how to do this.

**Comment by whyekit-motional** [comment]
@sharmasushil do check out `StaticLayerRasterizer`: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/prediction/input_representation/static_layers.py#L213

**Comment by whyekit-motional** [comment]
@sharmasushil without a working code snippet to reproduce your error, it is difficult to advise on your above issue

**Comment by sharmasushil** [comment]
Thank you so much for your response.

Please have a look snippet code

`def angle_of_rotation(yaw: float) -> float:
    """
    Given a yaw angle (measured from x axis), find the angle needed to rotate by so that
    the yaw is aligned with the y axis (pi / 2).
    :param yaw: Radians. Output of quaternion_yaw function.
    :return: Angle in radians.
    """
    return (np.pi / 2) + np.sign(-yaw) * np.abs(yaw)


def make_2d_rotation_matrix(angle_in_radians: float) -> np.ndarray:
    """
    Makes rotation matrix to rotate point in x-y plane counterclockwise
    by angle_in_radians.
    """

    return np.array([[np.cos(angle_in_radians), -np.sin(angle_in_radians)],
                     [np.sin(angle_in_radians), np.cos(angle_in_radians)]])




def quaternion_yaw(q):
    """
    Calculate the yaw angle from a quaternion.
    Note that this only works for a quaternion that represents a box in lidar or global coordinate frame.
    It does not work for a box in the camera frame.
    :param q: Quaternion of interest.
    :return: Yaw angle in radians.
    """

    # Project into xy plane.
    v = np.dot(q.rotation_matrix, np.array([1, 0, 0]))

    # Measure yaw using arctan.
    yaw = np.arctan2(v[1], v[0])

    return yaw


def convert_local_coords_to_global(coordinates,
                                   translation,
                                   rotation) -> np.ndarray:
     
    yaw = angle_of_rotation(quaternion_yaw(Quaternion(rotation)))

    transform = make_2d_rotation_matrix(angle_in_radians=-yaw)

    return np.dot(transform, coordinates.T).T[:, :2] + np.atleast_2d(np.array(translation)[:2]),yaw
cords,yaw = convert_local_coords_to_global(one_traj,trans,rot)
print(cords,yaw)

[[ 388.7578345  1138.26681101]
 [ 388.25082568 1136.59968422]
 [ 387.83820603 1134.90625759]
 [ 387.53955292 1132.76530785]
 [ 387.45559274 1130.38533341]
 [ 387.70181637 1128.07120612]
 [ 388.37717556 1125.24231328]
 [ 389.01544244 1122.28603999]
 [ 390.04813959 1119.31858386]
 [ 391.15290192 1116.38250574]
 [ 392.34535829 1113.47693446]
 [ 393.62129173 1110.6065869 ]] 3.5611174458917887



from nuscenes.prediction.input_representation.static_layers import StaticLayerRasterizer
from nuscenes.prediction.input_representation.agents import AgentBoxesWithFadedHistory
from nuscenes.prediction.input_representation.interface import InputRepresentation
from nuscenes.prediction.input_representation.combinators import Rasterizer

static_layer_rasterizer = StaticLayerRasterizer(helper)#,resolution = 0.04)
agent_rasterizer = AgentBoxesWithFadedHistory(helper, seconds_of_history=1)
mtp_input_representation = InputRepresentation(static_layer_rasterizer, agent_rasterizer, Rasterizer())

instance_token_img, sample_token_img = 'bc38961ca0ac4b14ab90e547ba79fbb6', '7626dde27d604ac28a0240bdd54eba7a'
#instance_token_img, sample_token_img = 'bc38961ca0ac4b14ab90e547ba79fbb6', '356d81f38dd9473ba590f39e266f54e5'

anns = [ann for ann in nuscenes.sample_annotation if ann['instance_token'] == instance_token_img]
img = mtp_input_representation.make_input_representation(instance_token_img, sample_token_img)


# img = mtp_input_representation.make_input_representation(instance_token_img, sample_token_img)
print(img.shape)
implot = plt.imshow(img)
#for x_y in cords.tolist():
for x_y in one_traj.tolist():

    x,y = x_y 
    yaw = 0#3.7078152365245884
    plt.scatter([x], [y])
    #     print(x,y)

#     closest_lane = nusc_map.get_closest_lane(x, y, radius=2)

    
    print(closest_lane)
#     lane_record = nusc_map.get_arcline_path(closest_lane)
#     poses = arcline_path_utils.discretize_lane(lane_record, resolution_meters=1)
#     closest_pose_on_lane, distance_along_lane = arcline_path_utils.project_pose_to_lane((x, y, yaw), lane_record)
# #     print(closest_pose_on_lane)

(500, 500, 3)
5933500a-f0f2-4d69-9bbc-83b875e4a73e
5933500a-f0f2-4d69-9bbc-83b875e4a73e
5933500a-f0f2-4d69-9bbc-83b875e4a73e
5933500a-f0f2-4d69-9bbc-83b875e4a73e
5933500a-f0f2-4d69-9bbc-83b875e4a73e
5933500a-f0f2-4d69-9bbc-83b875e4a73e
5933500a-f0f2-4d69-9bbc-83b875e4a73e
5933500a-f0f2-4d69-9bbc-83b875e4a73e
5933500a-f0f2-4d69-9bbc-83b875e4a73e
5933500a-f0f2-4d69-9bbc-83b875e4a73e
5933500a-f0f2-4d69-9bbc-83b875e4a73e
5933500a-f0f2-4d69-9bbc-83b875e4a73e

`

![image](https://user-images.githubusercontent.com/70905483/224688935-f3dbe82b-154b-4bdb-a1cd-879aa11e0383.png)
