### ISSUE TITLE
label rule

### ISSUE THREAD

**Issue by AndyYuan96** [nutonomy/nuscenes-devkit#893]
Hi, I just wonder how is the labeling rule for nuscenes, as I find that for object has little points in point cloud(less than 5 points) in far away, but the object is very clear in image, the nuscenes dataset don't have label, I use a lidar-camera fusion model to inference with nuscenes val dataset.

**Comment by whyekit-motional** [comment]
@AndyYuan96 you can find more details on how the labeling of boxes in nuScenes was done [here](https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/instructions_nuscenes.md#special-rules). In particular, the section "Minimum number of points" might be of interest to you:

> Label any target object containing at least 1 LIDAR or RADAR point, as long as you can be reasonably sure you know the location and shape of the object. Use your best judgment on correct cuboid position, sizing, and heading.

Also, note that if the object is far away (i.e. more than the ranges specified [here](https://github.com/nutonomy/nuscenes-devkit/blob/9bc2f9e74d8a3dd27ef6ce83336508dd8926f867/python-sdk/nuscenes/eval/detection/configs/detection_cvpr_2019.json#L2-L13)), then it will be ignored during evaluation anyway.
