### ISSUE TITLE
Some questions about using nuScenes Map Expansion(lane_divider : segment_type)

### ISSUE THREAD

**Issue by longzuyan** [nutonomy/nuscenes-devkit#894]
Hi！
Can you tell me why the segment_type of lane_divider is marked on each node? Does it mean that the physical appearance from this node to the next node? (e.g The segment_type between nodes  '57d546eb-682c-4540-871c-2e8d6a67f2de' and 'fef2c634-7096-4b48-bf87-6575d2a67b56' is DOUBLE_DASHED_WHITE？)
In addition, how do I extract the segment_type parameter from nuScenes Map Expansion?
Thanks!

`{'token': '00569b72-a7dc-4cdf-9bf3-7f3583c6dbae',
 'line_token': '9ac741dc-20b5-44f3-9f0a-41e371a722ee',
 'lane_divider_segments': [{'node_token': '57d546eb-682c-4540-871c-2e8d6a67f2de',
   'segment_type': 'DOUBLE_DASHED_WHITE'},
  {'node_token': 'fef2c634-7096-4b48-bf87-6575d2a67b56',
   'segment_type': 'DOUBLE_DASHED_WHITE'},
  {'node_token': '153990f1-b0da-4243-a065-e4a99d29e180',
   'segment_type': 'DOUBLE_DASHED_WHITE'},
  {'node_token': '8ad3000f-c1e9-4eda-8bf1-c5f64a879c54',
   'segment_type': 'NIL'}],
 'node_tokens': ['57d546eb-682c-4540-871c-2e8d6a67f2de',
  'fef2c634-7096-4b48-bf87-6575d2a67b56',
  '153990f1-b0da-4243-a065-e4a99d29e180',
  '8ad3000f-c1e9-4eda-8bf1-c5f64a879c54']}`

**Comment by whyekit-motional** [comment]
@longzuyan do check out the tutorial for the nuScenes map expansion: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/tutorials/map_expansion_tutorial.ipynb

In particular,
> The `lane_divider_segments` field consist of different `node`s and their respective `segment_type`s which denotes their physical appearance.

**Comment by Wolfybox** [comment]
> @longzuyan do check out the tutorial for the nuScenes map expansion: https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/tutorials/map_expansion_tutorial.ipynb
> 
> In particular,
> 
> > The `lane_divider_segments` field consist of different `node`s and their respective `segment_type`s which denotes their physical appearance.

the tutorial didnt explain why the segment type is given with respect to single node (middle of the segment perhaps?) rather than the starting and ending points of the segment.

**Comment by whyekit-motional** [comment]
@Wolfybox this is just a choice that was made in defining the schema when the data was being annotated and release

**Comment by Wolfybox** [comment]
> @Wolfybox this is just a choice that was made in defining the schema when the data was being annotated and release

Given a line of a-b-c-d-e (letters represent line node), if a is DOUBLE_DASHED_WHITE, b is NIL,  then the segment a-b should be of type DOUBLE_DASHED_WHITE?
Do a and e mean exactly the starting and ending points of the line?
Also, how many types are there and what are their meaning?

**Comment by whyekit-motional** [comment]
@Wolfybox I've played around with the maps a little, and here are my replies:

> if a is DOUBLE_DASHED_WHITE, b is NIL, then the segment a-b should be of type DOUBLE_DASHED_WHITE?

I think the node type refers to the type of divider the node is sitting on, e.g. if node n sits on a white double-dashed line, then it will be of `DOUBLE_DASHED_WHITE` - here are some examples:

![image](https://github.com/user-attachments/assets/8eb53686-e1ca-4493-b3e1-874cf96be7a5)
![image](https://github.com/user-attachments/assets/9cca785e-b106-4cd7-9ea9-e2ce2243913d)

> Do a and e mean exactly the starting and ending points of the line?

Note that the `lane_divider_segments` / `node_tokens` in the `lane_divider` records are dictionaries, so the ordering of the nodes which make up a given line is not guaranteed

> Also, how many types are there and what are their meaning?

So far, I've only seen `DOUBLE_DASHED_WHITE`, `SINGLE_SOLID_WHITE` and `NIL` (see my images above to get an idea of what they look like) - do let me know if you come across more!

**Comment by Wolfybox** [comment]
I went through all the lane_dividers by using nusc_map.lane_divider and found there are about 1000 DOUBLE_DASHED_WHITE, 400 SINGLE_SOLID_WHITE, 1000 NIL. Other segment_types include SINGLE_SOLID_WHITE, DOUBLE_SOLID_WHITE, SINGLE_ZIGZAG_WHITE, but only make up a very small amount (< 50).  It also shows that the type set does not cover all possible laneline types in real-world, far from brewing a decent real-world laneline perception model.

**Comment by Wolfybox** [comment]
> @Wolfybox I've played around with the maps a little, and here are my replies:
> 
> > if a is DOUBLE_DASHED_WHITE, b is NIL, then the segment a-b should be of type DOUBLE_DASHED_WHITE?
> 
> I think the node type refers to the type of divider the node is sitting on, e.g. if node n sits on a white double-dashed line, then it will be of `DOUBLE_DASHED_WHITE` - here are some examples:
> 
> ![image](https://private-user-images.githubusercontent.com/62535720/362968836-8eb53686-e1ca-4493-b3e1-874cf96be7a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5OTQ1MTAsIm5iZiI6MTcyNDk5NDIxMCwicGF0aCI6Ii82MjUzNTcyMC8zNjI5Njg4MzYtOGViNTM2ODYtZTFjYS00NDkzLWIzZTEtODc0Y2Y5NmJlN2E1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDA1MDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5MjU0ZDkzMjEwMTA0OGU4MzM5MDc2ZGE1MjFkNDFlYTc3ZjYwNGQ4ZjA0ZGE5MDM4NzA2MzE5NmRkMThiNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rdGJHui90Fj-C6-rpXu2lOAfILBjfqTXdSUXgmLDSpA) ![image](https://private-user-images.githubusercontent.com/62535720/362969122-9cca785e-b106-4cd7-9ea9-e2ce2243913d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5OTQ1MTAsIm5iZiI6MTcyNDk5NDIxMCwicGF0aCI6Ii82MjUzNTcyMC8zNjI5NjkxMjItOWNjYTc4NWUtYjEwNi00Y2Q3LTllYTktZTJjZTIyNDM5MTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDA1MDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMGU3N2RkYjUyY2IxNGY4OTU2OGFjMjZkNmNjY2EzZGY0YTM2MzZmZTVkNTA2ZWEwZjJlY2QxMWMyNTgzN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ONavbsYH8UANYOcxBVWnZfFwWxrfdvH1_4s5LuG2uHU)
> 
> > Do a and e mean exactly the starting and ending points of the line?
> 
> Note that the `lane_divider_segments` / `node_tokens` in the `lane_divider` records are dictionaries, so the ordering of the nodes which make up a given line is not guaranteed
> 
> > Also, how many types are there and what are their meaning?
> 
> So far, I've only seen `DOUBLE_DASHED_WHITE`, `SINGLE_SOLID_WHITE` and `NIL` (see my images above to get an idea of what they look like) - do let me know if you come across more!

BTW, did you draw the node and the line by hands or by projection? AFAIK, nusc map expansion does not provide z axis with the annotation, so the projection is usually inaccurate and misaligned in the images.

**Comment by whyekit-motional** [comment]
There would be some inaccuracies / misalignment when plotting the nodes on the camera images, but it should be sufficient to give you an idea of what the nodes types are
