### ISSUE TITLE
what is the extrinsic parameters of IMU?

### ISSUE THREAD

**Issue by GeJintian** [nutonomy/nuscenes-devkit#897]
Hello, thank you for your great work!

However, when we are trying to validate some SLAM algorithms on CAN BUS, we found that IMU has angular velocity on all three axes, see the picture below.
![Screenshot from 2023-03-14 17-36-55](https://user-images.githubusercontent.com/51193204/224959079-b73b927e-e1dd-4062-a7fd-c12dd36b6ab4.png)
But I suppose only yaw angle velocity should exist. So I wonder what are the extrinsic parameters of IMU? Is its xy-plane perpendicular to the gravity direction?

**Comment by whyekit-motional** [comment]
@GeJintian the xy-plane in the IMU frame may not always be perpendicular to the direction of gravity, e.g. when the ego is traveling on a slope
