### ISSUE TITLE
training with one part of the dataset

### ISSUE THREAD

**Issue by dakaiss28** [nutonomy/nuscenes-devkit#899]
Hi,
I would like to train my model on Nuscenes but I cannot download all blobs of the v1.0-trainval. 
Is there a way to get the metadata only for the first blob (v1.0-trainval01blob) ? 
If I use the metadata for the whole v1.0-trainval, I have some "FileNotFound" Errors. 
Thanks !

**Comment by whyekit-motional** [comment]
@dakaiss28 I don't think there's a straightforward to hack the devkit in order for you to train only on one blob

Perhaps using the `v1.0-mini` split might be better in your case
