### ISSUE TITLE
failed with 'pip install nuscenes-devkit'

### ISSUE THREAD

**Issue by harborsarah** [nutonomy/nuscenes-devkit#903]
Hi,
I would like to ask if python 3.9 is suitable for installing nuscenes package? Also, I check the requirement.txt files and didn't find it is required to install 'pycocotools' but when i try to download nuscenes, it is always error when build wheel of pycocotools. I would like to ask how to solve this problem.
![image](https://user-images.githubusercontent.com/65909204/227902156-37e9315a-4485-4d31-9519-14a0cebf69de.png)

Thanks for the help

**Comment by whyekit-motional** [comment]
@harborsarah the devkit is tested for Python 3.6 and Python 3.7, so installing it in an environment that uses `python=3.7` might solve your issue
