### ISSUE TITLE
Question about the boston-seaport map

### ISSUE THREAD

**Issue by sutong-st** [nutonomy/nuscenes-devkit#907]
Hi,
      I want to align the openstreepmap to nuscenes map,so i convert the osm data from WGS84 coordinate system to epsg:3857. 
The origins are given by the map api. From the vis results, all of the singapore maps are matched while the boston-seaport are failed. I noticed that it seems like the map seems to be scaling (not sure).
      I use the same pyproj function to convert all maps, am i missing something?
      Here is my function:
      Transformer.from_crs("epsg:4326", "epsg:3857", always_xy=True)
the osm vis
![boston-seaport_crossing_ SD_MAP_3](https://user-images.githubusercontent.com/57938437/231745918-08b274eb-3d68-45e0-9ba5-ca3b65d40f46.png)

the nuscnes vis
![drivable_area_MAP_1](https://user-images.githubusercontent.com/57938437/231746078-a29f244c-8d03-481a-a862-e3d3949c748d.png)
    It seems like the right part are matching worsely.

**Comment by whyekit-motional** [comment]
@sutong-st do see if this helps you: https://github.com/nutonomy/nuscenes-devkit/issues/144#issuecomment-505377023
