### ISSUE TITLE
Why is class ID 0 skipped for the sMOTSA panoptic tracking eval?

### ISSUE THREAD

**Issue by Ali2500** [nutonomy/nuscenes-devkit#910]
I noticed the following two lines of code in [python-sdk/nuscenes/eval/panoptic/panoptic_track_evaluator.py#L339](https://github.com/nutonomy/nuscenes-devkit/blob/6d7fc293a092f069efadb0aad2edabc8d8a4f73c/python-sdk/nuscenes/eval/panoptic/panoptic_track_evaluator.py#L339):

```python
iou = self.pan_iou[1:self.min_stuff_cls_id].astype(np.double)
ids = self.pan_ids[1:self.min_stuff_cls_id].astype(np.double)
````

where `self.pan_iou` and `self.pan_ids` both have shape [num_classes]. I wanted to know why the first class ID is being skipped here? This corresponds to the BARRIER class. Is there something special about it?

**Comment by whyekit-motional** [comment]
@Ali2500 class ID 1 is not being skipped - in the code snippet you showed above, the arrays are being indexed starting from 1 ( `[1:self.min_stuff_cls_id]`), i.e. where `1` is included

**Comment by Ali2500** [comment]
Class ID 1 is not skipped, but class ID 0 is. My question was why ID 0 is being skipped.

**Comment by whyekit-motional** [comment]
@Ali2500 class ID 0 is the `void / ignore` class (see [here](https://github.com/nutonomy/nuscenes-devkit/tree/master/python-sdk/nuscenes/eval/panoptic#classes)), and so it is skipped during evaluation
