### ISSUE TITLE
Details about how splits are constructed?

### ISSUE THREAD

**Issue by AngelosSE** [nutonomy/nuscenes-devkit#911]
Where can I find the details about how the splits in  [nuscenes-devkit](https://github.com/nutonomy/nuscenes-devkit)/[python-sdk](https://github.com/nutonomy/nuscenes-devkit/tree/master/python-sdk)/[nuscenes](https://github.com/nutonomy/nuscenes-devkit/tree/master/python-sdk/nuscenes)/[utils](https://github.com/nutonomy/nuscenes-devkit/tree/master/python-sdk/nuscenes/utils)/splits.py are constructed? What was the requirements?

**Comment by whyekit-motional** [comment]
@AngelosSE the general motivation when defining the splits include:

- Roughly same distribution of classes across the splits
- As little overlap as possible in logs across the splits
