### ISSUE TITLE
Camera calibration pitch offset?

### ISSUE THREAD

**Issue by Lapayo** [nutonomy/nuscenes-devkit#912]
Hi, 
I am currently trying to project the point cloud in the image, but to me it looks like the camera extrinsics are not accurate. Probably the pitch is off?
I noticed the issue on multiple scenes, usually its pretty clear on the traffic lights.
e.g. 
![Annotation 2023-04-17 170942](https://user-images.githubusercontent.com/1183538/232532356-ded13eda-77f2-4ea4-bb21-a084ece35ddb.jpg)

![Annotation 2023-04-17 170930](https://user-images.githubusercontent.com/1183538/232532365-9653726d-7943-478c-afeb-4b7a9c217950.jpg)
(Also on the left side the traffic lights are off)

It is also visible in 0464 and there isnt even any ego motion.

Is that to be expected?

You can reproduce the issue with the the devkit as follows:
```
from nuscenes.nuscenes import NuScenes

nusc = NuScenes(version='v1.0-trainval', dataroot='/home/data/datasets/public/nuscenes/data/', verbose=False)
SCENE_NAME = "scene-0480" # or 0103

scene = [x for x in nusc.scene if x["name"] == SCENE_NAME][0]
samples = sorted([x for x in nusc.sample if x["scene_token"] == scene["token"]], key=lambda x: x["timestamp"])

FRAME_ID = 14 # or 17
sample = samples[FRAME_ID]

nusc.render_pointcloud_in_image(sample["token"], pointsensor_channel='LIDAR_TOP')
```

**Comment by whyekit-motional** [comment]
@Lapayo I agree with you that the calibration in this scene isn't very good 

The yaw is good here, but the roll and pitch seem slightly off
