### ISSUE TITLE
How to transform GPS/IMU files into KITTI format?

### ISSUE THREAD

**Issue by Quantum-matrix** [nutonomy/nuscenes-devkit#914]
Thanks for your great work!
I've transformed the annotations into KITTI format using your code. But how to transform GPS/IMU files into KITTI format which is like oxts/0000.txt?

**Comment by whyekit-motional** [comment]
@Quantum-matrix I don't think there's currently any ready-made script within `nuscenes-devkit` for conversion of GPS/IMU files - but do feel free to write one and share it :smile:
