### ISSUE TITLE
Difference between NuScenes Data and NuPlan Data

### ISSUE THREAD

**Issue by QuanyiLi** [nutonomy/nuscenes-devkit#916]
Hi,

I would like to train a prediction model and wonder if combining two datasets can improve the performance or not. 

If data in both datasets are diverse and different, it would, ideally, benefit the performance as I trained with more data. Thus I would like to know if there is some overlap between NuScenes data and NuPlan data. If so, how many scenarios are the same?

Thank you

**Comment by whyekit-motional** [comment]
@QuanyiLi there is no overlap in data between nuScenes and nuPlan - besides the fact that the years during which the data was collected is different, there are other differences as well (e.g. different vehicle setup)
