### ISSUE TITLE
Cannot download with wget in China

### ISSUE THREAD

**Issue by sunnyHelen** [nutonomy/nuscenes-devkit#917]
Hi, it seems that the dataset cannot be downloaded with wget command in China recently. Can you please help me check it? Thanks a lot.

**Comment by whyekit-motional** [comment]
@sunnyHelen do see if this issue is still persisting now

**Comment by sunnyHelen** [comment]
Yes, it still exists.
<img width="665" alt="image" src="https://user-images.githubusercontent.com/28101548/235391428-4d4089cd-2682-4bf4-876c-adebf06b9434.png">

**Comment by whyekit-motional** [comment]
@sunnyHelen in that case, you might want to check if there's any restriction on your end (e.g. due to geographic location, firewalls, etc.)
