### ISSUE TITLE
pixel coordinate to global coordinate

### ISSUE THREAD

**Issue by ChengWang2018** [nutonomy/nuscenes-devkit#918]
Hi,

I use a lane detection algorithm to detect the lanes in Nuscene dataset. The results (points) are on the pixel coordinate system, How can I convert it global coordinate system so that I can compare the results with lanes in the map.

Thanks a lot!

**Comment by whyekit-motional** [comment]
@ChengWang2018 I think this depends on how you transformed the lanes in the map from the global coordinate system to the pixel coordinate system in the first place

**Comment by ChengWang2018** [comment]
I have not done that. I use images for the lane detection. Thus, the mp is firstly not needed. So, I donot quite understand your ideas. Could you explain it a bit more? Thanks!

**Comment by whyekit-motional** [comment]
There's a method [`map_pointcloud_to_image`](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L834) which maps a set of 3D coordinates to a given image - perhaps you can use some of the ideas in there to do the reverse
