### ISSUE TITLE
get the pixel coordinates and then assign to each pixel depth value

### ISSUE THREAD

**Issue by Jezer-Zhang** [nutonomy/nuscenes-devkit#919]
hi, i am trying to extract one channel tensor form lidar samples, containing the depth value (z) in corresponding pixel coordinate.
is there any developer that can help?

**Comment by whyekit-motional** [comment]
@Jezer-Zhang one possibility is to refer to [`map_pointcloud_to_image`](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/nuscenes.py#L834) to figure out which image pixel each lidar point falls in
