### ISSUE TITLE
How can the measured radar doppler velocity be extracted?

### ISSUE THREAD

**Issue by rs271** [nutonomy/nuscenes-devkit#924]
My question is related to #748 and https://forum.nuscenes.org/t/radar-vx-vy-and-vx-comp-vy-comp/283, but I didn't find a satisfying answer in either of them.

The radar data provides the velocities (vx, vy) and (vx_comp, vy_comp) for each detection.
My main question is: **How can the doppler velocity as measured by the radar sensor** (i.e. the relative radial velocity in the radar frame of reference) **be derived from those**?

And some related follow up questions:

- Does the radar also measure/estimate the tangential velocity components?
   - If not, why are there 2 independent components for (vx, vy)? (By independent, I mean that they are not all pointing radially into the sensor direction, or into the same cartesian direction.)
   - If yes, then why do (vx_comp, vy_comp) contain only one independent component? (They all point radially into the sensor direction.)
- In the code documentation https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/data_classes.py#L330, it says that the compensation is only with respect to the ego motion. But that can't be correct, otherwise (vx, vy) and (vx_comp, vy_comp) should be identical when the ego vehicle is not moving, which is not the case (see e.g. sample[200] in the "mini" dataset used in the [tutorial](https://www.nuscenes.org/tutorials/nuscenes_tutorial.html)). So how exactly does the compensation work?

**Comment by whyekit-motional** [comment]
@rs271 let me see if I can clarify your various queries:

> My main question is: **How can the doppler velocity as measured by the radar sensor** (i.e. the relative radial velocity in the radar frame of reference) **be derived from those**?

If you know the angle between the radar and the object you are measuring, you could resolve `vx_comp` and `vy_comp` to get the radial velocity

> Does the radar also measure/estimate the tangential velocity components?

I believe you can can estimate the tangential velocity components in a similar manner as what I described above for estimating the radial velocity

> So how exactly does the compensation work?

Unfortunately, we do not have access to the algorithm that the radar uses internally for compensation - `vx_comp` and `vy_comp` are simply taken from the output of the radar

**Comment by rs271** [comment]
@whyekit-motional Thanks for your reply!

> > My main question is: How can the doppler velocity as measured by the radar sensor (i.e. the relative radial velocity in the radar frame of reference) be derived from those?
> 
> If you know the angle between the radar and the object you are measuring, you could resolve vx_comp and vy_comp to get the radial velocity

The radial component of (vx_comp, vy_comp) can't be the measured doppler velocity, because those are the compensated velocities; e.g., the doppler from stationary objects, when the ego vehicle is moving, are non-zero, whereas (vx_comp, vy_comp) is zero then.

It would be obvious to asume that instead, the doppler is the radial component of (vx, vy). But there are several problems with this assumption:

1. (vx, vy) don't always point into the sensor direction, as would have to be the case if they only contained the measured doppler velocity, converted into a purely radial vector. (In principle, it could be that the radar signal processing actually also estimates the tangential velocities, but that's clearly not the case, as can be seen from the plot below.)
2. Instead, for moving objects, (vx, vy) only has one nonzero cartesian component (namely the forward-direction in sensor coordinates), as can be seen from this example (a similar plot as in the [tutorial](https://www.nuscenes.org/tutorials/nuscenes_tutorial.html), but using (vx, vy) instead of (vx_comp, vy_comp), for sample[200]; the ego vehicle is stopped at a crossing here):
![sample_200_uncomp](https://github.com/nutonomy/nuscenes-devkit/assets/134615753/da2057c8-a26e-4c54-85a7-89e90fbe978d)
![sample_200_cam](https://github.com/nutonomy/nuscenes-devkit/assets/134615753/96e65f98-a2e2-4727-9a13-4522decef25a)

One could then assume that vx (in sensor coordinates) is the doppler. For moving objects, this seems to work in general, as in this example (vx, vy for sample[20]):
![sample_20_vel_uncomp](https://github.com/nutonomy/nuscenes-devkit/assets/134615753/bcf3887b-b7c0-478d-8abd-02c23b91d91b)
![sample_20_cam](https://github.com/nutonomy/nuscenes-devkit/assets/134615753/a0619ae1-4b7c-4179-8caf-787b66e65fb4)

Note that for the moving car in front, again (vx, vy) only have one nonzero cartesian component (in sensor direction). But for the detections from stationary objects, that's obviously not the case. Apparently, they have some additional velocity components induced by the ego motion, which doesn't make sense to me, as that should only be the case for (vx_comp, vy_comp), and implies that neither the radial component nor the vx component (in sensor coordinates) can be the doppler.

**So it is still unclear how to obtain the measured doppler from the data.**

> Unfortunately, we do not have access to the algorithm that the radar uses internally for compensation - vx_comp and vy_comp are simply taken from the output of the radar

But could you perhaps provide some more detailed documentation on the meaning of (vx, vy), (vx_comp, vy_comp) that the radar algorithm outputs? Even if you don't have access to the algorith, I expect there should be a more detailed interface documentation?

[Note: I wanted to re-open this issue, because it's not resolved yet, but wasn't able because @whyekit-motional  had closed it.]

**Comment by SimmyZhu** [comment]
> If you know the angle between the radar and the object you are measuring, you could resolve `vx_comp` and `vy_comp` to get the radial velocity

How can you use compensated velocity `vx_comp` and `vy_comp` to get the radial velocity? I can imagine that for stationary objects the compensated velocities will be zero but not the radial velocity

**Comment by SimmyZhu** [comment]
> But could you perhaps provide some more detailed documentation on the meaning of (vx, vy), (vx_comp, vy_comp) that the radar algorithm outputs? Even if you don't have access to the algorith, I expect there should be a more detailed interface documentation?

Hi, I have the same problem as you. Does the following link help?
https://forum.nuscenes.org/t/radar-vx-vy-and-vx-comp-vy-comp/283/5

**Comment by nightrome** [comment]
Hi. I'd like to chime in as one of the original authors of nuScenes. I have seen many radar experts discussing the nuScenes radar, but with no clear conclusions. I think we have the right understanding in general of how motion compensation works and how to convert between the x/y and radial representations. 
However, what we see in the data does not exactly match the theory. One possible explanation is that the radar received the raw ego motion data (e.g. from the IMU), whereas the nuScenes dataset comes with the highly processed / smoothed localization data that is a product of lidar localization and IMU. Thus the motion compensation is not exact. Alternatively the radar itself may also be doing something unexpected. Unfortunately the manufacturer's handbook does not provide any information on this topic. 
So unless somebody comes up with new convincing evidence on what may have happened, let us **consider this topic closed**.
