### ISSUE TITLE
Dimensions and position of local maps

### ISSUE THREAD

**Issue by AndreSchakkal** [nutonomy/nuscenes-devkit#925]
Hello,

I'm currently working on adapting your dataset to the task of pedestrian trajectory prediction and it's working pretty well. However, I have a small question: Is there a way to get the dimensions and position (in meters) of the locally generated bird's eye view map (shown in the figure).
I'm asking you this because I need these values to be able to transform the pedestrians' coordinates from meters (in the global frame) to pixels (in the local frame). If retrieving these values is not possible, is there a way to find the coordinates of the pedestrians in the local map's reference?

Thank you for your help. 
![Screenshot 2023-05-25 193902](https://github.com/nutonomy/nuscenes-devkit/assets/126706635/eb3e5a33-5b89-4167-a50f-76134fbbb3c0)

**Comment by whyekit-motional** [comment]
@AndreSchakkal there's a method [`to_pixel_coords`](https://github.com/nutonomy/nuscenes-devkit/blob/da3c9a977112fca05413dab4e944d911769385a9/python-sdk/nuscenes/nuscenes.py#L1195) which you could check out to get inspiration from

**Comment by AndreSchakkal** [comment]
Thank you for your answer.
I'm now able to get the coordinates (more or less), however I think there's some rotation that's missing in my code. Do you happen to know what's missing?
![download (2)](https://github.com/nutonomy/nuscenes-devkit/assets/126706635/0e14a8e4-01ea-42f2-babf-1f86e9d4237d)

**Comment by whyekit-motional** [comment]
You could check if you have performed a rotation of the map (as part of the transformation to the ego frame), like what is done here: https://github.com/nutonomy/nuscenes-devkit/blob/da3c9a977112fca05413dab4e944d911769385a9/python-sdk/nuscenes/nuscenes.py#L1201-L1203
