### ISSUE TITLE
How to download metadata file of nuPlan v1.1 Dataset

### ISSUE THREAD

**Issue by nguyenlam185** [nutonomy/nuscenes-devkit#927]
Please anybody tell me how to download the metadata file.
I created an account and have all the zip files of the dataset v1.1 downloaded, except the metadata file.
When click on the Link (both US and Asia) there was just the loading icon appeared for a while, just like the other files, but then nothing happen
![image](https://github.com/nutonomy/nuscenes-devkit/assets/5319157/18d28273-d2c1-4b15-b762-ef4f8f4fa272)

**Comment by whyekit-motional** [comment]
@nguyenlam185 for nuPlan issues, pls post them at https://github.com/motional/nuplan-devkit/issues
