### ISSUE TITLE
class "Traffic signs "

### ISSUE THREAD

**Issue by brahami14** [nutonomy/nuscenes-devkit#934]
Hello, 

Thank you for this work,
I have a question please, there are sequences that contained traffic signs and annotated or traffic signs were not annotated,

Thanks in advance

**Comment by whyekit-motional** [comment]
@brahami14 pls define what you mean by "traffic signs", and check if your definition falls under one of the labels in nuScenes: https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/instructions_nuscenes.md

**Comment by brahami14** [comment]
Thank you for your answer, 

i meant traffic sign excluding its mounting, spurious points in a layer in front and behind the traffic sign are also labled as traffic sign 

unfortunately i didn't find class "traffic signs", in the nuscences tags, i don't know if you give it another name

**Comment by whyekit-motional** [comment]
@brahami14 perhaps you can include a screenshot to more clearly illustrate what you see

**Comment by whyekit-motional** [comment]
@brahami14 are those images from nuScenes? If they are, what are the sample tokens for them?

**Comment by brahami14** [comment]
they are from Semantickitti

**Comment by brahami14** [comment]
link: http://semantic-kitti.org/dataset.html

**Comment by whyekit-motional** [comment]
It is probably better to post questions regarding the data of SemanticKITTI at https://github.com/PRBonn/semantic-kitti-api/issues

**Comment by whyekit-motional** [comment]
Based on the list of classes in nuScenes, I don't think traffic signs are labelled: https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/instructions_nuscenes.md

**Comment by brahami14** [comment]
oKay, thank you for your answer, 
Have a nice day
