### ISSUE TITLE
A minor issue for virtual environment setup 

### ISSUE THREAD

**Issue by JieYu2001** [nutonomy/nuscenes-devkit#94]
If the nuScenes-devkit is the first virtual environment a user creates, the procedure needs a small tweak. Before the step of "Create the virtual environment", $PATH needs to be updated to include the path of [VIRTUAL_ENV_LOCATION]. I guess "source ~/.profile" will work - if yes, then add a line "source ~/.profile" to bashrc in the previous step "Install virtualenvwrapper" will do. But I used a dumb reboot to resolve the "error: virtualenvwrapper could not find virtualenv in your path" I encountered by following the original steps.

**Comment by nightrome** [comment]
Thank you for your feedback. We noticed the same and have already fixed it in the full dataset release scheduled for March 26.
