### ISSUE TITLE
Question about annotation files in the V1.0.

### ISSUE THREAD

**Issue by Gatsby23** [nutonomy/nuscenes-devkit#945]
Dear Professors:
         Thank you for your outstanding work that greatly contributes to the industries and research. Your dataset is truly exceptional, and it has the potential to significantly enhance the autonomous driving industry. Recently, I wanna to filter out the moving object in the lidar points. I noticed that you have annoated some moving objects in the V1.0 data as showned below:
<img width="698" alt="image" src="https://github.com/nutonomy/nuscenes-devkit/assets/18000675/d19fc04f-3f79-4332-8bb0-bced7f35f2c4">
But I only can see the annotation in the sample dataset. So where can I find these labels and can use it to filter out the dynamic objects？

Yours
Qi Wu

**Comment by whyekit-motional** [comment]
@Gatsby23 you can access the attributes of each annotation via something like this:
```python
from nuscenes.nuscenes import NuScenes


sample_idx = 0
sample_ann_idx = 1

nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=False)

my_sample = nusc.sample[sample_idx]
my_sample_ann_token = my_sample['anns'][sample_ann_idx]
my_sample_ann = nusc.get('sample_annotation', my_sample_ann_token)
my_sample_ann_attr_tokens = my_sample_ann['attribute_tokens']

for attr_token in my_sample_ann_attr_tokens:
    attr = nusc.get('attribute', attr_token)['name']
    print(attr)
```

**Comment by Gatsby23** [comment]
> @Gatsby23 you can access the attributes of each annotation via something like this:
> 
> ```python
> from nuscenes.nuscenes import NuScenes
> 
> 
> sample_idx = 0
> sample_ann_idx = 1
> 
> nusc = NuScenes(version='v1.0-mini', dataroot='/data/sets/nuscenes', verbose=False)
> 
> my_sample = nusc.sample[sample_idx]
> my_sample_ann_token = my_sample['anns'][sample_ann_idx]
> my_sample_ann = nusc.get('sample_annotation', my_sample_ann_token)
> my_sample_ann_attr_tokens = my_sample_ann['attribute_tokens']
> 
> for attr_token in my_sample_ann_attr_tokens:
>     attr = nusc.get('attribute', attr_token)['name']
>     print(attr)
> ```

Sorry, my previous statement was  not clear enough. The problem is where can I find the annotation files for v1.0 Fulldataset？ I can only find the annotation file for the sample file, that is not enough for my topic

**Comment by whyekit-motional** [comment]
@Gatsby23 you can download the full dataset from https://www.nuscenes.org/nuscenes#download:

![image](https://github.com/nutonomy/nuscenes-devkit/assets/62535720/14b79271-df5c-4708-9669-183f34c9aed0)

**Comment by Gatsby23** [comment]
> @Gatsby23 you can download the full dataset from https://www.nuscenes.org/nuscenes#download:
> 
> ![image](https://user-images.githubusercontent.com/62535720/251025045-14b79271-df5c-4708-9669-183f34c9aed0.png)

Sorry for bothering you about this one. I know what's wrong: The sample data notation is the whole data that has annoted the atrribute, Right?

**Comment by whyekit-motional** [comment]
Each sample in the dataset is annotated (e.g. boxes, attributes, velocities, etc.)

The dataset also contains sweeps, which are not annotated
