### ISSUE TITLE
cannot download all data, any suggestion?

### ISSUE THREAD

**Issue by teddyluo** [nutonomy/nuscenes-devkit#946]
Hi, I cannot download any data from the official site, even after I log in using a different account. can you provide any help?
all data download link is missing.

**Comment by Qiang-Xu** [comment]
I tested both US and Asia links on nuScenes download page, it worked for me. @teddyluo can you be more specific about what data on which page you were not able to download?

**Comment by whyekit-motional** [comment]
I've also verified that both the US and Asia links are working from my location
