### ISSUE TITLE
AttributeError data_split

### ISSUE THREAD

**Issue by z0v0z** [nutonomy/nuscenes-devkit#947]
the error: AttributeError:'nuScenesDataset' object has no attribute 'data_split'. my nuscense-devkit is 1.1.8。

**Comment by whyekit-motional** [comment]
@z0v0z pls provide a code snippet to reproduce the error

**Comment by z0v0z** [comment]
@whyekit-motional my code is 
 nusc = NuScenes("v1.0-trainval", "/data/nuScenes")
Dataset = nuScenesDataset(nusc, "train", nusc_dataset_kwargs)
if Dataset.data_split == "val":
and then error.  
my nusence_devkit is 1.1.8.
i will be appreciated  if you can slove my problem.
thanks

**Comment by whyekit-motional** [comment]
Where is `nuScenesDataset` coming from?

**Comment by z0v0z** [comment]
@whyekit-motional 
from data import nuScenesDataset, ONCEDataset, CollateFn

**Comment by whyekit-motional** [comment]
@z0v0z it seems the package `data` (where you are importing `nuScenesDataset` from) does not belong to nuscenes-devkit - you should probably ask the folks who are behind the `data` package
