### ISSUE TITLE
Question on releasing the full nuScenes dataset with 1000 scenes

### ISSUE THREAD

**Issue by amiltonwong** [nutonomy/nuscenes-devkit#95]
Hi, organizers,

As shown from [here](https://www.nuscenes.org/download), the full nuScenes dataset with 1000 scenes will be released by 25/3. However, the corresponding download link still not appears...
When will it be released for download?

THX!

**Comment by Alex-nutonomy** [comment]
Hi @amiltonwong,
The website is just a day early and should be March 26th (USA). We will correct the website now.
Alex
