### ISSUE TITLE
[Question] How do nuScenes developpers annotate road boundaries in map expansion?

### ISSUE THREAD

**Issue by alexwangxiang** [nutonomy/nuscenes-devkit#950]
Dear nuScenes developpers of Motional,
I'm currently doing a project that requires annotating road boundaries like curbs, and I'm interested in how do you annotate them in nuScenes map expansion. This blog [scale-ai-guide](https://scale.com/guides/data-labeling-annotation-guide#data-labeling-for-computer-vision) provides some introduction to 3d object detection annotation pipeline using scale studio. However, I still don't know how do you annotate long objects such as curbs and solid lines exactly. Our raw data are collected from one lidar and four cameras, which is similar to your multimodal sensors containing one lidar and six cameras. Thank you!

Yours,
Wang Xiang

**Comment by venice-erin** [comment]
Hi Xiang Wang,

We have an in-house annotation tool for annotating our maps using 2D map rasters. See our blog post: https://motional.com/news/technically-speaking-mapping for more details

I suggest to look at the [lidar top down task from scale](https://docs.scale.com/reference/lidar-topdown-task) for your needs.
