### ISSUE TITLE
Assert unachieved_thresholds + duplicate_thresholds + len(thresh_metrics) == self.num_thresholds

### ISSUE THREAD

**Issue by LLLehom** [nutonomy/nuscenes-devkit#952]
Hi~I just try to val my tracking results, error like below:
File "/home/L/anaconda3/envs/Lnet/lib/python3.8/site-packages/nuscenes/eval/tracking/algo.py", line 156, in accumulate
    assert unachieved_thresholds + duplicate_thresholds + len(thresh_metrics) == self.num_thresholds
AssertionError
Could you inform me about the problem?

**Comment by whyekit-motional** [comment]
@LLLehom do see if this helps you: https://github.com/nutonomy/nuscenes-devkit/issues/700

If not, pls provide a working code snippet to reproduce your issue

**Comment by LLLehom** [comment]
@whyekit-motional Thank you for your reply.

In #700 and #718  I found the answer and successfully tested it.
