### ISSUE TITLE
How often to calibrate the sensor parameters, such as camera, lidar and IMU?

### ISSUE THREAD

**Issue by rockywind** [nutonomy/nuscenes-devkit#956]
Hi, thank you for sharing the great work!
1. nuscene's camera parameters are very accurate, and I would like to know if the sensor parameters should be calibrated once before each data acquisition.
2. Or is there any way to ensure the accuracy of sensor calibration.

**Comment by whyekit-motional** [comment]
@rockywind unfortunately the people that worked on the original nuScenes calibration moved on, thus I can only give you my best guesses. Generally, we used our own proprietary codebase and hardware for calibration to ensure reproducibility of the calibration, which was highly accurate. When manually reviewing the settings, it was not possible to improve upon it by eyeballing.

However, for the nuScenes data collection, the calibration was not validated for every car on a daily basis. As such there can be all kinds of disturbances (potholes, violently closing the trunk) that mess up calibration. E.g. in https://github.com/nutonomy/nuscenes-devkit/issues/912 there is a noticeable pitch offset.

**Comment by rockywind** [comment]
Hi, thank you for you help.
How to fixed the offset?

**Comment by whyekit-motional** [comment]
@rockywind unfortunately, I don't think there's a straightforward way to fix the offset

**Comment by rockywind** [comment]
Thanks a lot!
