### ISSUE TITLE
how to check which scene one sample_token is in?

### ISSUE THREAD

**Issue by GilgameshD** [nutonomy/nuscenes-devkit#957]
Hi, after I get the sample_token, how can I check which scene it is in? Thanks.

**Comment by whyekit-motional** [comment]
With the sample token, you can retrieve the sample record via:
```python
my_sample = nusc.get('sample', my_sample_token)
```
Within the sample record, there will be a scene token under `scene_token`

You can then retrieve the scene record via:
```python
my_scene_token = my_sample['scene_token']
my_scene = nusc.get('sample', my_scene_token)
```

**Comment by GilgameshD** [comment]
Thanks for the quick response!
