### ISSUE TITLE
Calculating metrics(NDS, mAP and ...) on test set

### ISSUE THREAD

**Issue by apourghani** [nutonomy/nuscenes-devkit#962]
Hello,
Is there any way to calculate metrics like mAP and NDS on test dataset, before submitting to NuScenes leaderboard? We want to optimize some parameters and check the validity of our model before publishing paper.
Thanks for your kind attention,
Aliasghar Pourghani,
Electrical engineering bachelor student,
Sharif University of Technology

**Comment by whyekit-motional** [comment]
@apourghani if you wish to get metrics for the test split, you can submit it to the nuScenes detection challenge server here: https://eval.ai/web/challenges/challenge-page/356/overview
