### ISSUE TITLE
how to fix translation-z in ego_pose?

### ISSUE THREAD

**Issue by poodarchu** [nutonomy/nuscenes-devkit#963]
1. all z values in ego pose is set to 0, how to recover a accurate z?
2. Is it possible to traverse all scenes of a map in sequence such that we could using lidar odometry to reconstruct the full map scene? How to get a valid scene sequence?

**Comment by whyekit-motional** [comment]
@poodarchu hope the following helps you:
1. z was deliberately dropped as the localization in nuScenes does not have a z component (but the annotations do)
2. You could use the code snippet I provided in https://github.com/nutonomy/nuscenes-devkit/issues/900#issuecomment-1480626303 as a reference

**Comment by poodarchu** [comment]
Thanks for your response, is there any way to recover the z value in ego pose?

**Comment by whyekit-motional** [comment]
As this data was recorded quite a few years ago, I don't think there's a feasible way to recover the z-value
