### ISSUE TITLE
Arbitrariness of wlh with respect to xyz ?

### ISSUE THREAD

**Issue by polo5** [nutonomy/nuscenes-devkit#970]
Hi,

Thanks for all the hard work. 
I'm confused about the conventions you use when it comes to width,length,height of bboxes. In [this issue](https://github.com/nutonomy/nuscenes-devkit/issues/131) it seems to be claimed that the x,y,z directions of some sensor and the wlh values of some bbox in that sensor's coordinate system are not related. But then what is the meaning of width, length and height ?

Furthermore, in the `corners()` method of the `Box` data class ([here](https://github.com/nutonomy/nuscenes-devkit/blob/a5c089133baa001d3ab3c5583a103957e4ae8375/python-sdk/nuscenes/utils/data_classes.py#L603)) it seems to be casually assumed that width,length,height run along y,x,z respectively (looks like the ego frame). Wouldn't this assume that if the ego vehicle turns by 90 degrees, the width and length of the bbox will be swapped?

Thanks for your clarification!

**Comment by polo5** [comment]
These questions came up because I have 8 corners from an axis aligned bbox I drew in the lidar pointcloud/coordinate system, and I would like to express it in the global [xc,yc,zc,w,l,h,yaw] representation that nuscenes uses.

**Comment by whyekit-motional** [comment]
@polo5 the xyz of a box center (as given in the raw annotations) is wrt the global frame, while the wlh of the box is independent of the coordinate frame

**Comment by polo5** [comment]
Thanks @whyekit-motional. As I said I'm aware of this already though. I was hoping for some extra clarification. 

When annotating bboxes _some_ choice was made about the meaning of width,length,height and I'm asking for that very design choice. Is it based on each class geometry, e.g. length runs from the back of the car to the front of the car? Again, the reason I thought this design choice could be related to some coordinate system is the code for corners [here ](https://github.com/nutonomy/nuscenes-devkit/blob/a5c089133baa001d3ab3c5583a103957e4ae8375/python-sdk/nuscenes/utils/data_classes.py#L613 ) which explicitly assumes some fixed relationship for x,y,z and w,l,h.

**Comment by whyekit-motional** [comment]
@polo5 yes, length runs along the longitudinal axis of the ego, while width runs along the latitudinal axis of the ego
