### ISSUE TITLE
Point Acquisition Order in .pcd files

### ISSUE THREAD

**Issue by enrlc0** [nutonomy/nuscenes-devkit#973]
Hi,
I just wanted to know wether I can assume that points in the first rows of the .pcd files are recorded before points towards the end of the file. Or possibly the other way round.

Thanks in advance and kind regards
Enrico

**Comment by whyekit-motional** [comment]
@enrlc0 there's no specific ordering to the points in the .pcd files

**Comment by enrlc0** [comment]
OK thanks @whyekit-motional  then maybe you could tell me instead if the sensor rotates clockwise (mathematically negative) or counterclockwise (mathematically positive)?

**Comment by whyekit-motional** [comment]
@enrlc0 I believe it should be counter-clockwise, when looking down at the top of the lidar (however, it might be best to confirm with the manual for the Velodyne HDL32E, which is the lidar used in nuScenes)

**Comment by enrlc0** [comment]
@whyekit-motional thanks for the hint, until now I had only looked at the spec sheet but the full manual indicates that the rotational direction is mathematically negative (clockwise if viewed from above) even though it is not entirely clear as the graphic misses some annotation.

![image](https://github.com/nutonomy/nuscenes-devkit/assets/73635664/bbb5582e-c67f-4ed3-9625-0968cce98686)
