### ISSUE TITLE
visualization with pickle

### ISSUE THREAD

**Issue by SISTMrL** [nutonomy/nuscenes-devkit#974]
hello, i want to visualize the 3d bounding boxes in nuscenes_infos_train.pkl, could you please give me some suggestions? thanks!

**Comment by whyekit-motional** [comment]
@SISTMrL where is `nuscenes_infos_train.pkl` coming from?

**Comment by SISTMrL** [comment]
> @SISTMrL where is `nuscenes_infos_train.pkl` coming from?

it's genrerated by mmdetection3d

**Comment by whyekit-motional** [comment]
@SISTMrL in that case, it is probably more appropriate to open your issue at https://github.com/open-mmlab/mmdetection3d
