### ISSUE TITLE
The results is "None" in My Submissions

### ISSUE THREAD

**Issue by ZhouPPuro** [nutonomy/nuscenes-devkit#975]
Hi
Thanks for all the hard work.
My submission did not return any results, please help me check whether it was submitted successfully.

![image](https://github.com/nutonomy/nuscenes-devkit/assets/143164088/86d91392-25da-403b-8084-01a5ad5daead)

**Comment by whyekit-motional** [comment]
@ZhouPPuro it seems there are a number of teams whose submissions are also stuck in the "Submitted" status. This is likely to be an EvalAI issue. Pls send an email to them (team@cloudcv.org) to get someone from the EvalAI team to check.

**Comment by whyekit-motional** [comment]
@ZhouPPuro EvalAI seems to be working now - pls give it a check
