### ISSUE TITLE
render_pointcloud_in_image  logic

### ISSUE THREAD

**Issue by ZOUYIyi** [nutonomy/nuscenes-devkit#976]
since image is trigered when the lidar sweep the center of image, and the timestamp of the pointcloud is at the finish of the sweep ,why there is still involves time and ego pose to do the render_pointcloud_in_image

**Comment by whyekit-motional** [comment]
@ZOUYIyi this is because you would need to project the points (which are in the lidar frame) into the image (which is in the camera frame), and this is done by transforming the frame of the points in this order: 

1. Transform points in lidar frame to ego frame
2. Transform points in ego frame to global frame
3. Transform points in global frame to ego frame of the timestamp of the image
4. Transform points in ego frame of the timestamp of the image to camera frame

**Comment by ZOUYIyi** [comment]
> @ZOUYIyi this is because you would need to project the points (which are in the lidar frame) into the image (which is in the camera frame), and this is done by transforming the frame of the points in this order:
> 
> 1. Transform points in lidar frame to ego frame
> 2. Transform points in ego frame to global frame
> 3. Transform points in global frame to ego frame of the timestamp of the image
> 4. Transform points in ego frame of the timestamp of the image to camera frame

thanks for reply ,but i think the true reson is that the pointcloud is be transformed by motion distortion. if it is just the ori pointcloud ,we can just aply 1,4 step ,since 2,3 is just about time align

**Comment by whyekit-motional** [comment]
If the timestamp at which the lidar data is captured is exactly the same at which the camera data is captured, then probably doing only steps 1 and 4 will suffice

But there is usually a slight difference, so going through steps 1, 2, 3 and 4 gives a more accurate projection

**Comment by ZOUYIyi** [comment]
> 

as the nusence says ,the camera trigered when the lidar sweep just in the center of the image, so there is no need to do 2,3 if we use the ori pointcloud .but i suppose that the pointcloud is undistored by motion, so we need 2,3.

**Comment by ZOUYIyi** [comment]
> If the timestamp at which the lidar data is captured is exactly the same at which the camera data is captured, then probably doing only steps 1 and 4 will suffice
> 
> But there is usually a slight difference, so going through steps 1, 2, 3 and 4 gives a more accurate projection

the timestamp of the lidar is just the sweep end , and the sweep cant be as quick as image capture, that is what i think is the key  
of the design

**Comment by whyekit-motional** [comment]
Yes @ZOUYIyi that is correct - the capture times of the lidar and the camera are slightly different
