### ISSUE TITLE
database version not found

### ISSUE THREAD

**Issue by Michal12Zurawka** [nutonomy/nuscenes-devkit#977]
hello i would like to convert full nuscenes 1.0 to kitti format. But when i run this code              i still have error about  database version.
Could you tell me where put data and what parameters must be changed? 
class KittiConverter:
    def __init__(self,
                 nusc_kitti_dir: str = '~/nusc_kitti',
                 cam_name: str = 'CAM_FRONT',
                 lidar_name: str = 'LIDAR_TOP',
                 image_count: int = 9999999,
                 nusc_version: str = 'v1.0',
                 split: str = 'trainval'):
                 
  $ python export_kitti.py nuscenes_gt_to_kitti --nusc_kitti_dir ./kitti
Traceback (most recent call last):
  File "export_kitti.py", line 362, in <module>
    fire.Fire(KittiConverter)
  File "/home/dev/anaconda3/envs/nuscenes/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/dev/anaconda3/envs/nuscenes/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/dev/anaconda3/envs/nuscenes/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "export_kitti.py", line 84, in __init__
    self.nusc = NuScenes(version=nusc_version)
  File "/home/dev/Desktop/nuscenes-devkit/python-sdk/nuscenes/nuscenes.py", line 62, in __init__
    assert osp.exists(self.table_root), 'Database version not found: {}'.format(self.table_root)
AssertionError: Database version not found: /data/sets/nuscenes/v1.0

**Comment by whyekit-motional** [comment]
@Michal12Zurawka `nusc_version` is usually `v1.0-trainval`, `v1.0-test` or `v1.0-mini` (you have used `v1.0` in your above code snippet)

**Comment by Michal12Zurawka** [comment]
Okey, i changed this but issue is the same. 
assert osp.exists(self.table_root), 'Database version not found: {}'.format(self.table_root)
AssertionError: Database version not found: /data/sets/nuscenes/v1.0-trainval

Actually i have data here /home/dev/Desktop/nuscenes-devkit/python-sdk/nuscenes

**Comment by whyekit-motional** [comment]
@Michal12Zurawka I would suggest to transfer the data to `/data/sets/nuscenes`

**Comment by Michal12Zurawka** [comment]
![Screenshot from 2023-09-07 13-48-55](https://github.com/nutonomy/nuscenes-devkit/assets/137154749/5d0725a6-7322-48bf-ad83-f95be70bc995)

This location is good?
i still have the same error :(

**Comment by whyekit-motional** [comment]
@Michal12Zurawka from your screenshot, it seems that the location of the dataset on your machine is `~/data/sets/nuscenes` - it should be `/data/sets/nuscenes`

**Comment by Michal12Zurawka** [comment]
yes my bad, now working
