### ISSUE TITLE
Eval AI Submission Stuck at the status “Submitted”

### ISSUE THREAD

**Issue by toyot-li** [nutonomy/nuscenes-devkit#978]
Hi, the submitted result at Eval AI is stuck at the "submitted" status and not actually evaluated. I have emailed Eval AI bu still received no response now. Could you please give a help? Thanks.

**Comment by whyekit-motional** [comment]
@zen-d sure thing, I've reached out to the EvalAI folks to check on this

**Comment by whyekit-motional** [comment]
@zen-d as of 18 Sep, submissions to the nuScenes tracking leaderboard were able to complete evaluation successfully:

![image](https://github.com/nutonomy/nuscenes-devkit/assets/62535720/87ac274d-7262-4f15-ba21-29dd9878c7c9)

Perhaps you can try re-submitting to the EvalAI server and see if you still face issues
