### ISSUE TITLE
Is IMU noise available in Nuscenes?

### ISSUE THREAD

**Issue by GeJintian** [nutonomy/nuscenes-devkit#979]
Hello, I wonder if we could obtain noise information of IMU from Nuscenes? Like other datasets (TUM vi, for example):
"\# Inflated values (to account for unmodelled effects)
\# Those values work well with Kalibr cam-imu calibration.
\#  - white noise multiplied by 2
\#  - bias random walk multiplied by 10
accelerometer_noise_density: 0.0028     \# m/s^1.5
accelerometer_random_walk:   0.00086    \# m/s^2.5
gyroscope_noise_density:     0.00016    \# rad/s^0.5
gyroscope_random_walk:       0.000022   \# rad/s^1.5"
This could be useful for IMU pre-integration. Is there any way we can obtain these data in Nuscenes? Thank you very much.

**Comment by whyekit-motional** [comment]
@GeJintian perhaps the manual for Advanced Navigation Spatial will have what you need

**Comment by whyekit-motional** [comment]
@GeJintian the official website of Advanced Navigation might have what you need: https://www.advancednavigation.com/inertial-navigation-systems/mems-gnss-ins/spatial/#Documentation

**Comment by GeJintian** [comment]
@whyekit-motional Great, I will check it. Thank you so much.
