### ISSUE TITLE
Wrong shape error with Lidar point cloud

### ISSUE THREAD

**Issue by harborsarah** [nutonomy/nuscenes-devkit#980]
Hi, 
Could you tell me which part here contains data for scene 710?
![image](https://github.com/nutonomy/nuscenes-devkit/assets/65909204/51c2a8df-b4eb-4476-8cdb-a1b485f3755e)

When I try to load lidar points for this scene, this error always appears, `ValueError: cannot reshape array of size 32768 into shape (5)`
I checked other issues and you said this might happen because the data is corrupted.

Thanks a lot for your help. It might also be nice if there is a way for only downloading the data for this specific scene.

**Comment by whyekit-motional** [comment]
@harborsarah I think the first blob contains the first 85 scenes, the second blob contains the next 85 scenes and so on

We can then do a quick calculation like so:
```python
from nuscenes.utils.splits import create_splits_scenes 


splits_scenes = create_splits_scenes()
trainvaltest_scenes = sorted(list(set(scenes['train'] + scenes['val'] + scenes['test'])))
print(trainvaltest_scenes.index('scene-0710') // 85)
```
So my guess is that scene 710 is in part 7

**Comment by harborsarah** [comment]
> @harborsarah I think the first blob contains the first 85 scenes, the second blob contains the next 85 scenes and so on
> 
> We can then do a quick calculation like so:
> 
> ```python
> from nuscenes.utils.splits import create_splits_scenes 
> 
> 
> splits_scenes = create_splits_scenes()
> trainvaltest_scenes = sorted(list(set(scenes['train'] + scenes['val'] + scenes['test'])))
> print(trainvaltest_scenes.index('scene-0710') // 85)
> ```
> 
> So my guess is that scene 710 is in part 7

okay, I see. Now I know how it works. But it might be in part 8 :)
Thanks a lot for your quick reply.

**Comment by whyekit-motional** [comment]
Oh yes, you are right - it is probably in part 8 (since I wrote the code with 0-indexing in mind :sweat_smile:)

**Comment by harborsarah** [comment]
> Oh yes, you are right - it is probably in part 8 (since I wrote the code with 0-indexing in mind 😅)

Haha yes. Anyway, I hope this will solve the problem. Thanks for your time XD
