### ISSUE TITLE
How to obtain latitude and longitude information from the NuScenes dataset?

### ISSUE THREAD

**Issue by myc634** [nutonomy/nuscenes-devkit#981]
Hello NuScenes team,

Following the problem mentioned in #966, I tried converting the coordinate system to latitude and longitude. However, I still encountered the mismatch issue similar to what was described in #960. Could you provide more comments or solutions to address this?

Any guidance would be greatly appreciated. Thank you in advance!

**Comment by whyekit-motional** [comment]
@myc634 pls see https://github.com/nutonomy/nuscenes-devkit/issues/960#issuecomment-1738641717
