### ISSUE TITLE
Knowing 5 cams have a 70deg FOV and 1 has a 110deg FOV, do all cams have the same sensor and same lens?

### ISSUE THREAD

**Issue by actiarka** [nutonomy/nuscenes-devkit#986]
Hi everyone,

First of all, thank you very much to all the team for sharing your work to the community! It is very useful!

**Could you please clarify how the six cameras are set up?**

From this [source (issue #827)](https://github.com/nutonomy/nuscenes-devkit/issues/827#issuecomment-1272537811), it is confirmed that 5 cameras have the same Field Of View (FOV) of 70 degrees and only the BACK camera has a different FOV of 110 degrees.

Yet, in the [article (table 2)](https://arxiv.org/pdf/1903.11027.pdf) and the [docs](https://www.nuscenes.org/nuscenes#data-collection), it seems as **_all cameras have the same sensor equipped with the same lens_** (i.e a **focal of 5.5mm** and a **sensor size of 7.2mm x 5.4mm** as confirmed in [issue #185](https://github.com/nutonomy/nuscenes-devkit/issues/185#issuecomment-511284000) ). **Is this correct?**

**If it is correct, how can there be the same spatial resolution over all cameras?** (since we need the same spatial resolution on all images in order for the model to learn distances appropriately).

Thank you in advance for taking the time to read this question.
We stay at your disposal if you need more information.

Best regards,
Antoine

**Comment by whyekit-motional** [comment]
@actiarka could you clarify what you mean by "spatial resolution" in the context of cameras?

**Comment by actiarka** [comment]
Hi @whyekit-motional, thank you for asking here are some clarifications:

We are trainng models doing 3D objects detection from monocular images (i.e. 2D images).

If we train a model on NuSc and use it to infer 3D BBoxes with images from Kitti (for instance) then the model will be given images taken from a camera with a focal of 4mm and a sensor size of 6.4 x 4.8mm. These camera parameters are different from those of NuSc so this difference will inevitably change the perception of objects (what I perhaps wrongly referred as spatial resolution) and the model will predict 3D BBoxes further away than reality.

We can counter act this effect with a computation that depends on the focal and the pixel resolution of the two different cameras involved. Therefore we need to know exactly those two set of parameters. 

Yet in NuSc, the documentation mentions that all cameras have the same sensor equipped with the same lens (i.e a sensor size of 7.2mm x 5.4mm and a focal of 5.5mm) and that the CAM BACK has a different FOV from the other ones (i.e. 110 vs 70 degrees). We do not see how can the FOV be different?

Best regards,
Antoine

**Comment by whyekit-motional** [comment]
@actiarka for `CAM_BACK`, the lens should have a focal of 4 mm (sensor remains the same as that of the other cameras)

**Comment by ihaohe** [comment]
> @actiarka for `CAM_BACK`, the lens should have a focal of 4 mm (sensor remains the same as that of the other cameras)

Hi, can you share the exact type of the rear camera's len? (something like N118B05518W F1.8 f5.5mm for the front camera's len).
I can't find a len which has 110deg FOV. 
Thanks for ur help!

**Comment by ihaohe** [comment]
> @actiarka for `CAM_BACK`, the lens should have a focal of 4 mm (sensor remains the same as that of the other cameras)

Hi @whyekit-motional  , can you share the exact type of the rear camera's len? (something like N118B05518W F1.8 f5.5mm for the front camera's len).
I can't find a len which has 110deg FOV.
Thanks for ur help!

**Comment by whyekit-motional** [comment]
@ihaohe I think the rear camera uses the following lens: Evetar Lens M118B0418IR F1.8 f4mm 1/1.8"

**Comment by ihaohe** [comment]
> @ihaohe I think the rear camera uses the following lens: Evetar Lens M118B0418IR F1.8 f4mm 1/1.8"

Got It. Thanks

**Comment by ihaohe** [comment]
> @ihaohe I think the rear camera uses the following lens: Evetar Lens M118B0418IR F1.8 f4mm 1/1.8"

@whyekit-motional ， I found rear lens（Evetar Lens M118B0418IR F1.8 f4mm 1/1.8"）has S-mount type, But the camera Basler acA1600-60gc has the C-mount type. How does their connector match?

**Comment by whyekit-motional** [comment]
@ihaohe you could probably use some sort of adaptor to connect the two
