### ISSUE TITLE
How to predefine baseline route and get map coordinate (can_bus/*_route.json) in data collection?

### ISSUE THREAD

**Issue by Songustc** [nutonomy/nuscenes-devkit#988]

**Comment by whyekit-motional** [comment]
@Songustc the baseline routes are simply the idealized path an AV should take (assuming there are no obstacles), while the coordinates given in `pose` of the CAN bus data are identical to the [nuScenes ego pose](https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/schema_nuscenes.md#ego_pose) but sampled at a higher frequency

**Comment by Songustc** [comment]
> @Songustc the baseline routes are simply the idealized path an AV should take (assuming there are no obstacles), while the coordinates given in `pose` of the CAN bus data are identical to the [nuScenes ego pose](https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/schema_nuscenes.md#ego_pose) but sampled at a higher frequency

Thank you for your very detailed answer
Is the ideal path generated in advance from the HD map? Can you explain the relevant routing algorithm?

**Comment by whyekit-motional** [comment]
The baseline paths are typically the center line of the lanes (no fancy algorithm there :smile:)

**Comment by Songustc** [comment]
Thanks for clarification 😄
