### ISSUE TITLE
Strategy used to generate "train_detect" and "train_track"

### ISSUE THREAD

**Issue by lasnik** [nutonomy/nuscenes-devkit#990]
Hi,

would you be able to share the strategy you used to split the training split into the "detect" and "track" halves?

Thanks in advance!

Best,
Niklas

**Comment by whyekit-motional** [comment]
@lasnik in a tracking-by-detection paradigm, `train_detect` would be used to train a detector, and `train_track` could be used to train / tune a tracker. Both splits have the same distribution of Singapore, Boston, night and rain data.
