### ISSUE TITLE
Editing drivable area and querying Traffic light status

### ISSUE THREAD

**Issue by kumarmanas** [nutonomy/nuscenes-devkit#994]
Is it possible to edit the "drivable_area" so that new drivable area is based on the new requirnment. Say, I wanted to add or remove  map information or sections from the provided drivable area to expand/reduce it further. 
Also, right now traffic light has only positions and color. How can we query the map to get at what instance traffic light is green or red? As this is dynamic information.

**Comment by whyekit-motional** [comment]
@kumarmanas here are my replies: 
> Is it possible to edit the "drivable_area" so that new drivable area is based on the new requirnment.

In theory, it should be possible - the drivable area is made up of various polygons (pls see https://www.nuscenes.org/tutorials/map_expansion_tutorial.html for details), and you could drop / add more polygons as per your use case

> How can we query the map to get at what instance traffic light is green or red? As this is dynamic information.

We generally don't support traffic light states, as our map is entirely static.

**Comment by kumarmanas** [comment]
Thanks @whyekit-motional  for your answer and suggestions. 

For traffic light which is static right now, can we know the static status of the traffic light for the road? As after extracting traffic light information for specific lane or section, I see the location and shape of the traffic light but it does not explicitly says which light bulb is active at that static instance.  As most  '`to_road_block_tokens`' field associated with traffic light bulb is empty. So any other way to know what is the static color of traffic light for the road or lane Segment.

**Comment by whyekit-motional** [comment]
@kumarmanas as I mentioned above, nuScenes does not have traffic light states, i.e. there is no way, for any given traffic light, to know which bulb is active at a specific timestamp

**Comment by kumarmanas** [comment]
@whyekit-motional  Sorry, might be I was not clear earlier. My question was not about time stamp, but it is more about "road or lane is being controlled by which bulb of traffic light?". 
If that is not the case, then traffic light information in the dataset is just there for indicating the infrastructure. But it seems like there are some additional purpose for that information as well.

**Comment by whyekit-motional** [comment]
@kumarmanas there is a `from_road_block_tokens` which denotes from which road block the traffic light guides (pls see https://www.nuscenes.org/nuscenes?tutorial=maps for more details) - perhaps it can help in your use-case
