### ISSUE TITLE
weird lidar-sample correspondence

### ISSUE THREAD

**Issue by poodarchu** [nutonomy/nuscenes-devkit#995]
I try to extract sweeps using the nuscenes api.

![Screenshot 2023-10-06 at 7 20 41 PM](https://github.com/nutonomy/nuscenes-devkit/assets/11813362/b27151ba-96f9-466a-9c16-7858e5758fcd)

If I use lidar_data's "next" key to obtain the next lidar scan, and use the "sample_token" of the next lidar scane to get its sample, then I find that next_sample["data"]["LIDAR_TOP"] is different from next_lidar["token"].

![Screenshot 2023-10-06 at 7 38 34 PM](https://github.com/nutonomy/nuscenes-devkit/assets/11813362/0b7ebc42-97f6-4b44-8b69-e9ad2b5baa45)

**Comment by whyekit-motional** [comment]
@poodarchu when you use "sample_data" to retrieve the next lidar scan, it gets the next immediate lidar scan

In contrast, when you use "sample_token" to retrieve the next lidar scan, it gets the lidar scan of the next keyframe (which is approx. 0.05 secs away)

**Comment by poodarchu** [comment]
next_lidar is retrieved by nusc.get("sample_data"), and it contains a "sample_token" key. So why a non-key frame links to next key sample?

**Comment by whyekit-motional** [comment]
That refers to the "nearest" sample which the non-keyframe sweep is associate with

A better indicator of whether the sweep belongs to a keyframe is the `is_key_frame` key
