### ISSUE TITLE
AssertionError: Database version not found

### ISSUE THREAD

**Issue by nican2018** [nutonomy/nuscenes-devkit#996]
Well. I have been struggling myself. I think I need help now. I'm following this tutorial https://mmdetection3d.readthedocs.io/en/latest/advanced_guides/datasets/nuscenes.html. 

After installing all packages, I download the v1.0-mini dataset, and unzip, following this tutorial. https://colab.research.google.com/github/nutonomy/nuscenes-devkit/blob/master/python-sdk/tutorials/nuscenes_tutorial.ipynb#scrollTo=pmfAToXe7Enf.

Then I'm getting error while trying to preprocess the data. 

(opencood) root@root:/home/s_214708038/mmdetection3d# python tools/create_data.py nuscenes --root-path /data1/s_214708038/datasets/nuscenes/ --out-dir /data1/s_214708038/datasets/nuscenes/ --extra-tag nuscenes
Traceback (most recent call last):
  File "tools/create_data.py", line 314, in <module>
    max_sweeps=args.max_sweeps)
  File "tools/create_data.py", line 75, in nuscenes_data_prep
    root_path, info_prefix, version=version, max_sweeps=max_sweeps)
  File "/home/s_214708038/mmdetection3d/tools/dataset_converters/nuscenes_converter.py", line 45, in create_nuscenes_infos
    nusc = NuScenes(version=version, dataroot=root_path, verbose=True)
  File "/opt/conda/envs/opencood/lib/python3.7/site-packages/nuscenes/nuscenes.py", line 62, in __init__
    assert osp.exists(self.table_root), 'Database version not found: {}'.format(self.table_root)
AssertionError: Database version not found: /data1/s_214708038/datasets/nuscenes/v1.0-trainval

Please did I missed something?

**Comment by whyekit-motional** [comment]
@nican2018 you mentioned that you downloaded the `v1.0-mini` data, but from the `AssertionError` you have provided, it seems you are trying to load the `v1.0-trainval` data instead
