### ISSUE TITLE
about rotation order

### ISSUE THREAD

**Issue by yu8ri1** [nutonomy/nuscenes-devkit#998]
<img width="1472" alt="スクリーンショット 2023-10-21 1 20 15" src="https://github.com/nutonomy/nuscenes-devkit/assets/101169773/999b35d6-0179-4468-a0d0-fa5364885266">

I would like to know the rotation order of the rotaion at the Euler angles of the front camera and lidar in this image.

**Comment by whyekit-motional** [comment]
@yu8ri1 pls clarify what you mean by "rotation order"

**Comment by yu8ri1** [comment]
I am trying to express the rotation angle (roll->pitch->yaw) in a simulator with different coordinate systems in the coordinate system of each sensor in nuscenes.
I think it is possible to convert the coordinate system by switching the axes and changing the sign in the roll, pitch, and yaw states. In this case, I would like to match the order of rotation when nuscense is expressed as roll->pitch->yaw.
What I want to ask is the rotation order when nuscense is expressed as roll->pitch->yaw.

Translated with www.DeepL.com/Translator (free version)

**Comment by whyekit-motional** [comment]
@yu8ri1 the transformation is simply done as a matrix operation (i.e. there is no order of roll / pitch / yaw) - pls see here for an example: https://github.com/nutonomy/nuscenes-devkit/blob/9b165b1018a64623b65c17b64f3c9dd746040f36/python-sdk/nuscenes/nuscenes.py#L884

**Comment by yu8ri1** [comment]
Thanks for the reply ...
I understand about the order of rotation. The question is about rotation and translation for each sensor." .json" file are the rotations and translations of each sensor adapted to a specific coordinate system?

**Comment by LeningWang** [comment]
> Thanks for the reply . I understand about the order of rotation. The question is about rotation and translation for each sensor." .json" file are the rotations and translations of each sensor adapted to a specific coordinate system?

Maybe we have same problem.
You can refer to https://github.com/nutonomy/nuscenes-devkit/issues/1001 for the discussion
