### ISSUE TITLE
Can bus and nuscenes data

### ISSUE THREAD

**Issue by jeho-lee** [nutonomy/nuscenes-devkit#999]
According to below,

https://github.com/nutonomy/nuscenes-devkit/blob/9b165b1018a64623b65c17b64f3c9dd746040f36/python-sdk/nuscenes/can_bus/can_bus_api.py#L36-L45

The route and ego pose are not aligned for some scenes. 
Could you give me a more detailed explanation?
Does it mean the trajectories of the ego car are not well aligned with the map route?

**Comment by whyekit-motional** [comment]
@jeho-lee there are some scenes where the ego poses and baseline route are misaligned, and hence those are blacklisted - you can see the full details of how this is determined here: https://github.com/nutonomy/nuscenes-devkit/blob/9b165b1018a64623b65c17b64f3c9dd746040f36/python-sdk/nuscenes/can_bus/can_bus_api.py#L163-L188

**Comment by jeho-lee** [comment]
Thank you for the response. I will check the details.
